force-app/main/default/objects/SpiffPricing__c/SpiffPricing__c.object-meta.xml
<CustomObject>
    <description>Object to update the spiff for active products</description>
    <label>Spiffs</label>
    <nameField>
        <label>SpiffPricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SpiffPricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SpiffPricing__c/fields/CDW__c.field-meta.xml
<CustomField>
    <fullName>CDW__c</fullName>
    <label>CDW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SpiffPricing__c/fields/Distribution__c.field-meta.xml
<CustomField>
    <fullName>Distribution__c</fullName>
    <label>Distribution</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SpiffPricing__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestSpiffPricing.cls
@IsTest
public class TestSpiffPricing  {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    
    Static testmethod void testmasterspiff() {
        test.startTest();
        Pricebookentry pbe = [Select id, product2.name, pricebook2.name from pricebookentry limit 1];
        spiffpricing__c sp = new spiffpricing__c(sku__c = pbe.product2.name, 
                                                 price_book__c = pbe.pricebook2.name,
                                                 Distribution__c = 5);
        insert sp;
        TriggerContextUtility.setFirstRunTrue();
        sp.CDW__c = 4;
        update sp;
        
        
        
        test.stopTest();
        
    }
}