force-app/main/default/objects/Case/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Quote_Product__c.field-meta.xml
<CustomField>
    <fullName>Quote_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EvalQuoteReset.cls
public class EvalQuoteReset {
    //Apex properties or variables

    public Id Id { get; set; }
    public Eval_Request__c eval { get; set; }

    //constructor to get the Case record
    public EvalQuoteReset(ApexPages.StandardController controller) {
    eval =  (Eval_Request__c) controller.getRecord();
    Id = eval.Id;
    System.debug('The eval record: ' + eval);
    }

    //Method that can is called from the Visual Force page action attribute
     //@InvocableMethod(label='Update Teams' description='Updates Opportunity Team Members')
    
    public PageReference reset() {
        System.debug('eval Id: ' + Id);
        List<Eval_Unit_Details__c> unitsToUpdate = new List<Eval_Unit_Details__c>();
        List<Eval_Unit_Details__c> evals;
          evals = [SELECT Id,Eval_Request__c, 	Quote_Product__c from Eval_Unit_Details__c
                    WHERE Eval_Request__c =: eval.Id];

          for(Eval_Unit_Details__c e : evals){
          	e.Quote_Product__c = false;
          	unitsToUpdate.add(e);

          }

         	update unitsToUpdate;
            
            //PageReference pageRef = new PageReference(ApexPages.currentPage().getUrl());
            return null; 

          }
    }