force-app/main/default/objects/SalesQuarter__c/SalesQuarter__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Days in Quarter for Each Quarter in CY</description>
    <label>Sales Quarter</label>
</CustomObject>

force-app/main/default/objects/SalesQuarter__c/fields/Days_In_CQ__c.field-meta.xml
<CustomField>
    <fullName>Days_In_CQ__c</fullName>
    <label>Days In CQ</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TestQuotaCQDays.cls
@IsTest
public class TestQuotaCQDays {
     @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    Static testmethod void QuotaCQDays() {
        //create the custom settings for test method
        insert new SalesQuarter__c(Days_In_CQ__c = 60,
                                   SetupOwnerId = UserInfo.getOrganizationId());

        PageReference myVfPage = Page.Quotachangedaysinq;
        Test.setCurrentPageReference(myVfPage);
        QuotaCQDays q = new QuotaCQDays();
        q.updatedays();
        q.updatecs();
    }
}