force-app/main/default/objects/SalesQuarter__c/SalesQuarter__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Days in Quarter for Each Quarter in CY</description>
    <label>Sales Quarter</label>
</CustomObject>

force-app/main/default/objects/SalesQuarter__c/fields/Days_In_CQ__c.field-meta.xml
<CustomField>
    <fullName>Days_In_CQ__c</fullName>
    <label>Days In CQ</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/QuotaCQDays.cls
public without sharing class QuotaCQDays {
  public Decimal cqdays {get; set;}
    
    public void updatecs(){
    	List<SalesQuarter__c> sq = [SELECT Id, Name, SetupOwnerId, Days_In_CQ__c FROM SalesQuarter__c
                				where SetupOwnerId =: UserInfo.getOrganizationId()];
        sq[0].Days_In_CQ__c = cqdays;
        
        update sq[0];
  }
  
 public void updatedays(){
      List<SalesQuarter__c> sq = [SELECT Id, Name, SetupOwnerId, Days_In_CQ__c FROM SalesQuarter__c
                				where SetupOwnerId =: UserInfo.getOrganizationId()];     
     cqdays= sq[0].Days_In_CQ__c;
  }
     
   
}