force-app/main/default/objects/CustomerKeys__mdt/CustomerKeys__mdt.object-meta.xml
<CustomObject>
    <label>CustomerKey</label>
    <pluralLabel>CustomerKey</pluralLabel>
</CustomObject>

force-app/main/default/objects/CustomerKeys__mdt/fields/key__c.field-meta.xml
<CustomField>
    <fullName>key__c</fullName>
    <label>key</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerKeys__mdt/fields/SiteEducationSite__c.field-meta.xml
<CustomField>
    <fullName>SiteEducationSite__c</fullName>
    <label>SiteEducationSite</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Devices_Students_Use__c.field-meta.xml
<CustomField>
    <fullName>Devices_Students_Use__c</fullName>
    <label>Devices Students Use</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Windows/PC</fullName>
            </value>
            <value>
                <fullName>Chromebook</fullName>
            </value>
            <value>
                <fullName>Macbook</fullName>
            </value>
            <value>
                <fullName>Ipad</fullName>
            </value>
            <value>
                <fullName>Tablet Android</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Devices_You_Use__c.field-meta.xml
<CustomField>
    <fullName>Devices_You_Use__c</fullName>
    <label>Devices Techers Use</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Windows/PC</fullName>
            </value>
            <value>
                <fullName>Chromebook</fullName>
            </value>
            <value>
                <fullName>Macbook</fullName>
            </value>
            <value>
                <fullName>Ipad</fullName>
            </value>
            <value>
                <fullName>Tablet Android</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SpaNumber__c.field-meta.xml
<CustomField>
    <fullName>SpaNumber__c</fullName>
    <label>SpaNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/What_Browsers_do_you_Use__c.field-meta.xml
<CustomField>
    <fullName>What_Browsers_do_you_Use__c</fullName>
    <label>What Browsers do you Use?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chrome</fullName>
            </value>
            <value>
                <fullName>Microsoft Edge</fullName>
            </value>
            <value>
                <fullName>Safari</fullName>
            </value>
            <value>
                <fullName>Firefox</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/What_type_of_Casting_would_you_like__c.field-meta.xml
<CustomField>
    <fullName>What_type_of_Casting_would_you_like__c</fullName>
    <label>What type of Casting would you like</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>myViewBoard</fullName>
            </value>
            <value>
                <fullName>Vcast</fullName>
            </value>
            <value>
                <fullName>Chrome Cast for Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Which_do_you_want_to_focus_on__c.field-meta.xml
<CustomField>
    <fullName>Which_do_you_want_to_focus_on__c</fullName>
    <label>Which do you want to focus on?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>myViewBoard</fullName>
            </value>
            <value>
                <fullName>Android whiteboarding</fullName>
            </value>
            <value>
                <fullName>Tools to use with Mac OS</fullName>
            </value>
            <value>
                <fullName>myViewBoard.com setup</fullName>
            </value>
            <value>
                <fullName>Quickboard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/PriceBook__c.field-meta.xml
<CustomField>
    <fullName>PriceBook__c</fullName>
    <formula>Pricebook2.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>PriceBook</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ordersMasterClass.cls
public class ordersMasterClass{
    // These variables store Trigger.oldMap and Trigger.newMap
    Map<Id, Order> oldOrders;
    Map<Id, Order> newOrders;
    
    List<Order> OrdersToUpdate = new List<Order>();
    // This is the constructor
    // A map of the old and new records is expected as inputs
    public ordersMasterClass(
        Map<Id, Order> oldTriggerOrders, 
        Map<Id, Order> newTriggerOrders) {
            oldOrders = oldTriggerOrders;
            newOrders = newTriggerOrders;
        }
    public void  spaUpdated() {
        //if spa is added to order then the order items will be updated
        
        List<String> ordersToUpdate = new List<String>();
        for(Order o :  newOrders.values()){
            Order old  = oldOrders.get(o.Id);
            if(old.QuoteId != o.QuoteId && o.QuoteId != null){
                ordersToUpdate.add(o.Id);
            } 
        }
        
        List<OrderItem> odi = [Select id, order.quoteid, quotelineitemid, pricebookentryid,
                               Order.SpaNumber__c, 
                               order.pricebook2id, OrderId ,product2Id
                               from orderitem where orderid in : ordersToUpdate];
        
        system.debug('order quote id');
        if(odi.size()> 0){
            system.debug(odi[0].Order.quoteid);
        }else{
            system.debug('no order items found');
        }
        
        
        Map<Id,OrderItem> oi = new Map<Id,OrderItem>();
        
        masterOrderItemClass oc = 
            new masterOrderItemClass(oi,oi);	
        
        system.debug('orderprods found');
        system.debug(odi);
        oc.quoteLine(odi);
        
        
    }

    public void pricebookSet(List<order> records) {
        
        
        
        CustomerKeys__mdt k = [SELECT key__c, SiteEducationSite__c, Pricebook__c  FROM CustomerKeys__mdt  limit 1]; 
        String pricebk = k.Pricebook__c;
        List<Pricebook2> pb = [Select id from pricebook2 where name =: pricebk and isActive = true limit 1 ];
        
        List<String> orders = new List<String>();
        for(Order o : records){
            orders.add(o.SpaNumber__c);
            if(pb.size()>0){
                o.Pricebook2Id = pb[0].Id;
                
            }            
        }
        
        
        
        Map<String,Quote> oppAcct = new Map<String,Quote>();
        List<Id> accts = new List<Id> (); 
        for(Quote q : [Select id, name,OpportunityId,Opportunity.AccountId from quote where name in : orders]){
            oppAcct.put(q.Name, q);
        }
        
        for(Order o : records){
            
            system.debug(orders.size()+ ' size of orders list');
            system.debug(orders);
            if(oppAcct.containsKey(o.spanumber__c)){
                system.debug('orders has spa found');
                Quote q = oppAcct.get(o.spanumber__c);
                system.debug('Account and opp ' +o.SpaNumber__c+' '+q.OpportunityId+' '+q.Opportunity.AccountId );
                o.AccountId = q.Opportunity.AccountId;
                o.Opportunity__c = q.OpportunityId;
                o.QuoteId = q.Id;
                accts.add(q.Opportunity.AccountId);
            }
        }
        
        Map<String,Order> relatedorders = new Map<String,Order>();
        for(order o : [Select  id, AccountId, Devices_Students_Use__c ,Devices_You_Use__c ,
                       What_Browsers_do_you_Use__c , What_type_of_Casting_would_you_like__c , 
                       Which_do_you_want_to_focus_on__c from order where accountid in: accts]){
                           relatedorders.put(o.accountId, o);
                           
                  }
        
        for(Order rod : records){
            if(relatedorders.containsKey(rod.AccountId)){
                Order o = relatedorders.get(rod.Accountid);
                rod.Devices_Students_Use__c = o.Devices_Students_Use__c;
                rod.Devices_You_Use__c = o.Devices_You_Use__c;
                rod.What_Browsers_do_you_Use__c = o.What_Browsers_do_you_Use__c;
                rod.What_type_of_Casting_would_you_like__c = o.What_type_of_Casting_would_you_like__c;
                rod.Which_do_you_want_to_focus_on__c = o.Which_do_you_want_to_focus_on__c;
            }
            
        }

        
    }
}