force-app/main/default/objects/OpportunityLineItem/fields/Landing_Cost2__c.field-meta.xml
<CustomField>
    <fullName>Landing_Cost2__c</fullName>
    <label>Landed Cost</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>if(Approved_Price__c = 0,
((UnitPrice  -  Landed_Cost__c )/UnitPrice),
((Approved_Price__c -  PricebookEntry.Total_Cost__c   )/Approved_Price__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/MarginText__c.field-meta.xml
<CustomField>
    <fullName>MarginText__c</fullName>
    <label>Margin</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/MarginUpdate__c.field-meta.xml
<CustomField>
    <fullName>MarginUpdate__c</fullName>
    <description>0,
&apos;0.00%&apos; !=  MarginText__c,
if(Margin__c&lt; 0 ,
text(round(Margin__c*10000,0)/100)&amp;&apos;.00%&apos; !=  MarginText__c,


if(
text(round(Margin__c*10000,0)/100)&amp;&apos;%&apos; !=  MarginText__c))</description>
    <formula>MarginText__c != marginchecktest__c
&amp;&amp; text(round((Margin__c*100),2))&amp;&apos;%&apos; != MarginText__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MarginUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Landed Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LandedCostChange__c.field-meta.xml
<CustomField>
    <fullName>LandedCostChange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LandedCostChange</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateOppLineItems.cls
global class UpdateOppLineItems implements 
    Database.Batchable<sObject>, Database.Stateful {
    
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;

    global Database.QueryLocator start(Database.BatchableContext bc) {
        return Database.getQueryLocator(
            'SELECT ID FROM OpportunityLineItem Where MarginUpdate__c = true AND '+
            'Product2.IsActive = True AND  Opportunity.Spa_Stage__c != null'
        );
    }

    global void execute(Database.BatchableContext bc, List<OpportunityLineItem> olines){
        // create a list to update each list 
       List<OpportunityLineItem> lineitems = new List<OpportunityLineItem>();
        //loop through a list of lists and set size at 200 each to prevent
        //dml size limit errors
        //
        for(List<OpportunityLineItem> lines : [Select Id,OpportunityId, Opportunity.AccountId,Margin__c,MarginText__c,
                    Landing_Cost2__c,Product2Id, Product2.Cost__c from OpportunityLineItem where Id In: olines
                                              Order By OpportunityId ]){
                     
                     for(OpportunityLineItem Line : lines){
                        line.MarginText__c = String.valueOf(line.Margin__c)+'%';
                        Line.Landing_Cost2__c = Line.Product2.Cost__c;
                        lineitems.add(Line);
              }
               //create a string for error messages
               //update the line items and the clear the line item list
               //send any errors to admin
                                           String  errormessages = '';
                                           TriggerContextUtility.setFirstRunFalse();
                                           List<Database.SaveResult> updateResults = database.update(lineitems, false);
                                           lineitems.clear();
                                                  for(Integer i=0;i<updateResults.size();i++){
                                                      if (!updateResults.get(i).isSuccess()){
                                                          Database.Error error = updateResults.get(i).getErrors().get(0);
                                                            String failedDML = error.getMessage();
                                                            lineitems.get(i);//failed record from the list
                                                            system.debug('Failed ID '+lineitems.get(i).Id); 
                                                            system.debug('Message '+ failedDML);
                                                            errormessages += 'Name: '+lineitems.get(i).Id+'<br/>'+'Error: '+ failedDML+ '<br/><br/>';
                                                          
                                                      }
                                                      
                                                  }
                                          Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
                                          String[] toAddresses = new String[] {Label.AdminEmail};
                                          mail.setToAddresses(toAddresses);
                                          mail.setReplyTo(Label.AdminEmail);
                                          mail.setSenderDisplayName('Apex oppline '+ ' error message');
                                          mail.setSubject('Error from Org : ' + UserInfo.getOrganizationName());
                                          mail.setPlainTextBody(errormessages);
                                          Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            }
                                                 
               
               
               List<Product2> prodToUpdate = new List<Product2>();
               List<Product2> prods = [Select Id from Product2 where LandedCostChange__c = true];
            
               for(Product2 p : prods){
                   p.LandedCostChange__c  = false;
                   prodToUpdate .add(p); 
               }                   
              update prodToUpdate ;    

        
    }    

    global void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records processed. Shazam!');
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
            JobItemsProcessed,
            TotalJobItems, CreatedBy.Email
            FROM AsyncApexJob
            WHERE Id = :bc.getJobId()];
        // call some utility to send email
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {'jason.orbison@viewsonic.com'};
        mail.setToAddresses(toAddresses);
        mail.setReplyTo('jason.orbison@viewsonic.com');
        mail.setSenderDisplayName('Apex Batch Results');
        mail.setSubject('Batch Oppline Items Result: ');
        mail.setPlainTextBody('Errors: ' + job.NumberOfErrors + ' Total Job Items '+ job.TotalJobItems);
        //Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });

    }    

}