force-app/main/default/objects/OpportunityLineItem/fields/Landed_Cost__c.field-meta.xml
<CustomField>
    <fullName>Landed_Cost__c</fullName>
    <formula>PricebookEntry.Product2.Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Landed Cost Formula</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Landing_Cost2__c.field-meta.xml
<CustomField>
    <fullName>Landing_Cost2__c</fullName>
    <label>Landed Cost</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>if(Approved_Price__c = 0,
((UnitPrice  -  Landed_Cost__c )/UnitPrice),
((Approved_Price__c -  PricebookEntry.Total_Cost__c   )/Approved_Price__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/MarginText__c.field-meta.xml
<CustomField>
    <fullName>MarginText__c</fullName>
    <label>Margin</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Landed Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/OpplineItems.cls
public without sharing class OpplineItems
{
    public static void UpdateMarginsfromProducts(List<Product2> records)
    {

    	// add a line item list to update after query
        List<OpportunityLineItem> lineitems = new  List<OpportunityLineItem> ();

        //Query and iterate over a all oppline items that are affected by the change in list prices. 

        for(OpportunityLineItem line : [Select Id, Product2Id,Margin__c,MarginText__c,	ListPrice,	Landing_Cost2__c,
         					Landed_Cost__c,Product2.Cost__c from OpportunityLineItem where Product2Id In: records]){

        	  line.MarginText__c = String.valueOf(line.Margin__c)+'%';
        	  Line.Landing_Cost2__c = Line.Product2.Cost__c;

        	  lineitems.add(line);

         }

         update lineitems;
      
    }
}