force-app/main/default/objects/OpportunityLineItem/fields/MarginUpdate__c.field-meta.xml
<CustomField>
    <fullName>MarginUpdate__c</fullName>
    <description>0,
&apos;0.00%&apos; !=  MarginText__c,
if(Margin__c&lt; 0 ,
text(round(Margin__c*10000,0)/100)&amp;&apos;.00%&apos; !=  MarginText__c,


if(
text(round(Margin__c*10000,0)/100)&amp;&apos;%&apos; !=  MarginText__c))</description>
    <formula>MarginText__c != marginchecktest__c
&amp;&amp; text(round((Margin__c*100),2))&amp;&apos;%&apos; != MarginText__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>MarginUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Landed Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LandedCostChange__c.field-meta.xml
<CustomField>
    <fullName>LandedCostChange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LandedCostChange</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestUpdateLineItems.cls
@isTest
private class TestUpdateLineItems {
	@testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    // Dummy CRON expression: midnight on March 15.
    // Because this is a test, job executes
    // immediately after Test.stopTest().
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';

    static testmethod void testUpdateLineItems() {
       Test.Starttest();
        // Create products with landed cost updates needed
        List<Product2> prods = new List<Product2>();
        for (Integer i=0; i<10; i++) {
            Product2 p = new Product2 (
                Name = 'productcool' + i,
                Family = 'test apex family',
                List_Price__c = 25.00,
                Cost__c = 20.00,
                LandedCostChange__c = true
            );
            prods.add(p);
        }
        insert prods;
        
        /*
        OpportunityLineItem line= [Select id,MarginUpdate__c,OpportunityId from OpportunityLineItem where Product2.Name = 'Apex Test' Limit 1 ];
        
        Opportunity opp = [Select id from Opportunity where id =: line.OpportunityId];
        
        
        update opp;
        */
        Product2 p = [Select Id, Name,Cost__c from Product2 Where Name = 'Apex Test' Limit 1 ];
        p.Cost__c = 20;
        update p;
        
        
        // Get the IDs of the opportunities we just inserted
        Map<Id, Product2> opptyMap = new Map<Id, Product2>(prods);
        List<Id> opptyIds = new List<Id>(opptyMap.keySet());

       
        // Schedule the test job
        //String jobId = System.schedule('ScheduledApexTest',
            //CRON_EXP, 
            //new UpdateOppLineMargins());         
        // Verify the scheduled job has not run yet.
        Test.stopTest();
        
        // Now that the scheduled job has executed,
        // check that our tasks were created
        //lt = [SELECT Id 
            //FROM Task 
            //WHERE WhatId IN :opptyIds];
        //System.assertEquals(opptyIds.size(), 
            //lt.size(), 
            //'Tasks were not created');

    }
}