force-app/main/default/objects/Quote/fields/Auto_Renew__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Auto Renew Flag</description>
    <label>Auto_Renew</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Auto_Renew_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew_End_Date__c</fullName>
    <description>End Date for Auto Renewal request (2 Years from Approval Date)</description>
    <label>Auto_Renew_End_Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Auto_Renew_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Auto_Renew_Start_Date__c</fullName>
    <description>Start Date from Auto Renewal Approval</description>
    <label>Auto_Renew_Start_Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/BR_ManagerId__c.field-meta.xml
<CustomField>
    <fullName>BR_ManagerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manager for the rep that submitted a BR request. This is used in the approval process for BR to route to manager</description>
    <label>BR ManagerId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>CASESAFEID(OpportunityId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Reason_For_Renewal__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Renewal__c</fullName>
    <description>Reason For SPA Auto Renewal Request</description>
    <label>Reason_For_Renewal</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SpaAutoRenewalController.cls
public class SpaAutoRenewalController {
    @AuraEnabled 
    public static quote  getUpdatedQuote(string reason,string currentRecord){
        quote  q = [select id, Reason_For_Renewal__c,Auto_Renew_End_Date__c,Auto_Renew_Start_Date__c,Auto_Renew__c,
                    BR_ManagerId__c from quote where id =:currentRecord];
        User u = [Select id, managerid from user where id =: userinfo.getUserId()];
        
        q.Reason_For_Renewal__c = reason;
        q.BR_ManagerId__c = u.managerId;
        //q.Auto_Renew_Start_Date__c = date.today();
        //q.Auto_Renew_End_Date__c = date.today().addYears(2); 
        //q.Auto_Renew__c = true;
        //commenting out line 8 because the approval final action will control this field
        //commenting line 6 and 7 by changing this update to field update on approval step of the approval process.
        
        update q;
        system.debug('@@@Q-------'+q); 
        
         /////Invoking the Approval process
        //
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitted for SPA Auto Renewal Approval');
        req1.setObjectId(q.id);   // req1.setObjectId(q.OpportunityId__c);
        
        // Submit on behalf of a specific submitter
        //req1.setSubmitterId(unsub.Id); 

        // Submit the record to specific process and skip the criteria evaluation
        req1.setProcessDefinitionNameOrId('SPA_Auto_Renewal_Reques2');
        //req1.setSkipEntryCriteria(true);
        SYSTEM.debug('@@@@@Approval'+req1);
        // Submit the approval request for the account
        try{
        Approval.ProcessResult result = Approval.process(req1);
        }catch(Exception e){
            //throw new AuraHandledException(e.getMessage());
        }
        
        
        return q;
    }
    
}