force-app/main/default/objects/Quote/fields/BR_ManagerId__c.field-meta.xml
<CustomField>
    <fullName>BR_ManagerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manager for the rep that submitted a BR request. This is used in the approval process for BR to route to manager</description>
    <label>BR ManagerId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Business_Reason_for_Bid_Registration__c.field-meta.xml
<CustomField>
    <fullName>Business_Reason_for_Bid_Registration__c</fullName>
    <label>BR Business Reason</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/List_of_Work_Activity_c__c.field-meta.xml
<CustomField>
    <fullName>List_of_Work_Activity_c__c</fullName>
    <label>BR List of Work</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>CASESAFEID(OpportunityId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Scope_of_Bid_Registration__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Bid_Registration__c</fullName>
    <label>BR Scope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Spa_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Spa_Request_Type__c</fullName>
    <defaultValue>&quot;Spa Request&quot;</defaultValue>
    <label>Spa Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spa Request</fullName>
            </value>
            <value>
                <fullName>Bid Register Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateSpaController.cls
public class UpdateSpaController {
    @AuraEnabled 
    public static quote  getQuoteDetails(string currentRecord){
         quote  q = [select id, Business_Reason_for_Bid_Registration__c,Scope_of_Bid_Registration__c, List_of_Work_Activity_c__c,
                      BR_ManagerId__c from quote where id =:currentRecord];
      system.debug('@@@Q-------'+q);
        return q;
    }
     @AuraEnabled 
    public static String  getUpdatedRecord(string currentRecord,string WorkActivity,string ScopeOfBidRegistration,string BusinessReasonforBidRegistration){
      // ResponseItemWrapper resp = new ResponseItemWrapper();
        quote  q = [select id, Spa_Request_Type__c,Business_Reason_for_Bid_Registration__c,OpportunityId__c,Scope_of_Bid_Registration__c, List_of_Work_Activity_c__c,
                    BR_ManagerId__c from quote where id =:currentRecord];
        User unsub = [SELECT Id,managerid FROM User WHERE id = :userInfo.getUserId() limit 1];
        string oppid = q.OpportunityId__c;
        q.Spa_Request_Type__c ='Bid Register Request';
        q.List_of_Work_Activity_c__c = WorkActivity;
        q.Business_Reason_for_Bid_Registration__c = BusinessReasonforBidRegistration;
        q.Scope_of_Bid_Registration__c = ScopeOfBidRegistration;
        q.BR_ManagerId__c = unsub.managerid;
        try{
            update q;
            //resp.SUCCESS = true;
            //resp.oppId = q.OpportunityId__c;
            
        }catch(Exception e){
            //resp.SUCCESS = false;
           // resp.MESSAGE = e.getMessage();
           system.debug(e.getMessage());
           throw new AuraHandledException('There was an error: '+e.getMessage());
        
        }
        
        //Id userId = userInfo.getUserId();
        
        

        system.debug('@@@@@q'+q);
       
        /////Invoking the Approval process
        //
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for approval.');
        req1.setObjectId(q.id);   // req1.setObjectId(q.OpportunityId__c);
        
        // Submit on behalf of a specific submitter
        req1.setSubmitterId(unsub.Id); 
        
        // Submit the record to specific process and skip the criteria evaluation
        req1.setProcessDefinitionNameOrId('Bid_Register_Spa_Request');
        req1.setSkipEntryCriteria(true);
        SYSTEM.debug('@@@@@Approval'+req1);
        // Submit the approval request for the account
        Approval.ProcessResult result = Approval.process(req1);
        
		return oppid;
        
    }
    
   /* public class ResponseItemWrapper{
        @AuraEnabled public Boolean SUCCESS {get;set;}
        @AuraEnabled public Id oppId {get;set;}
        @AuraEnabled public String MESSAGE {get;set;}
    }*/

}