force-app/main/default/objects/Portal_Task__c/Portal_Task__c.object-meta.xml
<CustomObject>
    <label>Partner Portal Task</label>
    <nameField>
        <label>Portal Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PortalOnboardingProgress__c/PortalOnboardingProgress__c.object-meta.xml
<CustomObject>
    <label>Portal Onboarding Progress</label>
    <nameField>
        <label>PortalOnboardingProgress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porta lOnboarding Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PortalOnboardingProgress__c/fields/Partner_Portal_Task__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Portal Task</label>
    <referenceTo>Portal_Task__c</referenceTo>
    <relationshipLabel>Porta lOnboarding Progress</relationshipLabel>
    <relationshipName>Porta_lOnboarding_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PortalOnboardingProgress__c/fields/Portal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Portal_Contact__c</fullName>
    <label>Portal Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Porta lOnboarding Progress</relationshipLabel>
    <relationshipName>Porta_lOnboarding_Progress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/testpp_schOnboardingTaks.cls
@isTest
private class testpp_schOnboardingTaks{
     public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void TestposSerial() {
        
        test.startTest();
        Contact con = [Select id from contact limit 1];
        Portal_Task__c  pt = new Portal_Task__c ();
        pt.Required__c = false;
        pt.Name = 'w9test';
        insert pt;
        
        
        PortalOnboardingProgress__c pp = new PortalOnboardingProgress__c();
        pp.Portal_Contact__c = con.Id;
        pp.Partner_Portal_Task__c = pt.Id;
        insert pp;      
        
        
         // Schedule the test job
        String jobId = System.schedule('ScheduledApexTestAcctAggrPosSerial',
                                       CRON_EXP, 
                                       new pp_schOnboardingTaks());
        Test.stopTest();
        
        
        
    }
}