force-app/main/default/objects/Portal_Task__c/Portal_Task__c.object-meta.xml
<CustomObject>
    <label>Partner Portal Task</label>
    <nameField>
        <label>Portal Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portal_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>AV Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testPortalOnboardTasks.cls
@isTest
private class testPortalOnboardTasks {
     @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    @isTest
    static void testAssignment(){
        test.startTest();
		Contact c = [Select id from contact limit 1];
        Portal_Task__c pt = new Portal_Task__c();
        pt.Active__c = true;
        pt.Required__c = true;
        pt.Type__c = 'Onboarding';
        insert pt;
        String conId = c.Id;
        portalOnboardingAssignTask.assignTaks(conId); 
        test.stopTest();
        
    }
}