force-app/main/default/objects/Order/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Price Book Entries</relationshipLabel>
    <relationshipName>Price_Book_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Inactive.recordType-meta.xml
<RecordType>
    <fullName>Inactive</fullName>
    <active>true</active>
    <label>Inactive</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/Active_Product__c.field-meta.xml
<CustomField>
    <fullName>Active_Product__c</fullName>
    <formula>PricebookEntry.IsActive</formula>
    <label>Active Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/ApprovedPriceHiigherLIst__c.field-meta.xml
<CustomField>
    <fullName>ApprovedPriceHiigherLIst__c</fullName>
    <formula>PricebookEntry.UnitPrice &lt;  Approved_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ApprovedPriceHiigherLIst</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>if(Landed_Cost__c=0,0,
if(Approved_Price__c = 0,
((UnitPrice  -  Landed_Cost__c)/UnitPrice),
((Approved_Price__c - Landed_Cost__c)/Approved_Price__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>PricebookEntry.Product2.ProductCode</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spa_Claims__c/Spa_Claims__c.object-meta.xml
<CustomObject>
    <description>API tool , Informatica, adds records from Oracle when the spa id is found. It links claims with spas</description>
    <label>Spa Claims</label>
    <nameField>
        <label>Spa Claims Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spa Claims</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Spa_Claims__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Spa Claims</relationshipLabel>
    <relationshipName>Spa_Claims</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Spa_Claims__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spa_Claims__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Spa Claims</relationshipLabel>
    <relationshipName>Spa_Claims</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spa_Claims__c/fields/Total_Spa_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Spa_Amount__c</fullName>
    <formula>Quantity__c *  Unit_Selling_Price__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Spa Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Spa_Claims__c/fields/Transaction_Line_Amount__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Line_Amount__c</fullName>
    <label>Transaction Line Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Spa_Claims__c/fields/Unit_Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Selling_Price__c</fullName>
    <label>Unit Selling Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/qproducts.cls
public class qproducts {
        Quote q {get;set;}
        public List<QuoteLineItem> highprods {get;set;}
        public List<Spa_Claims__c> spaclaims {get;set;}
        Public Boolean inactive {get;set;}
        Public Boolean high {get;set;}
        public List<QuoteLineItem> inprods {get;set;}
        public qproducts(ApexPages.StandardController stdController){
            q = (Quote)stdController.getRecord();
            system.debug('quote' +q);
            
        }
        public PageReference getprods()
        { 
            Quote qt = [Select Id,OpportunityId,AccountId from Quote where id =: q.id]; 
            
            highprods = [Select Id,Product2.name,Quantity,Approved_Price__c,ListPrice,Pricebookentry.UnitPrice, Active_Product__c,Margin__c ,Landed_Cost__c  
                         from QuoteLineItem where QuoteId =: q.Id and ApprovedPriceHiigherLIst__c  = true];
            if(highprods.size() > 0){
                high=true;
                    }else{
                        high = false;
                    }
            
            inprods = [Select Id,Product2.name,Quantity,Approved_Price__c,ListPrice,Pricebookentry.UnitPrice, Active_Product__c  
                       from QuoteLineItem where QuoteId =: q.Id and Active_Product__c  = false];
            
            if(inprods.size() > 0){
                inactive=true;
                    }else{
                        inactive = false;
                    }
            
            spaclaims = [Select Id, Product__c , Quantity__c, Order_Date__c ,Creation_Date__c ,Total_Spa_Amount__c,Transaction_Line_Amount__c ,Unit_Selling_Price__c ,Spa_Price__c ,SKU__c,
                          SKU__r.Name,SKU__r.family
                         from Spa_Claims__c where opportunity__c = : qt.OpportunityId order by Order_Date__c  desc];
            
            return null;
        }
     public PageReference uphighprods()
        {
            update highprods;
            return null;
        }
     public PageReference upInactive()
        {
            update inprods;
            return null;
        }
    
        
    }