force-app/main/default/objects/Order/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <formula>Account.Owner.FirstName &amp; Account.Owner.LastName &amp; br() &amp;
Account.Owner.Phone &amp; br() &amp;
Account.Owner.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sales Rep</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <description>Need to Deprectate this object and update associated classes that reference it
TestmyNewQuota
BuildTestData
importDataFromCSVController</description>
    <label>Quota</label>
    <nameField>
        <displayFormat>Quota - {0000000}</displayFormat>
        <label>Quota Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quota</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/Assigned_Quota__c.field-meta.xml
<CustomField>
    <fullName>Assigned_Quota__c</fullName>
    <label>Quota Assigned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Product_Focus_Attainment__c.field-meta.xml
<CustomField>
    <fullName>Product_Focus_Attainment__c</fullName>
    <label>Product Focus Attainment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Product_Focus_Quota__c.field-meta.xml
<CustomField>
    <fullName>Product_Focus_Quota__c</fullName>
    <label>Product Focus Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Quota_Attained__c.field-meta.xml
<CustomField>
    <fullName>Quota_Attained__c</fullName>
    <label>Quota Attained</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quota</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/SPG_Attainment__c.field-meta.xml
<CustomField>
    <fullName>SPG_Attainment__c</fullName>
    <label>SPG Attainment</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/SPG_Quota__c.field-meta.xml
<CustomField>
    <fullName>SPG_Quota__c</fullName>
    <label>SPG Quota</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/importDataFromCSVController.cls
public class importDataFromCSVController {
public Blob csvFileBody{get;set;}
public string csvAsString{get;set;}
public String[] csvFileLines{get;set;}
public List<Quota__c> acclist{get;set;}
  public importDataFromCSVController(){
    csvFileLines = new String[]{};
    acclist = New List<Quota__c>(); 
  }
  
  public void importCSVFile(){
      List<Quota__c>quotatoupdate = new List<Quota__c>(); 
      
      List<Quota__c> quotas = [Select Id,Assigned_Quota__c,Quota_Attained__c,SPG_Quota__c,SPG_Attainment__c,
                       Product_Focus_Quota__c,Product_Focus_Attainment__c,Sales_Rep__c,Sales_Rep__r.Name
                        from Quota__c where Sales_Rep__c != null];
      system.debug(quotas.size());
      try{
           csvAsString = csvFileBody.toString();
           csvFileLines = csvAsString.split('\n'); 
            
           for(Integer i=1;i<csvFileLines.size();i++){
               Quota__c accObj = new Quota__c() ;
               string[] csvRecordData = csvFileLines[i].split(',');
               		for(Quota__c q : quotas){
                        system.debug('rep name '+q.Sales_Rep__r.Name+ ' row1name '+csvRecordData[0]);
                        if(q.Sales_Rep__r.Name == csvRecordData[0] && q.Sales_Rep__c!= null ){                            
                            accObj.Id = q.Id;
                            accObj.Assigned_Quota__c =  integer.valueOf(csvRecordData[1]) ;             
               				accObj.Quota_Attained__c = integer.valueOf(csvRecordData[2]);
              				accObj.SPG_Quota__c = integer.valueOf(csvRecordData[3]) ;             
               				accObj.SPG_Attainment__c = integer.valueOf(csvRecordData[4]);
               				accObj.Product_Focus_Quota__c = integer.valueOf(csvRecordData[5]) ;             
               				accObj.Product_Focus_Attainment__c = integer.valueOf(csvRecordData[6]);
                            quotatoupdate.add(accObj);
                            system.debug('csv name '+csvRecordData[0]+' record name '+q.Sales_Rep__r.Name);
                        }                                 
          			} 
               
               //acclist.add(accObj); 
           }
           system.debug(acclist);
          system.debug('update list' +quotatoupdate);          
          
           upsert quotatoupdate;
        }
        catch (Exception e)
            
        {
            system.debug(e);
            ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured while importin data Please make sure input csv file is correct. Must be csv file,'+
                                                                   'no blanks (replace with 0) and columns must be in order. Sales Rep - Quota Assigned - Quota Attained - SPG Quota - SPG Attainment'+
                                                                  ' - Product Focus Quota - Product Focus Attainment');
            ApexPages.addMessage(errorMessage);
        }  
  }
}