force-app/main/default/objects/BatchQuery__mdt/BatchQuery__mdt.object-meta.xml
<CustomObject>
    <label>BatchQuery</label>
    <pluralLabel>BatchQuerys</pluralLabel>
</CustomObject>

force-app/main/default/objects/BatchQuery__mdt/fields/BatchClass__c.field-meta.xml
<CustomField>
    <fullName>BatchClass__c</fullName>
    <label>BatchClass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BatchQuery__mdt/fields/batchNumber__c.field-meta.xml
<CustomField>
    <fullName>batchNumber__c</fullName>
    <label>batchNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BatchQuery__mdt/fields/fromDate__c.field-meta.xml
<CustomField>
    <fullName>fromDate__c</fullName>
    <label>fromDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/BatchQuery__mdt/fields/ToDate__c.field-meta.xml
<CustomField>
    <fullName>ToDate__c</fullName>
    <label>ToDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/schAssetAccountRevenue.cls
global class schAssetAccountRevenue implements Schedulable {
    global void execute(SchedulableContext ctx) {
        
        BatchQuery__mdt  q = [select id,fromDate__c , toDate__c, batchNumber__c  from BatchQuery__mdt   where BatchClass__c  = 'assetAccountReveneBch' limit 1];
        Integer batchSize = Integer.valueOf(q.batchNumber__c)  ; 
        
        assetAccountReveneBch b = new assetAccountReveneBch(); 
        database.executebatch(b,batchSize);
        
        assetResellerRevenueBatch bres = new assetResellerRevenueBatch(); 
        database.executebatch(bres,batchSize);        
        
    }
    
}