force-app/main/default/objects/SPIFF__c/SPIFF__c.object-meta.xml
<CustomObject>
    <label>Spiff</label>
    <nameField>
        <label>SPIFF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPIFFs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPIFF__c/fields/AV__c.field-meta.xml
<CustomField>
    <fullName>AV__c</fullName>
    <label>AV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPIFF__c/fields/Distrubution__c.field-meta.xml
<CustomField>
    <fullName>Distrubution__c</fullName>
    <label>Distribution</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPIFF__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPIFF__c/fields/NSP__c.field-meta.xml
<CustomField>
    <fullName>NSP__c</fullName>
    <label>NSP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPIFF__c/fields/PriceBook__c.field-meta.xml
<CustomField>
    <fullName>PriceBook__c</fullName>
    <label>PriceBook</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPIFF__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testSpiffToPrices.cls
@isTest
private class testSpiffToPrices {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void getLines()
    {		        
        List<Spiff__c> spiff = new List<Spiff__c>();
         
        List<Pricebookentry> pbedisti = [Select id, pricebook2.name, product2.name from Pricebookentry where isActive = true and pricebook2.name = 'VSA Distributor Price List' limit 1];
        
        Spiff__c sdisti = new Spiff__c (SKU__c = pbedisti[0].product2.name,
                                   SPG__c = 1,
                                   AV__c = 1,
                                   CDW__c = 1,
                                   NSP__c = 1,
                                   Distrubution__c = 1,
                                   ExternalId__c = pbedisti[0].product2.name+pbedisti[0].pricebook2.name,
                                   PriceBook__c = pbedisti[0].pricebook2.name);
        
         spiff.add(sdisti);
        
        List<Pricebookentry> pbecdw = [Select id, pricebook2.name, product2.name from Pricebookentry where isActive = true and pricebook2.name = 'VSA CDW Price List' limit 1];
        
        Spiff__c scdw = new Spiff__c (SKU__c = pbecdw[0].product2.name,
                                   SPG__c = 1,
                                   AV__c = 1,
                                   CDW__c = 1,
                                   NSP__c = 1,
                                   Distrubution__c = 1,
                                   ExternalId__c = pbecdw[0].product2.name+pbecdw[0].pricebook2.name,
                                   PriceBook__c = pbecdw[0].pricebook2.name);
        
         spiff.add(scdw);
        
        List<Pricebookentry> pbeav = [Select id, pricebook2.name, product2.name from Pricebookentry where isActive = true and pricebook2.name = 'VSA AV Solution Partner Price List' limit 1];
        
        //Spiff__c sav = new Spiff__c (SKU__c = pbeav[0].product2.name,
                                   //SPG__c = 1,
                                   //AV__c = 1,
                                   //CDW__c = 1,
                                   //NSP__c = 1,
                                   //Distrubution__c = 1,
                                   //ExternalId__c = pbeav[0].product2.name+pbeav[0].pricebook2.name,
                                   //PriceBook__c = pbeav[0].pricebook2.name);
        
         //spiff.add(sav);
        
        List<Pricebookentry> pbedmr = [Select id, pricebook2.name, product2.name from Pricebookentry where isActive = true and pricebook2.name = 'VSA DMR Price List' limit 1];
        
        //Spiff__c sdmr = new Spiff__c (SKU__c = pbedmr[0].product2.name,
                                   //SPG__c = 1,
                                   //AV__c = 1,
                                   //CDW__c = 1,
                                   //NSP__c = 1,
                                   //Distrubution__c = 1,
                                   //ExternalId__c = pbedmr[0].product2.name+pbedmr[0].pricebook2.name,
                                   //PriceBook__c = pbedmr[0].pricebook2.name);
        
         //spiff.add(sdmr);
        
        
        
        
        insert spiff;
        
        
        test.startTest();
        SpiffToPrices.updateSpiffs();
        test.stopTest();
    }
}