force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Attachments__c.field-meta.xml
<CustomField>
    <fullName>Attachments__c</fullName>
    <label>Attachments</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/EvalAttachmentCount.cls
public class EvalAttachmentCount {
    Map<Id, ContentDocumentLink> oldatt;
    Map<Id, ContentDocumentLink> newatt;
    
    
    public EvalAttachmentCount(
        Map<Id, ContentDocumentLink> oldTriggeratt,
        Map<Id, ContentDocumentLink> newTriggeratt) {
            oldatt = oldTriggeratt;
            newatt = newTriggeratt;
        }
    public static void evalAttach(List<ContentDocumentLink> attch){
        Set<Id> evalId = new Set<Id>();
        for(ContentDocumentLink c : attch){
            evalId.add(c.LinkedEntityId);
        }
        
        List<Eval_Request__c> evalcount = [Select id , Attachments__c  from Eval_Request__c where id in: evalId];
        
        if(evalcount.size() > 0){
            
            for(Eval_Request__c e :evalcount){
                if( e.Attachments__c == null ||  e.Attachments__c == 0){
                    e.Attachments__c = 1;
                }else{
                    e.Attachments__c = e.Attachments__c +1;
                }
            }
            update evalcount;
        }
        
        
    }
}