force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Quote_Sent_Out__c.field-meta.xml
<CustomField>
    <fullName>Eval_Quote_Sent_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eval Quote Sent Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Quote_Product__c.field-meta.xml
<CustomField>
    <fullName>Quote_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EvalRequestMaster.cls
public class EvalRequestMaster {
	public static void QuoteRequest(List<Eval_Request__c> evals) {

		//create a list of quotes, eval requests where quotes have been sent out
		//to cross refrence with child records, units that need update

		List <Eval_Request__c> quotes = new List<Eval_Request__c>();
		
		for(Eval_Request__c e : evals){
			if(e.Eval_Quote_Sent_Out__c == true){
				
				e.Eval_Quote_Sent_Out__c = false;
				quotes.add(e);
				
			}
		}

		//create a list to update all the child records, units, that belong to the eval requests in this trigger meeting
		//the condition of having a eval quote sent out

		List <Eval_Unit_Details__c> unitsToUpdate = new List<Eval_Unit_Details__c>();

		//make sure that there are records in the quotes list
		if(quotes.size() < 0){
			return;
		}

			for(Eval_Unit_Details__c u : [Select Id,Quote_Product__c,Eval_Request__c from Eval_Unit_Details__c where Eval_Request__c In: quotes ]){
				u.Quote_Product__c = false;
				unitsToUpdate.add(u);

			}

			try{

				update unitsToUpdate;
			}catch(Exception e){
            String t = 'Eval Units quote reset';
            AdminErrorMessage.SendError(e,t);

			}
					
	}
}