force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Process_Stage__c.field-meta.xml
<CustomField>
    <fullName>Eval_Process_Stage__c</fullName>
    <defaultValue>&quot;Awaiting Submission Request&quot;</defaultValue>
    <description>Gives stage to all parties to determine where in the process the request is held  up.</description>
    <label>Eval Process Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission Request</fullName>
                <default>true</default>
                <label>Awaiting Submission Request</label>
            </value>
            <value>
                <fullName>Awaiting Approval from Director or VP</fullName>
            </value>
            <value>
                <fullName>Awaiting Upload of Agreement</fullName>
            </value>
            <value>
                <fullName>Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancellation Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Large_Format_Request__c.field-meta.xml
<CustomField>
    <fullName>Large_Format_Request__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This gets updated from a workflow rule in which any large format over 70 inches will be sent through VP approval Process</description>
    <label>Large Format Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_3__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_4__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_5__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2)</booleanFilter>
        <errorMessage>This is a bundle, you must select a non bundle product.

Also Products cannot have -2, -3,-4 in IFP Name. Please use the non dash skus.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>identifies which email to be sent out</description>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding (Not Past Due)</fullName>
                <default>true</default>
                <label>Outstanding (Not Past Due)</label>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Returned/Purchased</fullName>
            </value>
            <value>
                <fullName>Written Off</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Eval_Special_Approval__c.field-meta.xml
<CustomField>
    <fullName>Eval_Special_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if evaluation needs two layer special aprovals</description>
    <label>Eval Special Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/masterEvalUpdate.cls
public class masterEvalUpdate {
    
    Map<Id, Eval_Request__c> oldEvals;
    Map<Id, Eval_Request__c> newEvals;
    
    public masterEvalUpdate(
        Map<Id, Eval_Request__c> oldTriggerEvals,
        Map<Id, Eval_Request__c> newTriggerEvals) {
            oldEvals = oldTriggerEvals;
            newEvals = newTriggerEvals;
        }
    public  void closed()
    {
        for(Eval_Request__c e : newEvals.values()){
            if(e.Product_Status__c == 'Closed' && e.Eval_Process_Stage__c != 'Closed'){
                e.Eval_Process_Stage__c = 'Closed';
            }else if(e.Product_Status__c != 'Closed' && e.Eval_Process_Stage__c == 'Closed'){
                e.Eval_Process_Stage__c = 'Shipped';
            }
        }
        
    }
    public static  void specialApproval(List<Eval_Request__c> evalreq)
    {
        //List<Product2> prods = [Select id,Eval_Special_Approval__c from product2 where  Eval_Special_Approval__c = true];
        
        List<Eval_Request__c> evals = [Select id,Product_Name__r.Eval_Special_Approval__c ,Product_Name_2__r.Eval_Special_Approval__c  ,Product_Name_3__r.Eval_Special_Approval__c
                                       ,Product_Name_4__r.Eval_Special_Approval__c ,Product_Name_5__r.Eval_Special_Approval__c, Large_Format_Request__c  
                                      from Eval_Request__c where id in: evalreq];
        
        for(Eval_Request__c e : evals){
          if(e.Product_Name__r.Eval_Special_Approval__c == true || e.Product_Name_2__r.Eval_Special_Approval__c == true || e.Product_Name_3__r.Eval_Special_Approval__c == true
             || e.Product_Name_4__r.Eval_Special_Approval__c == true || e.Product_Name_5__r.Eval_Special_Approval__c == true ){
                e.Large_Format_Request__c  = true; 
             }else{
                 e.Large_Format_Request__c  = false; 
             }
        }
        
    }
}