force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Shipping_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/searchOjbectsSosl.cls
public with sharing class searchOjbectsSosl {
    @AuraEnabled
    public static List<List<SObject>> getRecId(String recordId){
        
        List<List<SObject>> searchList = new List<List<SObject>>(); 
        
        List<Eval_Request__c> evals = [Select id,name from Eval_Request__c where Billing_Contact_Name__r.AccountId =: recordId or Shipping_Contact_Name__r.AccountId =:recordId];
        
        List<Opportunity> oppids = [Select id from Opportunity where AccountId =: recordId];
        
        List<Quote> spaids = [Select id from Quote where AccountId =: recordId];
        
        List<Contact> cons = [Select id from Contact where AccountId =: recordId];
        
        List<Task> tasks = [Select id,subject,activityDate,type, Description,whatid,whoid,ownerId,Owner.Name from 
                            Task where Type != 'Email' and Type != 'email' and (whatid =:recordId or whatid  in :oppids or whoid  in :cons or whatid  in :spaids ) order by activityDate desc limit 10];
        
        
        List<Event> events = [Select id,subject,activityDate, Description,whatid,whoid,OwnerId,Owner.Name from 
                              Event where whatid =:recordId or whatid  in :oppids or whatid  in :spaids or whoid  in :cons order by activityDate desc limit 10];        
        
        
        List<EmailMessage> mailmsg = [Select id,subject,MessageDate , TextBody ,HtmlBody,ParentId,FromName,fromAddress  from 
                                      EmailMessage where RelatedToId  =:recordId or RelatedToId in :oppids or RelatedToId in :spaids order by MessageDate  desc limit 10];
        
        
        searchList.add(tasks);
        searchList.add(events); 
        searchList.add(mailmsg);
        searchList.add(evals); 
        
        system.debug('rec id '+recordId);
        system.debug(searchList);
        
        return searchList;
        
    }
    
}