force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2)</booleanFilter>
        <errorMessage>This is a bundle, you must select a non bundle product.

Also Products cannot have -2, -3,-4 in IFP Name. Please use the non dash skus.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Testing Field. Will pull from product</inlineHelpText>
    <label>SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Transfer_Requested__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transfer Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestEvalNew.cls
@isTest
private class TestEvalNew {
@testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
static testmethod void getUser()  
  {
      //passed 10.27 
      //
      test.startTest();
      Eval_request__c eval = [Select id,Product_Name__c  from eval_request__c limit 1];
      List<Eval_unit_details__c> units = new  List<Eval_unit_details__c>();
	  Eval_unit_details__c u = new Eval_unit_details__c();
      u.Eval_request__c = eval.Id;
      u.name = '123123434';
      u.Transfer_Requested__c = true;
      u.SKU__c = eval.Product_Name__c;
      units.add(u);
      
      Eval_unit_details__c u1 = new Eval_unit_details__c();
      u1.Eval_request__c = eval.Id;
      u1.name = '12312343422';
      u1.Transfer_Requested__c = true;
      u1.SKU__c = eval.Product_Name__c;
      units.add(u1);
      
      
      insert units;
      
      Eval_request__c evalCheck = [Select id,Product_Name__c,
                              (select id from eval_unit_details__r)  from eval_request__c where id =:  eval.Id];
      for(Eval_unit_details__c ev : evalCheck.eval_unit_details__r){
		ev.Transfer_Requested__c = true;
      }
      
      List<Eval_unit_details__c> unitsUpdate = new  List<Eval_unit_details__c>(evalCheck.eval_unit_details__r);
      update unitsUpdate;
      
      system.debug('eval check size of data ');
      system.debug(evalCheck);
      system.debug(evalCheck.eval_unit_details__r.size());
      system.debug(evalCheck.eval_unit_details__r);
      NewEval.getEval(eval.Id);
      NewEval.getUser();       
      Boolean trade = false;
      NewEval.getTypes(trade);
      trade = true;
      NewEval.getTypes(trade);
     
       
      test.stopTest();
  }

}