force-app/main/default/objects/VSA_Open_Order__c/VSA_Open_Order__c.object-meta.xml
<CustomObject>
    <label>VSA_Open_Orders</label>
    <nameField>
        <label>VSA_Open_Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VSA_Open_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VSA_Open_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oracle_Orders</relationshipLabel>
    <relationshipName>Oracle_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Line_ID__c.field-meta.xml
<CustomField>
    <fullName>Line_ID__c</fullName>
    <externalId>true</externalId>
    <label>Line_ID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Spa_Number__c.field-meta.xml
<CustomField>
    <fullName>Spa_Number__c</fullName>
    <label>Spa Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testAcctConOrderSearch.cls
@isTest
private class testAcctConOrderSearch {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    } 
  
    static testmethod void accountVIP()
    {		        
        test.startTest();
        String spaid = '';
        String ponumber = '';
        
        
        Quote q = [Select id, name,accountid from Quote limit 1];
        VSA_Open_Order__c o = new VSA_Open_Order__c();
        o.Account__c = q.accountId;
        o.PO_Number__c = '1234';
        o.Spa_Number__c = q.name;
        o.Line_ID__c = '423423423';
        insert o;
        
        ponumber = '1234';
        spaid = q.Name;
        getAccountsConsSpa.getAccount(spaid);
        getAccountsConsSpa.getOpportunity(ponumber);
        getAccountsConsSpa.getShippingInstPackingInst(ponumber);
        getAccountsConsSpa.getAccountPO(ponumber);
        getAccountsConsSpa.getShippingInst(ponumber);
        test.stopTest();
    }
}