force-app/main/default/objects/VSA_Open_Order__c/VSA_Open_Order__c.object-meta.xml
<CustomObject>
    <label>VSA_Open_Orders</label>
    <nameField>
        <label>VSA_Open_Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VSA_Open_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VSA_Open_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oracle_Orders</relationshipLabel>
    <relationshipName>Oracle_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Oracle_Orders</relationshipLabel>
    <relationshipName>Oracle_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Oracle_Orders</relationshipLabel>
    <relationshipName>Oracle_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Spa_Number__c.field-meta.xml
<CustomField>
    <fullName>Spa_Number__c</fullName>
    <label>Spa Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpenOrderMasterClass.cls
public class OpenOrderMasterClass{
    // These variables store Trigger.oldMap and Trigger.newMap
    Map<Id, VSA_Open_Order__c> oldOrders;
    Map<Id, VSA_Open_Order__c> newOrders;
    
    List<VSA_Open_Order__c> OrdersToUpdate = new List<VSA_Open_Order__c>();
    // This is the constructor
    // A map of the old and new records is expected as inputs
    public OpenOrderMasterClass(
        Map<Id, VSA_Open_Order__c> oldTriggerOrders, 
        Map<Id, VSA_Open_Order__c> newTriggerOrders) {
            oldOrders = oldTriggerOrders;
            newOrders = newTriggerOrders;
        }
    public void updateLookups(List<VSA_Open_Order__c> records) {
        Set<String> spas = new Set<String>();
        for(VSA_Open_Order__c o : records){
            spas.add(o.Spa_Number__c);
        }
        
        Map<String,Quote> lookups = new Map<String,Quote>();
        for(Quote q : [Select name,opportunityid,id,accountid from quote where name in : spas]){
            lookups.put(q.name ,q);
        }
        
        for(VSA_Open_Order__c ord : records){
            if(lookups.containsKey(ord.Spa_Number__c)){
                Quote q = lookups.get(ord.Spa_Number__c);
                ord.Account__c = q.AccountId;
                ord.Opportunity__c = q.OpportunityId;
                ord.Quote__c = q.Id;
                
            }
        }
        
        
    }
}