force-app/main/default/objects/User_Interactions__c/User_Interactions__c.object-meta.xml
<CustomObject>
    <label>User Interactions</label>
    <nameField>
        <label>User Interaction</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Interactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Interactions__c/fields/Interaction_Name__c.field-meta.xml
<CustomField>
    <fullName>Interaction_Name__c</fullName>
    <label>Interaction Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User_Interactions__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>User_Interactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdminErrorMessage.cls
public class AdminErrorMessage
{
    public static void SendError(Exception e,String t){
    
        User u = [ select Id,Name from User where Id = :UserInfo.getUserId() ];
        if(limits.getEmailInvocations() < 9 ){     

       Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
       String[] toAddresses = new String[] {Label.AdminEmail};
       mail.setToAddresses(toAddresses);
            mail.setReplyTo(Label.AdminEmail);
            mail.setSenderDisplayName('Apex  '+t+ ' error message');
            mail.setSubject('Error from Org : ' + UserInfo.getOrganizationName());
            mail.setPlainTextBody(e.getMessage()+' User'+u.Name);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
          }

          User_Interactions__c ui = new User_Interactions__c (Interaction_Name__c = t,
                                                  User__c = u.Id);         
            insert ui;
            
            
   }
            
}