force-app/main/default/objects/Asset/fields/BundleItem__c.field-meta.xml
<CustomField>
    <fullName>BundleItem__c</fullName>
    <label>BundleItem</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <label>Distributor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets (Distributor Account)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <externalId>true</externalId>
    <label>End User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/End_User_Cleansed__c.field-meta.xml
<CustomField>
    <fullName>End_User_Cleansed__c</fullName>
    <label>End User Cleansed</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/isShipmentData__c.field-meta.xml
<CustomField>
    <fullName>isShipmentData__c</fullName>
    <label>isShipmentData</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <externalId>true</externalId>
    <label>Order #</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <externalId>true</externalId>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <externalId>true</externalId>
    <label>Reseller</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Reseller_Account__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Sold Assets</relationshipLabel>
    <relationshipName>ResellerSoldAssets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/SpaId2__c.field-meta.xml
<CustomField>
    <fullName>SpaId2__c</fullName>
    <label>SpaId2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/SpaId__c.field-meta.xml
<CustomField>
    <fullName>SpaId__c</fullName>
    <externalId>true</externalId>
    <label>SpaId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Spiff_Request__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spiff Request</label>
    <referenceTo>Spiff_Request__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/TP__c.field-meta.xml
<CustomField>
    <fullName>TP__c</fullName>
    <label>TP</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Type 2 or more characters and Press Enter to Search for a Distributor</inlineHelpText>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <errorMessage>Please Use an Account that is the Type Distributor</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Auto_Create_Disti__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>equals</operation>
            <value>Data Visual Marketing</value>
        </filterItems>
        <infoMessage>Press Enter to Search for Distributor Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Distributor)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This ensures that competing distributors are not added to the opportunity partners.</inlineHelpText>
    <label>Partner Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>End_User_Company__c</formula>
    <inlineHelpText>For Reporting. Clean Column and dashboard look</inlineHelpText>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Contact__c.field-meta.xml
<CustomField>
    <fullName>End_User_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The email Address will be attached to the opportunity once an email is attached to the contact</inlineHelpText>
    <label>End User Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (End User Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_Resellers__c.field-meta.xml
<CustomField>
    <fullName>SPA_Resellers__c</fullName>
    <label>SPA Resellers</label>
    <summaryFilterItems>
        <field>Opportunity_Partner__c.Partner_Type__c</field>
        <operation>equals</operation>
        <value>Reseller / VAR</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity_Partner__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>Opportunity__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Quote.Specialty_Spa__c</field>
            <operation>notEqual</operation>
            <value>FTB, Demo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Reseller_Account_Owner__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Account_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Account Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>Opportunity.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/SpaId__c.field-meta.xml
<CustomField>
    <fullName>SpaId__c</fullName>
    <formula>Opportunity.SPA_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SpaId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>Quote.Opportunity.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>PricebookEntry.Product2.ProductCode</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Spa_ID__c.field-meta.xml
<CustomField>
    <fullName>Spa_ID__c</fullName>
    <description>Used for informatica task that matches spa price with spa  claim</description>
    <formula>Quote.Opportunity.SPA_ID__c</formula>
    <label>Spa ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Spiff Requests (Distributor)</relationshipLabel>
    <relationshipName>Spiff_RequestsDisti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Spiff Requests (End User)</relationshipLabel>
    <relationshipName>Spiff_RequestsEU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/End_User_Contact__c.field-meta.xml
<CustomField>
    <fullName>End_User_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End User Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Spiff Requests (End User Contact)</relationshipLabel>
    <relationshipName>Spiff_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/End_User_Email__c.field-meta.xml
<CustomField>
    <fullName>End_User_Email__c</fullName>
    <label>End User Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Spiff RequestsProduct</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requester</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Requester_Company__c.field-meta.xml
<CustomField>
    <fullName>Requester_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requester Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MasterAssetClass.cls
public class MasterAssetClass{
    // These variables store Trigger.oldMap and Trigger.newMap
    Map<Id, Asset> oldAssets;
    Map<Id, Asset> newAssets;
    
    
    public MasterAssetClass(
        Map<Id, Asset> oldTriggerAssets, 
        Map<Id, Asset> newTriggerAssets) {
            oldAssets = oldTriggerAssets;
            newAssets = newTriggerAssets;
        }
    public static void assetNullData(List<Asset> records) {
        for(Asset a : records){
            if(a.order__c == null || a.order__c == ''){a.order__c = 'noOrderNumGiven';
            }}  
        
        
    }
    
    public void spiffRequestClaimed() {
        List<String> spiffs = new List<String>();
        
        for(Asset a :  newAssets.values()){
            Asset old = oldAssets.get(a.Id);
            if(a.Spiff_Request__c != old.Spiff_Request__c && a.Spiff_Request__c != null){
                spiffs.add(a.Spiff_Request__c);
            }
        }
        
        Map<String,Spiff_request__c> spiffData = new Map<String,Spiff_request__c>();
        for(Spiff_request__c sp : [Select id,Requester_Company__c ,End_User__c ,
                                   End_User_Email__c , Distributor__c ,Requester__c , End_User_Contact__c
                                   from Spiff_request__c where id in: spiffs]){
                                       spiffData.put(sp.Id,sp);
                                   }
        
        Account vsa = [Select id,name from account where name = 'ViewSonic Corporation' and Type = 'End User' limit 1];
        system.debug('vsa '+vsa);
        Account testA = new Account();
        system.debug('spiff info '+spiffData );
        system.debug('asset info '+ newAssets.values());
        for(Asset a :  newAssets.values()){            
            if(spiffData.containsKey(a.Spiff_Request__c))  {
                Spiff_Request__c s = spiffData.get(a.Spiff_Request__c);
                if(a.Distributor_Account__c == null){
                    a.Distributor_Account__c = s.Distributor__c;
                }
                if(a.Reseller_Account__c == null){
                    a.Reseller_Account__c = s.Requester_Company__c;                     
                }
                if(a.AccountId == vsa.Id || a.AccountId == '0011200001Dq2NAAAZ'){
                    system.debug('update accId '+ s.End_User__c);
                    a.AccountId = s.End_User__c;
                }
                if(a.contactId == null){
                    a.contactId = s.End_User_Contact__c;
                }
            } 
        }
        
    }
    public static void newAsset(List<Asset> records) {
        // Clean the formatting of the spas 
        // Create a list of spas in order to get account ids
        // Also update the asset with cleaned up spa
        // 
        Set<String> spas = new Set<String>();
        Set<String> aliases = new Set<String>();
        Set<String> endUserCleansed = new Set<String>();
        Set<String> prods = new Set<String>();
        Set<String> SerialTest = new Set<String>();
        
        
        
        
        
        
        Account viewsonic = [Select id from account where name = 'ViewSonic Corporation' limit 1];
        
        for(Asset s : records){
            prods.add(s.Product__c);            
            if(s.isShipmentData__c == 'TRUE'){
                SerialTest.add(s.SerialNumber);
            }
            
            if(s.BundleItem__C != null && s.BundleItem__C != ''){
                String prod = s.product__c.left(s.product__c.indexOf('-'));
                String bund = s.BundleItem__c.left(s.BundleItem__c.indexOf('-'));
                if(prod != bund){
                    s.Price = 0;
                }
            }
            
            
            s.AccountId = viewsonic.Id;
            if(s.SpaId__c != null){
                String spa = s.SpaId__c.toUpperCase() ;
                spa = spa.remove(' ');
                spa = spa.remove('/');
                spa = spa.remove('BR');
                spa = spa.remove('ACC');
                spa = spa.remove('-');
                spa = spa.remove('/');
                s.SpaId__c  = spa;
                spas.add(spa);
            }else  if(s.SpaId2__c != null){
                String spa = s.SpaId2__c.toUpperCase();
                spa = spa.remove(' ');
                spa = spa.remove('/');
                spa = spa.remove('BR');
                spa = spa.remove('ACC');
                spa = spa.remove('-');
                spa = spa.remove('/');
                s.SpaId__c  = spa;
                spas.add(spa);
            }
            if(s.End_User_Cleansed__c != '' && s.End_User_Cleansed__c != null && s.End_User_Cleansed__c != ' '){
                s.End_User__c = s.End_User_Cleansed__c; 
            }
            
            aliases.add(s.TP__c);
            aliases.add(s.Reseller__c);
            aliases.add(s.End_User__c);
            endUserCleansed.add(s.End_User__c );
            
            if(s.product__c != null &&  (s.product__c.toUpperCase().startsWith('IFP') ||
                                         s.product__c.toUpperCase().startsWith('VA2252SM') ||
                                         s.product__c.toUpperCase().startsWith('VA2452SM') ||
                                         s.product__c.toUpperCase().startsWith('VA2452SM') ||
                                         s.product__c.toUpperCase().startsWith('VG2239SMH') ||
                                         s.product__c.toUpperCase().startsWith('VG2439SMH'))
               && (s.product__c.toUpperCase().endsWith ('-2') || s.product__c.toUpperCase().endsWith ('-3')
                   || s.product__c.toUpperCase().endsWith ('-3'))){
                       s.Product__c = s.product__c.removeEndIgnoreCase('-2');
                       s.Product__c = s.product__c.removeEndIgnoreCase('-3');
                       s.Product__c = s.product__c.removeEndIgnoreCase('-4');
                   }  
            
            prods.add(s.Product__c);
            
        }
        
        // get map of opportunities with the account id as the key to update assets end user account info
        // 
        system.debug('oppquery');
        Map<String, Opportunity> opps = new Map<String,Opportunity>();
        for(Opportunity o : [Select id, AccountId, Spa_ID__c, SPA_Resellers__c ,
                             (Select partner_account__c,Partner_account__r.Name from Opportunity_partners__r 
                              where Partner_Type__c = 'Reseller / VAR'
                              and opportunity__r.SPA_Resellers__c =1)
                             from opportunity 
                             where Spa_ID__c in : spas
                             and Spa_ID__c != null]){
                                 opps.put(o.SPA_ID__c , o);  
                             }
        
        
        
        
        // mapping the product
        Map<String, Product2> prodMap = new Map<String,Product2>();
        
        for(Product2 p : [Select id,name from Product2 
                          where name in : prods]){
                              prodMap.put(p.Name , p);  
                          } 
        
        
        
        //get map of reseller and distributor account aliases to map the Account Names
        Map<String,POSAccountAliases__c> distis = new Map<String,POSAccountAliases__c>();
        Map<String,POSAccountAliases__c> resellers = new Map<String,POSAccountAliases__c>();
        Map<String,POSAccountAliases__c> endusers = new Map<String,POSAccountAliases__c>();
        system.debug('pos query');
        for(POSAccountAliases__c p:  [Select id, DistributorAlias__c ,Reseller_Alias__c,End_User_Alias__c,
                                      SFDC_Account__c  from POSAccountAliases__c  where (DistributorAlias__c in : aliases
                                                                                         or Reseller_Alias__c in : aliases
                                                                                         or End_User_Alias__c in : aliases)
                                      and name != null
                                      limit 5000]){
                                          distis.put(p.DistributorAlias__c , p);
                                          resellers.put(p.Reseller_Alias__c , p);
                                          endusers.put(p.End_User_Alias__c, p);
                                      }
        
        //get map of end user aliases from end user cleansed
        Map<String, Account> acc = new Map<String,Account>();
        
        system.debug('acct eu clensed query');
        for(Account o : [Select id,POS_Alias__c,assetChange__c   from Account where POS_Alias__c  in : endUserCleansed and
                         POS_Alias__c != null limit 2000]){
                             acc.put(o.POS_Alias__c , o);
                             
                         } 
        
        for(Asset a : records){
            
            if(distis.containsKey(a.TP__c )){
                POSAccountAliases__c o = distis.get(a.TP__c );
                a.Distributor_Account__c  = o.SFDC_Account__c;
            }
            if(resellers.containsKey(a.Reseller__c) && a.Reseller__c != null){
                POSAccountAliases__c res = resellers.get(a.Reseller__c );
                a.Reseller_Account__c  = res.SFDC_Account__c;
                
            }
            if(opps.containsKey(a.SpaId__c )){
                Opportunity o = opps.get(a.SpaId__c);
                a.AccountId = o.AccountId;
                a.Opportunity__c = o.Id;
                if(a.Reseller_Account__c == null && o.Opportunity_partners__r.size()>0){
                    a.Reseller_Account__c = o.Opportunity_partners__r[0].partner_account__c;
                    a.Reseller__c = o.Opportunity_partners__r[0].Partner_account__r.Name;
                }
            }
            //only use this map if spa was not found 
            if( a.Id != viewsonic.Id){
                // checking if account POSAlias is present
                if(acc.containsKey(a.end_user__c)){
                    Account eu = acc.get(a.end_user__c );
                    a.AccountId  = eu.Id;
                    // checking if  POSAlias object has record 
                }else if(endusers.containsKey(a.end_user__c)){
                    POSAccountAliases__c eua = endusers.get(a.end_user__c );
                    a.AccountId  = eua.SFDC_Account__c;
                }
            }
            
            if(prodMap.containsKey(a.product__c )){
                Product2 pr = prodMap.get(a.product__c );
                a.Product2Id   = pr.Id;
                prods.add(pr.Id);
            }
            
        }
        Map<Id,Account> accts = new Map<Id,Account>();
        
        for(Asset a : records){
            system.debug('adding account to map asset');
            Account euact = new Account();
            euact.Id = a.AccountId;
            euact.assetChange__c = true;      
            accts.put(euact.Id, euact);
            
            if(a.Reseller_Account__c == null){              
                Account resact = new Account();
                resact.Id = a.AccountId;
                resact.assetChange__c = true;
                accts.put(resact.Id, resact);
            }
        }
        system.debug('aasset acct map');
        system.debug(accts);
        update accts.values();
        
        Map<String,Asset> existingSerials = new Map<String,Asset>();
        for(Asset a : [Select id, serialnumber from asset where serialnumber in : SerialTest]){
            existingSerials.put(a.SerialNumber, a);
        }
        Set<Id> assetsToDelete = new Set<Id>();
        for(Asset s : records){            
            if(s.isShipmentData__c == 'TRUE'){
                if(existingSerials.containsKey(s.SerialNumber )){
                    if(existingSerials.get(s.SerialNumber).Id != s.Id){
                        s.addError('This serial is already in system');
                        
                        //assetsToDelete.add(s.Id);
                        
                    }
                    
                }
            }
            
        }
        
        
        //mapping for quotelines
        Map<String,QuoteLineItem> lines = new Map<String,QuoteLineItem>();
        for(QuoteLineItem q : [Select id, quote.name, Product2Id,quote.Opportunity.SPA_ID__c from quotelineitem where Product2Id in : prods
                               and quote.Opportunity.SPA_ID__c in: spas order by quote.expirationdate desc  nulls last ]){
                                   String quoteId = q.quote.Opportunity.SPA_ID__c+q.Product2Id;
                                   lines.put(quoteId,q); 
                                   system.debug('spa name and product '+ quoteId);
                               }
        
        for(Asset a : records){
            String lineKey = a.SpaId__c+a.Product2Id;
            system.debug('spa line key '+lineKey+ ' sn '+a.SerialNumber);
            if(lines.containsKey(lineKey)){
                QuoteLineItem ql = lines.get(lineKey);
                a.Spa_Product__c = ql.Id;
            }
        }
        
        
    }
    @future
    public static void assetToDelete(Set<Id> records) {
        List<Asset> ass = [select id from Asset where id in : records];
        delete ass;
        
    }
}