force-app/main/default/objects/Asset/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <label>Distributor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Assets (Distributor Account)</relationshipLabel>
    <relationshipName>Assets1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <externalId>true</externalId>
    <label>End User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <externalId>true</externalId>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Reseller_Account__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Sold Assets</relationshipLabel>
    <relationshipName>ResellerSoldAssets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Spiff_Request__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spiff Request</label>
    <referenceTo>Spiff_Request__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Spiff Requests (Distributor)</relationshipLabel>
    <relationshipName>Spiff_RequestsDisti</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Spiff Requests (End User)</relationshipLabel>
    <relationshipName>Spiff_RequestsEU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/End_User_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>End_User_Contact_Last_Name__c</fullName>
    <label>End User Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/End_User_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>End_User_Contact_Name__c</fullName>
    <label>End User Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/End_User_Email__c.field-meta.xml
<CustomField>
    <fullName>End_User_Email__c</fullName>
    <label>End User Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Spiff RequestsProduct</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requester</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Requester_Company__c.field-meta.xml
<CustomField>
    <fullName>Requester_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requester Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Sale_Date__c.field-meta.xml
<CustomField>
    <fullName>Sale_Date__c</fullName>
    <label>Sale Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/testSerialNumberSearch.cls
@isTest
private class testSerialNumberSearch {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    } 
  
    static testmethod void getAssetstest()
    {		        
         test.startTest();
        
        List<Account> a = [Select id,name from account limit 2];
        List<Account> dist = [Select id,name from account where 
                              type = 'Distributor' limit 2];
        product2 prod = [Select id,name from product2 where isactive = true limit 1];
        Contact con = [Select id from Contact limit 1];
        
        Asset ab = new Asset();
        ab.purchasedate = date.today();
        ab.AccountId = a[0].Id;
        ab.Distributor_Account__c = dist[0].Id;
        ab.Reseller_Account__c = a[0].Id;
        ab.Product2Id = prod.Id;
        ab.Name = prod.name;
        insert ab;
        
        Spiff_Request__c s = new Spiff_Request__c();
        s.Sale_Date__c = date.today();
        s.product__c = prod.Id;
        s.Distributor__c = dist[0].Id;
        s.Requester_Company__c = a[0].Id;
        s.End_User__c = a[0].Id;
        s.Quantity__c = 1;
        s.Requester__c = con.Id;
        s.End_User_Email__c = 'johnsmith@nowhere.com';
        s.End_User_Contact_Name__c = 'john';
        s.End_User_Contact_Last_Name__c = 'smith';
        insert s;
        
        String wherestmnt= '';
        String addfields= '';
        String orderstmnt= '';
        String spiffId= '';
        String limitstmt= '';
        String spaId = '';
        Boolean spiffSearch= false;  
        
       
        List <Asset> records = getAssetSearch.getSerialNumber(wherestmnt, addfields, orderstmnt, spiffId, limitstmt, spiffSearch,spaId);
        
        spiffId = s.Id;
        getAssetSearch.getSerialNumber(wherestmnt, addfields, orderstmnt, spiffId, limitstmt, spiffSearch,spaId);
        getAssetSearch.updateSpiffs(wherestmnt, addfields, orderstmnt, spiffId, limitstmt, spiffSearch,records,spaId);
        test.stopTest();
    }
}