force-app/main/default/objects/Asset/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <label>Distributor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <externalId>true</externalId>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <externalId>true</externalId>
    <label>Reseller</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/SpaId__c.field-meta.xml
<CustomField>
    <fullName>SpaId__c</fullName>
    <externalId>true</externalId>
    <label>SpaId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Type 2 or more characters and Press Enter to Search for a Distributor</inlineHelpText>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <errorMessage>Please Use an Account that is the Type Distributor</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Auto_Create_Disti__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>equals</operation>
            <value>Data Visual Marketing</value>
        </filterItems>
        <infoMessage>Press Enter to Search for Distributor Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Distributor)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PosSerialNumber__c/PosSerialNumber__c.object-meta.xml
<CustomObject>
    <description>Reviewed 7.19.2021 this object is needed as it is a temporary memory for pos spa information that is used it the serial number update process.</description>
    <label>PosSerialNumber</label>
    <nameField>
        <label>PosSerialNumber Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PosSerialNumbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PosSerialNumber__c/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <label>Reseller</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PosSerialNumber__c/fields/SaleDate__c.field-meta.xml
<CustomField>
    <fullName>SaleDate__c</fullName>
    <label>SaleDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PosSerialNumber__c/fields/SpaIdKey__c.field-meta.xml
<CustomField>
    <fullName>SpaIdKey__c</fullName>
    <formula>BLANKVALUE(SpaId__c, SpaId2__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SpaIdKey</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PosSpaBatch.cls
global class PosSpaBatch implements 
Database.Batchable<sObject>, Database.Stateful {
    
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        //This will batch class will run on Monday Night and add assets
        //and then on tuesday morning, there will be an update on the account level
        //as a summary. 
        
        
        return Database.getQueryLocator(
            'select id,Distributor__c ,Product__c ,Reseller__c ,Revenue__c , SaleDate__c ,Serial_Number__c, SpaId__c , SpaIdKey__c   from PosSerialNumber__c'
        );
    }
    
    global void execute(Database.BatchableContext bc, List<PosSerialNumber__c> sers){
        //
        //Need to get records of object and then clean up the spaid to take away any spaces, text, or special characters. It should only
        //be numeric values. We will then use the spa id to map the accountid for the deal
        //then insert as assest the record
        //then delete the records in pos serial number
        //because it is a pass through for pos serial numbers, alllowing post
        //processing on informatica
        //
        

        Set<String> spas = new Set<String>();
                
        for(PosSerialNumber__c s : sers){
            String spa = s.SpaIdKey__c ;
            
            spa = spa.remove(' ');
            spa = spa.remove('/');
            spa = spa.remove('br');
            spa = spa.remove('acc');
            spa = spa.remove('-');
            spa = spa.remove('/');
            
            s.SpaId__c  = spa;
            spas.add(spa);
            
        }
                
        Set<Id> acc = new Set<Id>();        
        Map<String, Opportunity> opps = new Map<String,Opportunity>();
        
        for(Opportunity o : [Select id, AccountId, Spa_ID__c from opportunity where Spa_ID__c in : spas]){
            opps.put(o.SPA_ID__c , o);
            acc.add(o.AccountId);      
        }     
        
        List<Asset> serials = new List<Asset>();
        for(PosSerialNumber__c s : sers){
            if(opps.containsKey(s.SpaId__c)){
                Opportunity o = opps.get(s.SpaId__c);
                
                Asset a = new Asset();
                a.AccountId = o.AccountId;
                a.SerialNumber = s.Serial_Number__c;
                a.Product__c  = s.Product__c;
                a.PurchaseDate = s.SaleDate__c;
                a.Price = s.Revenue__c;
                a.Reseller__c = s.Reseller__c;
                a.Distributor__c = s.Distributor__c;
                a.name = s.Serial_Number__c;
                serials.add(a);

            }
        }        
        insert serials;
        delete sers;
        
    }    
    
    global void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records processed. disaster averted!');
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
                            JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
        system.debug(job);
    }    
    
}