force-app/main/default/objects/Asset/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <externalId>true</externalId>
    <label>End User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Spiff_Request__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spiff Request</label>
    <referenceTo>Spiff_Request__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>End User</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Spiff Requests (End User)</relationshipLabel>
    <relationshipName>Spiff_RequestsEU</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testSchBatchSerialsSpiffs.cls
@IsTest
//this is a class for api to EA so need to do see all data
private class testSchBatchSerialsSpiffs{
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';   
    static testmethod void schposCYtest() {        
        test.startTest();
        // Schedule the test job
        // 
        String vsacctid = [Select id from account where name = 'ViewSonic Corporation' limit 1].Id;
        Spiff_request__c spiff = [Select id, name from Spiff_request__c  
                                   where End_User__c != null limit 1];
        
        Asset ass = new Asset();
        ass.Spiff_Request__c = spiff.Id;
        ass.accountId = vsacctid;
        ass.SerialNumber = 'test12342347029348023';
        ass.name = 'test12342347029348023';
        insert ass;
        
        
        String jobId = System.schedule('schSerialsSpiffs',
                                       CRON_EXP, 
                                       new schBatchSerialsEndUserResellerSpiffs());
        Test.stopTest();
    }
    
    
}