force-app/main/default/objects/Asset/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <externalId>true</externalId>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Spiff_Request__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spiff Request</label>
    <referenceTo>Spiff_Request__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/TP__c.field-meta.xml
<CustomField>
    <fullName>TP__c</fullName>
    <label>TP</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/finchLegacySerialNumbers__c/finchLegacySerialNumbers__c.object-meta.xml
<CustomObject>
    <label>finchLegacySerialNumbers</label>
    <nameField>
        <label>finchLegacySerialNumbers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>finchLegacySerialNumbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/finchLegacySerialNumbers__c/fields/legacySpiffId__c.field-meta.xml
<CustomField>
    <fullName>legacySpiffId__c</fullName>
    <label>legacySpiffId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/finchLegacySerialNumbers__c/fields/SaleDate__c.field-meta.xml
<CustomField>
    <fullName>SaleDate__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>SaleDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/finchLegacySerialNumbers__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <externalId>true</externalId>
    <label>SerialNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/finchLegacySerialNumbers__c/fields/Spiff_Request__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spiff Request</label>
    <referenceTo>Spiff_Request__c</referenceTo>
    <relationshipLabel>finchLegacySerialNumbers</relationshipLabel>
    <relationshipName>finchLegacySerialNumbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/fields/Legacy_Spiff_Claim_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Spiff_Claim_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Spiff Claim Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Spiff RequestsProduct</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/queueAddSerialNumber.cls
public class queueAddSerialNumber implements Queueable {
    private List<finchLegacySerialNumbers__c> spiffs;
    public queueAddSerialNumber(List<finchLegacySerialNumbers__c> noSerial) {
        this.spiffs = noSerial;
    }
    public void execute(QueueableContext context) {
        
        List<Account> vs = [Select id, name from account where name = 'ViewSonic Corporation' limit 1];
        Set<String> pr = new Set<String>();
        Map<String,Product2> prod = new Map<String,Product2>();
        Set<String> legacy = new Set<String> ();
        for(finchLegacySerialNumbers__c f : spiffs){
            pr.add(f.Product__c);
            legacy.add(f.legacySpiffId__c);
        }
        /*
        
        for(Product2 p : [Select id, name from Product2 where name in : pr]){
            prod.put(p.name, p);
        }
       */
        
        Map<String,Spiff_Request__c> spiff = new Map<String,Spiff_Request__c>(); 
        for(Spiff_Request__c s : [Select id, Legacy_Spiff_Claim_Id__c  from Spiff_Request__c where Legacy_Spiff_Claim_Id__c  in: legacy ]){
            spiff.put(s.Legacy_Spiff_Claim_Id__c , s);
        } 
        
        
        List<Asset> newSerials = new List<Asset>();
        for( finchLegacySerialNumbers__c f : spiffs ){
            Spiff_Request__c s = new Spiff_Request__c ();           
            if(spiff.containsKey(f.legacySpiffId__c)){
                s = spiff.get(f.legacySpiffId__c);
            }
            
            
            Asset a = new Asset();
            a.TP__c = 'spiffLegacy';
            a.name = 'spiffLegacy';
            a.AccountId = vs[0].Id;
            a.serialnumber = f.SerialNumber__c;
            a.Product__c = f.Product__c;
            a.PurchaseDate = f.SaleDate__c;
            a.Spiff_Request__c = s.Id;
            newSerials.add(a);
		
        }

        insert newSerials;
        
    }
    
}