force-app/main/default/objects/Asset/fields/Reseller_Account__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Reseller Sold Assets</relationshipLabel>
    <relationshipName>ResellerSoldAssets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Spiff_Request__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spiff Request</label>
    <referenceTo>Spiff_Request__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/fields/Requester_Company__c.field-meta.xml
<CustomField>
    <fullName>Requester_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requester Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/getAssetSearch.cls
public without sharing class getAssetSearch {
    @AuraEnabled
    public static List<Asset> getSerialNumber(String wherestmnt,String addfields,
                                              string orderstmnt,String spiffId,
                                              String limitstmt,Boolean spiffSearch,
                                             String spaId){       
        system.debug('spiff is ' +spiffId);
        system.debug('where is ' +wherestmnt);
        system.debug('order is ' +orderstmnt);
        system.debug('limit is ' +limitstmt);
                                                  
		if(limitstmt == null){
            limitstmt = ' limit 100';
		} 
                                                  
		if(wherestmnt == null){
            wherestmnt = ' ';
		} 
        if(orderstmnt == null){
            orderstmnt = ' ';
		} 
                                                  
        system.debug('where is ' +wherestmnt);
        system.debug('order is ' +orderstmnt);
        system.debug('limit is ' +limitstmt);
        DescribeSObjectResult describeResult = Asset.getSObjectType().getDescribe();        
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
        
        //if spiff page, use the spiff info to search just spiffs.         
        String resellerParent = '';
        
        system.debug('spiff id '+spiffId );
        if(spiffId == null || spiffId == ''){
            //do nothing 
            system.debug('spiff id does not exist');
        } else{
            Account a = [Select id, name, parentId from account where id in
                         (Select Requester_Company__c from Spiff_Request__c where id = : SpiffId) limit 1];
            if(a.parentId == null ){
                resellerParent = a.Id;
            }else{
                resellerParent = a.ParentId;
            }
        }
        
        system.debug('parent id '+ resellerParent);
        
        
        if(spiffSearch){
           wherestmnt =  ' WHERE Reseller_Account__c = : resellerParent ';
        }
         system.debug('where statement'+ wherestmnt);
        
        String query =		  ' SELECT ' +		      String.join( fieldNames, ',' ) +	addfields +	  ' FROM '
            +		      describeResult.getName()	+ wherestmnt+ orderstmnt+limitstmt;		
        // return generic list of sobjects or typecast to expected type
        // 
        system.debug('query below');
        system.debug(query);
        system.debug(query.substring(286));
        system.debug(query.substring(572));
        system.debug(query.substring(750));
        
        List<Asset> records = Database.query( query );		
        System.debug( records );
        
        return records;
    }
    
     @AuraEnabled
    public static List<Asset> updateSpiffs(String wherestmnt,String addfields,
                                              string orderstmnt,String spiffId,
                                              String limitstmt,Boolean spiffSearch,List<Asset> serials,String SpaId){
                                                  for(Asset a : serials){
                                                      a.Spiff_Request__c = spiffId;
                                                  }
                                                  
                                                  update serials;
                                                  system.debug('update worked ');
                                                  /*
                                                  try{
                                                      serials = getAssetSearch.getSerialNumber(wherestmnt, addfields, orderstmnt, spiffId, limitstmt, spiffSearch,spaId);  
                                                  }catch(Exception e){
                                                      serials = getAssetSearch.getSerialNumber(wherestmnt, addfields, orderstmnt, spiffId, limitstmt, spiffSearch,spaId);
                                                  }
                                                */
     
     return serials;
                                              }
    
}