force-app/main/default/objects/Asset/fields/SerialLine__c.field-meta.xml
<CustomField>
    <fullName>SerialLine__c</fullName>
    <description>Concatenation of Serial Number and  Line Id. This will be the unique id for upsert calls when we add new resellers or updating other columns of data.</description>
    <externalId>true</externalId>
    <label>SerialLine</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Asset/fields/Spiff_Request__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spiff Request</label>
    <referenceTo>Spiff_Request__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/testPPSerialUploadCSV.cls
@isTest
private class testPPSerialUploadCSV{
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void TestposSerial() {
        
        test.startTest();
        Account a = [Select id from account limit 1];
        Asset ass = new Asset();
        ass.AccountId = a.Id;
        ass.SerialNumber = 'testing123letsgo';
        ass.Name = 'testing123letsgo';
        ass.SerialLine__c = 'testing123letsgo';
        ass.PurchaseDate = date.today();
        ass.name ='test';
        insert ass;
        String spiff = [Select Name from spiff_request__c limit 1].Name;

        String str = 'SerialNumber,Spiff Request\ntesting123letsgo,'+spiff+
        '\nserailnumber2,spiff223';
        Blob csvFileBody = Blob.valueOf(str);

        ContentVersion cv1 = new ContentVersion(
                Title='SampleTitle', 
                PathOnClient ='SampleTitle.csv',
                VersionData = csvFileBody, 
                origin = 'H'
            );
            insert cv1;
            
           //String versId = cv1.Id; 
           ContentVersion vers =  [Select id, contentDocumentId from ContentVersion
           where id =:cv1.Id
           limit 1]; 
            String contid = vers.contentDocumentId;
            system.debug('the content version id '+ cv1.Id+' document Id '+contid);
            String recordId = [Select id from spiff_request__c limit 1].Id;
            try{
                fileUploadCSV.csvFileRead(contid,recordId);
            }catch(Exception ex){
                system.debug('there was an excption on the insert with record id'+ ex.getMessage());
            }
            recordId = null;
            system.debug('cv1 id '+ cv1.Id);
            try{
                fileUploadCSV.csvFileRead(contid,recordId);
            }catch(Exception ex){
                system.debug('there was an excption on the insert without recordid '+ ex.getMessage());
            }
            

        Test.stopTest();
        
        
        
    }
}