force-app/main/default/objects/Asset/fields/Spiff_Request__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spiff Request</label>
    <referenceTo>Spiff_Request__c</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/TP__c.field-meta.xml
<CustomField>
    <fullName>TP__c</fullName>
    <label>TP</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/finchLegacySerialNumbers__c/finchLegacySerialNumbers__c.object-meta.xml
<CustomObject>
    <label>finchLegacySerialNumbers</label>
    <nameField>
        <label>finchLegacySerialNumbers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>finchLegacySerialNumbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/finchLegacySerialNumbers__c/fields/legacySpiffId__c.field-meta.xml
<CustomField>
    <fullName>legacySpiffId__c</fullName>
    <label>legacySpiffId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/finchLegacySerialNumbers__c/fields/SaleDate__c.field-meta.xml
<CustomField>
    <fullName>SaleDate__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>SaleDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/finchLegacySerialNumbers__c/fields/SerialNumber__c.field-meta.xml
<CustomField>
    <fullName>SerialNumber__c</fullName>
    <externalId>true</externalId>
    <label>SerialNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/finchLegacySerialNumbers__c/fields/Spiff_Request__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spiff Request</label>
    <referenceTo>Spiff_Request__c</referenceTo>
    <relationshipLabel>finchLegacySerialNumbers</relationshipLabel>
    <relationshipName>finchLegacySerialNumbers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/fields/Legacy_Spiff_Claim_Id__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Spiff_Claim_Id__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Spiff Claim Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testLegacyFinchSpiffSerials.cls
@IsTest
public class testLegacyFinchSpiffSerials  {
   @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    
    Static testmethod void testMasterTrigger() {
        
        test.startTest();
        //build test data will cover the class currently. This is set up for future testing
        //on the master class
        List<Account> vs = [Select id, name from account where name = 'ViewSonic Corporation' limit 1];
        
        Asset vsa = new Asset();
        vsa.TP__c = 'disti';
        vsa.name = 'vsa';
        vsa.AccountId = vs[0].Id;
        vsa.serialnumber = '234w4r4445';
        insert vsa;
        
        Spiff_request__c spiff = [Select id,Legacy_Spiff_Claim_Id__c from Spiff_request__c limit 1];
        spiff.Legacy_Spiff_Claim_Id__c = '12455';
        update spiff;
        TriggerContextUtility.setFirstRunTrue();
        finchLegacySerialNumbers__c fs = new finchLegacySerialNumbers__c();
        fs.SerialNumber__c = '234w4r4445';
        fs.legacySpiffId__c = '12455';
        insert fs;
        
        TriggerContextUtility.setFirstRunTrue();
        fs.SaleDate__c = date.today();
        update fs;
        
        delete fs;
        
        
        TriggerContextUtility.setFirstRunTrue();
        finchLegacySerialNumbers__c fsa = new finchLegacySerialNumbers__c();
        fsa.SerialNumber__c = '234w4r4445333';
        fsa.legacySpiffId__c = '12455';
        insert fsa;
        
        test.stopTest();
        
        Asset upAss = [Select id, Spiff_Request__c from Asset where id = : vsa.Id];
        system.assertEquals(upAss.Spiff_Request__c, spiff.Id);
        
    }
    
}