force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>My Bundle Product</label>
    <nameField>
        <displayFormat>P - {0000000}</displayFormat>
        <label>Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My Bundle Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Product_Package__c.field-meta.xml
<CustomField>
    <fullName>Product_Package__c</fullName>
    <label>Product Package</label>
    <referenceTo>Product_Package__c</referenceTo>
    <relationshipName>Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Package__c/Product_Package__c.object-meta.xml
<CustomObject>
    <label>My Product Bundle</label>
    <nameField>
        <label>Product Packages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Product Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testMasterBundleProductsTrigger.cls
@isTest
public class testMasterBundleProductsTrigger {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void getRecords(){
        Product_Package__c  pk = new Product_Package__c (name='test apex');
        insert pk;
        
        List<Product2> prods = [Select id from product2 where isactive = true limit 2];
        
        Package__c  c = new Package__c(Product_Package__c = pk.id,
                               Product__c   = prods[0].Id );   
        
        test.startTest();
        insert c;
        TriggerContextUtility.setFirstRunTrue();
        c.Product__c = prods[1].Id;
        update c;
        TriggerContextUtility.setFirstRunTrue();
        delete c;       
        
        test.stopTest();
        
        
        
    }    

}