force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>My Bundle Product</label>
    <nameField>
        <displayFormat>P - {0000000}</displayFormat>
        <label>Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My Bundle Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Product_Package__c.field-meta.xml
<CustomField>
    <fullName>Product_Package__c</fullName>
    <label>Product Package</label>
    <referenceTo>Product_Package__c</referenceTo>
    <relationshipName>Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Package__c/Product_Package__c.object-meta.xml
<CustomObject>
    <label>My Product Bundle</label>
    <nameField>
        <label>Product Packages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Product Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Package__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/MasterBundleProduct.cls
public class MasterBundleProduct {    
    Map<Id, Package__c> oldPack;
    Map<Id, Package__c> newPack;
    
    public MasterBundleProduct(
        Map<Id, Package__c> oldTriggerPack,
        Map<Id, Package__c> newTriggerPack) {
            oldPack = oldTriggerPack;
            newPack = newTriggerPack;
        }
    public static  void updateParent(List<Package__c> records)
    {
        //after update,insert or delete, will query all the records
        //for each parent record that was changed and update a field
        //that summarizes all the data in the children
        //doing after insert or after delete so that the query of the parent 
        //record will accurately depict the most recent set of children records
        
        Set<String> parent = new Set<String>();
        for(Package__c p : records){
            parent.add(p.Product_Package__c);
            
        }
        
        String products = '';        
        List<Product_Package__c> pupdate = new List<Product_Package__c>();
        List<Product_Package__c> parentToUpdate = [Select Id, products__c,(Select Id,Product__r.name from Packages__r) from Product_Package__c where id in: parent];
        for(Product_Package__c pk :  parentToUpdate){
            products ='';
            for(Package__c p : pk.Packages__r){
                if(products == ''){
                    products = p.Product__r.name;
                }else{
                    products = products+'<br/>'+p.Product__r.name;
                }
            }
            pk.products__c = products;
            pupdate.add(pk);
        }
        
        update pupdate;
    } 
     public  void updateParentdel()
    {
        system.debug(oldPack);
        Set<String> parent = new Set<String>();
        for(Package__c p : oldPack.values()){
            parent.add(p.Product_Package__c);
            
        }
        
        String products = '';        
        List<Product_Package__c> pupdate = new List<Product_Package__c>();
        List<Product_Package__c> parentToUpdate = [Select Id, products__c,(Select Id,Product__r.name from Packages__r) from Product_Package__c where id in: parent];
        for(Product_Package__c pk :  parentToUpdate){
            products ='';
            for(Package__c p : pk.Packages__r){
                if(products == '' && !oldPack.containsKey(p.Id)){
                    products = p.Product__r.name;
                }else if(!oldPack.containsKey(p.Id)){
                    products = products+'<br/>'+p.Product__r.name;
                }
            }
            pk.products__c = products;
            pupdate.add(pk);
        }
        
        update pupdate;
    }
}