force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>My Bundle Product</label>
    <nameField>
        <displayFormat>P - {0000000}</displayFormat>
        <label>Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My Bundle Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Product_Package__c.field-meta.xml
<CustomField>
    <fullName>Product_Package__c</fullName>
    <label>Product Package</label>
    <referenceTo>Product_Package__c</referenceTo>
    <relationshipName>Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Package__c/Product_Package__c.object-meta.xml
<CustomObject>
    <label>My Product Bundle</label>
    <nameField>
        <label>Product Packages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Product Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestCompMultiSelect.cls
@isTest
public class TestCompMultiSelect {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void getRecords(){
        String wherestmt = 'where Name != null';
        String limitstmt = 'limit 5';
        String orderstmnt = '';
        String obj = 'Product_Package__c';
        String addfields = '';
        String parentid = '';
        String searchtxt = '';
        String topbutton = 'false';
        Product_Package__c  pk = new Product_Package__c (name='test apex');
        insert pk;
        
        Product2 p = [Select id from product2 where isactive = true limit 1];
        
        List<SObject> children = new List<SObject>();
        String objToCreate = 'Package__c';
        List<String>  objToCreateFields = new List<String>();
        objToCreateFields.add('Product_Package__c');
        objToCreateFields.add('Product__c');
        //objToCreateFields.add('Product__c');
        
        Package__c  c = new Package__c(Product_Package__c = pk.id,
                               Product__c   = p.Id );
        children.add(c);
        
        parentId = pk.Id;
        
        
        test.startTest();
        CompMultiSelect.getRecords(wherestmt, limitstmt, orderstmnt, obj, searchtxt, addfields, parentid, topbutton);
        CompMultiSelect.createChildren(children, parentId, objToCreate, objToCreateFields);
        
        test.stopTest();
        
        
        
    }    

}