force-app/main/default/objects/Package__c/Package__c.object-meta.xml
<CustomObject>
    <label>My Bundle Product</label>
    <nameField>
        <displayFormat>P - {0000000}</displayFormat>
        <label>Package Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My Bundle Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Package__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Packages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Package__c/fields/Product_Package__c.field-meta.xml
<CustomField>
    <fullName>Product_Package__c</fullName>
    <label>Product Package</label>
    <referenceTo>Product_Package__c</referenceTo>
    <relationshipName>Packages</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Price Book Entries</relationshipLabel>
    <relationshipName>Price_Book_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Package__c/Product_Package__c.object-meta.xml
<CustomObject>
    <label>My Product Bundle</label>
    <nameField>
        <label>Product Packages Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Product Bundles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/testOppPackageProducts.cls
@isTest
public class testOppPackageProducts {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void OppPackageProducts(){
        
        String recid = '';
        List<Product_Package__c> packages = new List<Product_Package__c>();
        String quant = '2';
        
        
        List<Product2> prods = [Select Id from Product2 limit 3];
        
        test.startTest();
        Opportunity opp = [Select id,pricebook2ID from opportunity limit 1];
        pricebookentry pbe = [Select id,product2.name,product2Id from pricebookentry where isactive = true and pricebook2id = : opp.Pricebook2Id limit 1];
        
        Product_Package__c  pk = new Product_Package__c (name='test apex');
        insert pk;
        
        Package__c  c = new Package__c(Product_Package__c = pk.id,
                                       Product__c   = pbe.product2Id );
        insert c;
        
        packages.add(pk);
        
        recid = opp.id;
        
        OppPackageProducts.addRecords(recid, packages, quant);
        
        OppPackageProducts.addLines(recid, prods, quant);
        
        test.stopTest();
        
        
        
    }
    static testmethod void QuotePackageProducts(){        
        
        List<Product2> prods = [Select Id from Product2 limit 3];
        String recid = '';
        String quant = '2';
        
        test.startTest();
        Opportunity opp = [Select id,pricebook2ID from opportunity limit 1];  
        
        Quote q = new Quote(name= 'test',opportunityid= opp.id);
        insert q;
        recid = q.id;
        OppPackageProducts.addQuoteLines(recid, prods, quant);
        
        test.stopTest();
    }
    
}