force-app/main/default/objects/Event_Types__mdt/fields/Event_Types__c.field-meta.xml
<CustomField>
    <fullName>Event_Types__c</fullName>
    <label>Event Types</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Trade Show</fullName>
                <default>true</default>
                <label>Trade Show</label>
            </value>
            <value>
                <fullName>Customer Training</fullName>
            </value>
            <value>
                <fullName>VS Internal</fullName>
            </value>
            <value>
                <fullName>SFDC System Reminder</fullName>
            </value>
            <value>
                <fullName>Meeting Site</fullName>
            </value>
            <value>
                <fullName>Meeting Web</fullName>
            </value>
            <value>
                <fullName>Meeting Phone</fullName>
            </value>
            <value>
                <fullName>Floor Walk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Event_Types__mdt/fields/Subject_Matching_Phrase__c.field-meta.xml
<CustomField>
    <fullName>Subject_Matching_Phrase__c</fullName>
    <label>Subject Matching Phrase</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Event_Types__mdt/fields/Type_Rank__c.field-meta.xml
<CustomField>
    <fullName>Type_Rank__c</fullName>
    <description>The ranking of the type may not be used</description>
    <label>Type Rank</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MasterEventClass.cls
public class MasterEventClass{
    Map<Id,Event> oldEvents;
    Map<Id,Event> newEvents;
    public MasterEventClass(Map<Id,Event> oEvents,Map<Id,Event> nEvents){
        oldEvents = oEvents;
        newEvents = nEvents;        
    }
    public static void privateevent(List<Event> records){
        List<Event> EventsToDelete = [Select id from Event where isPrivate = true and id in: records];
        database.delete(EventsToDelete, false);
        
    }
    public static void typeSearch(List<Event> records){
        // Get subject and map keywords to get type using the metadata type to cross reference
        // because the types may change and the keywords may change 
        // the map could be a list but used a map in case we want to use it later
        
        Map<String,Event_Types__mdt> etypes = new Map<String,Event_Types__mdt>();
        for(Event_Types__mdt et: [Select Id, Event_Types__c , Subject_Matching_Phrase__c ,Type_Rank__c 
                                  from Event_Types__mdt])
            etypes.put(et.Subject_Matching_Phrase__c.toLowerCase() , et);
        system.debug('running event trigger'); 
        system.debug(etypes);
        system.debug(records);
        for(Event e : records){
            if(e.subject != null){
                for(Event_Types__mdt types : etypes.values()){
                    String sub = e.Subject.toLowerCase();
                    system.debug(sub);
                    system.debug(types.Subject_Matching_Phrase__c);
                    system.debug(types.Subject_Matching_Phrase__c.toLowerCase());
                    
                    if(sub.contains(types.Subject_Matching_Phrase__c.toLowerCase()) && String.isBlank(e.type)) {
                        e.type = types.Event_Types__c; 
                    } 
                    
                }
                
            }
            
            
        } 
        
    }
    
}