force-app/main/default/objects/Modal__c/Modal__c.object-meta.xml
<CustomObject>
    <label>Modal</label>
    <nameField>
        <label>Modal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modal_Settings__c/Modal_Settings__c.object-meta.xml
<CustomObject>
    <label>Modal Setting</label>
    <nameField>
        <label>Modal Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modall Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Modal_Settings__c/fields/Last_Date_Shown__c.field-meta.xml
<CustomField>
    <fullName>Last_Date_Shown__c</fullName>
    <defaultValue>today()+1</defaultValue>
    <label>Last Date Shown</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Modal_Settings__c/fields/Modal__c.field-meta.xml
<CustomField>
    <fullName>Modal__c</fullName>
    <label>Modal</label>
    <referenceTo>Modal__c</referenceTo>
    <relationshipLabel>Modall Settings</relationshipLabel>
    <relationshipName>Modall_Settings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Modal_Settings__c/fields/Never_Show__c.field-meta.xml
<CustomField>
    <fullName>Never_Show__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Never Show</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Modal_Settings__c/fields/Times_Clicked__c.field-meta.xml
<CustomField>
    <fullName>Times_Clicked__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Times Clicked</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modal_Settings__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Modall_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testmodalUniveralcmp.cls
@isTest
public class testmodalUniveralcmp {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    
    Static testmethod void modalUniversal () {
        
        test.startTest();
        
        List<Modal_Settings__c> records = new List<Modal_Settings__c>();
        Schema.SObjectType convertType = Schema.getGlobalDescribe().get('Modal_Settings__c');
        Sobject genericObject = convertType.newSObject();
        
        DescribeSObjectResult describeResult = genericObject.getSObjectType().getDescribe();
        
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
        
        String query =		  ' SELECT ' +		      String.join( fieldNames, ',' ) +'   FROM '
            +		      describeResult.getName()	+' limit 1';	
        
        records = Database.query( query );
        Modal_Settings__c ms = records[0];
        
        //Modal_Settings__c ms = [Select id, User__c,Times_Clicked__c from Modal_Settings__c limit 1];
        
        
        
        
        
        ms.User__c = UserInfo.getUserId();
        update ms;
        
        Modal__c md = [Select id from Modal__c  where name = 'test modal'];
               
        
        
        String parentFields = ',Modal__r.Name,User__r.Name';
        String whereStatement = ' and Never_Show__c = false';
        String orderStatement = 'order by Last_Date_Shown__c asc';
        String limitStatement = 'Limit 1';
        String modalName = 'test modal';
		String action = 'click';
		Boolean remove = true;
        
        Modal_Settings__c mset = modalUniversalClass.getModalSetting(parentFields, whereStatement, orderStatement, limitStatement, modalName);
        
        Modal_Settings__c mset2 = modalUniversalClass.updateSetting(ms,action,remove);
        
        delete md;
        
        Modal_Settings__c mset3 = modalUniversalClass.getModalSetting(parentFields, whereStatement, orderStatement, limitStatement, modalName);
        
       
        
        //modalUniversalClass.getModalSetting(parentFields, whereStatement, orderStatement, limitStatement, modalName);
        
        test.stopTest();
        
        system.assertEquals(mset.Modal__r.Name, modalName);
        system.assertEquals(mset2.Times_Clicked__c, 1);
        system.assertEquals(mset2.Never_Show__c, true);
        system.assertEquals(mset3, null);
        
        system.debug('test mod name '+ mset.Modal__r.Name);
        
    }    
    
}