force-app/main/default/objects/Modal__c/Modal__c.object-meta.xml
<CustomObject>
    <label>Modal</label>
    <nameField>
        <label>Modal Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Modal_Settings__c/Modal_Settings__c.object-meta.xml
<CustomObject>
    <label>Modal Setting</label>
    <nameField>
        <label>Modal Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Modall Settings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Modal_Settings__c/fields/Last_Date_Shown__c.field-meta.xml
<CustomField>
    <fullName>Last_Date_Shown__c</fullName>
    <defaultValue>today()+1</defaultValue>
    <label>Last Date Shown</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Modal_Settings__c/fields/Modal__c.field-meta.xml
<CustomField>
    <fullName>Modal__c</fullName>
    <label>Modal</label>
    <referenceTo>Modal__c</referenceTo>
    <relationshipLabel>Modall Settings</relationshipLabel>
    <relationshipName>Modall_Settings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Modal_Settings__c/fields/Never_Show__c.field-meta.xml
<CustomField>
    <fullName>Never_Show__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Never Show</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Modal_Settings__c/fields/Times_Clicked__c.field-meta.xml
<CustomField>
    <fullName>Times_Clicked__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Times Clicked</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modal_Settings__c/fields/Times_Dismissed__c.field-meta.xml
<CustomField>
    <fullName>Times_Dismissed__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Times Dismissed</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Modal_Settings__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Modall_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/modalUniversalClass.cls
public without sharing class modalUniversalClass {
    @auraEnabled
    public static Modal_Settings__c  getModalSetting(String parentFields,String whereStatement,
                                                     String orderStatement,String limitStatement, String modalName){
        
        List<Modal_Settings__c> records = new List<Modal_Settings__c>();
        
        User u = [Select id from User where id = : UserInfo.getUserId() limit 1];
        String currentUser = u.Id;
        /*                                                 
        Modal_Settings__c ms1 = [Select id, user__c,modal__r.name from Modal_Settings__c limit 1];
        system.debug(ms1);
        system.debug('the modal seettgin info');
        */                                                 
        Schema.SObjectType convertType = Schema.getGlobalDescribe().get('Modal_Settings__c');
        Sobject genericObject = convertType.newSObject();
        
        DescribeSObjectResult describeResult = genericObject.getSObjectType().getDescribe();
        
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
        
        String query =		  ' SELECT ' +		      String.join( fieldNames, ',' ) +' '+ parentFields + '  FROM '
            +		      describeResult.getName()	+' where Modal__r.Name = : modalName and Modal__r.isActive__c = true and User__c = : currentUser ' + whereStatement + ' '+ orderStatement+' '+ limitStatement;	
         Modal_Settings__c ms = null;
                                                         system.debug('query');
                                                         system.debug(query);
       	  try{
            records = Database.query( query );
            ms =   records[0];
        }catch(exception e){            
            String t = 'Error on the Modal '+ modalName + ' User '+UserInfo.getUserName();
            ms = null;
            system.debug('error ');
            system.debug(e);
            system.debug(t);
            //AdminErrorMessage.SendError(e, t);
        }   
        return ms;
    }
    @auraEnabled
    public static Modal_Settings__c  updateSetting(Modal_Settings__c mset,String action,Boolean remove){
        mset.Last_Date_Shown__c = date.today();
        mset.Never_Show__c = remove;
        if(action == 'click'){
            mset.Times_Clicked__c =  mset.Times_Clicked__c +1;
        }else{
            mset.Times_Dismissed__c  =  mset.Times_Dismissed__c +1;
        }
        update mset;
        
        return mset;
                                                         
                                                         
                                                         
  }

}