force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>This is for cross referencing city and state and getting  the county for accounts
can be used for heat maps</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <label>StateCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/Eval_Quote__c.object-meta.xml
<CustomObject>
    <description>Eval Quote Custom Object</description>
    <label>Eval Quote</label>
    <nameField>
        <displayFormat>EvalQuote-{000000}</displayFormat>
        <label>Eval Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Quote__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Shipping_City__c.field-meta.xml
<CustomField>
    <fullName>Shipping_City__c</fullName>
    <label>Shipping City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Shipping_State__c.field-meta.xml
<CustomField>
    <fullName>Shipping_State__c</fullName>
    <label>Shipping State</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Price_Low__c.field-meta.xml
<CustomField>
    <fullName>Eval_Price_Low__c</fullName>
    <label>Eval Price Low</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Quote__c.field-meta.xml
<CustomField>
    <fullName>Eval_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eval Quote</label>
    <referenceTo>Eval_Quote__c</referenceTo>
    <relationshipLabel>Eval Unit Details</relationshipLabel>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Recycle_Fee__c.field-meta.xml
<CustomField>
    <fullName>Recycle_Fee__c</fullName>
    <description>Product Recycle fees based on Billing State (Quote)</description>
    <label>Recycle Fee</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Testing Field. Will pull from product</inlineHelpText>
    <label>SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Sku_Alt_Name__c.field-meta.xml
<CustomField>
    <fullName>Sku_Alt_Name__c</fullName>
    <formula>left(Sku_Text__c, len(Sku_Text__c ) -2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Sku Alt Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Sku_Text__c.field-meta.xml
<CustomField>
    <fullName>Sku_Text__c</fullName>
    <label>Sku Text</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Tax_Rate__c.field-meta.xml
<CustomField>
    <fullName>Tax_Rate__c</fullName>
    <label>Tax Rate</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Price Book Entries</relationshipLabel>
    <relationshipName>Price_Book_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recycle_Fee__c/Recycle_Fee__c.object-meta.xml
<CustomObject>
    <label>Recycle Fee</label>
    <nameField>
        <label>Recycle Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recycle Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recycle_Fee__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Recycle Fees</relationshipLabel>
    <relationshipName>Recycle_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Recycle_Fee__c/fields/Recycle_Fee__c.field-meta.xml
<CustomField>
    <fullName>Recycle_Fee__c</fullName>
    <label>Recycle Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Sales_Tax__c/Sales_Tax__c.object-meta.xml
<CustomObject>
    <label>Sales Tax</label>
    <nameField>
        <label>Sales Tax Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Tax</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Tax__c/fields/STATE_PROVINCE__c.field-meta.xml
<CustomField>
    <fullName>STATE_PROVINCE__c</fullName>
    <label>STATE_PROVINCE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sales_Tax__c/fields/TOTAL_TAX_RATE__c.field-meta.xml
<CustomField>
    <fullName>TOTAL_TAX_RATE__c</fullName>
    <formula>CITY_RATE__c +  COUNTY_RATE__c +  STATE_RATE__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TOTAL_TAX_RATE</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/EvalQuoteFlow.cls
global class EvalQuoteFlow {
    @InvocableMethod
    public static void getRates(List<String> quoteids) {
        //get eval quote info first and use the city and state to get the tax rate if applicable
        //mapping the quote so it can be used in the loop of eval units
        
        List<Eval_Quote__c> quotes = [Select id,Tax_Rate__c,Shipping_City__c,Shipping_State__c 
                                      from Eval_Quote__c where id in: 
                                      quoteids];
        
        
        List<Eval_Unit_Details__c> units = [Select id from Eval_Unit_Details__c where Eval_Quote__c =: quoteids ];
        
        String quoteid = quotes[0].Id;
        String city ='';
        String state = '';
        
        Map<String, Pricebookentry> pblow = new Map<String, Pricebookentry>();
        for(Pricebookentry pbe : [Select Id, UnitPrice,product2.name from PricebookEntry 
                                  where pricebook2.name ='VSA Product Request Bottom Purchase Price List'])
            pblow.put(pbe.product2.Name, pbe);
        
        system.debug('quote');
        system.debug(quotes);
        if(quotes.size() >0){
            city = quotes[0].Shipping_City__c;
            state = quotes[0].Shipping_State__c;
            
            Map<Id, Eval_Quote__c> quote = new Map<Id,Eval_Quote__c>(quotes);
            
            List<Sales_Tax__c> rate = [Select id, City__c, State_Province__c , Total_Tax_Rate__c from Sales_Tax__c 
                                       where State_Province__c = : state and City__c =: city];
            
            //validating city and state if not, will send email to admin. may need to stop the process later but for now
            //will monitor it becasue the shiping city and state is done through the system not by user most of the time.
             Map<String, County__c > cities = new Map<String, County__c >();
            
            try{
                for(County__c c : [Select id, City__c , Statecode__c from County__c where Statecode__c = : state.toUpperCase()]){
                cities.put(string.valueOf(c.City__c).toLowerCase()+string.valueOf(c.Statecode__c).toLowerCase(), c);
                }
                
            }catch(Exception e){
                
            }
           
            
            if(!cities.containsKey(city.toLowerCase()+state.toLowerCase())){
                system.debug('there is a misspelling');
                CalloutException e = new CalloutException();
                e.setMessage('Eval quote has an invalid city and state');                
                String t = 'Eval quote may have an invalid city and state. The state: '+state+' city: '+ city+' Eval quote : '+quotes;
                AdminErrorMessage.SendError(e, t);
            }
                
            
            List<Eval_Unit_Details__c> details = [Select id,Tax_Rate__c ,Name,Eval_Price_Low__c ,Recycle_Fee__c ,sku__r.Name,Sku_Text__c,Sku_Alt_Name__c ,  Eval_Quote__c,Eval_Quote__r.Shipping_State__c
                                                  from Eval_Unit_Details__c  where id in: units];
            //need to map the recycle fees by product because each product may have a separte fee
            //the map puts the sku as the unique id and then compares each eval unit sku
            //if there is a fee, than the fee is added
            //otherwise the fee will be 0 this is added to each line that is being quoted
            //
            Map<String,Recycle_Fee__c> fees = new Map<String,Recycle_Fee__c>();
            
            for(Recycle_Fee__c rf : [Select Id ,Product__c,Product__r.name ,Recycle_Fee__c from Recycle_Fee__c where Country__c = 'US'])
                fees.put(rf.Product__r.name , rf);
            
            system.debug(fees);
            
            String prods = '';            
            for(Eval_Unit_Details__c e : details){
                system.debug(e.sku__r.name);
                system.debug('sku name');                    
                if(rate.size()>0){
                    e.Tax_Rate__c = rate[0].Total_Tax_Rate__c;
                    quotes[0].Tax_Rate__c = rate[0].Total_Tax_Rate__c;
                }
                
                if(pblow.containsKey(e.sku__r.name)){
                    Double price = pblow.get(e.sku__r.name).UnitPrice;
                    e.Eval_Price_Low__c  = price;                        
                    prods = prods+'SKU: '+ e.sku__r.name+' Price: '+price+' SN: '+e.Name+' \n';
                }
                if(fees.containsKey(e.sku__r.Name)){
                    e.Recycle_Fee__c = fees.get(e.sku__r.Name).Recycle_Fee__c;
                }else{
                    e.Recycle_Fee__c = 0;
                } 
            }
            quotes[0].Products__c = prods;
            update details;
            update quotes[0];
            system.debug(details);
            system.debug(quotes[0]); 
        }
        
    }
}