force-app/main/default/objects/Account/recordTypes/Inactive.recordType-meta.xml
<RecordType>
    <fullName>Inactive</fullName>
    <active>false</active>
    <label>Inactive</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Committed__c.field-meta.xml
<CustomField>
    <fullName>Committed__c</fullName>
    <formula>ISPICKVAL(StageName, &apos;Closed Won&apos;) ||
ISPICKVAL(StageName, &apos;Agreed to Purchase&apos;) ||
ISPICKVAL(StageName, &apos;Pending PO&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Committed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Contact__c.field-meta.xml
<CustomField>
    <fullName>End_User_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The email Address will be attached to the opportunity once an email is attached to the contact</inlineHelpText>
    <label>End User Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (End User Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Manager_Note__c.field-meta.xml
<CustomField>
    <fullName>Manager_Note__c</fullName>
    <label>Manager Note</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Notes__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Notes__c</fullName>
    <description>Sales Rep can enter notes to set up reminders and situation on the the opportunity</description>
    <inlineHelpText>Sales Rep can enter notes to set up reminders and situation on the the opportunity</inlineHelpText>
    <label>Opportunity Notes</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Account_Search__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account_Search__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Re-Seller VAR will be added to opportunity partners. If you need to add additional Resellers, Please Use Opportunity Partners.</inlineHelpText>
    <label>Reseller Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Added__c.field-meta.xml
<CustomField>
    <fullName>Product_Added__c</fullName>
    <inlineHelpText>Test out the product price flow..temp field</inlineHelpText>
    <label>Product Added Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Name_Main__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Main__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is for mobile users to quickly add a product to an opportunity so that it has the most important Product Listed. This Could be used to update the Opportunity Name.</inlineHelpText>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>This product must be active and must be part of the default price book.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_or_Site_Information__c.field-meta.xml
<CustomField>
    <fullName>Project_or_Site_Information__c</fullName>
    <inlineHelpText>Adds Project Name or Site information to Opportunity Name</inlineHelpText>
    <label>Project or Site Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResellerContact__c.field-meta.xml
<CustomField>
    <fullName>ResellerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Reseller Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resellers_and_Type__c.field-meta.xml
<CustomField>
    <fullName>Resellers_and_Type__c</fullName>
    <description>Updated by flow</description>
    <label>Resellers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trade_Show_or_Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Trade_Show_or_Marketing_Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign or Trade Show</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Inactive.recordType-meta.xml
<RecordType>
    <fullName>Inactive</fullName>
    <active>true</active>
    <businessProcess>VSA Sales Stages</businessProcess>
    <label>Inactive</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Competitor_SKU__c.field-meta.xml
<CustomField>
    <fullName>Competitor_SKU__c</fullName>
    <label>Competitor SKU</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Likely_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Likely_Purchase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Likely Purchase</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Pillar__c.field-meta.xml
<CustomField>
    <fullName>Product_Pillar__c</fullName>
    <label>Product Pillar</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Ship_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Out_Date__c</fullName>
    <label>Ship Out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Interest&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Quote Request</fullName>
            </value>
            <value>
                <fullName>Agreed to Purchase</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Decided not to buy</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Pillar__c.field-meta.xml
<CustomField>
    <fullName>Product_Pillar__c</fullName>
    <formula>Product_Line__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Pillar</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MyOpportunityPipeline.cls
public class MyOpportunityPipeline {
    
@AuraEnabled
     public static User getUser()
    {     
         return getUser.getUser();
    }
    @AuraEnabled
     public static List<String> getReps()
    {     
         
        List<User> myReps = [Select Id,FirstName,LastName from User where ManagerId =:UserInfo.getUserId() or Manager.ManagerId =: UserInfo.getUserId()];
        
        List<String> reps = new List<String>();
        reps.add('All');
        
        for (User u : myReps) {
            reps.add(u.Firstname+' '+u.LastName);
        }         
        system.debug('reps'); 
        
        return reps;
    }
    
    @AuraEnabled
    public static List<Opportunity> getOpps(String product,String reseller,String enduser,String industry,String prodtype,String srep)
    {     
     
        List<String> usernames = new List<String>();
        if(srep == 'all' || srep == '' || srep == null){
            usernames = MyOpportunityPipeline.getReps();
            usernames.add(UserInfo.getFirstName()+' '+UserInfo.getLastName());           
        }else{
             usernames.add(srep);
        }         
        
        
        List<Opportunity> pipeline = new List<Opportunity>();
        
        //reseller is a long text field and the like part of query does not work if null
        //so if reseller is not blank, the code below ensures it will not show up in results
        //a workaround I know. I hope you enjoy it or update it. thanks some dev guy
        String nreseller = 'xxxxxxxxxxx';
        if(reseller == null || reseller == ''){
          nreseller = '';
        }
        //cleanse out the strings for proper query and avoiding sql injection

        reseller = stringQuery.cleanString(reseller);
        product  = stringQuery.cleanString(product);
        enduser  = stringQuery.cleanString(enduser);
        industry = stringQuery.cleanString(industry);
        prodtype = stringQuery.cleanString(prodtype);

        system.debug('reserler '+reseller);
        
        List<OpportunityLineItem> opps = [Select ProductCode,OpportunityId,Opportunity.Account.Name,Opportunity.StageName,name
               ,quantity,ServiceDate,unitprice,product2id,product2.name,opportunity.name,opportunity.Opportunity_Notes__c,
               opportunity.Project_or_Site_Information__c,opportunity.Manager_Note__c,opportunity.Resellers_and_Type__c,Ship_Out_Date__c,
               status__c ,PricebookEntry.Product2.Product_Pillar__c
               from OpportunityLineItem
               where
               Opportunity.Owner.Name in : usernames  AND
               Product2.Name Like :product AND
               (Opportunity.Account.Industry Like :industry) AND                           
               Opportunity.Name Like :enduser AND
               PricebookEntry.Product2.Product_Pillar__c Like :  prodtype AND                         
               (Opportunity.Resellers_and_Type__c Like  : reseller OR Opportunity.Resellers_and_Type__c = :nreseller) And
               Opportunity.StageName != 'Closed Won' AND
               Opportunity.StageName != 'Closed Lost'
               Order By  OpportunityId desc  NULLS last limit 100];
        
        Set<String> oppids = new Set<String>();
            for (OpportunityLineItem oline : opps) oppids.add(oline.opportunityId);
        
        
        pipeline =  [Select Id, StageName,Opportunity_Notes__c,Manager_Note__c,AccountId, Account.Name,Product_Name_Main__c,CloseDate
                      ,Project_or_Site_Information__c,name,Resellers_and_Type__c,Pricebook2Id ,Partner_Account_Search__c,ResellerContact__c,End_User_Contact__c,
                      Trade_Show_or_Marketing_Campaign__c,CampaignId,Product_Added__c,(SELECT name,Quantity,Product2Id,product2.Name,ServiceDate
                                        ,Ship_Out_Date__c,status__c FROM OpportunityLineItems 
                                        where product2.name Like :product  
                                        and status__c != 'Shipped'                                               
                                        order by product2.name)                         
                      from opportunity where id in: oppids order by CloseDate asc, id];
        
        return pipeline;
    }
    @AuraEnabled
    public static List<OpportunityLineItem> getSchedule(String product,String reseller,String enduser,
                                                        String industry,String prodtype,String srep,
                                                        Boolean myopps, Boolean likely, Boolean committed)
    {     
        
        system.debug('toggles '+myopps+likely+committed);
        List<String> usernames = new List<String>();
        
        
        
        if(srep == 'all' || srep == '' || srep == null){
            usernames = MyOpportunityPipeline.getReps();
            usernames.add(UserInfo.getFirstName()+' '+UserInfo.getLastName()); 
        }else{
            usernames.add(srep);
        }
        List<User> oppusers = [Select id, firstname, lastname from user];
        if(!myopps){
            for(user u : oppusers){
                usernames.add(u.firstname+' '+u.lastname);
            }
        }
        system.debug('sales reps in list '+usernames);
        system.debug('string srep '+srep);
        //User u = [Select Id from User where Id =:UserInfo.getUserId()];
        
        Date cm = System.today().toStartOfMonth().addDays(-1);
        //List<Opportunity> pipeline = new List<Opportunity>();
         system.debug('product schedule 1 '+product);
        //reseller is a long text field and the like part of query does not work if null
        //so if reseller is not blank, the code below ensures it will not show up in results
        //a workaround I know. I hope you enjoy it or update it. thanks some dev guy
        String nreseller = 'xxxxxxxxxxx';
        if(reseller == null || reseller == ''){
          nreseller = '';
        }
        //cleanse out the strings for proper query and avoiding sql injection

        reseller = stringQuery.cleanString(reseller);
        product  = stringQuery.cleanString(product);
        enduser  = stringQuery.cleanString(enduser);
        industry = stringQuery.cleanString(industry);
        prodtype = stringQuery.cleanString(prodtype);

        system.debug('product schedule 2'+product);
        
        List<OpportunityLineItem> oppprods = [Select ProductCode,OpportunityId,Opportunity.Account.Name,Opportunity.StageName,name,Likely_Purchase__c,
               quantity,ServiceDate,unitprice,product2id,product2.name,opportunity.name,opportunity.Opportunity_Notes__c,Opportunity.CloseDate,Opportunity.Owner.Name,
               opportunity.Project_or_Site_Information__c,opportunity.Manager_Note__c,opportunity.Resellers_and_Type__c,Ship_Out_Date__c,
               status__c ,PricebookEntry.Product2.Product_Pillar__c,(Select Id,ScheduleDate,Quantity,type from OpportunityLineItemSchedules where ScheduleDate > :cm order by ScheduleDate asc limit 12) 
               from OpportunityLineItem
               where HasSchedule = true AND
               Likely_Purchase__c =: likely AND
               Opportunity.recordtype.name != 'Inactive' AND
               Opportunity.Committed__c = : committed    and                           
               Opportunity.Owner.Name in: usernames  AND
               Product2.Name Like :product AND
               (Opportunity.Account.Industry Like :industry) AND                           
               Opportunity.Name Like :enduser AND
               PricebookEntry.Product2.Product_Pillar__c Like :  prodtype AND                         
               (Opportunity.Resellers_and_Type__c Like  : reseller OR Opportunity.Resellers_and_Type__c = :nreseller) And
               Opportunity.StageName != 'Closed Won' AND
               Opportunity.StageName != 'Closed Lost'
               Order By  Opportunity.CloseDate asc, OpportunityId desc  NULLS last limit 100];
      
        
        return oppprods;
    }
    @AuraEnabled
   public static String updateopps(List<Opportunity> opps,List<OpportunityLineItem> lines){  
        
      String errors = '';
      errors = UpdateOppsProducts.updateopps(opps,lines);
       
      return errors;
 }
     @AuraEnabled
   public static String updatesch(List<OpportunityLineItem> opps,List<OpportunityLineItemSchedule> lines){  
        
      String errors = '';
      errors = UpdateOppsSchedules.updateopps(opps,lines);
       
      return errors;
 }
    @AuraEnabled
   public static List<Date> getmonths(List<OpportunityLineItem> opps,List<OpportunityLineItemSchedule> lines){  
        
     
      List<Date> dates = months.getMonths();
       
      return dates;
 }
    @AuraEnabled
    public static List<String> getStatus()  
  {
        return GetProductStatus.getStatus();
    }
    @AuraEnabled
    public static List<String> getProducts()  
  {
      List<String> prods = new List<String>();  
      
      List<Product2> aproducts = [Select Id, Name from Product2 where isActive = true order by name asc];
      for(Product2 p : aproducts){
          prods.add(p.name);
      }
      
      system.debug('products active '+prods);
      
      return prods;
    }
     @AuraEnabled
    public static List<String> getProdTypes()  
  {
        
      return productTypes.getProdTypes();
    }
     @AuraEnabled
    public static String getPricebook(String oppid)  
  {
      String pricebook = '';
      List<Opportunity> opp = [Select id, pricebook2id from opportunity where id = : oppid];
      
      pricebook = opp[0].pricebook2id;
      
      return pricebook;
    }
   
    @AuraEnabled
    public static String newprod(String oppid,
                             String prodid,
                             Decimal quant,
                             Decimal spaprice,
                             String ship,
                             String status,
                             String compete)  
  {
               
      Date shpdt = Date.valueOf(ship);
      system.debug('opp '+oppid+ ' prod id '+prodid+' quan '+quant+' ship '+shpdt+' status '+status+' compete '+compete);
      //Opportunity opp = [Select Id, Pricebook2Id,Pricebook2.Name from Opportunity
                              //Where Id =:oppid Limit 1];
      
      
      //get the pricebook entry
      List<PriceBookEntry> pbe = [Select Id,unitprice,IsActive,product2.name,pricebook2.name from Pricebookentry 
                            where id  = : prodid
                            Limit 1];
      
      system.debug('pbe id '+pbe[0].Id);
      system.debug('pbe id '+pbe[0].IsActive);
      
      OpportunityLineItem line = new OpportunityLineItem(PriceBookEntryId = prodid,
                                            UnitPrice = pbe[0].unitprice,
                                            Quantity = quant,
                                            OpportunityId = oppid,
                                            Status__c = status,
                                            Ship_Out_Date__c= shpdt,
                                            Competitor_SKU__c = compete);
          
           
      system.debug('line info '+line);
      if(pbe[0].Isactive==false){
          throw new AuraHandledException('The product '+ pbe[0].product2.name+' is not active in the current price book of '+pbe[0].pricebook2.name);
      }else{
          insert line;      
      }
      
     
      return line.Id;
    }
    @AuraEnabled
    public static List<OpportunityLineItem> delProd(String prodid,List<Opportunity> opps,List<OpportunityLineItem> lines,String product){  
    
       List<OpportunityLineItem> pline = [Select Id from OpportunityLineItem where id =: prodid];
       system.debug('line items delete'+pline);
       //delete pline;
       return pline; 
 } 
     @AuraEnabled
    public static List<String> getIndustries()  
  {
       
       
     return industries.getIndustries();
    }
}