force-app/main/default/objects/Account/recordTypes/Inactive.recordType-meta.xml
<RecordType>
    <fullName>Inactive</fullName>
    <active>false</active>
    <label>Inactive</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Bid_Registered__c.field-meta.xml
<CustomField>
    <fullName>Bid_Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Automatically updated when Spa Request field has bid registered selected.</inlineHelpText>
    <label>Bid Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resellers__c.field-meta.xml
<CustomField>
    <fullName>Resellers__c</fullName>
    <description>Field is used for Wave Pipeline to search for Resellers.</description>
    <label>Resellers</label>
    <length>8000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Inactive.recordType-meta.xml
<RecordType>
    <fullName>Inactive</fullName>
    <active>true</active>
    <businessProcess>VSA Sales Stages</businessProcess>
    <label>Inactive</label>
</RecordType>

force-app/main/default/objects/Quote/fields/Bid_Registered__c.field-meta.xml
<CustomField>
    <fullName>Bid_Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bid Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Resellers__c.field-meta.xml
<CustomField>
    <fullName>Resellers__c</fullName>
    <formula>Opportunity.Resellers_and_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resellers</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Inactive.recordType-meta.xml
<RecordType>
    <fullName>Inactive</fullName>
    <active>true</active>
    <label>Inactive</label>
</RecordType>

force-app/main/default/classes/quotesMobile.cls
public class quotesMobile {
    @AuraEnabled
    public static List<Quote> getSpas(String searchtxt){
        
        system.debug('Search given '+searchtxt);       
        
        String srchtxt = '%'+searchtxt+'%';
        system.debug('search like stm '+srchtxt);        
        
        List<Quote> quotes = [Select id,name,expirationdate,account.name,resellers__c,
                              opportunity.name,
                              bid_registered__c,status,(select product2.name from quotelineitems)
                              from quote where (account.name like : srchtxt or name like : srchtxt
                              or resellers__c like : srchtxt) and status != 'Inactive' 
                              order by expirationdate desc limit 300 ];        
        
        system.debug('quotes found');
        system.debug(quotes);
        return quotes;
        
    }
}