force-app/main/default/objects/Eval_Quote__c/Eval_Quote__c.object-meta.xml
<CustomObject>
    <description>Eval Quote Custom Object</description>
    <label>Eval Quote</label>
    <nameField>
        <displayFormat>EvalQuote-{000000}</displayFormat>
        <label>Eval Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Quote__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Eval Quotes</relationshipLabel>
    <relationshipName>Eval_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Quote__c.field-meta.xml
<CustomField>
    <fullName>Eval_Quote__c</fullName>
    <description>&quot;&amp;id=&quot; + Id +
&quot;&amp;queryid=a0o1200000AvHp9&quot; + 
&quot;&amp;defaultpdf=1&quot; + 
&quot;&amp;emailtemplateid=00X12000001raQN&quot; + 
&quot;&amp;templateid=a0p12000003vik9&quot; + 
&quot;&amp;emailtoid=&quot; + $User.Contact_ID__c +
&quot;&amp;emailadditionalto=&quot; + Billing_Contact_Email_Invoice__c +
&quot;&amp;emailcc=&quot; + Evaluation_Owner_Email__c +
&quot;&amp;qmode=SendEmail&quot; + 
&quot;&amp;ofn=Evaluation Purchase Quote for RMA &quot; + RMA__c + &quot; &quot; + Name +
&quot;&amp;uf0=1 &quot; + 
&quot;&amp;sc1=Chatter&quot; + 
&quot;&amp;sc0=1&quot; + 
&quot;&amp;mfts0=Eval_Quote_Sent_Out__c&quot; + 
&quot;&amp;mftsvalue0=True&quot;</description>
    <formula>&quot;&amp;id=&quot; + Id +
&quot;&amp;queryid=a0o1200000AvHp9&quot; + 
&quot;&amp;defaultpdf=1&quot; + 
&quot;&amp;emailtemplateid=a0n12000006mpFy&quot; + 
&quot;&amp;templateid=a0p12000003vik9&quot; + 
&quot;&amp;emailadditionalto=&quot; + Billing_Contact_Email_Invoice__c +&apos;,&apos;+ Eval_Submitter_Email__c + &apos;,Lori.Smith@viewsonic.com&apos; +
&quot;&amp;qmode=SendEmail&quot; + 
&quot;&amp;ofn=Evaluation Purchase Quote for RMA &quot; + RMA__c + &quot; &quot; + Name +
&quot;&amp;uf0=1 &quot; + 
&quot;&amp;sc1=Chatter&quot; + 
&quot;&amp;sc0=1&quot; + 
&quot;&amp;mfts0=Eval_Quote_Sent_Out__c&quot; + 
&quot;&amp;mftsvalue0=True&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Eval Quote</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Quote__c.field-meta.xml
<CustomField>
    <fullName>Eval_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eval Quote</label>
    <referenceTo>Eval_Quote__c</referenceTo>
    <relationshipLabel>Eval Unit Details</relationshipLabel>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Testing Field. Will pull from product</inlineHelpText>
    <label>SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Unit_Selected__c.field-meta.xml
<CustomField>
    <fullName>Unit_Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Unit Selected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/EvalUnitstoQuote.cls
public class EvalUnitstoQuote { 
    /// Adding a method getaccesscheck to Check Custom Permission on the Profile
     @AuraEnabled
    public static Boolean getAccessCheck(){
        Boolean hasPermission = FeatureManagement.checkPermission('Eval_Special_Price_Access');
        return hasPermission;
    }
    @AuraEnabled
    public static List<Eval_Unit_Details__c> getUnits(String recordId){
        
        DescribeSObjectResult describeResult = Eval_Unit_Details__c.getSObjectType().getDescribe();
        
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
        
        String query =		  ' SELECT ' +		      String.join( fieldNames, ',' ) +		  ', SKU__r.Name  FROM '
            +		      describeResult.getName()	+' WHERE Eval_Request__c  = : recordId'	;		
        // return generic list of sobjects or typecast to expected type
        
        List<Eval_Unit_Details__c> records = Database.query( query );		
        System.debug( records );
        
        return records;
    }
     @AuraEnabled
    public static void updateUnits(List<Eval_Unit_Details__c> units, String quoteId){
        for(Eval_Unit_Details__c e : units){
            e.Eval_Quote__c = quoteid;
        }
        update units;
    }
    @AuraEnabled
    public static List<Eval_Unit_Details__c> updateSelected(List<Eval_Unit_Details__c> units){
        system.debug('units to Update Shpping Return ');
        /*
        for(Eval_Unit_Details__c e : units){
            e.Unit_Selected__c  = true;
        }
        */
        update units;
        return units;
    }

}