force-app/main/default/objects/Eval_Quote__c/Eval_Quote__c.object-meta.xml
<CustomObject>
    <description>Eval Quote Custom Object</description>
    <label>Eval Quote</label>
    <nameField>
        <displayFormat>EvalQuote-{000000}</displayFormat>
        <label>Eval Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Quote__c/fields/Eval_Quote_Status__c.field-meta.xml
<CustomField>
    <fullName>Eval_Quote_Status__c</fullName>
    <defaultValue>&quot;New&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>Return Quote/PO</label>
            </value>
            <value>
                <fullName>PO Received</fullName>
                <label>Waiting for Invoice Creation</label>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Invoiced</fullName>
                <isActive>false</isActive>
                <label>Invoiced</label>
            </value>
            <value>
                <fullName>Needs Correction</fullName>
                <isActive>false</isActive>
                <label>Needs Correction</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Eval Quotes</relationshipLabel>
    <relationshipName>Eval_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Process_Stage__c.field-meta.xml
<CustomField>
    <fullName>Eval_Process_Stage__c</fullName>
    <defaultValue>&quot;Awaiting Submission Request&quot;</defaultValue>
    <description>Gives stage to all parties to determine where in the process the request is held  up.</description>
    <label>Eval Process Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission Request</fullName>
                <default>true</default>
                <label>Awaiting Submission Request</label>
            </value>
            <value>
                <fullName>Awaiting Approval from Director or VP</fullName>
            </value>
            <value>
                <fullName>Awaiting Upload of Agreement</fullName>
            </value>
            <value>
                <fullName>Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancellation Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Quote__c.field-meta.xml
<CustomField>
    <fullName>Eval_Quote__c</fullName>
    <description>&quot;&amp;id=&quot; + Id +
&quot;&amp;queryid=a0o1200000AvHp9&quot; + 
&quot;&amp;defaultpdf=1&quot; + 
&quot;&amp;emailtemplateid=00X12000001raQN&quot; + 
&quot;&amp;templateid=a0p12000003vik9&quot; + 
&quot;&amp;emailtoid=&quot; + $User.Contact_ID__c +
&quot;&amp;emailadditionalto=&quot; + Billing_Contact_Email_Invoice__c +
&quot;&amp;emailcc=&quot; + Evaluation_Owner_Email__c +
&quot;&amp;qmode=SendEmail&quot; + 
&quot;&amp;ofn=Evaluation Purchase Quote for RMA &quot; + RMA__c + &quot; &quot; + Name +
&quot;&amp;uf0=1 &quot; + 
&quot;&amp;sc1=Chatter&quot; + 
&quot;&amp;sc0=1&quot; + 
&quot;&amp;mfts0=Eval_Quote_Sent_Out__c&quot; + 
&quot;&amp;mftsvalue0=True&quot;</description>
    <formula>&quot;&amp;id=&quot; + Id +
&quot;&amp;queryid=a0o1200000AvHp9&quot; + 
&quot;&amp;defaultpdf=1&quot; + 
&quot;&amp;emailtemplateid=a0n12000006mpFy&quot; + 
&quot;&amp;templateid=a0p12000003vik9&quot; + 
&quot;&amp;emailadditionalto=&quot; + Billing_Contact_Email_Invoice__c +&apos;,&apos;+ Eval_Submitter_Email__c + &apos;,Lori.Smith@viewsonic.com&apos; +
&quot;&amp;qmode=SendEmail&quot; + 
&quot;&amp;ofn=Evaluation Purchase Quote for RMA &quot; + RMA__c + &quot; &quot; + Name +
&quot;&amp;uf0=1 &quot; + 
&quot;&amp;sc1=Chatter&quot; + 
&quot;&amp;sc0=1&quot; + 
&quot;&amp;mfts0=Eval_Quote_Sent_Out__c&quot; + 
&quot;&amp;mftsvalue0=True&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Eval Quote</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>identifies which email to be sent out</description>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding (Not Past Due)</fullName>
                <default>true</default>
                <label>Outstanding (Not Past Due)</label>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Returned/Purchased</fullName>
            </value>
            <value>
                <fullName>Written Off</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Write_Off_Date__c.field-meta.xml
<CustomField>
    <fullName>Write_Off_Date__c</fullName>
    <label>Write Off Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Quote__c.field-meta.xml
<CustomField>
    <fullName>Eval_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eval Quote</label>
    <referenceTo>Eval_Quote__c</referenceTo>
    <relationshipLabel>Eval Unit Details</relationshipLabel>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Testing Field. Will pull from product</inlineHelpText>
    <label>SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Sku_Text__c.field-meta.xml
<CustomField>
    <fullName>Sku_Text__c</fullName>
    <label>Sku Text</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of eval unit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product Returned</fullName>
            </value>
            <value>
                <fullName>Purchased/Invoiced</fullName>
            </value>
            <value>
                <fullName>Write-off</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
                <default>true</default>
                <label>Outstanding</label>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Status_Date_Change__c.field-meta.xml
<CustomField>
    <fullName>Status_Date_Change__c</fullName>
    <label>Status Date Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Write_Off_Date__c.field-meta.xml
<CustomField>
    <fullName>Write_Off_Date__c</fullName>
    <label>Prodcut Write Off Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EvalUnitsMasterClass.cls
public without sharing class EvalUnitsMasterClass {
    Map<Id,Eval_Unit_Details__c> oldUnits;
    Map<Id,Eval_Unit_Details__c> newUnits;
    
    public EvalUnitsMasterClass(Map<Id,Eval_Unit_Details__c> oldtriggerunits, Map<Id,Eval_Unit_Details__c> newtriggerunits){
        oldUnits = oldtriggerunits;
        newUnits = newtriggerunits;
        
    }
    
    public static void productSearch(List<Eval_Unit_Details__c> records){
        
        Map<String, Product2> prods = New Map<String,Product2>();
        for(Product2 p : [Select id,name from product2 where isactive = true]){
            prods.put(p.name, p);
        }
        
        for(Eval_Unit_Details__c e : records){
            if(e.Sku_Text__c != null){
                if(prods.containsKey(e.Sku_Text__c.substringBeforeLast('-'))){
                    product2 p = prods.get(e.Sku_Text__c.substringBeforeLast('-'));
                    e.SKU__c = p.Id;
                }else if(prods.containsKey(e.Sku_Text__c.substringBefore('-'))){
                    product2 p = prods.get(e.Sku_Text__c.substringBefore('-'));
                    system.debug(e.SKU__c);
                    e.SKU__c = p.Id;
                    system.debug(e.SKU__c);
                }   
                
            }
            
            
        }
    }
    
    
    public static void updateunits(List<Eval_Unit_Details__c> units){
        
        for(Eval_Unit_Details__c u : units){
            if(u.Status__c != null && u.Status_Date_Change__c == null){
                u.Status_Date_Change__c = Date.today();
            }
            if(u.Status__c == 'Write-off' && u.Write_Off_Date__c == null){
                u.Write_Off_Date__c = Date.today();
            }            
        }        
    }
    public void invoiced(){
        
        Set<Id> quotes = new Set<Id>();
        
        for(Eval_Unit_Details__c neweu : newUnits.values()){
           Eval_Unit_Details__c oldeu = oldUnits.get(neweu.Id);
            if(neweu.Status__c != oldeu.Status__c && neweu.Status__c.toLowerCase().contains('purchased')  && neweu.Eval_Quote__c != null){
                quotes.add(neweu.Eval_Quote__c);             
                
            }
        }
        List<Eval_Quote__c> quotesToUpdate = new List<Eval_Quote__c>();
        for(Id q : quotes){
           Eval_Quote__c eq = new Eval_Quote__c(id = q,Eval_Quote_Status__c ='Closed');
            quotesToUpdate.add(eq);
        }
        update quotesToUpdate;
    }
    public void closed(){
       //checking to see if eval is closed. then check other units to see if the entire order should be closed.
       //
        Set<Id> evals = new Set<Id>();
        for(Eval_Unit_Details__c neweu : newUnits.values()){
           
            Eval_Unit_Details__c oldeu = oldUnits.get(neweu.Id);
            if(neweu.Status__c != oldeu.Status__c){
                evals.add(neweu.eval_request__c);                
            }
        }
        EvalUnitsMasterClass.evalstatus(evals);
    }
    @future
    public static void evalstatus(Set<Id> records) {
        // review the evals and all their units to see if the order should be closed or not. 
         List <Eval_request__c> evalstoupdate = new List <Eval_request__c>();
         List <Eval_request__c> units = [Select id,Eval_Process_Stage__c,product_status__c ,(Select status__c from Eval_Unit_Details__r)  from Eval_request__c  where id in : records];
         
         for(Eval_request__c e : units){
         Boolean closed = true;
             for(Eval_Unit_Details__c u : e.Eval_Unit_Details__r){
                 if(u.Status__c == null || u.Status__c == '' || u.Status__c == 'Outstanding'){
                     closed = false;
                 }
             }
             if(closed == true){
                 e.Eval_Process_Stage__c = 'Closed';
                 e.product_status__c = 'Closed';
             }else{
                 e.Eval_Process_Stage__c = 'Shipped';
                 e.product_status__c = 'Past Due';
             }
             evalstoupdate.add(e);
             system.debug('status' +e.Eval_Process_Stage__c);
             system.debug('true of false' +closed);
        }
        try{
            update evalstoupdate;
        }catch(exception e){
            system.debug('error '+e);
        }
        
        system.debug(evalstoupdate);
        
        
    }
}