force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product Manager object. easily update any changes to product line</description>
    <label>Product Pillar</label>
    <referenceTo>Product_Manager__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Product_Manager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Manager__c.field-meta.xml
<CustomField>
    <fullName>Product_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Manager__c/Product_Manager__c.object-meta.xml
<CustomObject>
    <description>Delete this object but need to update classes that reference it</description>
    <label>Product Pillar</label>
    <nameField>
        <label>Product Pillar</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Pillars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Manager__c/fields/Product_Manager__c.field-meta.xml
<CustomField>
    <fullName>Product_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Product_Manager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductService.cls
public with sharing class ProductService
{
    public static void findProductManager(List<Product2> records)
    {
        Set<String> families = new Set<String>();
        for (Product2 record : records) families.add(record.Family);

        Map<String, Product_Manager__c> managers = new Map<String, Product_Manager__c>();
        for (Product_Manager__c manager : [
            SELECT Name FROM Product_Manager__c
            WHERE Name IN :families
        ]) managers.put(manager.Name, manager);

        for (Product2 record : records)
            if (managers.containsKey(record.Family))
             if(record.Product_Line__c == null){
                record.Product_Line__c = managers.get(record.Family).Id;
            }
    }
}