force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>VAR</fullName>
            </value>
            <value>
                <fullName>NSP</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Hot_Swap__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Hot Swap</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/Hot_Swap__c.object-meta.xml
<CustomObject>
    <label>Hot Swap</label>
    <nameField>
        <label>Hot Swap  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hot Swaps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hot_Swap__c/fields/Customer_Service_Action__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Action__c</fullName>
    <label>Customer Service Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Hot_Swap_Products_Tracking_Id__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Products_Tracking_Id__c</fullName>
    <label>Hot Swap Products Tracking Id &amp; Case Id</label>
    <length>38768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/HotSwap_Product_Quantity__c.field-meta.xml
<CustomField>
    <fullName>HotSwap_Product_Quantity__c</fullName>
    <label>Requested Qty/Sold Qty-Product Requested</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>PostalCode</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Reason_For_Hot_Swap__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Hot_Swap__c</fullName>
    <label>Reason For Hot Swap</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Recipient_Email__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Email__c</fullName>
    <label>Recipient Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Recipient_Name__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Name__c</fullName>
    <label>Recipient Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Recipient_Phone__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Phone__c</fullName>
    <label>Recipient Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/SPA__c.field-meta.xml
<CustomField>
    <fullName>SPA__c</fullName>
    <label>SPA</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Hot Swaps</relationshipLabel>
    <relationshipName>Hot_Swaps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Region of the deal.</description>
    <inlineHelpText>Region of deal. The distributors added depend on this field. US, Canada, or no distributors will be added based on this field.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>VSI</fullName>
            </value>
            <value>
                <fullName>VSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>End_User_Company__c</formula>
    <inlineHelpText>For Reporting. Clean Column and dashboard look</inlineHelpText>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Spa__c.field-meta.xml
<CustomField>
    <fullName>Spa__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spa Master Link</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Spa Related Opportunites</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>Opportunity__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Hot_Swap_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Quantity__c</fullName>
    <label>Hot Swap Quantity</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Quantity_Sold__c.field-meta.xml
<CustomField>
    <fullName>Product_Quantity_Sold__c</fullName>
    <description>Created Field for hotswap project which shows how many products are sold</description>
    <label>Product Quantity Sold</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>Opportunity.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Hot_Swap_Requested__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check Box to Know if this SPA has Hot Swap Requested or Not</description>
    <label>Hot Swap Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/In_Approval_Review__c.field-meta.xml
<CustomField>
    <fullName>In_Approval_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Approval Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Partner</label>
    <referenceTo>Opportunity_Partner__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/StateSpaSync__c.field-meta.xml
<CustomField>
    <fullName>StateSpaSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>StateSpaSync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>Quote.Opportunity.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Hotswap_Identification__c.field-meta.xml
<CustomField>
    <fullName>Hotswap_Identification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to Identify to update the HotSwap Flag after approving or rejecting the HotSwap</description>
    <label>Hotswap_Identification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>Disti List Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/HotSwapCmpControllerTest.cls
@isTest
public class HotSwapCmpControllerTest {
    @testSetup
    public static void createdata ()
     {
       BuildTestData.AddRecords();        
    }
    
    static testMethod void getUpdateSpaProductsTest() { 
           test.startTest();
        Product2 prodstate = new Product2(Name = 'statesyncApex Test', family = 'test family',List_Price__c=5.00, IsActive= true,ProductCode = 'test', Hot_Swap_Quantity__c='7',Product_Quantity_Sold__c='20');
           insert prodstate;
      //  Account acc=new Account(Name='abc',Account_Type__c='Distributor',CurrencyIsoCode='USD');
       // insert acc;
        PriceBookEntry pbEntrys = new PriceBookEntry(
                UnitPrice = 300,
                PriceBook2Id = Test.getStandardPricebookId() ,
                Product2Id = prodstate.Id,
                IsActive = true
        	    );
         
        insert pbEntrys;
        
        
        
        String recid ='';
        Opportunity opp = [Select Id,Pricebook2Id,End_User__c,
                           (Select PricebookEntryId from OpportunityLineItems where pricebookentry.isactive = true) from opportunity
                            where Id in (Select Opportunityid from OpportunityLineItem where pricebookentry.isactive = true) limit 1];
        recid = opp.Id;
        OppQuote.getSpas(recid);
        
        //Opportunity_Partner__c opc=new Opportunity_Partner__c(
                                                     //   Partner_Account__c=acc.Id,
            										//	Opportunity__c=opp.Id	
                                                     //   );
       //insert opc;
        PriceBookEntry pbEntry = new PriceBookEntry(
                UnitPrice = 300,
                PriceBook2Id = opp.Pricebook2Id ,
                Product2Id = prodstate.Id,
                IsActive = true);
        
        insert pbEntry;
       
        
        Quote q = new Quote(OpportunityId = opp.Id,
                           name = 'Apex Test',
                           Pricebook2Id = opp.PriceBook2Id,
                           StateSpaSync__c  = true,
                           Status = 'Needs Review');
        insert q;
        Set< Id> olines = new Set<Id>();        
        
        String pbe = '';
            for(OpportunityLineItem oline : opp.OpportunityLineItems){
                
                pbe = oline.PricebookentryId;
                olines.add(oline.PricebookEntryId);
            } 
       
            Hot_Swap__c newHotSwap=new Hot_Swap__c();
           newHotSwap.SPA__c=q.Id;
            newHotSwap.Recipient_Name__c='Recipient';
            newHotSwap.Recipient_Phone__c='6789342';
            newHotSwap.Recipient_Email__c='reci@gmail.com';
            newHotSwap.Reason_For_Hot_Swap__c='test reason';
            newHotSwap.Street__c='street';
            newHotSwap.State__c='state';
            newHotSwap.PostalCode__c='672';
            newHotSwap.City__c='city';
            newHotSwap.Country__c='Country__c';
            newHotSwap.HotSwap_Product_Quantity__c= 'product-quantity';
 			newHotSwap.Hot_Swap_Products_Tracking_Id__c='product-quantity tracking';
            newHotSwap.Customer_Service_Action__c='Pending';
            insert newHotSwap;
        
        List<PricebookEntry> pb = [Select id from pricebookentry 
                             where pricebook2id = :opp.PriceBook2Id 
                             and isactive = true and id not in:olines ];
        
        QuoteLineItem lineitem = new QuoteLineItem(QuoteId = q.Id,
                                            Quantity = 3, 
                                            unitPrice = 300,
                                             Product2Id=prodstate.Id,
                                                 
                                            pricebookentryId = pbe);
         
        ///test
        insert lineitem;
        list<QuoteLineItem> qlList = new list<QuoteLineItem>();
        qlList.add(lineitem);
        
        test.stopTest();
        
        HotSwapCmpController.getSpaProducts(q.id);
        System.debug('Quote info'+q.id);
         System.debug('newHotSwap info'+newHotSwap);
         System.debug('qlList info'+qlList);
        System.debug('prodstate info'+prodstate);
       HotSwapCmpController.getUpdateSpaProducts(q.id,newHotSwap,qlList);
    }
     static testMethod void updateHotSwapFlagTest() { 
           test.startTest();
        Product2 prodstate = new Product2(Name = 'statesyncApex Test', family = 'test family',List_Price__c=5.00, IsActive= true,ProductCode = 'test');
           insert prodstate;
        
        PriceBookEntry pbEntrys = new PriceBookEntry(
                UnitPrice = 300,
                PriceBook2Id = Test.getStandardPricebookId() ,
                Product2Id = prodstate.Id,
                IsActive = true
        	    );
         
        insert pbEntrys;
        
        
        
        String recid ='';
        Opportunity opp = [Select Id,Pricebook2Id,End_User__c,
                           (Select PricebookEntryId from OpportunityLineItems where pricebookentry.isactive = true) from opportunity
                            where Id in (Select Opportunityid from OpportunityLineItem where pricebookentry.isactive = true) limit 1];
        recid = opp.Id;
        OppQuote.getSpas(recid);
        
        PriceBookEntry pbEntry = new PriceBookEntry(
                UnitPrice = 300,
                PriceBook2Id = opp.Pricebook2Id ,
                Product2Id = prodstate.Id,
                IsActive = true);
        
        insert pbEntry;
       
        
        Quote q = new Quote(OpportunityId = opp.Id,
                           name = 'Apex Test',
                           Pricebook2Id = opp.PriceBook2Id,
                           StateSpaSync__c  = true,
                            In_Approval_Review__c = true,
                           Status = 'Needs Review');
        insert q;
        
         
        Set< Id> olines = new Set<Id>();        
        
        String pbe = '';
            for(OpportunityLineItem oline : opp.OpportunityLineItems){
                
                pbe = oline.PricebookentryId;
                olines.add(oline.PricebookEntryId);
            } 
       
               
        List<PricebookEntry> pb = [Select id from pricebookentry 
                             where pricebook2id = :opp.PriceBook2Id 
                             and isactive = true and id not in:olines ];
        
        QuoteLineItem lineitem = new QuoteLineItem(QuoteId = q.Id,
                                            Quantity = 3, 
                                            unitPrice = 300,
                                             Hotswap_Identification__c = true,
                                                  
                                            pricebookentryId = pbe);
         
        ///test
        insert lineitem;
         
         q.In_Approval_Review__c = false;
         q.Hot_Swap_Requested__c = true;
         update q;
         
        
        
        test.stopTest();
        
      
    }
    
     
     static testMethod void updateHotSwapFlagTest2() { 
           test.startTest();
        Product2 prodstate = new Product2(Name = 'statesyncApex Test', family = 'test family',List_Price__c=5.00, IsActive= true,ProductCode = 'test');
           insert prodstate;
        
        PriceBookEntry pbEntrys = new PriceBookEntry(
                UnitPrice = 300,
                PriceBook2Id = Test.getStandardPricebookId() ,
                Product2Id = prodstate.Id,
                IsActive = true
        	    );
         
        insert pbEntrys;
        
        
        
        String recid ='';
        Opportunity opp = [Select Id,Pricebook2Id,End_User__c,
                           (Select PricebookEntryId from OpportunityLineItems where pricebookentry.isactive = true) from opportunity
                            where Id in (Select Opportunityid from OpportunityLineItem where pricebookentry.isactive = true) limit 1];
        recid = opp.Id;
        OppQuote.getSpas(recid);
        
        PriceBookEntry pbEntry = new PriceBookEntry(
                UnitPrice = 300,
                PriceBook2Id = opp.Pricebook2Id ,
                Product2Id = prodstate.Id,
                IsActive = true);
        
        insert pbEntry;
       
        
        Quote q = new Quote(OpportunityId = opp.Id,
                           name = 'Apex Test',
                           Pricebook2Id = opp.PriceBook2Id,
                           StateSpaSync__c  = true,
                            In_Approval_Review__c = true,
                           Status = 'Needs Review');
        insert q;
        
         
        Set< Id> olines = new Set<Id>();        
        
        String pbe = '';
            for(OpportunityLineItem oline : opp.OpportunityLineItems){
                
                pbe = oline.PricebookentryId;
                olines.add(oline.PricebookEntryId);
            } 
       
               
        List<PricebookEntry> pb = [Select id from pricebookentry 
                             where pricebook2id = :opp.PriceBook2Id 
                             and isactive = true and id not in:olines ];
        
        QuoteLineItem lineitem = new QuoteLineItem(QuoteId = q.Id,
                                            Quantity = 3, 
                                            unitPrice = 300,
                                             Hotswap_Identification__c = true,
                                            pricebookentryId = pbe);
         
        ///test
        insert lineitem;
         
         q.In_Approval_Review__c = false;
         update q;
        
        
        test.stopTest();
        
      
    }
    
}