force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/VSSubRegion__c.field-meta.xml
<CustomField>
    <fullName>VSSubRegion__c</fullName>
    <label>VS SubRegion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_SubRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/CsvUploaderMapping__mdt/CsvUploaderMapping__mdt.object-meta.xml
<CustomObject>
    <label>CSV Uploader Mapping</label>
    <pluralLabel>CSV Uploader Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CsvUploaderMapping__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sell_Through_Report_Import__c</fullName>
                <default>true</default>
                <label>Sell_Through_Report_Import__c</label>
            </value>
            <value>
                <fullName>Stock_Report_Import__c</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Sell_Through_Report_Import__c/Sell_Through_Report_Import__c.object-meta.xml
<CustomObject>
    <label>Sell Through Report Import</label>
    <nameField>
        <label>Sell Through Report Imports Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sell Through Report Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sell_Through_Report_Import__c/fields/CsvUploaderFileIdentifier__c.field-meta.xml
<CustomField>
    <fullName>CsvUploaderFileIdentifier__c</fullName>
    <inlineHelpText>An unique file identifier for records loaded from CSV Uploader.
            The identifier is composed of CSV File Name + Today + Timestamp.</inlineHelpText>
    <label>CSV Uploader File Identifier</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sell_Through_Report_Import__c/fields/distributor__c.field-meta.xml
<CustomField>
    <fullName>distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.VSSubRegion__c</field>
            <operation>equals</operation>
            <valueField>$Source.VS_SubRegion__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sell Through Report Imports</relationshipLabel>
    <relationshipName>Sell_Through_Report_Imports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sell_Through_Report_Import__c/fields/VS_Region__c.field-meta.xml
<CustomField>
    <fullName>VS_Region__c</fullName>
    <label>VS Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Stock_Report_Import__c/Stock_Report_Import__c.object-meta.xml
<CustomObject>
    <label>Stock Report Import</label>
    <nameField>
        <label>Stock Report Import Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Stock Report Imports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Stock_Report_Import__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.VSSubRegion__c</field>
            <operation>equals</operation>
            <valueField>$Source.VS_SubRegion__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Stock Report Imports</relationshipLabel>
    <relationshipName>Stock_Report_Imports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Stock_Report_Import__c/fields/Ready_to_Sync_to_TCRM__c.field-meta.xml
<CustomField>
    <fullName>Ready_to_Sync_to_TCRM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ready to Sync to TCRM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Stock_Report_Import__c/fields/VS_SubRegion__c.field-meta.xml
<CustomField>
    <fullName>VS_SubRegion__c</fullName>
    <label>VS SubRegion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_SubRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>VS Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/DistributorCsvUploaderController.cls
public class DistributorCsvUploaderController
{
    @AuraEnabled
    public static User getUserInfo() {
        return [SELECT UserType, Region__c, ContactId, Contact.AccountId, Contact.Account.Name FROM User WHERE Id =: UserInfo.getUserId()][0];
    }

    @AuraEnabled
    public static Map<String, List<String >> getMappingLabel2ObjectName() {
        Map<String, List<String >> mappingLabel2ObjectNames = new Map<String, List<String >> ();
        for (CsvUploaderMapping__mdt mapping: CsvUploaderMapping__mdt.getAll().values())
        {
            if (!mappingLabel2ObjectNames.containsKey(mapping.MasterLabel)) mappingLabel2ObjectNames.put(mapping.MasterLabel, new List<String> ());
            mappingLabel2ObjectNames.get(mapping.MasterLabel).add(mapping.Object__c);
        }

        User currentUser = getUserInfo();
        Map<String, List<String >> mappingLabel2ObjectNames2 = new Map<String, List<String >> ();        
        for (Account distri: [SELECT Id, Name FROM Account WHERE Name In: mappingLabel2ObjectNames.keySet()])
        {
            if (currentUser.ContactId != null && distri.Id == currentUser.Contact.AccountId)
            {
                mappingLabel2ObjectNames2.put(distri.Name, mappingLabel2ObjectNames.get(distri.Name));
                break;
            }
            else if (currentUser.ContactId == null)
            {
                mappingLabel2ObjectNames2.put(distri.Name, mappingLabel2ObjectNames.get(distri.Name));
            }
        }
        return mappingLabel2ObjectNames2;
    }

    @AuraEnabled
    public static Map<String, String> getCsvMapping(String mappingLabel, String mappingObject)
    {
        Map<String, String> csvHeader2FieldApi = new Map<String, String> ();
        List<CsvUploaderMapping__mdt> mappings = [SELECT Id FROM CsvUploaderMapping__mdt WHERE MasterLabel =: mappingLabel AND Object__c =: mappingObject];
        if (mappings.isEmpty()) return csvHeader2FieldApi;

        CsvUploaderMapping__mdt mappingRec = CsvUploaderMapping__mdt.getInstance(mappings[0].Id);
        Set<String> allMappingFields = Schema.SObjectType.CsvUploaderMapping__mdt.fields.getMap().keySet();
        Map<String, Schema.SObjectField> fieldName2FieldDesc = Schema.getGlobalDescribe().get(mappingRec.Object__c).getDescribe().fields.getMap();
        for (Integer i = 1; i<100; i++)
        {
            String csvHeaderField = 'csvheader_' + i + '__c';
            String objectField = 'objectfield_' + i + '__c';
            if (!allMappingFields.contains(csvHeaderField)) break;

            String csvHeaderFieldValue = String.valueOf(mappingRec.get(csvHeaderField));
            String objectFieldValue = String.valueOf(mappingRec.get(objectField));
            if (String.isEmpty(csvHeaderFieldValue) || String.isEmpty(objectFieldValue)) break;

            if(fieldName2FieldDesc.containsKey(objectFieldValue))
            {
            	String objectFieldType = fieldName2FieldDesc.get(objectFieldValue).getDescribe().getType().name();
            	csvHeader2FieldApi.put(csvHeaderFieldValue, objectFieldValue + ',' + objectFieldType);    
            }
        }
        return csvHeader2FieldApi;
    }

    @AuraEnabled
    public static Map<Integer, String> createSellThroughReportImports(String mappingLabel, String fileIdentifier, List<Sell_Through_Report_Import__c> records)
    {
        Account distributor = getDistributor(mappingLabel);
        for (Sell_Through_Report_Import__c rec: records)
        {
            rec.CsvUploaderFileIdentifier__c = fileIdentifier;
            rec.Ready_to_Sync_to_TCRM__c = true;
            rec.Distributor__c = distributor.Id;
            rec.VS_Region__c = distributor.VSRegion__c;
            rec.VS_SubRegion__c = distributor.VSSubRegion__c;
        }
        return insertObjectRecords(records);
    }

    @AuraEnabled
    public static Map<Integer, String> createStockReportImports(String mappingLabel, String fileIdentifier, List<Stock_Report_Import__c> records)
    {
        Account distributor = getDistributor(mappingLabel);
        for (Stock_Report_Import__c rec: records)
        {
            rec.CsvUploaderFileIdentifier__c = fileIdentifier;
            rec.Ready_to_Sync_to_TCRM__c = true;
            rec.Account__c = distributor.Id;
            rec.VS_Region__c = distributor.VSRegion__c;
            rec.VS_SubRegion__c = distributor.VSSubRegion__c;
        }
        return insertObjectRecords(records);
    }

    public static Account getDistributor(String distriName)
    {
    	List<Account> distributors = [SELECT Id, VSRegion__c, VSSubRegion__c FROM Account WHERE Name =: distriName];
        if (distributors.isEmpty())
        {
            throw new AuraHandledException('The distributor you choosed cannot be found! Please contact system administrator.');
        }
        return distributors[0];
    }
    
    public static Map<Integer, String> insertObjectRecords(List<SObject> records)
    {
        Savepoint sp = Database.setSavepoint();
        Map<Integer, String> lineNum2Error = new Map<Integer, String> ();
        Database.SaveResult[] srList = Database.insert(records, false);
        Integer lineIndex = 0;
        for (Database.SaveResult sr: srList)
        {
            if (!sr.isSuccess() && !sr.getErrors().isEmpty())
            {
                lineNum2Error.put(lineIndex, sr.getErrors()[0].getMessage());
            }
            lineIndex++;
        }
        if (lineNum2Error.size()> 0) Database.rollback(sp);
        return lineNum2Error;
    }
}