force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <formula>Partner_Account__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Interest&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Quote Request</fullName>
            </value>
            <value>
                <fullName>Agreed to Purchase</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Decided not to buy</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OppPipelineRecPage.cls
public class OppPipelineRecPage {
     @AuraEnabled
    public static List<Opportunity> getPipe(String recid,String oppfields, String prodfields,String clause)
    {    
        //get account fields from contact and account
        //need to determine account type also need all parent child account
        //relationships to add to list when querying opportunity partner or 
        //opportunity ...may do opp partner object and cross query either partner and/or
        //end user could be where opportunity__r.Accountid in: accts Or Account__c in : accts
        //
        //also need to query for stage, only show open opps, not closed opps. They can use reports for open and close
        //otherwise there will be too many
        //
        //get report button, would be a nice add on
        
        
        //if is end user, query all related pipeline
        //related pipeline is not spa and is related to parent or child accounts
        
        Set<Id> accts = new Set<Id>();
        Set<Id> oppids = new Set<Id>();
        
        if(recid.substring(0,3) == '001'){
            //this is an account
            List<Account> accounts = [Select ID, Type,ParentId from Account where ParentId = : recid or Id =: recid ];
            for(Account a : accounts){
                accts.add(a.Id);
                if(a.ParentId != null){
                  accts.add(a.ParentId);
              }
            }
         }
        
        if(recid.substring(0,3) == '003'){
             //this is an contact
            List<Contact> contacts = [Select AccountId, Account.Type,Account.ParentID from Contact where Id = : recid];
            //add the opportunity ids where contact relates to an opportunity
            List<OpportunityContactRole> conopp = [Select OpportunityID from OpportunityContactRole where ContactId = : recid];
            for(OpportunityContactRole o : conopp){
                oppids.add(o.OpportunityID);
                
            }
            //add the account ids to the account for query
            for(Contact c : contacts){
                accts.add(c.AccountId);
                if(c.Account.ParentId != null){
                accts.add(c.Account.ParentId);
              }
            }
         }
        
        //go through lists and get the parent account ids from all accounts
        List<Account> parents = [Select Parent.Id from Account where Id in: accts and Parent.Id != null ];
        for(Account a: parents){
            accts.add(a.Id);
        }
    	
    	List<Opportunity_Partner__c> partners = [Select  Opportunity__c from Opportunity_Partner__c where Account_Id__c in: accts];
        for(Opportunity_Partner__c op : partners){
            oppids.add(op.opportunity__c);
        }
        
        String shipped = 'Shipped';
        system.debug('Select '+oppfields+',(Select '+prodfields+                                             
                      ' from OpportunityLineItems where Status__c != \'' + String.escapeSingleQuotes(shipped)+'\' ) from Opportunity where (AccountId in: accts or Id in: oppids)'+
                       ' '+ String.escapeSingleQuotes(clause)+' order by CloseDate desc limit 30');
        
        List<Opportunity> oppsToReturn = Database.query('Select '+oppfields+',(Select '+prodfields+                                             
                      ' from OpportunityLineItems where Status__c != \'' + String.escapeSingleQuotes(shipped)+'\' ) from Opportunity where (AccountId in: accts or Id in: oppids)'+
                       ' '+ String.escapeSingleQuotes(clause)+' order by CloseDate desc limit 30');
        system.debug('opps returning '+oppsToReturn);
        
      	return oppsToReturn;
    }
    @AuraEnabled
     public static User getUser()
    {     
        
         return getUser.getUser();
    }
    @AuraEnabled
    public static List<String> getStatus()  
  {   
      return GetProductStatus.getStatus();
    }
    @AuraEnabled
   public static List<Opportunity> updateopps(List<Opportunity> opps,List<OpportunityLineItem> lines){  
    
        //save the opportuntiy and line items in collections after clicking on save
     
       String  errormessages = '';
       Integer numerrors = 0;
       Integer numsuccess = 0;
       Integer numopps = 1;
        
        List<Database.SaveResult> updateResults = Database.update(opps, false);
                for(Integer i=0;i<updateResults.size();i++){
                    if (updateResults.get(i).isSuccess()){
                        updateResults.get(i).getId();
                        system.debug('success id '+ opps.get(i).Name);
                        numsuccess += 1;
                
                    }else if (!updateResults.get(i).isSuccess()){
                        // DML operation failed
                        Database.Error error = updateResults.get(i).getErrors().get(0);
                        String failedDML = error.getMessage();
                        opps.get(i);//failed record from the list
                        system.debug('Failed ID '+opps.get(i).Name);
                        system.debug('Message '+ failedDML);
                        numerrors += 1;
                     }
                }
        
        system.debug('number of errors '+numerrors+ ' successes '+numsuccess);
        
        List<Database.SaveResult> updateResultsp = Database.update(lines, false);
                for(Integer i=0;i<updateResultsp.size();i++){
                    if (updateResultsp.get(i).isSuccess()){
                        updateResultsp.get(i).getId();
                        system.debug('success id '+ lines.get(i).Name);
                        numsuccess += 1;
                    }else if (!updateResultsp.get(i).isSuccess()){
                        // DML operation failed
                        Database.Error error = updateResultsp.get(i).getErrors().get(0);
                        String failedDML = error.getMessage();
                        lines.get(i);//failed record from the list
                        system.debug('Failed ID '+lines.get(i).Name);
                        system.debug('Message '+ failedDML);
                        numerrors += 1;
                     }
                }
        
       system.debug('number of errors '+numerrors+ ' successes '+numsuccess);
    
       return null;
 }
    @AuraEnabled
    public static List<OpportunityLineItem> delProd(String prodid,List<Opportunity> opps,List<OpportunityLineItem> lines,String product){  
    
       List<OpportunityLineItem> pline = [Select Id from OpportunityLineItem where id =: prodid];
       system.debug('line items delete'+pline);
       delete pline;
       return null; 
 } 
    

}