force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>VAR</fullName>
            </value>
            <value>
                <fullName>NSP</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pp_Count_of_Partner_Enrollees__c.field-meta.xml
<CustomField>
    <fullName>pp_Count_of_Partner_Enrollees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>pp Count of Partner Enrollees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Inactive.recordType-meta.xml
<RecordType>
    <fullName>Inactive</fullName>
    <active>false</active>
    <label>Inactive</label>
</RecordType>

force-app/main/default/classes/batch_pp_Account_Enrolled.cls
global class batch_pp_Account_Enrolled implements 
Database.Batchable<sObject>, Database.Stateful {
    
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    
    global Database.QueryLocator start(Database.BatchableContext bc) {  
        String acctType = 'VAR';
        String status2 = 'Legacy - Inactive';
        String Status ='Not Enrolled';
        String qry = 'SELECT Id, (Select id from Contacts where '+
            ' Partner_Portal_Enrollment_Status__c != : status and  Partner_Portal_Enrollment_Status__c != : status2) '+
            ' from account where Account_type__c = : acctType';
        system.debug(qry);
        return Database.getQueryLocator(
            qry
        );        
    }
    
    global void execute(Database.BatchableContext bc, List<Account> records){
        for(Account a : records){
        a.pp_Count_of_Partner_Enrollees__c  = a.Contacts.size();  
        }
        
              
        
        Database.DMLOptions dml = new Database.DMLOptions(); 
        dml.DuplicateRuleHeader.allowSave = true;
        dml.OptAllOrNone = false;
        
       
        
        try{
            update records;
        }catch(Exception e){
            String recId = records[0].Id;String objType  ='Account';String apexClass ='batch_pp_AccountCounts';String errMessage = e.getmessage();
            apexerrorlog.logError(recId, objType, apexClass, errMessage);database.update (records,dml);
        }   
       
        
        
    }    
    
    global void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records processed. disaster averted!');
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
                            JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
        system.debug(job);
    }    
    
}