force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>VAR</fullName>
            </value>
            <value>
                <fullName>NSP</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/pp_Count_of_Contacts__c.field-meta.xml
<CustomField>
    <fullName>pp_Count_of_Contacts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>pp Count of Contacts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/pp_Count_of_Enrollees_Active__c.field-meta.xml
<CustomField>
    <fullName>pp_Count_of_Enrollees_Active__c</fullName>
    <defaultValue>0</defaultValue>
    <label>pp Count of Enrollees Active</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/pp_Count_of_Partner_Enrollees__c.field-meta.xml
<CustomField>
    <fullName>pp_Count_of_Partner_Enrollees__c</fullName>
    <defaultValue>0</defaultValue>
    <label>pp Count of Partner Enrollees</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Inactive.recordType-meta.xml
<RecordType>
    <fullName>Inactive</fullName>
    <active>false</active>
    <label>Inactive</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT (Account.Type)</formula>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Partner_Portal_Enrollment_Status__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Enrollment_Status__c</fullName>
    <formula>if( PortalUserId__r.IsActive &amp;&amp; PortalUserId__r.LastLogin__c &gt; now()-90 , &apos;Active - Enrolled&apos; , 
if( PortalUserId__r.IsActive,  &apos;Enrolled - Inactive&apos;,
if( text(Finch_Club_Status__c) == &apos;Inactive&apos; ,  &apos;Legacy - Inactive&apos;,
&apos;Not Enrolled&apos;)))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner Portal Enrollment Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Active.recordType-meta.xml
<RecordType>
    <fullName>Active</fullName>
    <active>true</active>
    <label>Active</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Inactive.recordType-meta.xml
<RecordType>
    <fullName>Inactive</fullName>
    <active>true</active>
    <description>Inactive contacts</description>
    <label>Inactive</label>
</RecordType>

force-app/main/default/classes/batch_pp_AccountCounts.cls
global class batch_pp_AccountCounts implements 
Database.Batchable<sObject>, Database.Stateful {
    
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    
    global Database.QueryLocator start(Database.BatchableContext bc) {  
        String acctType = 'VAR';
        String qry = 'SELECT Id,pp_Count_of_Contacts__c, '+
            'pp_Count_of_Enrollees_Active__c,pp_Count_of_Partner_Enrollees__c '+
            ' from account where Account_type__c = : acctType and id in (Select accountid from contact)';
        system.debug(qry);
        return Database.getQueryLocator(
            qry
        );        
    }
    
    global void execute(Database.BatchableContext bc, List<Account> records){
        
        Map<id,List<Contact>> ConAccMap = new Map<id,List<Contact>>();
         List<contact> contactsList = 
             [Select id ,Partner_Portal_Enrollment_Status__c,AccountId FROM Contact where AccountId In :records];
        
        for(Contact c : contactsList)
        {
             if(ConAccMap.containsKey(c.AccountId))
               {   
                ConAccMap.get(c.AccountId).add(c);
                   
               }
            else 
               {   
                ConAccMap.put(c.AccountId,new list<contact>{c}); 
               }
        }
        
        
        
        for(Account a : records){            
            Double cons = 0;
            Double enrolled = 0;
            Double active = 0;
            
            List<contact> contList = ConAccMap.get(a.Id);
            
            if(contList != null && contList.size()> 0 ){
                for(Contact c : contList){                
                    cons ++;
                    if(c.Partner_Portal_Enrollment_Status__c != 'Legacy - Inactive' &&
                       c.Partner_Portal_Enrollment_Status__c != 'Not Enrolled'){
                           enrolled++;
                       }
                    if(c.Partner_Portal_Enrollment_Status__c == 'Active - Enrolled'){
                        active++;
                    }
                }
            }
            a.pp_Count_of_Contacts__c = cons;
            a.pp_Count_of_Partner_Enrollees__c = enrolled;
            a.pp_Count_of_Enrollees_Active__c = active;
        }
        
        
        
        Database.DMLOptions dml = new Database.DMLOptions(); 
        dml.DuplicateRuleHeader.allowSave = true;
        dml.OptAllOrNone = false;
        
        
        
        try{
            update records;
        }catch(Exception e){
            String recId = records[0].Id;String objType  ='Account';String apexClass ='batch_pp_AccountCounts';String errMessage = e.getmessage();
            apexerrorlog.logError(recId, objType, apexClass, errMessage);database.update (records,dml);
        }   
        
        
        
    }    
    
    global void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records processed. disaster averted!');
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
                            JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
        system.debug(job);
    }    
    
}