force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/LRP_ViewBoard_Exists__c.field-meta.xml
<CustomField>
    <fullName>LRP_ViewBoard_Exists__c</fullName>
    <defaultValue>false</defaultValue>
    <label>LRP ViewBoard Exists</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Marketing_Post_Sales__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Post_Sales__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Marketing Post Sales</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/ViewBoard_User_Type__c.field-meta.xml
<CustomField>
    <fullName>ViewBoard_User_Type__c</fullName>
    <label>ViewBoard User Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Application Owner</fullName>
            </value>
            <value>
                <fullName>User</fullName>
            </value>
            <value>
                <fullName>Super Admin</fullName>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Admin</fullName>
                <isActive>false</isActive>
                <label>Admin</label>
            </value>
            <value>
                <fullName>IT Management</fullName>
                <isActive>false</isActive>
                <label>IT Management</label>
            </value>
            <value>
                <fullName>Instructional Coach</fullName>
                <isActive>false</isActive>
                <label>Instructional Coach</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>This is for cross referencing city and state and getting  the county for accounts
can be used for heat maps</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerKeys__mdt/CustomerKeys__mdt.object-meta.xml
<CustomObject>
    <label>CustomerKey</label>
    <pluralLabel>CustomerKey</pluralLabel>
</CustomObject>

force-app/main/default/objects/CustomerKeys__mdt/fields/key__c.field-meta.xml
<CustomField>
    <fullName>key__c</fullName>
    <label>key</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Devices_Students_Use__c.field-meta.xml
<CustomField>
    <fullName>Devices_Students_Use__c</fullName>
    <label>Devices Students Use</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Windows/PC</fullName>
            </value>
            <value>
                <fullName>Chromebook</fullName>
            </value>
            <value>
                <fullName>Macbook</fullName>
            </value>
            <value>
                <fullName>Ipad</fullName>
            </value>
            <value>
                <fullName>Tablet Android</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Devices_You_Use__c.field-meta.xml
<CustomField>
    <fullName>Devices_You_Use__c</fullName>
    <label>Devices Techers Use</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Windows/PC</fullName>
            </value>
            <value>
                <fullName>Chromebook</fullName>
            </value>
            <value>
                <fullName>Macbook</fullName>
            </value>
            <value>
                <fullName>Ipad</fullName>
            </value>
            <value>
                <fullName>Tablet Android</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/What_Browsers_do_you_Use__c.field-meta.xml
<CustomField>
    <fullName>What_Browsers_do_you_Use__c</fullName>
    <label>What Browsers do you Use?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Chrome</fullName>
            </value>
            <value>
                <fullName>Microsoft Edge</fullName>
            </value>
            <value>
                <fullName>Safari</fullName>
            </value>
            <value>
                <fullName>Firefox</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/What_type_of_Casting_would_you_like__c.field-meta.xml
<CustomField>
    <fullName>What_type_of_Casting_would_you_like__c</fullName>
    <label>What type of Casting would you like</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>myViewBoard</fullName>
            </value>
            <value>
                <fullName>Vcast</fullName>
            </value>
            <value>
                <fullName>Chrome Cast for Education</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Which_do_you_want_to_focus_on__c.field-meta.xml
<CustomField>
    <fullName>Which_do_you_want_to_focus_on__c</fullName>
    <label>Which do you want to focus on?</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>myViewBoard</fullName>
            </value>
            <value>
                <fullName>Android whiteboarding</fullName>
            </value>
            <value>
                <fullName>Tools to use with Mac OS</fullName>
            </value>
            <value>
                <fullName>myViewBoard.com setup</fullName>
            </value>
            <value>
                <fullName>Quickboard</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/VSA_Open_Order__c.object-meta.xml
<CustomObject>
    <label>VSA_Open_Orders</label>
    <nameField>
        <label>VSA_Open_Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VSA_Open_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VSA_Open_Order__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Oracle_Orders</relationshipLabel>
    <relationshipName>Oracle_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EducationRegLight.cls
global without sharing class EducationRegLight {
    @AuraEnabled
    global static Account updateAcct(Account acct){
        
        update acct;        
        return acct;
    }
    @AuraEnabled
    global static Account getAccount(String recid){
        system.debug('recid');
        system.debug(recid);
        CustomerKeys__mdt k = [SELECT key__c  FROM CustomerKeys__mdt  limit 1];
        
        //String decoded =
        Blob key = Blob.valueOf(k.key__c);
        Blob blobData = EncodingUtil.base64Decode(recid);
        
        Blob decryptedBlob = Crypto.decryptWithManagedIV('AES128', key, blobData);		
        string decodedId = decryptedBlob.toString();
        String urldcrpt = 'https://c.visualforce.com/apex/visualforcepage?id='+decodedId;
        
        system.debug(urldcrpt); 
        
        
        Account a =[Select id, Name,(Select id, firstname, lastname, email from Contacts),Industry,Type,
                    Owner.Name,OwnerId,owner.email,owner.manager.name,owner.manager.email,owner.phone,owner.manager.phone,
                    owner.MobilePhone ,owner.manager.MobilePhone,BillingCity,BillingState,County__c,BillingPostalCode, LRP_ViewBoard_Exists__c  
                    from account 
                    where id =: decodedId];
        system.debug('returned acc ');
        system.debug(a);
        return a;
    }
    @AuraEnabled
    global static List<Contact> getContacts(String accId){
        system.debug('acc id '+accId);
        List<Contact> cons = [Select id,Name,Email,Title,Marketing_Post_Sales__c,ViewBoard_User_Type__c,
                              Account.Name,MailingState,Account.Parent.Name,FirstName,LastName
                              from Contact 
                              where AccountId =: accId];
        return cons;
        
        
    }
    @AuraEnabled
    global static void updateContacts( List<Contact> cons){
        
        update cons;
        
    }
    @AuraEnabled
    global static List<Contact> createCons( List<Contact> con){
        Set<String> conEmails = new Set<String>();
        for(Contact cn : con){
            conEmails.add(cn.Email);    
        } 
        
        Map<String,Contact> conMap = new Map<String,Contact>();
        for(Contact c : [Select id, FirstName,Email from Contact where Email in :conEmails]){
            conMap.put(c.Email,c);
        }
        List<Contact> cons = new List<Contact>();
        
        for(Contact c : con){
            if(c.Email != '' && c.FirstName != '' && c.AccountId != null && c.Email.contains('@')){
                Id conid = null;                   
                if(conMap.containsKey(c.Email)){
                    Contact cm = conMap.get(c.Email);
                    conid = cm.Id;
                }
                Contact newcon = new Contact();
                newcon.Id = conid;
                newcon.FirstName = c.FirstName;
                newcon.LastName = c.LastName;
                newcon.Phone = c.Phone;
                newcon.Email = c.Email;
                newcon.AccountId = c.AccountId;
                newcon.ViewBoard_User_Type__c = c.ViewBoard_User_Type__c;
                newcon.Marketing_Post_Sales__c = true;
                cons.add(newcon);
            }
        }
        
        Account a = [Select id, LRP_ViewBoard_Exists__c,name,description from account where id =: con[0].AccountId];
        
        try{
            upsert cons;
            a.LRP_ViewBoard_Exists__c = true;
            update a;
        }catch(Exception e){
            String t = 'Error on Public education site';
            AdminErrorMessage.SendError(e, t);
            throw new AuraHandledException('Admin has been notified and will reach out.'+ ' Admin can be reached @ '
                                           +Label.AdminEmail+ ' Error message is : '+
                                           + e.getMessage());
        }
        
        return cons;
        
    }
    @AuraEnabled
    global static Contact createCon( Contact con){
        insert con;
        return con;
        
    }
    @AuraEnabled
    global static List<VSA_Open_Order__c> getPurchaseOrder(String acct){
        String po = '';
        
        List<VSA_Open_Order__c> orders = [Select PO_Number__c ,Account__c, Ship_Date__c   from VSA_Open_Order__c  where 
                                             Account__c  = : acct order by Ship_Date__c  desc];
         
        
        return orders;
        
    }
    
    @AuraEnabled
    global static Order upOrder(Order o){
        try{
            
            List<Order> relatedOrder = [select id, AccountId, Devices_Students_Use__c ,Devices_You_Use__c ,
                                        What_Browsers_do_you_Use__c , What_type_of_Casting_would_you_like__c , 
                                        Which_do_you_want_to_focus_on__c from order where accountid =: o.AccountId];
            for(Order rod: relatedOrder){
                rod.Devices_Students_Use__c = o.Devices_Students_Use__c;
                rod.Devices_You_Use__c = o.Devices_You_Use__c;
                rod.What_Browsers_do_you_Use__c = o.What_Browsers_do_you_Use__c;
                rod.What_type_of_Casting_would_you_like__c = o.What_type_of_Casting_would_you_like__c;
                rod.Which_do_you_want_to_focus_on__c = o.Which_do_you_want_to_focus_on__c;
            }  
            database.update(relatedorder, false);
            
            upsert o;
            
            List<Task> ts = new List<Task>();
            User pdtrainer = [Select id,email,firstname,lastname from user where isactive = true and name like '%blake%' and name like '%everhart%' limit 1];
            
            Task t = new Task();
            t.subject = 'Updated PD Order';
            t.Type = 'To Do';
            t.ActivityDate = date.today();
            t.ownerid = pdtrainer.Id;
            t.whatid = o.Id;            
            ts.add(t);
            
            
            Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {pdtrainer.email};
                mail.setToAddresses(toAddresses);
            mail.setReplyTo(pdtrainer.email);
            mail.setSenderDisplayName('EDU Portal Order Update');
            mail.setSubject('EDU Portal Order Update');
            mail.setPlainTextBody('PD order was updated through portal. Please check order Number '+o.OrderNumber+ '      https://viewsonic.my.salesforce.com/'+o.Id);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            insert ts;
        }catch(Exception e){
            
            throw new AuraHandledException('Admin has been notified and will reach out.'+ ' Admin can be reached @ '
                                           +Label.AdminEmail+ ' Error message is : '+
                                           + e.getMessage() + 'error ..heere is the order '+ o +' '+ o.Status+ ' order info here '+ o.Id);
            
            
        }
        
        return o;
        
    }

    @AuraEnabled
    global static Order createOrder(Order o){
        
                /*
        List<Order> ord = [Select id, accountId from Order 
        where Accountid = : a.Id and status != 'Completed ' and
        status != 'Activated'];
        
        if(ord.size()> 0){
        o.Id = ord[0].Id;
        }
        */
        
        try{
            
            List<Order> relatedOrder = [select id, AccountId, Devices_Students_Use__c ,Devices_You_Use__c ,
                                        What_Browsers_do_you_Use__c , What_type_of_Casting_would_you_like__c , 
                                        Which_do_you_want_to_focus_on__c from order where accountid =: o.AccountId];
            for(Order rod: relatedOrder){
                rod.Devices_Students_Use__c = o.Devices_Students_Use__c;
                rod.Devices_You_Use__c = o.Devices_You_Use__c;
                rod.What_Browsers_do_you_Use__c = o.What_Browsers_do_you_Use__c;
                rod.What_type_of_Casting_would_you_like__c = o.What_type_of_Casting_would_you_like__c;
                rod.Which_do_you_want_to_focus_on__c = o.Which_do_you_want_to_focus_on__c;
            }  
            database.update(relatedorder, false);
            
            upsert o;
            
            List<Task> ts = new List<Task>();
            User pdtrainer = [Select id,email,firstname,lastname from user where isactive = true and name like '%blake%' and name like '%everhart%' limit 1];
            
            Task t = new Task();
            t.subject = 'Updated PD Order';
            t.Type = 'To Do';
            t.ActivityDate = date.today();
            t.ownerid = pdtrainer.Id;
            t.whatid = o.Id;            
            ts.add(t);
            
            
            Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {pdtrainer.email};
                mail.setToAddresses(toAddresses);
            mail.setReplyTo(pdtrainer.email);
            mail.setSenderDisplayName('EDU Portal Order Update');
            mail.setSubject('EDU Portal Order Update');
            mail.setPlainTextBody('PD order was updated through portal. Please check order Number '+o.OrderNumber+ '      https://viewsonic.my.salesforce.com/'+o.Id);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            insert ts;
        }catch(Exception e){
            
            throw new AuraHandledException('Admin has been notified and will reach out.'+ ' Admin can be reached @ '
                                           +Label.AdminEmail+ ' Error message is : '+
                                           + e.getMessage() + 'error ..heere is the order '+ o +' '+ o.Status+ ' order info here '+ o.Id);
            
            
        }
        
        return o;
        
    }
    @AuraEnabled
    global static List<Order> editTraining(String orderId, String acctId){
        List<Order> orders = new List<Order>();        
        List<Order> acctOrders = new List<Order>();
        
        DescribeSObjectResult describeResult = Order.getSObjectType().getDescribe();	
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );	
        
        try{
            String query =	  ' SELECT ' +	      String.join( fieldNames, ',' ) +	  ',Account.Name FROM ' +	      describeResult.getName()	+' where Id = : orderId';
            orders = Database.query( query );
            
            String query2 =	  ' SELECT ' +	      String.join( fieldNames, ',' ) +	  ',Account.Name FROM ' +	      describeResult.getName()	+' where AccountId = : acctId and Devices_You_Use__c != null';
            acctOrders = Database.query( query2 );            
            
        }catch(Exception e){
            
                throw new AuraHandledException('Admin has been notified and will reach out.'+ ' Admin can be reached @ '
                                               +Label.AdminEmail+ ' Error message is : '+
                                               + e.getMessage() + 'error ..here is the order '+ orders);
        }
        
        if(orders.size()> 0 && acctOrders.size()> 0){
            if(orders[0].Devices_You_Use__c == null){
                orders[0].Devices_You_Use__c = acctOrders[0].Devices_You_Use__c;
                orders[0].Devices_Students_Use__c  = acctOrders[0].Devices_Students_Use__c ;
                orders[0].What_Browsers_do_you_Use__c  = acctOrders[0].What_Browsers_do_you_Use__c ;  
                orders[0].What_type_of_Casting_would_you_like__c  = acctOrders[0].What_type_of_Casting_would_you_like__c ;  
                orders[0].Which_do_you_want_to_focus_on__c  = acctOrders[0].Which_do_you_want_to_focus_on__c;  
            } 
        }else if(orders.size()== 0 && acctOrders.size()> 0){
            Order od = new Order();
            od.Devices_You_Use__c = acctOrders[0].Devices_You_Use__c;
            od.Devices_Students_Use__c  = acctOrders[0].Devices_Students_Use__c ;
            od.What_Browsers_do_you_Use__c  = acctOrders[0].What_Browsers_do_you_Use__c ;  
            od.What_type_of_Casting_would_you_like__c  = acctOrders[0].What_type_of_Casting_would_you_like__c ;  
            od.Which_do_you_want_to_focus_on__c  = acctOrders[0].Which_do_you_want_to_focus_on__c;
            od.AccountId = acctOrders[0].AccountId;
            od.Status = 'Draft';
            orders.add(od);
            
        }
        
        
        
        
        return orders;
         
    }
    @AuraEnabled
    global static List<Order> getTrainings(String acctId){
        
        List<SObject> orders = new List<SObject>();
        DescribeSObjectResult describeResult = Order.getSObjectType().getDescribe();	
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );	
        try{
            String query =	  ' SELECT ' +	      String.join( fieldNames, ',' ) +	  ',Account.Name FROM ' +	      describeResult.getName()	+' where accountid = : acctId';
            orders = Database.query( query );
        }catch(Exception e){
            
                throw new AuraHandledException('Admin has been notified and will reach out.'+ ' Admin can be reached @ '
                                               +Label.AdminEmail+ ' Error message is : '+
                                               + e.getMessage() + 'error ..here is the order '+ orders);
        }
        
        return orders;
        
    }
    
}