force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/District_Classroom_Count__c.field-meta.xml
<CustomField>
    <fullName>District_Classroom_Count__c</fullName>
    <label>District Classroom Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/DistrictId__c.field-meta.xml
<CustomField>
    <fullName>DistrictId__c</fullName>
    <description>Id for the district..distinct and external id for k-12 public education</description>
    <externalId>true</externalId>
    <inlineHelpText>Id for the district..distinct and external id for k-12 public education</inlineHelpText>
    <label>NCES District ID MasterId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>This is for cross referencing city and state and getting  the county for accounts
can be used for heat maps</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/School__c/School__c.object-meta.xml
<CustomObject>
    <description>Public Schools that are attached to a district</description>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schools</relationshipLabel>
    <relationshipName>Schools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/School__c/fields/DistrictId__c.field-meta.xml
<CustomField>
    <fullName>DistrictId__c</fullName>
    <externalId>true</externalId>
    <label>DistrictId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testAccountMapping.cls
@isTest
public class testAccountMapping {
     @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }

    public static testMethod void testMyMaps() {
        test.startTest(); 
        Account a = [Select id, name, billingcity,billingstate,BillingPostalCode,industry,annualrevenue,
                    phone,Type,District_Classroom_Count__c,County__c from account order by name desc limit 1 ];
        
        
        
        School__c sc = new School__c(account__c = a.Id,
                                    name = 'test school',
                                    DistrictId__c = '123');
        insert sc;
        
        String city = a.billingcity;
        String state = a.billingstate;
        String zip = a.BillingPostalCode;
        System.debug('zip '+zip);
        String ind = a.Industry;
        String acctType = '';
        Double classSize = 0;
        Double rev = 0;
        Boolean focus = false;
        String limitstmnt = 'limit 5';
        String orderstmnt = 'order by name desc';
        String wherestmnt = '';
        Double rank = 0;
        String county = a.County__c;
        
        if(zip==null){
           a.billingpostalcode = '123';
          
           zip = '12';
        }
        
        if(county==null){
           a.county__c = 'count';
           
           county = 'cou';
        }
        
         if(acctType==null){
           a.Type = 'End User';
           
           acctType = 'End User';
        }
        
        if(rev == null){
            rev = 0;
        }
        
         if(classSize == null){
            classSize = 0;
        }
        
         if(rank == null){
            rank = 0;
        }
        
        update a;
        System.debug('zip '+zip);  
		
        List <Account> accts = getAccountsMap.getaccts(city, state, zip, ind, acctType, classSize, rev, focus, rank, limitstmnt, orderstmnt, wherestmnt,county);        
        List<School__c> schls = getAccountsMap.getSchoolssMap(accts);
        
        test.stoptest();
        
        system.assertEquals(accts[0].Id, a.Id);
        system.assertEquals(schls[0].account__c, a.Id);
        
        
    }
}