force-app/main/default/objects/Account/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>AccountId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Account.Id for funded heads criteria</description>
    <label>AccountId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Business__c.field-meta.xml
<CustomField>
    <fullName>Business__c</fullName>
    <description>VS Reps category of flow. Need to be on contact level so that all people can see report category. This is part of a flow.</description>
    <label>Business</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links Viewsonic Users with contacts. Used in automation for the product request roll ups.</description>
    <label>UserID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Task/recordTypes/Call.recordType-meta.xml
<RecordType>
    <fullName>Call</fullName>
    <active>true</active>
    <label>Call</label>
</RecordType>

force-app/main/default/objects/User/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Accounting_Category__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Category__c</fullName>
    <label>Accounting Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Strategic</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Disti/Consumer</fullName>
            </value>
            <value>
                <fullName>Ex Employee</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Nationals</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>VAR-ISR</fullName>
            </value>
            <value>
                <fullName>VAR-TM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_ID__c</fullName>
    <defaultValue>$User.ContactId</defaultValue>
    <label>Contact ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/newPartnerWelcomeEmail__c.field-meta.xml
<CustomField>
    <fullName>newPartnerWelcomeEmail__c</fullName>
    <defaultValue>false</defaultValue>
    <label>newPartnerWelcomeEmail</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Category__c.field-meta.xml
<CustomField>
    <fullName>Sales_Category__c</fullName>
    <label>Sales Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RBM</fullName>
            </value>
            <value>
                <fullName>TM</fullName>
            </value>
            <value>
                <fullName>Managment</fullName>
            </value>
            <value>
                <fullName>Distributor Partner</fullName>
            </value>
            <value>
                <fullName>Manager/Director</fullName>
            </value>
            <value>
                <fullName>AV Solutions</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>Disti</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UserMasterClass.cls
global without sharing class UserMasterClass {
    Map<Id, User> oldUsers;
    Map<Id, User> newUsers;
    
    public UserMasterClass(
        Map<Id, User> oldTriggerUsers, 
        Map<Id, User> newTriggerUsers) {
            
            oldUsers = oldTriggerUsers;
            newUsers = newTriggerUsers;
        }
    
    global static void CreateContact(List<User> users) {
        
        Set<Id> resultIds = (new Map<Id,User>(users)).keySet();
        UserMasterClass.UserConInfo(resultIds);
    }
    global static void newParnterUserCreated(List<User> users) {
        
        List<User> userVSParnters= [Select id,contactId,isactive,email,newPartnerWelcomeEmail__c
                                    from user where newPartnerWelcomeEmail__c = true and id in :users];
        //if you need to ensure that user is part of specific community there 
        //are two options, one is to set a field in the partner application/form
        //that is specific to the community, which is what is done in this case or 
        //add the community for example 
        //Select id, isactive,email,newPartnerWelcomeEmail__c from user where id in 
        //from user where id in (select memberid from networkmember where networkid = 'communitynetworkid')

        
 		system.debug('new partner class running for partner users welcome email');            
            for(User u : userVSParnters){    
                 
                  System.resetPasswordWithEmailTemplate(u.Id, true, 'pp_Welcome_Email');
                  Task nT = new Task();
                  nT.Subject = 'Welcome Email Partner Program Sent';
                  nT.WhoId = u.ContactId;
                  nT.Status = 'Completed';
                  nt.ActivityDate = date.today();
                  nt.Type = 'Email';
                  insert nT;


            }
      
       
    }
    
    global void portalUserUpdate() {
        
        List<User> users = new  List<User>();
        
        for (User u : newUsers.values()) {
            User oldUser  = oldUsers.get(u.Id);
            if(u.usertype != 'Standard' && (u.email != oldUser.email || 
                                            u.phone != oldUser.phone ||
                                            u.city != oldUser.city ||
                                            u.State != oldUser.State ||
                                            u.Country != oldUser.Country
                                           )){
                                               //update the contat with a future call
                                               users.add(u);
                                           }
            
        }
        portalContactUpdate updateJob = new portalContactUpdate(users);
        System.enqueueJob(updateJob);
    }
    
    @future
    global static void UserConInfo(Set<Id> records) {
        system.debug(FutureContext.futureHasRun());
        if (!FutureContext.futureHasRun() || Test.isRunningTest()) {    
            FutureContext.setFutureRan();  
            
            List<User> users = [Select Id,Contact_ID__c,Contact_Name__c,usertype,AccountId__c,Email,Sales_Category__c,FirstName,
                                LastName,Phone,Street,City,State,PostalCode,Country,Title,Accounting_Category__c
                                from User where Id In: records ];
            
            List<User> usersToUpdate = new List<User>();
            
            List <Account> vs = [Select Id from account where name = 'ViewSonic Corporation' limit 1];
            
            for(User u : users){
                
                if(u.Sales_Category__c != 'Distributor Partner' &&
                   u.UserType =='Standard' && vs.size()>0){
                    
                    Contact con = new Contact(
                        FirstName= u.FirstName,
                        LastName=u.LastName, 
                        email= u.Email, 
                        phone=u.Phone,
                        MailingStreet = u.Street,
                        MailingCity = u.City,
                        MailingState = u.State,
                        MailingPostalCode = u.PostalCode,
                        MailingCountry = u.Country,
                        OwnerId = u.Id,
                        Title = u.Title,
                        Business__c = u.Accounting_Category__c,
                        AccountId = vs[0].Id,
                        UserID__c = u.Id
                    );
                    
                    if(!Test.isRunningTest()){
                        insert con;   
                    }
                    
                    
                    u.Contact_ID__c = con.Id;
                    u.Contact_Name__c = u.FirstName+' '+u.LastName;
                    u.AccountId__c = vs[0].Id;
                    usersToUpdate.add(u);
                    
                    
                }		
            }
            
            update usersToUpdate;
            
             
        }
    }
}