force-app/main/default/objects/Account/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <label>Account Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>VAR</fullName>
            </value>
            <value>
                <fullName>NSP</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Lookup_Account__c.field-meta.xml
<CustomField>
    <fullName>End_User_Lookup_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this to lookup existing end user accounts. If it does not exist, then you can just enter as text in the section below. &quot;End User Company, City, and state&quot; You only need to fill one section.</inlineHelpText>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Must Select End User Account. If you do not see an existing account, please make sure the Account &apos;Type&apos; is set as &apos;End User&apos;</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>End User</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User Lookup Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Account_Search__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account_Search__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Re-Seller VAR will be added to opportunity partners. If you need to add additional Resellers, Please Use Opportunity Partners.</inlineHelpText>
    <label>Reseller Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OpportunityTeamMember/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Custom</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Team</relationshipLabel>
    <relationshipName>Opportunity_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Partner</label>
    <referenceTo>Opportunity_Partner__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OppTeams.cls
public class OppTeams {
    //Apex properties or variables

    public Id Id { get; set; }
    public Opportunity opp { get; set; }

    //constructor to get the Case record
    public OppTeams(ApexPages.StandardController controller) {
    opp =  (Opportunity) controller.getRecord();
    Id = opp.Id;
    System.debug('The case record: ' + opp);
    }

    //Method that can is called from the Visual Force page action attribute
     //@InvocableMethod(label='Update Teams' description='Updates Opportunity Team Members')
    
    public PageReference updateteam() {
        List<Opportunity> opps = new List<Opportunity>();
        opps.add(opp);
        
        List<OpportunityTeamMember> teamdel = [select Id,OpportunityId,Opportunity.AccountId from OpportunityTeamMember
                where OpportunityId =:opp.id];

                delete teamdel;
        
        Boolean runrules = true;
        OpportunityTeamAdd.teams(opps,runrules);
        
        //System.debug('Opp Id: ' + Id);
        //Create list and add related accounts
        //by going through opp partners and end user account
        
        //add the end user account as will to update the account team
        
        
        //update account teams on related accounts
        
        //remove all team members\
        


        List<OpportunityTeamMember> oppTeamtoInsert = new List<OpportunityTeamMember>();


        //add RBM and director  based on End User State if it is not an etail retail account and TM if the End user
        //is from education
        //for (Opportunity  o : [select Id,StateLookup__r.RBM__c,
                                //End_User_Lookup_Account__c,End_User_Lookup_Account__r.Account_Type__c ,
                                //End_User_Lookup_Account__r.Industry,  Partner_Account_Search__c, 
                                //Partner_Account_Search__r.Account_Type__c,StateLookup__r.Director_RBM__c,
                                //StateLookup__r.Director_TM__c, StateLookup__r.Territory_Manager__c
                                //from Opportunity where id =: opp.id  ]){
        
           // OpportunityTeamMember rbm = new OpportunityTeamMember(
                                                       // OpportunityId = o.Id, 
                                                        //TeamMemberRole = 'RBM',
                                                        //UserId = o.StateLookup__r.RBM__c,
                                                        //OpportunityAccessLevel = 'Edit'    
                                                   // ); 
        
            //if(o.StateLookup__c != null && o.Partner_Account_Search__r.Account_Type__c != 'Retail/Etail'){

            //OpportunityTeamMember rbm = new OpportunityTeamMember(
                                            //OpportunityId = o.Id, 
                                            //TeamMemberRole = 'RBM',
                                            //UserId = o.StateLookup__r.RBM__c,
                                            //OpportunityAccessLevel = 'Edit'    
                                        //); 

                                          //oppTeamtoInsert.add(rbm); 
                                      
            //OpportunityTeamMember rbmdir = new OpportunityTeamMember(
                                            //OpportunityId = o.Id, 
                                            //TeamMemberRole = 'Manager/Director',
                                            //UserId = o.StateLookup__r.Director_RBM__c,
                                            //OpportunityAccessLevel = 'Edit'    
                                       // ); 

                                         // oppTeamtoInsert.add(rbmdir); 

             //if(o.End_User_Lookup_Account__r.Industry == 'Education'){
                    //OpportunityTeamMember tm = new OpportunityTeamMember(
                                            //OpportunityId = o.Id, 
                                            //TeamMemberRole = 'TM',
                                            //UserId = o.StateLookup__r.Territory_Manager__c,
                                            //OpportunityAccessLevel = 'Edit'    
                                        //); 

                                          //oppTeamtoInsert.add(tm); 
                                      
                    //OpportunityTeamMember tmdir = new OpportunityTeamMember(
                                            //OpportunityId = o.Id, 
                                            //TeamMemberRole = 'Manager/Director',
                                            //UserId = o.StateLookup__r.Director_TM__c,
                                            //OpportunityAccessLevel = 'Edit'    
                                        //); 

                                          //oppTeamtoInsert.add(tmdir); 
                                      //}

                                    //}
        


            //Get all the opportunity partners and query them and put the account Id in the list for each
            //Then query all account team  members that are on in the new string list of accounts in partners
            //before adding them to a list to insert, ensure the user id is active

            //Set<String> accts = new Set<String>();
                //for (Opportunity_Partner__c mem : [
                    //Select Id, Partner_Account__c, Opportunity__c ,Partner_Account__r.Id from Opportunity_Partner__c
                    //where Opportunity__c =:opp.id]) accts.add(mem.Partner_Account__c);
            
            //for(AccountTeamMember team : [Select UserId ,TeamMemberRole,User.IsActive from AccountTeamMember where AccountId IN : accts]){

                    //if(team.User.IsActive  ==true){
                        //OpportunityTeamMember resteam = new OpportunityTeamMember(
                                           // OpportunityId = opp.Id, 
                                            //TeamMemberRole =  team.TeamMemberRole,
                                            //UserId = team.UserId,
                                            //OpportunityAccessLevel = 'Edit'    
                                     //   ); 

                                          //oppTeamtoInsert.add(resteam); 


                   // }
                    

            //} 
                                                
                            //insert oppTeamtoInsert;


        //}



      List<Quote> q = [Select id from Quote where opportunityid =: Id order by createddate desc limit 1];
        
       Id redir = opp.Id;

        if(q.size() > 0){
            redir = q[0].id;
        }else{
            redir = opp.Id;
        }         
       
        
       //PageReference pageRefquote = new PageReference('/'+q[0].Id);
        
       PageReference pageRef = new PageReference('/'+redir);
       
       pageRef.setRedirect(true);
        
        
       return pageRef; //Returns to the opp page
    }
}