force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>This is for cross referencing city and state and getting  the county for accounts
can be used for heat maps</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order/fields/School__c.field-meta.xml
<CustomField>
    <fullName>School__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>School</label>
    <referenceTo>School__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/School__c/School__c.object-meta.xml
<CustomObject>
    <description>Public Schools that are attached to a district</description>
    <label>School</label>
    <nameField>
        <label>School Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schools</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/School__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Schools</relationshipLabel>
    <relationshipName>Schools</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/getAccountsMap.cls
public class getAccountsMap {
    @AuraEnabled
    public static List<Account> getaccts(String city,String state,String zip,
                                        String ind, String acctType,Double classSize,
                                        Double rev ,Boolean focus,Double rank,String limitstmnt,
                                       String orderstmnt,String wherestmnt,String county){
                                            
        
       ind = '%'+ind+'%';
       city = '%'+city+'%';
       state = '%'+state+'%';
       zip = '%'+zip+'%';
       acctType = '%'+acctType+'%';                                     
       county = '%'+county+'%';                                    
                                           
                                           
        DescribeSObjectResult describeResult = Account.getSObjectType().getDescribe();
        
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
            String query =      ' SELECT ' +          String.join( fieldNames, ',' )  +
            ' ,(Select id,name, email,phone,title from Contacts limit 3) FROM '
            +          describeResult.getName()  +' WHERE Industry like :ind and billingcity like : city  and billingpostalcode like: zip'
            +' and billingstate like : state and county__c like : county     '+
            '  '+ 
            wherestmnt + orderstmnt +' '+ limitstmnt;  
                                           
        system.debug('query');
        system.debug(query);
                                           
        List<SObject> accts = Database.query( query );    
        System.debug( accts );
        
        return accts;
                                           
    }
    
    @AuraEnabled
    public static List<School__c> getSchoolssMap(List<Account> acctIds) {
        
        DescribeSObjectResult describeResult = School__c.getSObjectType().getDescribe();
        
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
        
        String query =      ' SELECT ' +          String.join( fieldNames, ',' )  +    ' FROM '
            +          describeResult.getName()  +' WHERE account__c in:  acctIds order by Postal_Code__c desc nulls last  limit 50';    
        
        List <School__c> schls = Database.query( query );
        system.debug(schls);
        return schls;
        
    }
}