force-app/main/default/objects/Account/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <formula>1</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Accounts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/POS_Revenue__c.field-meta.xml
<CustomField>
    <fullName>POS_Revenue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>POS Revenue</label>
    <referenceTo>POS_Revenue__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountUpdateErrors__c/AccountUpdateErrors__c.object-meta.xml
<CustomObject>
    <label>AccountUpdateErrors</label>
    <nameField>
        <label>AccountUpdateErrors Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountUpdateErrors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountUpdateErrors__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AccountUpdateErrors</relationshipLabel>
    <relationshipName>AccountUpdateErrors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountUpdateErrors__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>ErrorMessage</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/POS_Revenue__c/POS_Revenue__c.object-meta.xml
<CustomObject>
    <label>POS Revenue</label>
    <nameField>
        <label>POS Revenue  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POS Revenue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POS_Revenue__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>POS Revenue</relationshipLabel>
    <relationshipName>POS_Revenue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/batchPOSRevenueAccountLinks.cls
global class batchPOSRevenueAccountLinks implements 
Database.Batchable<sObject>, Database.Stateful {
    
    // instance member to retain state across transactions
    global Integer recordsProcessed = 0;
    
    global Database.QueryLocator start(Database.BatchableContext bc) {
        //This will batch class will run on Monday Night and add assets
        //and then on tuesday morning, there will be an update on the account level
        //as a summary. 
        
        
        return Database.getQueryLocator(
            'Select id, POS_Revenue__c ,(select id from POS_Revenue__r) from account where id in (select Account_Name__c  from POS_Revenue__c)'
        );
    }
    
    global void execute(Database.BatchableContext bc, List<Account> records){        
        
        for(Account a : records){
            for(POS_Revenue__c r :a.POS_Revenue__r){
                a.POS_Revenue__c = r.Id;
            }
        }
        Database.SaveResult[] srList = database.update (records,false);
        List<AccountUpdateErrors__c> errors = new List<AccountUpdateErrors__c>();
        
        for (Integer i = 0; i < srList.size(); i++) {
            AccountUpdateErrors__c acError = new AccountUpdateErrors__c ();
            if(!srList[i].isSuccess()){
                acError.Account__c = records[i].Id;
                //system.debug('acct id '+records[i].Id);
                for(Database.Error err : srList[i].getErrors()) {
                    acError.ErrorMessage__c = err.getStatusCode() + ': ' + err.getMessage();
                }
                 errors.add(acError); 
            }
           
        }
        
        insert errors;
    }
    
    global void finish(Database.BatchableContext bc){
        System.debug(recordsProcessed + ' records processed. disaster averted!');
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, 
                            JobItemsProcessed,
                            TotalJobItems, CreatedBy.Email
                            FROM AsyncApexJob
                            WHERE Id = :bc.getJobId()];
        system.debug(job);
    }    
    
}