force-app/main/default/objects/Account/fields/Acct_Team_Check__c.field-meta.xml
<CustomField>
    <fullName>Acct_Team_Check__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used for batch class to update the account team when industry, account type, or owner is changed</description>
    <label>Acct Team Check</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <formula>CASE(left(text(Type )  ,3), &apos;NSP&apos;, &apos;National&apos;,&apos;SPG&apos;, &apos;SPG&apos;,&apos;Dis&apos;,&apos;Distributor&apos;,&apos;Ret&apos;,&apos;Etail&apos;,&apos;LA &apos;,&apos;Latin America&apos;,&apos;End User&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/HQ_Account_Check_if_HQ__c.field-meta.xml
<CustomField>
    <fullName>HQ_Account_Check_if_HQ__c</fullName>
    <defaultValue>false</defaultValue>
    <description>HQ Account Flag</description>
    <inlineHelpText>Leave blank if this is a Daughter Account, if Parent/HQ account please check box.</inlineHelpText>
    <label>HQ Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/schAccountTeam.cls
global class schAccountTeam implements Schedulable {
  global void execute(SchedulableContext ctx) {
      List<Account> accts = [SELECT ID,Acct_Team_Check__c from Account where Acct_Team_Check__c = true limit 9999];
      List<AccountTeamMember> teamToDelete = [Select Id from AccountTeamMember where Accountid in : accts];
      List<AccountTeamMember> aTeamToUpdate = new List<AccountTeamMember>();
      database.delete(teamToDelete,false);
      
      for (Account  a : [SELECT Type,Id,ParentId,Name,BillingState,BillingCountry,BillingStreet,BillingCity,Acct_Team_Check__c,
                           ShippingStreet,OwnerId,ShippingCity,ShippingState,ShippingPostalCode,BillingPostalCode,
                           ShippingCountry,HQ_Account_Check_if_HQ__c, Owner.ManagerId ,Industry,
                           Channel__c FROM Account WHERE Id IN :accts]) {
                               a.Acct_Team_Check__c = false;
                               
        	
    	}
      database.insert(aTeamToUPdate, false);
      for(Account ac : accts){
          ac.Acct_Team_Check__c = false;
      }
      database.update(accts, false);
    }
  }