force-app/main/default/objects/Account/fields/aliasChange__c.field-meta.xml
<CustomField>
    <fullName>aliasChange__c</fullName>
    <defaultValue>false</defaultValue>
    <label>aliasChange</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/POSAccountAliases__c/POSAccountAliases__c.object-meta.xml
<CustomObject>
    <description>Aliases for Accounts and how they show on POS</description>
    <label>POSAccountAlias</label>
    <nameField>
        <label>Name to Display</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POSAccountAliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POSAccountAliases__c/fields/SFDC_Account__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFDC Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>POSAccountAliases</relationshipLabel>
    <relationshipName>POSAccountAliases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PosAliasMasterClass.cls
public class PosAliasMasterClass {
    public static void acctAliasMatch(List<POSAccountAliases__c>records) {
        Map<String,POSAccountAliases__c> alias = new Map<String,POSAccountAliases__c>();       
        for(POSAccountAliases__c p : records){
            if(p.SFDC_Account__c != null){
                alias.put(p.Name , p);
                system.debug('acct '+p);
            }
        }       
        system.debug('map then records');
        system.debug(alias);
        system.debug(records);
        
        
        List<POSAccountAliases__c> names = [Select id,name,SFDC_Account__c from POSAccountAliases__c
                                            where name in: alias.keyset() and id not in: records];
        system.debug('names '+names);
        for(POSAccountAliases__c p : names){
            if(alias.containsKey(p.name)){
                POSAccountAliases__c acct = alias.get(p.name);
                p.SFDC_Account__c = acct.SFDC_Account__c;
                
            }            
        }
        
        update names;
        
    }
    public static void accAlias(List<POSAccountAliases__c>records) {
        Map<Id,Account> accts = new Map<Id,Account>();   
        for(POSAccountAliases__c p : records){
            if(p.SFDC_Account__c != null){
                Account a = new Account();
                a.Id = p.SFDC_Account__c;
                a.aliasChange__c = true;
                accts.put(a.Id,a);
            }            
        }
        update accts.values();
    }
    
}