force-app/main/default/objects/Account/fields/ApprovalManagerId__c.field-meta.xml
<CustomField>
    <fullName>ApprovalManagerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ApprovalManagerId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/VIP_Hotline_Submitter__c.field-meta.xml
<CustomField>
    <fullName>VIP_Hotline_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VIP/Hotline Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Accounts5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/VIP_in_Approval_Process__c.field-meta.xml
<CustomField>
    <fullName>VIP_in_Approval_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VIP in Approval Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/VIP_Products__c.field-meta.xml
<CustomField>
    <fullName>VIP_Products__c</fullName>
    <label>VIP Products</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/fields/VIP_Service_Reason_for_Request__c.field-meta.xml
<CustomField>
    <fullName>VIP_Service_Reason_for_Request__c</fullName>
    <label>VIP Service Reason for Request</label>
    <length>12000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Asset/fields/TP__c.field-meta.xml
<CustomField>
    <fullName>TP__c</fullName>
    <label>TP</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountVIPService.cls
public without sharing class AccountVIPService {
    @AuraEnabled
    public static Account getStatus(String recid){
       Account a = [Select Id,VIP_Service_Reason_for_Request__c,VIP_in_Approval_Process__c  from Account where id = : recid limit 1];
        
       system.debug('vip '+a.VIP_in_Approval_Process__c);
        
       return a;
    }
    
    @AuraEnabled
    public static Account hotline(String recid){
        
        
        system.debug('this is the approval trigger');
        Account a = [Select Id,VIP_Service_Reason_for_Request__c, VIP_Products__c,
                     ApprovalManagerId__c, VIP_Hotline_Submitter__c     from Account where id = : recid limit 1];
        User curuser = [Select id, managerid from user where id =: Userinfo.getUserId()];
        
        a.VIP_Hotline_Submitter__c = curuser.id;
        a.ApprovalManagerId__c = curuser.managerid;
        update a;
        
        system.debug(a);
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for Hotline Service Only . '+ a.VIP_Service_Reason_for_Request__c);
        req1.setObjectId(a.id);  
        
        // Submit on behalf of a specific submitter
        req1.setSubmitterId(curuser.Id); 
        
        // Submit the record to specific process and skip the criteria evaluation
        req1.setProcessDefinitionNameOrId('Account_Hotline_Service');
        req1.setSkipEntryCriteria(true);
        SYSTEM.debug('@@@@@Approval'+req1);
        // Submit the approval request for the account
        Approval.ProcessResult result = Approval.process(req1);
        Approval.unlock(a.id);
        
                
        return a;
    }
    
    @AuraEnabled
    public static Account vip(String recid){
        Account a = [Select Id,VIP_Service_Reason_for_Request__c, VIP_Products__c,
                     ApprovalManagerId__c, VIP_Hotline_Submitter__c     from Account where id = : recid limit 1];
        User u = [Select id, managerid from user where id =: Userinfo.getUserId()];
        
        a.VIP_Hotline_Submitter__c = u.id;
        a.ApprovalManagerId__c = u.managerid;
        update a;
        
        system.debug(a);
        Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
        req1.setComments('Submitting request for VIP Approval . '+ a.VIP_Service_Reason_for_Request__c);
        req1.setObjectId(a.id);  
        
        // Submit on behalf of a specific submitter
        req1.setSubmitterId(u.Id);
        
        // Submit the record to specific process and skip the criteria evaluation
        req1.setProcessDefinitionNameOrId('Account_VIP_Service');
        req1.setSkipEntryCriteria(true);
        SYSTEM.debug('@@@@@Approval'+req1);
        // Submit the approval request for the account
        Approval.ProcessResult result = Approval.process(req1);
        Approval.unlock(a.id);
        
        List<Asset> prods = [Select id, product2.name from asset where accountid =: recid
                            and product2.name != null and TP__c = null and SerialNumber = null];
        String products = '';
        for(Asset p : prods){
            products = products+ p.product2.name+', ';
        }
        
        a.VIP_Products__c = products;
        update a;
        
        return a;
    }
}