force-app/main/default/objects/Account/fields/Auto_Create_Disti__c.field-meta.xml
<CustomField>
    <fullName>Auto_Create_Disti__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, will auto create distributors on opportunities</description>
    <label>Auto Create Disti</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Region of the deal.</description>
    <inlineHelpText>Region of deal. The distributors added depend on this field. US, Canada, or no distributors will be added based on this field.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>VSI</fullName>
            </value>
            <value>
                <fullName>VSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <inlineHelpText>Select the type of Partner</inlineHelpText>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Reseller / VAR</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Spa_ID__c.field-meta.xml
<CustomField>
    <fullName>Spa_ID__c</fullName>
    <description>Used for informatica task that matches spa price with spa  claim</description>
    <formula>Opportunity.SPA_ID__c</formula>
    <label>Spa ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Partner</label>
    <referenceTo>Opportunity_Partner__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuoteNewPriceBook.cls
global class QuoteNewPriceBook {
    @InvocableMethod
    public static List<String> ChangePB(List<String> pboppid) {
        String oppid ='';
        String pbid ='';
        system.debug('pboppid '+pboppid);
        for(String o: pboppid){
            oppid = o.substring(0, 18);
            pbid = o.substring(19, 37);
        }
        system.debug('opid '+oppid);
        system.debug('pbid '+pbid);
        List<OpportunityLineItem> opplines = [Select Id from OpportunityLineItem
                                              where opportunityid = : oppid ];
		
        
        
        Set<String> prodids = new Set<String>();
        
        Map<String, OpportunityLineItem> products = new Map<String,OpportunityLineItem>();
        
        for(OpportunityLineItem op : [Select Id, product2Id,quantity,opportunityid, opportunity.pricebook2id from OpportunityLineItem
                                      where opportunityid = : oppid ])
        {
            products.put(op.Product2Id,op);
            prodids.add(op.Product2Id);  
        }
        
        //have to delete quote and opp line items before creating new pricebook id and new line items
        List<Quote> quote = [Select id from Quote where opportunityId = : oppid];
        delete quote;
        delete opplines;
        
        Opportunity opp = [Select Id,pricebook2id,Spa_Id__c,country__c from opportunity where id =: oppid];
        
        opp.pricebook2id = pbid;
        update opp;

        
        List<Pricebookentry> pbes = [Select Id,UnitPrice,Product2Id from Pricebookentry where 
                                     product2Id in: prodids and pricebook2id =: pbid and isactive = true];
        
        List<OpportunityLineItem> linestoinsert = new List<OpportunityLineItem>();
        Double quant = 1;
        
        
        for(Pricebookentry e : pbes){
            OpportunityLineItem ol = products.get(e.Product2Id);
            //ensure quantity is not zero. if so, use 1
            if(ol.Quantity > 0){
                quant = ol.Quantity;
            }
            
            OpportunityLineItem nl = new OpportunityLineItem(OpportunityId = oppid,
                                                             Quantity=quant,
                                                             UnitPrice= e.UnitPrice,
                                                             pricebookentryid = e.Id);
            linestoinsert.add(nl);
        }
        
        List<Account> distis = [SELECT Id,Name,BillingCountry FROM Account where BillingCountry =: opp.Country__c AND Auto_Create_Disti__c = true] ;
        system.debug('queried distributors ' +distis);
        
        List<AccountTeamMember> distiacctteam = [SELECT Id,UserId,AccountId,Account.BillingCountry,TeamMemberRole FROM AccountTeamMember where AccountId In:distis] ;
        List<Opportunity_Partner__c> partstoinsert = new List<Opportunity_Partner__c>();
         for (Account a : distis){
             if(opp.Pricebook2Id == '01sA00000008gzSIAQ' || opp.Pricebook2Id == '01sA00000008gzXIAQ'){
                 Opportunity_Partner__c distipart = new Opportunity_Partner__c(
                            Opportunity__c = opp.id, 
                            Partner_Type__c = 'Distributor',
                            Partner_Account__c = a.Id );
                        partstoinsert.add(distipart);
             }   
         }
        
        insert partstoinsert;
        opp.pricebook2id = pbid;
        update opp;
        
        
        
        insert linestoinsert;
        
        system.debug(products+' pbes');
        
        Quote q = new Quote(OpportunityId=opp.Id,
                            name= opp.Spa_Id__c,
                            status= 'Needs Review');
        insert q;
        
        List<Id> quotids = new List<Id>();
        quotids.add(q.Id);
        
        return quotids;
        
    }
}