force-app/main/default/objects/Account/fields/Auto_Create_Disti__c.field-meta.xml
<CustomField>
    <fullName>Auto_Create_Disti__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, will auto create distributors on opportunities</description>
    <label>Auto Create Disti</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Region of the deal.</description>
    <inlineHelpText>Region of deal. The distributors added depend on this field. US, Canada, or no distributors will be added based on this field.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>VSI</fullName>
            </value>
            <value>
                <fullName>VSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/oppadddistis.cls
public class oppadddistis {
    @auraEnabled
    public static List<Account> getDistis(String recid){
        String country = '';
        Opportunity opp = new Opportunity();
        
        //getting the coutnry from the opporutniyt. sometimes reps do deals accross regions and best to 
        //use the opportunity field but if user is part of portal will look at country.
        //as this scales, we may need to add a region field from the User field to get the correct
        //list of distributors
        String viewsonic = '';
        try{
            opp = [Select id, Country__c from Opportunity where id = :recid];
            country = '%'+opp.Country__c+'%';
            if(opp.Country__c != 'Canada' && opp.Country__c != 'United States'){
                country = '%%';
            }
        }catch(Exception e){
            User u = [Select id , country from user where id =: Userinfo.getuserid()];country = u.Country;viewsonic = 'ViewSonic Corporation';
            
        }
        
        
        system.debug(opp);
        
        
        system.debug(country);
        List<Account> distis = [Select id, name, BillingStreet,BillingCity,Billingcountry,Type,
                               BillingState, phone, industry from account where (Auto_Create_Disti__c = true
                                and BillingCountry like : country) or name =: viewsonic  order by name asc];
        system.debug(distis);
            
        return distis;
    }
    
    @auraEnabled 
    public static void addDistis(List<Opportunity_Partner__c> distis){
        
        insert distis;
    }
}