force-app/main/default/objects/Account/fields/Auto_Create_Disti__c.field-meta.xml
<CustomField>
    <fullName>Auto_Create_Disti__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, will auto create distributors on opportunities</description>
    <label>Auto Create Disti</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <formula>CASE(left(text(Type )  ,3), &apos;NSP&apos;, &apos;National&apos;,&apos;SPG&apos;, &apos;SPG&apos;,&apos;Dis&apos;,&apos;Distributor&apos;,&apos;Ret&apos;,&apos;Etail&apos;,&apos;LA &apos;,&apos;Latin America&apos;,&apos;End User&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel_Pricing</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Clone_Quote_Products__c.field-meta.xml
<CustomField>
    <fullName>Clone_Quote_Products__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is on the quote action to create a quote. lets class know to clone the quote as well. otherwise, the clone will only clone the opp</description>
    <label>Clone Quote Products</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cloning__c.field-meta.xml
<CustomField>
    <fullName>Cloning__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to suppress unbulkified flows when cloning. Cloning buttons must be url hacked for this to work</description>
    <label>Cloning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Region of the deal.</description>
    <inlineHelpText>Region of deal. The distributors added depend on this field. US, Canada, or no distributors will be added based on this field.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>VSI</fullName>
            </value>
            <value>
                <fullName>VSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Account_Search__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account_Search__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Re-Seller VAR will be added to opportunity partners. If you need to add additional Resellers, Please Use Opportunity Partners.</inlineHelpText>
    <label>Reseller Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Product_Quantity__c</fullName>
    <label>Product Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reseller_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact_Email__c</fullName>
    <description>Do not need to add, if you put a contact name and the contact has an email address, the name will be added automatically.</description>
    <label>Reseller Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reseller_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact_Name__c</fullName>
    <label>Reseller Contact Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResellerContact__c.field-meta.xml
<CustomField>
    <fullName>ResellerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Reseller Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Spa_to_Transfer_to__c.field-meta.xml
<CustomField>
    <fullName>Spa_to_Transfer_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Part of workflow to transfer spa products from large deals with many products to other spas. this allows a process to ensure prices are consistent.</description>
    <label>Spa to Transfer to</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Spa to Transfer to)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Contact_Email__c</fullName>
    <label>Contact Email</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <description>Name of contact at the Reseller, End User, or Distributor</description>
    <inlineHelpText>Name of contact at the Reseller, End User, or Distributor</inlineHelpText>
    <label>Contact Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <inlineHelpText>Select the type of Partner</inlineHelpText>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Reseller / VAR</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Reseller_Contact__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Reseller_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact_Email__c</fullName>
    <formula>if(text(Partner_Type__c )=&quot;Distributor&quot;, &quot;&quot;,  Contact_Email__c )</formula>
    <label>Reseller Contact Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Spa_ID__c.field-meta.xml
<CustomField>
    <fullName>Spa_ID__c</fullName>
    <description>Used for informatica task that matches spa price with spa  claim</description>
    <formula>Opportunity.SPA_ID__c</formula>
    <label>Spa ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Partner</label>
    <referenceTo>Opportunity_Partner__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OppCloneProducts.cls
public class OppCloneProducts {
    public static Id ChangePBE(List<Opportunity> opps) {
        //create a set to be passed to at future class that update the cloned opp 
        //so that it can be cloned again if need be
        Set<Id> oppsupdating = new Set<Id>();
        system.debug('Clone class');
        String oldoppid = '';
        Opportunity opp = null;
        String channel = '';
        String country = '';
        for(Opportunity o : opps){
            if(o.cloning__c == true){
                oldoppid = o.Spa_to_Transfer_to__c;
                oppsupdating.add(o.Id);
                channel = o.Channel__c;
                country = o.Country__c;
                opp = o;
            }
        }
        
        system.debug('old opp id '+ oldoppid);
        system.debug(opp+' cloned opp');
       
        Set<String> prodids = new Set<String>();
        
        Map<String, OpportunityLineItem> products = new Map<String,OpportunityLineItem>();
        
        for(OpportunityLineItem op : [Select Id, product2Id,quantity,opportunityid, opportunity.pricebook2id, opportunity.Product_Quantity__c from OpportunityLineItem
                                      where opportunityid = : oldoppid ])
        {
            products.put(op.Product2Id,op);
            prodids.add(op.Product2Id);  
        }
        
        
        List<Pricebookentry> pbes = [Select Id,UnitPrice,Product2Id from Pricebookentry where 
                                     product2Id in: prodids and pricebook2id =: opp.Pricebook2Id and isactive = true];
        
        List<OpportunityLineItem> linestoinsert = new List<OpportunityLineItem>();
        
        Double quant = 1;
        
        
        for(Pricebookentry e : pbes){
            OpportunityLineItem ol = products.get(e.Product2Id);
            if(opp.Product_Quantity__c > 0){
            	quant = opp.Product_Quantity__c;                 
            }else if(ol.Quantity > 0){               
                quant = ol.Quantity;
            }else{
                 quant = 1;
            }
            
            OpportunityLineItem nl = new OpportunityLineItem(OpportunityId = opp.Id,
                                                             Quantity= quant,
                                                             UnitPrice= e.UnitPrice,
                                                             pricebookentryid = e.Id);
            linestoinsert.add(nl);
        }
        insert linestoinsert;
        
        List<Account> distis = [SELECT Id,Name,BillingCountry FROM Account where BillingCountry =: country AND Auto_Create_Disti__c = true] ;
        system.debug('queried distributors ' +distis);
        
        
        
        if(channel == '' ||channel== null){
            channel = 'Disti';
        }
        List<AccountTeamMember> distiacctteam = [SELECT Id,UserId,AccountId,Account.BillingCountry,TeamMemberRole FROM AccountTeamMember where AccountId In:distis] ;
        
        List<Opportunity_Partner__c> partstoinsert = new List<Opportunity_Partner__c>();
        /*
         for (Account a : distis){
             if(!channel.contains('Direct')){
                 Opportunity_Partner__c distipart = new Opportunity_Partner__c(
                            Opportunity__c = opp.id, 
                            Partner_Type__c = 'Distributor',
                            Partner_Account__c = a.Id );
                        partstoinsert.add(distipart);
             }   
         }
          */
        
        
        
        for(Opportunity o : opps){
            Opportunity_Partner__c op = new Opportunity_Partner__c(Partner_Account__c = o.Partner_Account_Search__c,
                                                                   Opportunity__c = o.Id,
                                                                   Reseller_Contact__c = o.ResellerContact__c ,
                                                                   Contact_Email__c  = o.Reseller_Contact_Email__c,
                                                                   Contact_Name__c = o.Reseller_Contact_Name__c,
                                                                   Partner_Type__c = 'Reseller / VAR');
            partstoinsert.add(op);
        }
        
        insert partstoinsert;
        
        Id quoteid = null;
        if(opp.Clone_Quote_Products__c == true){
            Quote q = new Quote(OpportunityId=opp.Id,
                                name= opp.Spa_Id__c,
                                status= 'Needs Review');
            insert q;
            quoteid = q.Id;
        }
        //OpportunityTeamAdd.teams(opps);
        OppCloneProducts.updateCloneOrigin(oppsupdating);
        return quoteid;
    }
    @future
    public static void updateCloneOrigin(Set<Id> opps){
        List<Opportunity> oppsToUpdate = [Select id,Spa_to_Transfer_to__c,Cloning__c,Clone_Quote_Products__c
                                          from opportunity where id in: opps];
        
        for(Opportunity o : oppsToUpdate){
            o.Spa_to_Transfer_to__c = null;
            o.Cloning__c = false;
            o.Clone_Quote_Products__c = false;
        }
        
        database.update(oppsToUPdate, false);
        
    }
    
}