force-app/main/default/objects/Account/fields/AV_Solutions_Partner__c.field-meta.xml
<CustomField>
    <fullName>AV_Solutions_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AV Solutions Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Duplicate_Rule_Suppres__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Rule_Suppres__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Duplicate Rule Suppres</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Spiff_Type__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Type__c</fullName>
    <label>Spiff Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Spiff_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advertising / PR / Press</fullName>
            </value>
            <value>
                <fullName>Architect / Consultant</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Distributor (Non-Active)</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Food Service</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality / Entertainment</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Manufacturer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical</fullName>
            </value>
            <value>
                <fullName>Rep Firm</fullName>
            </value>
            <value>
                <fullName>Retail / Convenience Store</fullName>
            </value>
            <value>
                <fullName>Supplier / Vendor</fullName>
            </value>
            <value>
                <fullName>Utility</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelProgram/fields/Automate_Members_via_Code__c.field-meta.xml
<CustomField>
    <fullName>Automate_Members_via_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automate Members via Code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChannelProgram/fields/AV_Certified_Only_Members__c.field-meta.xml
<CustomField>
    <fullName>AV_Certified_Only_Members__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AV Certified Only Members</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChannelProgram/fields/Spiff_Type_Specific__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Type_Specific__c</fullName>
    <description>only put a value if the sub category is spiff type and this is used to control who gets access to this program and its attachments</description>
    <label>Spiff Type Specific</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelProgram/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Spiff Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelProgram/fields/VS_Region__c.field-meta.xml
<CustomField>
    <fullName>VS_Region__c</fullName>
    <label>VS Region</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelProgram/fields/VS_SubRegion__c.field-meta.xml
<CustomField>
    <fullName>VS_SubRegion__c</fullName>
    <label>VS SubRegion</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_SubRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/testPP_AV_ProgramMembers.cls
@isTest
private class testPP_AV_ProgramMembers{
     public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void TestPP_AV_ChannelPrograms() {
        
        test.startTest();
        Account avAcct = new Account(Name='Some AV Company  LLC',Duplicate_Rule_Suppres__c  = true, 
        BillingCountryCode ='US', BillingStreet='12234343 masfasain',
        website = 'Zpdadfas345gwertwrtfesst.com',BillingCity='citysome',
        spiff_type__c = 'Sales Rep',
        AV_Solutions_Partner__c = false,
        billingPostalCode='7238389', BillingState = 'Arizona',
        Type='AV',Industry= 'Business');
        Database.DMLOptions dml = new Database.DMLOptions(); 
            dml.DuplicateRuleHeader.allowSave = true;
        database.insert(avAcct,dml);

        List<ChannelProgram> programs = new List<ChannelProgram>();
        
        ChannelProgram cp = new ChannelProgram();
        cp.Name = 'Test AV Spiff';
        cp.Automate_Members_via_Code__c = true;
        cp.Spiff_Type_Specific__c = 'Sales Rep';
        cp.Country__c = 'United States';
        cp.Category = 'AV';
        cp.Sub_Category__c = 'Spiff Type'; 
        cp.VS_Region__c = 'VSA';
        cp.VS_SubRegion__c = 'VSA US';     
        programs.add(cp);
        
        ChannelProgram cps = new ChannelProgram();
        cps.Name = 'Test AV Cert';
        cps.Automate_Members_via_Code__c = true;
        cps.AV_Certified_Only_Members__c = false;
        cps.Country__c = 'United States';
        cps.Category = 'AV';
        cps.VS_Region__c = 'VSA';
        cps.VS_SubRegion__c = 'VSA US';    
        cps.Sub_Category__c = 'Certification';       
        programs.add(cps);

        insert programs;
        
         // Schedule the test job
        String jobId = System.schedule('pp_AV_ProgramMembership',
                                       CRON_EXP, 
                                       new pp_AV_ProgramMembership());
        Test.stopTest();
        
        
        
    }
}