force-app/main/default/objects/Account/fields/AV_Solutions_Partner__c.field-meta.xml
<CustomField>
    <fullName>AV_Solutions_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AV Solutions Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Spiff_Type__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Type__c</fullName>
    <label>Spiff Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Spiff_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advertising / PR / Press</fullName>
            </value>
            <value>
                <fullName>Architect / Consultant</fullName>
            </value>
            <value>
                <fullName>Communication</fullName>
            </value>
            <value>
                <fullName>Competitor</fullName>
            </value>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Designer</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Distributor (Non-Active)</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Financial</fullName>
            </value>
            <value>
                <fullName>Food Service</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Hospitality / Entertainment</fullName>
            </value>
            <value>
                <fullName>Information Technology</fullName>
            </value>
            <value>
                <fullName>Manufacturer</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Pharmaceutical</fullName>
            </value>
            <value>
                <fullName>Rep Firm</fullName>
            </value>
            <value>
                <fullName>Retail / Convenience Store</fullName>
            </value>
            <value>
                <fullName>Supplier / Vendor</fullName>
            </value>
            <value>
                <fullName>Utility</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelProgram/fields/Automate_Members_via_Code__c.field-meta.xml
<CustomField>
    <fullName>Automate_Members_via_Code__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automate Members via Code</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChannelProgram/fields/AV_Certified_Only_Members__c.field-meta.xml
<CustomField>
    <fullName>AV_Certified_Only_Members__c</fullName>
    <defaultValue>false</defaultValue>
    <label>AV Certified Only Members</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ChannelProgram/fields/Spiff_Type_Specific__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Type_Specific__c</fullName>
    <description>only put a value if the sub category is spiff type and this is used to control who gets access to this program and its attachments</description>
    <label>Spiff Type Specific</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Corporate</fullName>
            </value>
            <value>
                <fullName>Sales Rep</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ChannelProgram/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Certification</fullName>
            </value>
            <value>
                <fullName>Spiff Type</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/pp_AV_ProgramMembership.cls
global class pp_AV_ProgramMembership implements Schedulable {
    global void execute(SchedulableContext ctx) {
        List<ChannelProgramMember> membersToAdd = new List<ChannelProgramMember> ();
        
        List<ChannelProgramMember> membersList = new List<ChannelProgramMember> ();
        
        
        List<Account> accts = [Select id,BillingCountry,spiff_type__c, AV_Solutions_Partner__c 
                               from account where type = 'AV' and BillingCountry != null];
        Map<String, ChannelProgram> spiff = new Map<String, ChannelProgram>();
        Map<String, ChannelProgram> cert = new Map<String, ChannelProgram>();
        List<ChannelProgram> cProgram = new List<ChannelProgram>();
        for(ChannelProgram cp : [ Select id, Sub_Category__c,Country__c, AV_Certified_Only_Members__c, Spiff_Type_Specific__c 
                                 from ChannelProgram where Automate_Members_via_Code__c = true]){
                                     cProgram.add(cp);
                                     if(cp.Sub_Category__c == 'Certification'){
                                         //String cString = string.valueOf(cp.AV_Certified_Only_Members__c);
                                         
                                         cert.put(cp.Country__c+string.valueOf(cp.AV_Certified_Only_Members__c),cp);
                                     }
                                     if(cp.Sub_Category__c == 'Spiff Type'){
                                         spiff.put(cp.Country__c+cp.Spiff_Type_Specific__c,cp);
                                     }
                                     
                                 }  
        system.debug(cert);
        system.debug('numb of accts '+ accts);
        
        for(Account a : accts){
            if(spiff.containsKey(a.BillingCountry+a.Spiff_Type__c)){
                ChannelProgram spiffType = spiff.get(a.BillingCountry+a.Spiff_Type__c);
                ChannelProgramMember m = new ChannelProgramMember();
                m.PartnerId = a.Id;
                m.ProgramId = spiffType.Id;
                membersList.add(m);
            }
            if(cert.containsKey(a.BillingCountry+string.valueOf(a.AV_Solutions_Partner__c))){
                ChannelProgram certType = cert.get(a.BillingCountry+string.valueOf(a.AV_Solutions_Partner__c));
                ChannelProgramMember mc = new ChannelProgramMember();
                mc.PartnerId = a.Id;
                mc.ProgramId = certType.Id;
                membersList.add(mc);
            }
        }
        Map<String, ChannelProgramMember> cpm = new Map<String, ChannelProgramMember>();
        for(ChannelProgramMember c : [Select id , partnerId , programid from channelprogrammember where programId in: cProgram]){
            cpm.put(string.valueOf(c.programId)+string.valueOf(c.PartnerId),c);
        }
        for(ChannelProgramMember mem : membersList){
            
            if(!cpm.containsKey(string.valueOf(mem.ProgramId)+string.valueOf(mem.PartnerId))){
                membersToAdd.add(mem);
            }
            
        }
        
        system.debug('member list then member list size then member to add and the member to add size');
        system.debug(membersList);
        system.debug(membersList.size());
        
        
        system.debug(membersToAdd);
        system.debug(membersToAdd.size());
        database.insert(membersToAdd,false);
        
    }
}