force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <formula>CASE(left(text(Type )  ,3), &apos;NSP&apos;, &apos;National&apos;,&apos;SPG&apos;, &apos;SPG&apos;,&apos;Dis&apos;,&apos;Distributor&apos;,&apos;Ret&apos;,&apos;Etail&apos;,&apos;LA &apos;,&apos;Latin America&apos;,&apos;End User&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/HQ_Account_Check_if_HQ__c.field-meta.xml
<CustomField>
    <fullName>HQ_Account_Check_if_HQ__c</fullName>
    <defaultValue>false</defaultValue>
    <description>HQ Account Flag</description>
    <inlineHelpText>Leave blank if this is a Daughter Account, if Parent/HQ account please check box.</inlineHelpText>
    <label>HQ Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Non_Geo_Account__c.field-meta.xml
<CustomField>
    <fullName>Non_Geo_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When account is not assigned via geo territories, tells trigger not to update owners and account teams</description>
    <label>Non Geo Account</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links Viewsonic Users with contacts. Used in automation for the product request roll ups.</description>
    <label>UserID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <description>This is for cross referencing city and state and getting  the county for accounts
can be used for heat maps</description>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <label>StateCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Accounting_Category__c.field-meta.xml
<CustomField>
    <fullName>Accounting_Category__c</fullName>
    <label>Accounting Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Business Strategic</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Disti/Consumer</fullName>
            </value>
            <value>
                <fullName>Ex Employee</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>Nationals</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>VAR-ISR</fullName>
            </value>
            <value>
                <fullName>VAR-TM</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountContactOwnerUpdate.cls
public class AccountContactOwnerUpdate {
    @future
    public static void UpdateOwners(Set<Id> cons,Set<Id> accts)
    {
        FutureContext.setFutureRan();
        
        Boolean a4 = FutureContext.futureHasRun();
        system.debug('before running has it ran '+a4 );
        
        List<Contact> conOwners = new List<Contact>();
        List<Account> accOwners = new List<Account>();
        //
        
        Set<Id> acctIds = new Set<Id>();
        
        system.debug('cons '+cons);
        
        if(accts.size() < 1){
            
            //this is an contact 
            //if the ownerid.profile name does not have sales then update the contact owner by
            //Account and or state rep
            conOwners = [Select Id, AccountId,Account.OwnerId,Account.Type,Owner.ProfileID,
                         Account.Owner.Profile.Name, OwnerId, Owner.Profile.Name,Account.Name,UserId__c, 
                         Account.Industry
                         from Contact where Id in: cons and Account.Non_Geo_Account__c = false];for(Contact c : conOwners){if(c.Account.Name == 'ViewSonic Corporation'){c.OwnerId = c.UserId__c;
                }else{if((c.Account.Type == 'VAR' || c.Account.Industry == 'Education' || c.Account.Industry == 'Education - Higher Education' )) {
                        acctIds.add(c.AccountId);}else if(c.Account.Type == 'End User'   && c.Account.Industry != 'Education' && c.Account.Industry != 'Education - Higher Education'){
                        acctIds.add(c.AccountId);}else if(c.Account.Type == 'VAR'){
                        acctIds.add(c.AccountId);}else{c.OwnerId = c.Account.OwnerId;}}}database.update(conOwners,false);
        }else{
            //this is an account
            //if the ownerid.profile name does not have sales then update the contact owner
            system.debug('okay, we got an account and are going to get the account info');
            accOwners = [Select Id, OwnerId,Type,Name,ParentId,BillingState,BillingCountry,Non_Geo_Account__c,
                         Owner.Profile.Name,Owner.ProfileID,Industry,BillingStreet,BillingCity,
                         ShippingStreet,ShippingCity,
                         ShippingState,ShippingPostalCode,BillingPostalCode,HQ_Account_Check_if_HQ__c,Channel__c,Owner.Accounting_Category__c,County__c
                         from Account where Id in: accts and Non_Geo_Account__c = false]; 
            
            accOwners = AccountContactOwnerUpdate.AccountAddress(accts);
            
            for(Account acc : accOwners){
                if(acc.Name == 'ViewSonic Corporation'){conOwners = [Select Id, UserId__c, OwnerId from Contact where AccountId =: acc.id];for(Contact c : conOwners){c.OwnerId = c.UserId__c;
                    }database.update(conOwners,false);
                }
                try{
                    update accOwners;}catch(Exception e){system.debug('error '+e);}
            }
        }
        accOwners = [Select Id, OwnerId,Type,Name,ParentId,BillingState,BillingCountry,Non_Geo_Account__c,
                     Owner.Profile.Name,Owner.ProfileID,Industry,BillingStreet,BillingCity,
                     ShippingStreet,ShippingCity,
                     ShippingState,ShippingPostalCode,BillingPostalCode,HQ_Account_Check_if_HQ__c,Channel__c,Owner.Accounting_Category__c,County__c
                     from Account where Id in: accts and Non_Geo_Account__c = true]; 
        
        accOwners = AccountContactOwnerUpdate.AccountAddress(accts);
        
        try{
            update accOwners;
        }catch(Exception e){
            system.debug('error '+e);
        }
    }
    public static List<Account> AccountAddress(Set<Id> accts)
    {
        
        system.debug('accounts and insert address');
        system.debug(accts);
        List<Account> accOwners = new List<Account>();
       
        
        accOwners = [Select Id, OwnerId,Type,Name,ParentId,BillingState,BillingCountry,Non_Geo_Account__c,
                     Owner.Profile.Name,Owner.ProfileID,Industry,BillingStreet,BillingCity,
                     ShippingStreet,ShippingCity,
                     ShippingState,ShippingPostalCode,BillingPostalCode,HQ_Account_Check_if_HQ__c,Channel__c,Owner.Accounting_Category__c,County__c
                     from Account where Id in: accts]; 
        
        system.debug('accowners list '+accOwners);
        
        Set<String> city = new Set<String>();
        for(Account acc : accOwners){
            if(acc.BillingCity != null){
                city.add(acc.BillingCity.toLowerCase());
            }
            
        }
        
        system.debug('set ');
        system.debug(city);
        
        Map<String, County__c> counties = new Map<String, County__c>();
        for (County__c c : [
            SELECT Name,Id,City__c,County__c, StateCode__c  FROM County__c
            WHERE City__c IN :city
        ]) 
            
            counties.put(c.City__c.toLowerCase()+ c.StateCode__c , c);
        
        system.debug('map ');
        system.debug(counties);
        for(Account a : accOwners){
            system.debug('the account cityand state ');
            system.debug(a.billingcity+a.billingstate);
            if(counties.size() > 0 && counties.containsKey(a.BillingCity.toLowerCase()+a.billingstate)){
                a.County__c = counties.get(a.billingcity.toLowerCase()+a.billingstate).Name;
                system.debug('there is a key');
                system.debug(counties.get(a.billingcity.toLowerCase()+a.billingstate).Name);
            }
            
            if(a.ShippingStreet == null){
                a.ShippingStreet = a.billingstreet;
                a.ShippingCity = a.billingcity;
                if(a.Owner.Accounting_Category__c !='Latin America'){
                    a.ShippingState = a.billingstate;
                }
                a.ShippingPostalCode = a.BillingPostalCode;
                a.ShippingCountry = a.BillingCountry;
            }
            if(a.ParentId == null){
                a.HQ_Account_Check_if_HQ__c = true;
            }else{
                a.HQ_Account_Check_if_HQ__c = false;
            }            
        }
        return accOwners;
    }
    
}