force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <formula>CASE(left(text(Type )  ,3), &apos;NSP&apos;, &apos;National&apos;,&apos;SPG&apos;, &apos;SPG&apos;,&apos;Dis&apos;,&apos;Distributor&apos;,&apos;Ret&apos;,&apos;Etail&apos;,&apos;LA &apos;,&apos;Latin America&apos;,&apos;End User&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POSAccountAliases__c/POSAccountAliases__c.object-meta.xml
<CustomObject>
    <description>Aliases for Accounts and how they show on POS</description>
    <label>POSAccountAlias</label>
    <nameField>
        <label>Name to Display</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POSAccountAliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POSAccountAliases__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>VAR</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>AV</fullName>
            </value>
            <value>
                <fullName>Pro AV</fullName>
                <isActive>false</isActive>
                <label>Pro AV</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/POSAccountAliases__c/fields/DistributorAlias__c.field-meta.xml
<CustomField>
    <fullName>DistributorAlias__c</fullName>
    <label>Distributor Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POSAccountAliases__c/fields/End_User_Alias__c.field-meta.xml
<CustomField>
    <fullName>End_User_Alias__c</fullName>
    <label>End User Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POSAccountAliases__c/fields/Reseller_Alias__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Alias__c</fullName>
    <label>Reseller Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/POSAccountAliases__c/fields/SFDC_Account__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFDC Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>POSAccountAliases</relationshipLabel>
    <relationshipName>POSAccountAliases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/posAliasApp.cls
public class posAliasApp {
     @AuraEnabled
    public static List<POSAccountAliases__c> getAliases(String aname){
        
        List<POSAccountAliases__c> alias = [Select id, name, channel__c, Reseller_Alias__c ,End_User_Alias__c,DistributorAlias__c,SFDC_Account__c,SFDC_Account__r.Name,
                                            SFDC_Account__r.Owner.Name from POSAccountAliases__c
                                           where Reseller_Alias__c = : aname or name = : aname or End_User_Alias__c = : aname or DistributorAlias__c = : aname];
        
        return alias;
        
    }

}