force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <formula>CASE(left(text(Type )  ,3), &apos;NSP&apos;, &apos;National&apos;,&apos;SPG&apos;, &apos;SPG&apos;,&apos;Dis&apos;,&apos;Distributor&apos;,&apos;Ret&apos;,&apos;Etail&apos;,&apos;LA &apos;,&apos;Latin America&apos;,&apos;End User&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Channel</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Duplicate_Rule_Suppres__c.field-meta.xml
<CustomField>
    <fullName>Duplicate_Rule_Suppres__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Duplicate Rule Suppres</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/ApexTest__c.field-meta.xml
<CustomField>
    <fullName>ApexTest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>used for test to run without hitting query limits on all the updates. This will be less needed as classes and triggers are updated with better efficiency</description>
    <label>Apex Test</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel_Pricing</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cloning__c.field-meta.xml
<CustomField>
    <fullName>Cloning__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to suppress unbulkified flows when cloning. Cloning buttons must be url hacked for this to work</description>
    <label>Cloning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Region of the deal.</description>
    <inlineHelpText>Region of deal. The distributors added depend on this field. US, Canada, or no distributors will be added based on this field.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>VSI</fullName>
            </value>
            <value>
                <fullName>VSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Contact__c.field-meta.xml
<CustomField>
    <fullName>End_User_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The email Address will be attached to the opportunity once an email is attached to the contact</inlineHelpText>
    <label>End User Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (End User Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Lookup_Account__c.field-meta.xml
<CustomField>
    <fullName>End_User_Lookup_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this to lookup existing end user accounts. If it does not exist, then you can just enter as text in the section below. &quot;End User Company, City, and state&quot; You only need to fill one section.</inlineHelpText>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Must Select End User Account. If you do not see an existing account, please make sure the Account &apos;Type&apos; is set as &apos;End User&apos;</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>End User</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User Lookup Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Account_Search__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account_Search__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Re-Seller VAR will be added to opportunity partners. If you need to add additional Resellers, Please Use Opportunity Partners.</inlineHelpText>
    <label>Reseller Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Name_Main__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Main__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is for mobile users to quickly add a product to an opportunity so that it has the most important Product Listed. This Could be used to update the Opportunity Name.</inlineHelpText>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>This product must be active and must be part of the default price book.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Product_Quantity__c</fullName>
    <label>Product Quantity</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Sales_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_Sales_Price__c</fullName>
    <inlineHelpText>Requested Spa Price if new spa request. The the spa has been approved and making a pipeline opportunity, then this is the price that was approved.</inlineHelpText>
    <label>Product Spa Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reseller_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact_Email__c</fullName>
    <description>Do not need to add, if you put a contact name and the contact has an email address, the name will be added automatically.</description>
    <label>Reseller Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reseller_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact_Name__c</fullName>
    <label>Reseller Contact Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResellerContact__c.field-meta.xml
<CustomField>
    <fullName>ResellerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Reseller Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Spa_to_Transfer_to__c.field-meta.xml
<CustomField>
    <fullName>Spa_to_Transfer_to__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Part of workflow to transfer spa products from large deals with many products to other spas. this allows a process to ensure prices are consistent.</description>
    <label>Spa to Transfer to</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunities (Spa to Transfer to)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Test_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Test_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For flows to not run when running Test Coverage on Apex Classes</description>
    <label>Test Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/CDW.recordType-meta.xml
<RecordType>
    <fullName>CDW</fullName>
    <active>true</active>
    <businessProcess>VSA Sales Stages</businessProcess>
    <label>CDW</label>
</RecordType>

force-app/main/default/objects/Pricebook2/fields/Channel_Pricing__c.field-meta.xml
<CustomField>
    <fullName>Channel_Pricing__c</fullName>
    <label>Channel Pricing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Channel_Pricing</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/CurrencyIsoCode__c.field-meta.xml
<CustomField>
    <fullName>CurrencyIsoCode__c</fullName>
    <label>CurrencyIsoCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/recordTypes/Main.recordType-meta.xml
<RecordType>
    <fullName>Main</fullName>
    <active>true</active>
    <label>Main</label>
</RecordType>

force-app/main/default/classes/TestMasterOpportunity.cls
@IsTest
public class TestMasterOpportunity  {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords(); 
        
    }
    
    Static testmethod void MasterOppInsert() {
        TriggerContextUtility.setFirstRunFalse();
        //Query the test records needed to create opportunities
        //Query Products, different account type and contacts associated with opportunity
        Test.startTest();
        
        Product2 prod =[Select Id, Name from Product2 where Name ='Apex Test' Limit 1];
        Account acc = [Select Id,Name,Type,BillingState from Account where name ='ZZpbest' Limit 1];
        Contact con = [Select Id, Name,Email from Contact where LastName= 'ApexTest' and email != '' Limit 1];
         
        Account edu = new Account(Name='ZZpbestEDdausidfhas',Duplicate_Rule_Suppres__c  = true, BillingCountryCode ='US',BillingStreet='123 main afasef',
                                           website = 'Zpbaasdfasdfasdfasfdsfesst.org',Industry='Education',BillingCity='citydfasdfasdfsome',billingPostalCode='7382342342389',BillingStateCode='CA' ,Type ='End User');
        
        Database.DMLOptions dml = new Database.DMLOptions(); 
        dml.DuplicateRuleHeader.allowSave = true;
        database.insert (edu,dml);        
        Account acccdw = [Select Id from Account where Name ='Cdw LLC' Limit 1];
        
        Pricebook2 pbNew = new Pricebook2();
        pbNew.Channel_Pricing__c = 'France Euro Standard';
        pbNew.Name = 'VSE Standard FRN Euro';
        pbNew.CurrencyIsoCode__c = 'EUR';
        pbNew.isActive = true;     
        insert pbNew;
        
        
        List<Opportunity> oppsToInsert = new List<Opportunity>();
        
        Opportunity opp = new Opportunity(Name = 'Apex disti Test',AccountID = acc.Id,Partner_Account_Search__c = acc.Id,
                                          ResellerContact__c = con.Id,
                                          Amount = 2000,CloseDate=Date.today(),StageName='Distributor SPA Request',Type='New Customer',
                                          Test_Opportunity__c=True, ApexTest__c= true );
        
        Opportunity oppPB = new Opportunity(Name = 'Apex disti Test',AccountID = acc.Id,Partner_Account_Search__c = acc.Id,
                                          ResellerContact__c = con.Id,Channel__c = pbNew.channel_pricing__c,
                                          Amount = 2000,CloseDate=Date.today(),StageName='Development',Type='Project',
                                          Test_Opportunity__c=True, ApexTest__c= true );
        
        oppsToInsert.add(oppPB);
        
       Opportunity dist = new Opportunity(Name = 'Apex Test',AccountID = acc.Id,Amount = 2000,CloseDate=Date.today(),
                                          StageName='Close Won',Type='New Customer',
                                          Test_Opportunity__c=True, ApexTest__c= true );
        
        
        
        oppsToInsert.add(dist);
        
         
        
        
        
        Opportunity oppus = new Opportunity(Name = 'Apex Test',End_User_Lookup_Account__c = acc.Id,Partner_Account_Search__c = acc.id, 
                                            Amount = 2000,CloseDate=Date.today(),StageName='Close Won',Type='New Customer',
                                            Test_Opportunity__c=True,End_User_Contact__c= con.id,
                                            ResellerContact__c = con.id, Product_Name_Main__c = prod.id,
                                            Product_Quantity__c=50, Country__c ='United States',ApexTest__c= true  );
        
        oppsToInsert.add(oppus);
        
        
        Opportunity oppObj4 = new Opportunity(Name = 'Apex Test',End_User_Lookup_Account__c = edu.Id,Partner_Account_Search__c = acccdw.id, 
                                              Amount = 2000,CloseDate=Date.today(),StageName='Development',Type='New Customer', 
                                              Test_Opportunity__c=True,End_User_Contact__c= con.id,
                                              Product_Sales_Price__c=200,Reseller_Contact_Name__c='Some Cool Test Name',Reseller_Contact_Email__c='mrcool@apextesting.com',
                                              Country__c= 'United States' , Product_Name_Main__c = prod.Id , Product_Quantity__c =10,ApexTest__c= true );
        
        oppsToInsert.add(oppObj4);
        
        Opportunity oppObj66 = new Opportunity(Name = 'Apex Test',End_User_Lookup_Account__c = edu.Id,Partner_Account_Search__c = acccdw.id, 
                                              Amount = 2000,CloseDate=Date.today(),StageName='Development',Type='New Customer', 
                                              Test_Opportunity__c=True,End_User_Contact__c= con.id,
                                              Product_Sales_Price__c=200,Reseller_Contact_Name__c='Some Cool Test Name',Reseller_Contact_Email__c='mrcool@apextesting.com',
                                              Country__c= edu.BillingCountry , Product_Name_Main__c = prod.Id , Product_Quantity__c =10,ApexTest__c= true );
        
        oppsToInsert.add(oppObj66);
        
        Opportunity can = new Opportunity(Name = 'Apex Test',End_User_Lookup_Account__c = acc.Id,Partner_Account_Search__c = acc.id, 
                                           Amount = 2000,CloseDate=Date.today(),StageName='Development',Type='New Customer',
                                           Test_Opportunity__c=True,End_User_Contact__c= con.id, Country__c ='Canada',
                                           Product_Sales_Price__c=200,Product_Name_Main__c=prod.id, Product_Quantity__c=50, ApexTest__c= true );
        
        oppsToInsert.add(can);
        
        Opportunity opp8 = new Opportunity(Name = 'Apex Test',End_User_Lookup_Account__c = edu.Id,Partner_Account_Search__c = acc.id, 
                                           Amount = 2000,CloseDate=Date.today(),StageName='Development',Type='New Customer',
                                           Test_Opportunity__c=True,End_User_Contact__c= con.id, Country__c ='Canada',
                                           Product_Sales_Price__c=200,Product_Name_Main__c=prod.id, Product_Quantity__c=50, ApexTest__c= true );
        
        oppsToInsert.add(opp8);
        
         Opportunity disti = new Opportunity(Name = 'Apex Test',End_User_Lookup_Account__c = edu.Id,Partner_Account_Search__c = acc.id, ResellerContact__c = null,
                                           Amount = 2000,CloseDate=Date.today(),StageName='Distributor SPA Request',Type='New Customer',
                                           Test_Opportunity__c=True,End_User_Contact__c= con.id, Country__c ='Canada',Cloning__c = false,
                                           Product_Sales_Price__c=200,Product_Name_Main__c=prod.id, Product_Quantity__c=50, ApexTest__c= true );
        
        oppsToInsert.add(disti);
        
        
        Opportunity disti2 = new Opportunity(Name = 'Apex Test',End_User_Lookup_Account__c = edu.Id,Partner_Account_Search__c = acc.id, ResellerContact__c = con.id,
                                           Amount = 2000,CloseDate=Date.today(),StageName='Distributor SPA Request',Type='New Customer',
                                           Test_Opportunity__c=True,End_User_Contact__c= con.id, Country__c ='Canada',Cloning__c = false,
                                           Product_Sales_Price__c=200,Product_Name_Main__c=prod.id, Product_Quantity__c=50, ApexTest__c= true );
        
        oppsToInsert.add(disti2);
        
        User uguest = [Select id from user where alias = 'guest' and isactive = true limit 1];
        
        Opportunity res = new Opportunity(Name = 'Apex Test',End_User_Lookup_Account__c = edu.Id,Partner_Account_Search__c = acc.id, 
                                           Amount = 2000,CloseDate=Date.today(),StageName='Development',Type='New Customer',ResellerContact__c = con.Id,
                                           Test_Opportunity__c=True,End_User_Contact__c= con.id, Country__c ='Canada',Cloning__c = false,
                                           Product_Sales_Price__c=200,Product_Name_Main__c=prod.id, Product_Quantity__c=50, ApexTest__c= true ,Ownerid = uguest.Id);
        
        oppsToInsert.add(res);
        
        
        
        database.insert (oppsToInsert,false);
        
        Opportunity oppqueried = [Select id from opportunity where country__c = 'United States' limit 1];
        Pricebookentry pbe = [Select Id,Pricebook2Id from Pricebookentry where isactive = true and pricebook2.name = 'VSA Distributor Price List' limit 1];
        
        
        OpportunityLineItem oline = new OpportunityLineItem(PricebookentryID = pbe.Id,
                                                            OpportunityId = oppqueried.Id,
                                                            Quantity = 10,
                                                            UnitPrice = 300);
        
        insert oline; 
        
        TriggerContextUtility.setFirstRunTrue();
        OpportunityLineItem doline = new OpportunityLineItem(PricebookentryID = pbe.Id,
                                                            OpportunityId = disti.Id,
                                                            Quantity = 10,
                                                            UnitPrice = 300);
        
        database.insert (doline,false);
        
        
        
        
        
        List<Opportunity> oppsToUpdate = new List<Opportunity>();
        
        
        
        /*
        TriggerContextUtility.setFirstRunTrue();
        
        disti.StageName = 'Distributor SPA Request';
        oppsToUpdate.add(disti);
        
        oppsToUpdate.add(oppus);
       
        update oppsToUpdate;
         */
        Test.stoptest();
    }
   
    Static testmethod void MasterOppClone() {
        test.startTest();        
        TriggerContextUtility.setFirstRunTrue();
        Opportunity opp = [Select Id,Cloning__c from opportunity limit 1];
        opp.cloning__c = true;
        opp.AccountId = null;
        update opp;
        test.stopTest();
    }

    Static testmethod void OppCloneProducts() {
        
        test.startTest();
        Product2 prod =[Select Id, Name from Product2 where Name ='Apex Test' Limit 1];
        Account acc = [Select Id,Name,Type,BillingState from Account where name ='ZZpbest' Limit 1];
        Contact con = [Select Id, Name from Contact where LastName= 'ApexTest' Limit 1];        
        Pricebookentry pbe = [Select Id,Pricebook2Id from Pricebookentry where isactive = true and pricebook2.name = 'VSA Distributor Price List' limit 1];
        
        TriggerContextUtility.setFirstRunTrue();
        
        
        Opportunity oppus = new Opportunity(Name = 'Apex Test',End_User_Lookup_Account__c = acc.Id,Partner_Account_Search__c = acc.id, 
                                            Amount = 2000,CloseDate=Date.today(),StageName='Close Won',Type='New Customer',
                                            Test_Opportunity__c=True,End_User_Contact__c= con.id,
                                            ResellerContact__c = con.id, Product_Name_Main__c = prod.id, Product_Quantity__c=50, Country__c ='United States', ApexTest__c= true   );
        
        insert oppus;
        
        OpportunityLineItem oline = new OpportunityLineItem(PricebookentryID = pbe.Id,
                                                            OpportunityId = oppus.Id,
                                                            Quantity = 10,
                                                            UnitPrice = 300);
        
        insert oline;
        
        Opportunity clone = new Opportunity(Name = 'Apex Test',End_User_Lookup_Account__c = acc.Id,Partner_Account_Search__c = acc.id, 
                                           Amount = 2000,CloseDate=Date.today(),StageName='Distributor SPA Request',Type='New Customer',
                                           Test_Opportunity__c=True,End_User_Contact__c= con.id, Country__c ='Canada',Cloning__c = true,
                                           Product_Sales_Price__c=200,Product_Name_Main__c=prod.id, Product_Quantity__c=50, ApexTest__c= true,
                                           Spa_to_Transfer_to__c = oppus.Id);
        
        insert clone;
        
        
        List<String> pboppid = new List<String>();
        pboppid.add(oppus.Id+','+pbe.Pricebook2Id);
        QuoteNewPriceBook.ChangePB(pboppid);
        test.stopTest();
    }
    
    
}