force-app/main/default/objects/Account/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <description>This formula tries to strip a website of any data that distracts from its&apos; domain name. It does not account for sub domains but does for folders that exist within the domain. It is then triggered by a workflow rule that updates a text field to better find duplicate records     
--Do Not Delete ---</description>
    <formula>left(SUBSTITUTE(
SUBSTITUTE(
SUBSTITUTE(
  SUBSTITUTE(
   SUBSTITUTE(Website, &quot;https:&quot;, &quot;&quot;),
    &quot;http:&quot;,&quot;&quot;)
       ,&quot;//&quot;,&quot;&quot;),&quot;www.&quot;,&quot;&quot;)
        ,&quot;www1.&quot;,&quot;&quot;) , if(
     
        FIND(&quot;/&quot;, SUBSTITUTE(
SUBSTITUTE(
SUBSTITUTE(
  SUBSTITUTE(
   SUBSTITUTE(Website, &quot;https:&quot;, &quot;&quot;),
    &quot;http:&quot;,&quot;&quot;)
       ,&quot;//&quot;,&quot;&quot;),&quot;www.&quot;,&quot;&quot;)
        ,&quot;www1.&quot;,&quot;&quot;)
        ) &gt;0 ,
        FIND(&quot;/&quot;, SUBSTITUTE(
SUBSTITUTE(
SUBSTITUTE(
  SUBSTITUTE(
   SUBSTITUTE(Website, &quot;https:&quot;, &quot;&quot;),
    &quot;http:&quot;,&quot;&quot;)
       ,&quot;//&quot;,&quot;&quot;),&quot;www.&quot;,&quot;&quot;)
        ,&quot;www1.&quot;,&quot;&quot;)
        ) -1,
 len(SUBSTITUTE(
SUBSTITUTE(
SUBSTITUTE(
  SUBSTITUTE(
   SUBSTITUTE(Website, &quot;https:&quot;, &quot;&quot;),
    &quot;http:&quot;,&quot;&quot;)
       ,&quot;//&quot;,&quot;&quot;),&quot;www.&quot;,&quot;&quot;)
        ,&quot;www1.&quot;,&quot;&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Parent_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account_Name__c</fullName>
    <formula>if( ParentId = null, Name,Parent.Name)</formula>
    <label>Company</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <description>gets domain from email address. allows contact email domain to be the map for leads and auto align the lead company name and lead company account type, leading to smoother conversion.</description>
    <formula>MID(Email, FIND(&apos;@&apos;, Email)+1, len(Email))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/portalResellerOnboarding.cls
global without sharing class portalResellerOnboarding {
    @AuraEnabled
    global static List<Account> mapAccount(String cemail){
        //attempt to map the contact to the correct account
        //We can use email domain names
        //The user can map themselves to any location that is part of their email 
        //domain because that has been verified. 
        //
        //We do need a way to map to an account and/or be verified if there is no existing contact domain 
        //but there is an existing account or have a new account be created
        //we can use the account website/domain field if the email domain and website domain field match
        //
        String conDomain = cemail.substringAfter('@');
        system.debug('Domain from Contact '+ conDomain);
        
        List<Account> acc = [Select id, name, billingcity,billingstate,billingpostalcode,billingstreet,billingcountry, Parent_Account_Name__c ,ownerid,
                             website, domain__c, owner.name,phone from account where id in (select accountid from contact where email like :'%'+conDomain
                                                                                           and email != '') 
                             and name != 'Partner Portal Unverified Contacts' 
                             limit 15];
        system.debug('Account Found from Contact '+acc.size());
        
        if(acc.size() == 0 && conDomain != ''){
            acc = [Select id, name, billingcity,billingstate,billingpostalcode,billingstreet,billingcountry, Parent_Account_Name__c ,
                   website, domain__c, owner.name from account where domain__c =: conDomain and domain__c != ''
                   limit 25];
            
        }
        
        system.debug(acc);
        
        return acc;
    }
}