force-app/main/default/objects/Account/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <description>This formula tries to strip a website of any data that distracts from its&apos; domain name. It does not account for sub domains but does for folders that exist within the domain. It is then triggered by a workflow rule that updates a text field to better find duplicate records     
--Do Not Delete ---</description>
    <formula>left(SUBSTITUTE(
SUBSTITUTE(
SUBSTITUTE(
  SUBSTITUTE(
   SUBSTITUTE(Website, &quot;https:&quot;, &quot;&quot;),
    &quot;http:&quot;,&quot;&quot;)
       ,&quot;//&quot;,&quot;&quot;),&quot;www.&quot;,&quot;&quot;)
        ,&quot;www1.&quot;,&quot;&quot;) , if(
     
        FIND(&quot;/&quot;, SUBSTITUTE(
SUBSTITUTE(
SUBSTITUTE(
  SUBSTITUTE(
   SUBSTITUTE(Website, &quot;https:&quot;, &quot;&quot;),
    &quot;http:&quot;,&quot;&quot;)
       ,&quot;//&quot;,&quot;&quot;),&quot;www.&quot;,&quot;&quot;)
        ,&quot;www1.&quot;,&quot;&quot;)
        ) &gt;0 ,
        FIND(&quot;/&quot;, SUBSTITUTE(
SUBSTITUTE(
SUBSTITUTE(
  SUBSTITUTE(
   SUBSTITUTE(Website, &quot;https:&quot;, &quot;&quot;),
    &quot;http:&quot;,&quot;&quot;)
       ,&quot;//&quot;,&quot;&quot;),&quot;www.&quot;,&quot;&quot;)
        ,&quot;www1.&quot;,&quot;&quot;)
        ) -1,
 len(SUBSTITUTE(
SUBSTITUTE(
SUBSTITUTE(
  SUBSTITUTE(
   SUBSTITUTE(Website, &quot;https:&quot;, &quot;&quot;),
    &quot;http:&quot;,&quot;&quot;)
       ,&quot;//&quot;,&quot;&quot;),&quot;www.&quot;,&quot;&quot;)
        ,&quot;www1.&quot;,&quot;&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign/recordTypes/VSA.recordType-meta.xml
<RecordType>
    <fullName>VSA</fullName>
    <active>true</active>
    <label>VSA</label>
</RecordType>

force-app/main/default/objects/Campaign/recordTypes/VSE.recordType-meta.xml
<RecordType>
    <fullName>VSE</fullName>
    <active>true</active>
    <label>VSE</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Domain__c.field-meta.xml
<CustomField>
    <fullName>Domain__c</fullName>
    <description>gets domain from email address. allows contact email domain to be the map for leads and auto align the lead company name and lead company account type, leading to smoother conversion.</description>
    <formula>MID(Email, FIND(&apos;@&apos;, Email)+1, len(Email))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Domain</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Log_Customer_Request__c.field-meta.xml
<CustomField>
    <fullName>Log_Customer_Request__c</fullName>
    <label>Log Customer Request</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/VSRegion__c.field-meta.xml
<CustomField>
    <fullName>VSRegion__c</fullName>
    <label>VS Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestMasterLeadTrigger.cls
@isTest
private class TestMasterLeadTrigger{
    @testSetup 
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void MasterLeadTrigger() {
        // set up some test data to work with
        User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        
        Test.Starttest();    
        Account a = [Select id,website,domain__c from account where website != null limit 1];
        
        List<Lead> leads = new List<Lead>();
        Contact c = new Contact(LastName = 'apex test',email= 'lostestingcon@apex.com', AccountId = a.Id);
        insert c;
        
        Lead l = new Lead (LastName='Just a Test delete', StateCode='CA',CountryCode='US',Company='ApexTestDelete',email= 'lostesting@'+a.domain__c);
        leads.add(l);
        
        Lead l2 = new Lead (LastName='Just a Test delete',Company='ApexTestDelete' ,Country='United Kingdom',CountryCode = 'GB');
        leads.add(l2);
        
        Lead finchnocamp = new Lead(FirstName = 'just a test finch',Company='finch company', LastName = 'Apex Test', Email = 'puser000finch@amamama.com');
        
        leads.add(finchnocamp);
        
        Campaign fc = new Campaign(Name = 'Finch Club Members',IsActive = true,Status = 'In Progress');
        insert fc;
        
        
        //insert a finch club member after we have a finch club campaign
        Lead finchcamp = new Lead(FirstName = 'just a test fc',Company='finch company',
                                  LastName = 'Apex Test fc',CountryCode = 'US', Email = 'puser000fc@amamama.com',ownerid=thisUser.Id);
        
        leads.add(finchcamp);
        
        insert leads;
        //update the member and see if we get the error because member already exists
        TriggerContextUtility.setFirstRunTrue();
        //test out finchcamp and log call classes from trigger
        finchcamp.Log_Customer_Request__c = 'test this out my friend';
        update finchcamp;
        
        LeadStateFind.findState(leads);
        Test.stopTest();
        
        Lead us = [Select id , country, VSRegion__c from Lead where id =: l.Id limit 1];
        Lead uk = [Select id , country, VSRegion__c from Lead where id =:l2.Id limit 1];

        system.assertEquals('VSA',us.VSRegion__c);
        system.assertEquals('VSE',uk.VSRegion__c);
        
    }
}