force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <formula>Account.BillingCity</formula>
    <label>Billing City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <formula>Account.BillingState</formula>
    <label>Billing State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <formula>Account.BillingStreet</formula>
    <label>Billing Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/Eval_Quote__c.object-meta.xml
<CustomObject>
    <description>Eval Quote Custom Object</description>
    <label>Eval Quote</label>
    <nameField>
        <displayFormat>EvalQuote-{000000}</displayFormat>
        <label>Eval Quote Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Quotes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Quote__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <inlineHelpText>Billing City</inlineHelpText>
    <label>Billing City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Billing_Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Company_Name__c</fullName>
    <inlineHelpText>Billing Company</inlineHelpText>
    <label>Billing Company Name</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Billing_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Email__c</fullName>
    <inlineHelpText>Eval Quote Contact Email</inlineHelpText>
    <label>Billing Contact Email</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <label>Billing Contact Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Billing_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Phone__c</fullName>
    <inlineHelpText>Contact Phone</inlineHelpText>
    <label>Billing Contact Phone</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <inlineHelpText>Billing Country</inlineHelpText>
    <label>Billing Country</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Billing State</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Billing_Street__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street__c</fullName>
    <inlineHelpText>Billing Street</inlineHelpText>
    <label>Billing Street</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Billing_Zip_Postal__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Postal__c</fullName>
    <inlineHelpText>Zip or Postal Code</inlineHelpText>
    <label>Billing Zip/Postal</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Quote__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Eval Quotes</relationshipLabel>
    <relationshipName>Eval_Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/BILLING_CITY__c.field-meta.xml
<CustomField>
    <fullName>BILLING_CITY__c</fullName>
    <formula>if( text(Eval_Type__c ) == &apos;ViewSonic Sales Rep Eval&apos;, 
Owner:User.City,   
if(not(isblank(Billing_Contact_Name__r.Account.BillingCity)), Billing_Contact_Name__r.Account.BillingCity, Oracle_Ship_City__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BILLING_CITY</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Billing_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Phone__c</fullName>
    <label>Billing Contact Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/BILLING_COUNTRY__c.field-meta.xml
<CustomField>
    <fullName>BILLING_COUNTRY__c</fullName>
    <formula>if( text(Eval_Type__c ) == &apos;ViewSonic Sales Rep Eval&apos;, 
Owner:User.Country,   
if(not(isblank(Billing_Contact_Name__r.Account.BillingCountry)), Billing_Contact_Name__r.Account.BillingCountry, Oracle_Ship_Country__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BILLING_COUNTRY</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/BILLING_STATE__c.field-meta.xml
<CustomField>
    <fullName>BILLING_STATE__c</fullName>
    <formula>if( text(Eval_Type__c ) == &apos;ViewSonic Sales Rep Eval&apos;, 
text(Owner:User.StateCode),   
if(not(isblank(text(Billing_Contact_Name__r.Account.BillingStateCode))), text(Billing_Contact_Name__r.Account.BillingStateCode), Oracle_Ship_State__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BILLING_STATE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/BILLING_STREET__c.field-meta.xml
<CustomField>
    <fullName>BILLING_STREET__c</fullName>
    <formula>if( text(Eval_Type__c ) == &apos;ViewSonic Sales Rep Eval&apos;, 
Owner:User.Street,   
if(not(isblank(Billing_Contact_Name__r.Account.BillingStreet)), Billing_Contact_Name__r.Account.BillingStreet, Oracle_Ship_Street__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>BILLING_STREET</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Quote__c.field-meta.xml
<CustomField>
    <fullName>Eval_Quote__c</fullName>
    <description>&quot;&amp;id=&quot; + Id +
&quot;&amp;queryid=a0o1200000AvHp9&quot; + 
&quot;&amp;defaultpdf=1&quot; + 
&quot;&amp;emailtemplateid=00X12000001raQN&quot; + 
&quot;&amp;templateid=a0p12000003vik9&quot; + 
&quot;&amp;emailtoid=&quot; + $User.Contact_ID__c +
&quot;&amp;emailadditionalto=&quot; + Billing_Contact_Email_Invoice__c +
&quot;&amp;emailcc=&quot; + Evaluation_Owner_Email__c +
&quot;&amp;qmode=SendEmail&quot; + 
&quot;&amp;ofn=Evaluation Purchase Quote for RMA &quot; + RMA__c + &quot; &quot; + Name +
&quot;&amp;uf0=1 &quot; + 
&quot;&amp;sc1=Chatter&quot; + 
&quot;&amp;sc0=1&quot; + 
&quot;&amp;mfts0=Eval_Quote_Sent_Out__c&quot; + 
&quot;&amp;mftsvalue0=True&quot;</description>
    <formula>&quot;&amp;id=&quot; + Id +
&quot;&amp;queryid=a0o1200000AvHp9&quot; + 
&quot;&amp;defaultpdf=1&quot; + 
&quot;&amp;emailtemplateid=a0n12000006mpFy&quot; + 
&quot;&amp;templateid=a0p12000003vik9&quot; + 
&quot;&amp;emailadditionalto=&quot; + Billing_Contact_Email_Invoice__c +&apos;,&apos;+ Eval_Submitter_Email__c + &apos;,Lori.Smith@viewsonic.com&apos; +
&quot;&amp;qmode=SendEmail&quot; + 
&quot;&amp;ofn=Evaluation Purchase Quote for RMA &quot; + RMA__c + &quot; &quot; + Name +
&quot;&amp;uf0=1 &quot; + 
&quot;&amp;sc1=Chatter&quot; + 
&quot;&amp;sc0=1&quot; + 
&quot;&amp;mfts0=Eval_Quote_Sent_Out__c&quot; + 
&quot;&amp;mftsvalue0=True&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Eval Quote</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Evaluation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Eval Requests (Evaluation Owner)</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Expected_Receive_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Receive_Date__c</fullName>
    <description>Date when the  customer would like to receive the item(s) by</description>
    <inlineHelpText>Date when the  customer would like to receive the item(s) by</inlineHelpText>
    <label>Expected Receive Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <formula>Eval_Request__r.Billing_City_Quote__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <formula>Eval_Request__r.Billing_Street_Quote__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Billing State</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Quote__c.field-meta.xml
<CustomField>
    <fullName>Eval_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eval Quote</label>
    <referenceTo>Eval_Quote__c</referenceTo>
    <relationshipLabel>Eval Unit Details</relationshipLabel>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestEvalUnitsToQuote.cls
@isTest
public class TestEvalUnitsToQuote {
    @testSetup
    Private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    
    //test pass 10.27
    
    static testmethod void testGetAccessCheck(){
        boolean result = EvalUnitstoQuote.getAccessCheck();
        //system.assertEquals(true, result);
    }
    static testmethod void testEvalUnitstoQuote(){
        test.startTest();
        Contact con = [Select id from contact where Account.Name like '%Viewsonic%' limit 1];
        
        Eval_Request__c eval = new Eval_Request__c(
            Expected_Receive_Date__c= date.today(),
            Evaluation_Owner__c = con.id           
        ); 
        
        insert eval;
        
        Eval_Unit_Details__c u = new Eval_Unit_Details__c(Eval_Request__c = eval.Id,
                                                          name = 'test');
        insert u;
        
        Eval_Quote__c q = new Eval_Quote__c(Billing_City__c = 'City',
                                            Billing_Country__c = 'Country',
                                            Billing_Company_Name__c ='company x',
                                            Billing_Contact_Email__c ='mail@mailapextest.com',
                                            Billing_Contact_Name__c ='Con Name',
                                            Billing_Contact_Phone__c ='555-1212',
                                            Billing_State__c = 'CA',
                                            Billing_Street__c ='123 main st',
                                            Billing_Zip_Postal__c ='90804',
                                            Eval_Request__c =eval.Id);
        insert q;
        
       
        List<Eval_Unit_Details__c> units = EvalUnitstoQuote.getUnits(eval.Id);
        system.debug('size of units '+units.size());
        
        
        system.assert(units.size()==1);
        
        EvalUnitstoQuote.updateUnits(units, q.Id);
        EvalUnitstoQuote.updateSelected(units); 
        test.stopTest();
    }
}