force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>PR Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ship_Method__c.field-meta.xml
<CustomField>
    <fullName>Ship_Method__c</fullName>
    <label>Ship Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Business_Case_Write_Off__c.field-meta.xml
<CustomField>
    <fullName>Business_Case_Write_Off__c</fullName>
    <inlineHelpText>You can write in paragraphs and use formatting.</inlineHelpText>
    <label>Business Case Write Off</label>
    <length>2500</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Expected_Receive_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Receive_Date__c</fullName>
    <description>Date when the  customer would like to receive the item(s) by</description>
    <inlineHelpText>Date when the  customer would like to receive the item(s) by</inlineHelpText>
    <label>Expected Receive Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/GovEd_Account_Waive_Agreement__c.field-meta.xml
<CustomField>
    <fullName>GovEd_Account_Waive_Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the Billing Account is a GovEd End User account, the waiver can be waived. by checking this box</description>
    <inlineHelpText>If the Billing Account is a GovEd End User account, the waiver can be waived. by checking this box</inlineHelpText>
    <label>GovEd Account Waive Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Missing_Info_Lightnning__c.field-meta.xml
<CustomField>
    <fullName>Missing_Info_Lightnning__c</fullName>
    <formula>null</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Missing Info Lightnning</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Missing_Information__c.field-meta.xml
<CustomField>
    <fullName>Missing_Information__c</fullName>
    <formula>null</formula>
    <label>Missing Information</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/No_Credit_Card_Eval_Agreement__c.field-meta.xml
<CustomField>
    <fullName>No_Credit_Card_Eval_Agreement__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check if you wish to have no agreement sent</description>
    <label>No Credit Card Eval Agreement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Opportunity_Name_f__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name_f__c</fullName>
    <formula>Opportunity_Name__r.Name</formula>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_3__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_4__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_5__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2)</booleanFilter>
        <errorMessage>This is a bundle, you must select a non bundle product.

Also Products cannot have -2, -3,-4 in IFP Name. Please use the non dash skus.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>identifies which email to be sent out</description>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding (Not Past Due)</fullName>
                <default>true</default>
                <label>Outstanding (Not Past Due)</label>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Returned/Purchased</fullName>
            </value>
            <value>
                <fullName>Written Off</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <formula>Product_Name__r.Name  &amp;br()&amp; Product_Name_2__r.Name&amp;br() &amp;Product_Name_3__r.Name&amp;br()&amp;Product_Name_4__r.Name &amp;br()&amp; Product_Name_5__r.Name</formula>
    <inlineHelpText>List of all Products on the request. Used for Approval Processes</inlineHelpText>
    <label>Products</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_2__c.field-meta.xml
<CustomField>
    <fullName>Quantity_2__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_3__c.field-meta.xml
<CustomField>
    <fullName>Quantity_3__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_4__c.field-meta.xml
<CustomField>
    <fullName>Quantity_4__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_5__c.field-meta.xml
<CustomField>
    <fullName>Quantity_5__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Reason_for_No_Credit_Card__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_No_Credit_Card__c</fullName>
    <description>List for reasons to waive credit card agreement. Goes on the VF Email approval to Directors</description>
    <inlineHelpText>List for reasons to waive credit card agreement. Goes on the VF Email approval to Directors</inlineHelpText>
    <label>Reason for No Credit Card/ No Agreement</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Reason_for_Request__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Request__c</fullName>
    <label>Reason for Request</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Ship_Method__c.field-meta.xml
<CustomField>
    <fullName>Ship_Method__c</fullName>
    <label>Ship Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>Transfer Eval from Previous Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Special_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Special_Instructions__c</fullName>
    <label>Shipping Instructions (No Addresses)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Trade_Show__c.field-meta.xml
<CustomField>
    <fullName>Trade_Show__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trade Show</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Trade_Show_Expected_Return_Date__c.field-meta.xml
<CustomField>
    <fullName>Trade_Show_Expected_Return_Date__c</fullName>
    <label>Trade Show Expected Return Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Trade_Show_Shipping_Address__c.field-meta.xml
<CustomField>
    <fullName>Trade_Show_Shipping_Address__c</fullName>
    <inlineHelpText>Address that product needs to be shipped to. For Trade shows only.</inlineHelpText>
    <label>Trade Show Shipping Address</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Trade_Show_Shipping_Phone__c.field-meta.xml
<CustomField>
    <fullName>Trade_Show_Shipping_Phone__c</fullName>
    <inlineHelpText>May not be necessary, but a phone number to call if using the trade show docks.</inlineHelpText>
    <label>Trade Show Shipping Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <formula>left(
if(not(isblank(Account.Name)),
SUBSTITUTE(Account.Name, &quot;&apos;&quot;, &quot;&quot;),
if(not(isblank( Partner_Account_Search__r.Name )),Partner_Account_Search__r.Name,&apos;Need End User or Reseller&apos;)),120)

&amp; &quot; &quot;&amp; if(not(isblank( School__c)) ,School__r.Name,  Project_or_Site_Information__c )    &amp;
 if(Count_of_Quotes__c=0,&quot; &quot;, &quot; Spa ID# &quot;&amp;SPA_ID__c&amp;&apos; &apos;)
&amp;
if(not(isblank(Product_Name__c)),Product_Name__c&amp; &quot; Qty &quot;&amp;text(Product_Quantity__c),&apos;&apos;)&amp;&apos; &apos;&amp;BR_Conga__c</formula>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <inlineHelpText>Workaround for Product Name appearing in Opportunity Name. This is not visible in any sales layouts.</inlineHelpText>
    <label>Product Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EvalRequest.cls
public class EvalRequest {
    @AuraEnabled
     public static Eval_Request__c getEval(String recid)
    {     
         Eval_Request__c e = [SELECT ID,Missing_Information__c,Missing_Info_Lightnning__c,
                              Opportunity_Name__c,Opportunity_Name_f__c,Name,GovEd_Account_Waive_Agreement__c,
                              Products__c,Expected_Receive_Date__c,Ship_Method__c,Special_Instructions__c,
                              No_Credit_Card_Eval_Agreement__c,Reason_for_No_Credit_Card__c,Product_Name__r.name,Product_Name_2__r.name,
                              Product_Name_3__r.name,Product_Name_4__r.name,Product_Name_5__r.name,Product_Status__c,Quantity__c,
                              Quantity_2__c,Quantity_3__c,Quantity_4__c,Quantity_5__c,Business_Case_Write_Off__c,
                              Trade_Show__c,Trade_Show_Expected_Return_Date__c,Trade_Show_Shipping_Address__c,
                              Trade_Show_Shipping_Phone__c,Opportunity_Name__r.Name,Reason_for_Request__c,Shipping_Contact_Name__r.Name,
                              Billing_Contact_Name__r.name,Billing_Contact_Name__r.Account.Name,Eval_Process_Stage__c
                              FROM Eval_Request__c WHERE Id = :recid limit 1];
         
         return e;
    }
}