force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>PR Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Process_Stage__c.field-meta.xml
<CustomField>
    <fullName>Eval_Process_Stage__c</fullName>
    <defaultValue>&quot;Awaiting Submission Request&quot;</defaultValue>
    <description>Gives stage to all parties to determine where in the process the request is held  up.</description>
    <label>Eval Process Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission Request</fullName>
                <default>true</default>
                <label>Awaiting Submission Request</label>
            </value>
            <value>
                <fullName>Awaiting Approval from Director or VP</fullName>
            </value>
            <value>
                <fullName>Awaiting Upload of Agreement</fullName>
            </value>
            <value>
                <fullName>Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancellation Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Type__c.field-meta.xml
<CustomField>
    <fullName>Eval_Type__c</fullName>
    <label>Evaluation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End-User/Reseller/Disty Eval</fullName>
            </value>
            <value>
                <fullName>ViewSonic Sales Rep Eval</fullName>
            </value>
            <value>
                <fullName>Write Off Request</fullName>
            </value>
            <value>
                <fullName>Reseller Demo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Shipping_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <formula>left(
if(not(isblank(Account.Name)),
SUBSTITUTE(Account.Name, &quot;&apos;&quot;, &quot;&quot;),
if(not(isblank( Partner_Account_Search__r.Name )),Partner_Account_Search__r.Name,&apos;Need End User or Reseller&apos;)),120)

&amp; &quot; &quot;&amp; if(not(isblank( School__c)) ,School__r.Name,  Project_or_Site_Information__c )    &amp;
 if(Count_of_Quotes__c=0,&quot; &quot;, &quot; Spa ID# &quot;&amp;SPA_ID__c&amp;&apos; &apos;)
&amp;
if(not(isblank(Product_Name__c)),Product_Name__c&amp; &quot; Qty &quot;&amp;text(Product_Quantity__c),&apos;&apos;)&amp;&apos; &apos;&amp;BR_Conga__c</formula>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resellers_and_Type__c.field-meta.xml
<CustomField>
    <fullName>Resellers_and_Type__c</fullName>
    <description>Updated by flow</description>
    <label>Resellers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Reseller_Contact__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OutlookEmailPane.cls
public class OutlookEmailPane {
    /*
this will get related contacts, accounts, opportunities, cases and evals. 
*/    
    @AuraEnabled
    public static List<Account>  getContacts(List<String> emails,String emailfrom) {
        List<Account> cons = [SELECT id, Name, parent.name, CreatedDate,BillingState,BillingCity,Type,
                              BillingPostalCode,(Select id, name, title, phone,email from contacts where email IN :emails
                                                or email =: emailfrom)
                              FROM Account 
                              WHERE id in (Select AccountId from Contact where email IN :emails or email =: emailfrom) ];
        system.debug('cons and emails');
        system.debug(cons);
        system.debug(emails);
        system.debug(emailfrom);
        
        return cons;
    }
    
    /*
get the opportunities that have a reseller contact or contact role relating to the email addresses
*/
    @AuraEnabled
    public static List<Opportunity> getOpps(List<String> emails,String emailfrom) {
        
        List<Opportunity> oppcons = [Select id, name, closedate, stagename, createddate,Resellers_and_Type__c ,owner.name, account.name,
                                     account.billingstate from opportunity where id in (SELECT opportunityId 
                                                                                        FROM OpportunityContactRole 
                                                                                        WHERE Contact.Email IN :emails
                                                                                        or Contact.Email =: emailfrom) ];
        
        List<Opportunity> oppparts = [Select id, name, closedate, stagename, createddate,owner.name,Resellers_and_Type__c , account.name,
                                      account.billingstate from opportunity where id in (SELECT opportunity__c 
                                                                                         FROM Opportunity_partner__c 
                                                                                         WHERE Reseller_Contact__r.Email IN :emails
                                                                                         or Reseller_Contact__r.Email =: emailfrom) ];
        
        //combine both lists and then deduplicate by putting in set and back into a list to return
        Set<Opportunity> allopps = new Set<Opportunity>();
        List<Opportunity> opps = new List<opportunity>();
        allopps.addall(oppcons);
        allopps.addall(oppparts);
        opps.addall(allopps);
        
        system.debug('opps cons, parts, all, opps, and emails');
        system.debug(emails);
        
        system.debug(oppcons);
        system.debug(oppparts);
        system.debug(allopps);
        system.debug(opps);
        
        return opps;
    }
    @AuraEnabled
    public static List<Eval_Request__c> getEvals(List<String> emails,String emailfrom) {
        List<Eval_Request__c> evals = new List<Eval_Request__c>();
        
        List<Eval_Request__c> billevals = [Select id, name, Shipping_Contact_Name__c,Eval_Type__c ,Billing_Contact_Name__r.account.name, Billing_Contact_Name__r.name, Billing_Contact_Name__r.email,
                                          Shipping_Contact_Name__r.account.name,Opportunity_Name__r.name, Shipping_Contact_Name__r.name, Shipping_Contact_Name__r.email, Eval_Process_Stage__c  
                                           from Eval_Request__c where Eval_Process_Stage__c != 'Closed' and Eval_Process_Stage__c != 'Cancelled' 
                                           and Eval_Type__c != 'ViewSonic Sales Rep Eval'
                                           and Eval_Type__c != ''
                                           and  Billing_Contact_Name__r.email != 'jason.orbison@viewsonic.com'
                                           and  Billing_Contact_Name__r.email != 'sfdcadmin@viewsonic.com'
                                           and (Billing_Contact_Name__r.email in : emails
                                           or Billing_Contact_Name__r.email = : emailfrom) ];
        
        List<Eval_Request__c> shipevals =[Select id, name, Shipping_Contact_Name__c,Eval_Type__c ,Billing_Contact_Name__r.account.name, Billing_Contact_Name__r.name, Billing_Contact_Name__r.email,
                                          Shipping_Contact_Name__r.account.name,Opportunity_Name__r.name, Shipping_Contact_Name__r.name, Shipping_Contact_Name__r.email, Eval_Process_Stage__c  
                                          from Eval_Request__c where Eval_Process_Stage__c != 'Closed' and Eval_Process_Stage__c != 'Cancelled'
                                          and Eval_Type__c != 'ViewSonic Sales Rep Eval'
                                          and Eval_Type__c != ''
                                          and Shipping_Contact_Name__r.email != 'jason.orbison@viewsonic.com'
                                          and Shipping_Contact_Name__r.email != 'sfdcadmin@viewsonic.com'
                                          and (Shipping_Contact_Name__r.email in : emails
                                               or Shipping_Contact_Name__r.email = : emailfrom)];
        
        Set<Eval_Request__c> allevals = new Set<Eval_Request__c>();
        allevals.addall(billevals);
        allevals.addall(shipevals);
        evals.addall(allevals);
        
        system.debug(emails);
        system.debug(billevals);
        system.debug(shipevals);
        system.debug(allevals);
        system.debug(evals);
        system.debug('size of set then list');
        system.debug(allevals.size());        
        system.debug(evals.size());
        
        
        return evals;
    }
    @AuraEnabled
    public static List<Case> getCases(List<String> emails,String emailfrom) {
        List<Case> cases = [Select id, subject, owner.name, createdby.name, status 
                            from case where (owner.email in : emails or owner.email = : emailfrom)
                            and subject != '' and owner.name != 'SFDC Admin' and status != 'Closed'];
        
        
        return cases;
        
    }
    
}