force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>PR Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Expected_Receive_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Receive_Date__c</fullName>
    <description>Date when the  customer would like to receive the item(s) by</description>
    <inlineHelpText>Date when the  customer would like to receive the item(s) by</inlineHelpText>
    <label>Expected Receive Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <formula>left(
if(not(isblank(Account.Name)),
SUBSTITUTE(Account.Name, &quot;&apos;&quot;, &quot;&quot;),
if(not(isblank( Partner_Account_Search__r.Name )),Partner_Account_Search__r.Name,&apos;Need End User or Reseller&apos;)),120)

&amp; &quot; &quot;&amp; if(not(isblank( School__c)) ,School__r.Name,  Project_or_Site_Information__c )    &amp;
 if(Count_of_Quotes__c=0,&quot; &quot;, &quot; Spa ID# &quot;&amp;SPA_ID__c&amp;&apos; &apos;)
&amp;
if(not(isblank(Product_Name__c)),Product_Name__c&amp; &quot; Qty &quot;&amp;text(Product_Quantity__c),&apos;&apos;)&amp;&apos; &apos;&amp;BR_Conga__c</formula>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestEvalContacts.cls
@isTest
public class TestEvalContacts {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    //passed 10.27.2021
 
    Static testmethod void TestEvalContact () {
        
         test.startTest();
        
        Contact c = [Select id, name,firstname,lastname,email,phone,mailingstreet,mailingcity,mailingstate,
                             mailingpostalcode,mailingcountry,title,Account.Type, Account.Industry,
                             Account.Owner.Name,Account.BillingStreet,Account.BillingCity,Account.BillingState,Account.BillingPostalCode,
                             Account.BillingCountry from contact where accountid != null and name !='tonythetester' limit 1];
        
        Opportunity o = [Select id from opportunity limit 1];
        system.debug('contact data for eval');
        
        system.debug(c);
        
        
        Eval_Request__c e = new Eval_Request__c(Expected_Receive_Date__c = date.today(),
                                               opportunity_name__c = o.Id);
        insert e;
        
        String recid = e.Id;
        EvalContacts.getRelatedRecords(recid);
        EvalContacts.checkShipping(c);
        EvalContacts.checkBilling(c);
        EvalContacts.getEval(e);
        test.stopTest();
        
    }    

}