force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/evalBillAcct.cls
public class evalBillAcct {
    @AuraEnabled
     public static Account getbillAcct(String evalid)
    {   
       Eval_Request__c e = [Select id,Billing_Contact_Name__r.AccountId from eval_request__c where id = :evalid limit 1];
        
        Account a = [Select Id, Name,Phone,Type,BillingAddress,BillingStreet,BillingCity,BillingState,
                     BillingPostalCode,BillingCountry,Industry
                     from Account where id =: e.Billing_Contact_Name__r.AccountId limit 1];
        //String acctid = e.Billing_Contact_Name__r.AccountId;
        
        return a;
    }
    @AuraEnabled
     public static Account updateAcct(Account acct)
    { 
        update acct;
        
        return acct;
    }

}