force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>PR Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links Viewsonic Users with contacts. Used in automation for the product request roll ups.</description>
    <label>UserID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Process_Stage__c.field-meta.xml
<CustomField>
    <fullName>Eval_Process_Stage__c</fullName>
    <defaultValue>&quot;Awaiting Submission Request&quot;</defaultValue>
    <description>Gives stage to all parties to determine where in the process the request is held  up.</description>
    <label>Eval Process Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission Request</fullName>
                <default>true</default>
                <label>Awaiting Submission Request</label>
            </value>
            <value>
                <fullName>Awaiting Approval from Director or VP</fullName>
            </value>
            <value>
                <fullName>Awaiting Upload of Agreement</fullName>
            </value>
            <value>
                <fullName>Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancellation Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <formula>Product_Name__r.Name  &amp;br()&amp; Product_Name_2__r.Name&amp;br() &amp;Product_Name_3__r.Name&amp;br()&amp;Product_Name_4__r.Name &amp;br()&amp; Product_Name_5__r.Name</formula>
    <inlineHelpText>List of all Products on the request. Used for Approval Processes</inlineHelpText>
    <label>Products</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Products_List__c.field-meta.xml
<CustomField>
    <fullName>Products_List__c</fullName>
    <formula>Product_Name__r.Name
&amp;if(not(isblank(Product_Name_2__r.Name))= true,&apos; || &apos;&amp;Product_Name_2__r.Name,&apos;&apos;)
&amp;if(not(isblank(Product_Name_3__r.Name))= true,&apos; || &apos;&amp;Product_Name_3__r.Name,&apos;&apos;)
&amp;if(not(isblank(Product_Name_4__r.Name))= true,&apos; || &apos;&amp;Product_Name_4__r.Name,&apos;&apos;)
&amp;if(not(isblank(Product_Name_5__r.Name))= true,&apos; || &apos;&amp;Product_Name_5__r.Name,&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Products List</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Shipping_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <formula>left(
if(not(isblank(Account.Name)),
SUBSTITUTE(Account.Name, &quot;&apos;&quot;, &quot;&quot;),
if(not(isblank( Partner_Account_Search__r.Name )),Partner_Account_Search__r.Name,&apos;Need End User or Reseller&apos;)),120)

&amp; &quot; &quot;&amp; if(not(isblank( School__c)) ,School__r.Name,  Project_or_Site_Information__c )    &amp;
 if(Count_of_Quotes__c=0,&quot; &quot;, &quot; Spa ID# &quot;&amp;SPA_ID__c&amp;&apos; &apos;)
&amp;
if(not(isblank(Product_Name__c)),Product_Name__c&amp; &quot; Qty &quot;&amp;text(Product_Quantity__c),&apos;&apos;)&amp;&apos; &apos;&amp;BR_Conga__c</formula>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EvalsUnshipped.cls
public class EvalsUnshipped {  
    @AuraEnabled
     public static List<Eval_Request__c> getEvals(String recid)
    {     
    	
        List<Eval_Request__c> e = new List<Eval_Request__c>();
        system.debug('recid is '+recid);
        //query user id so we can get contact id    	
        Id userId = UserInfo.getUserId();
        
        /*
        List<Contact> con = [SELECT ID FROM Contact WHERE UserID__c = :userId limit 1];         
        String conid = con[0].Id;
        */
        if(recid == null ){
            //get list of evals that have not shipped and belong to user and return to component
             e = [Select Id, name,Billing_Contact_Name__c,Billing_Contact_Name__r.Account.Name,Products_List__c ,
                          Eval_Process_Stage__c	,Opportunity_Name__r.Name, Products__c from Eval_Request__c
                          where Eval_Process_Stage__c != 'Shipped'
                          and Eval_Process_Stage__c != 'Closed' 
                          and Eval_Process_Stage__c != 'Cancelled'
                          and Eval_Process_Stage__c != 'Cancellation Requested'
                  	      and Eval_Process_Stage__c != ''
                          and ownerId =:userId];
        }else if(recid.substring(0,3) == '001'){
            
            e = [Select Id, name,Billing_Contact_Name__c,Billing_Contact_Name__r.Account.Name,
                 Eval_Process_Stage__c	,Opportunity_Name__r.Name, Products__c from Eval_Request__c
                where Billing_Contact_Name__r.AccountId = : recid or Shipping_Contact_Name__r.AccountId = : recid];
            
         }else if(recid.substring(0,3) == '003'){
             
              
             e = [Select Id, name,Billing_Contact_Name__c,Billing_Contact_Name__r.Account.Name,
                          Eval_Process_Stage__c	,Opportunity_Name__r.Name, Products__c from Eval_Request__c
                          where Billing_Contact_Name__c =:recid or Shipping_Contact_Name__c = : recid];
             
         }    
        
        return e;
         
    }

}