force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Evaluation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Eval Requests (Evaluation Owner)</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Expected_Receive_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Receive_Date__c</fullName>
    <description>Date when the  customer would like to receive the item(s) by</description>
    <inlineHelpText>Date when the  customer would like to receive the item(s) by</inlineHelpText>
    <label>Expected Receive Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/RMA__c.field-meta.xml
<CustomField>
    <fullName>RMA__c</fullName>
    <formula>text(RMA_From_Details__c)</formula>
    <label>RMA #</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/RMA__c.field-meta.xml
<CustomField>
    <fullName>RMA__c</fullName>
    <externalId>true</externalId>
    <label>RMA #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Testing Field. Will pull from product</inlineHelpText>
    <label>SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestItemEditController.cls
@isTest
public class TestItemEditController {

Static testmethod void TestItemEditController () {

    {

Test.startTest();

    // set the test's page to your VF page
     
     BuildTestData.AddRecords();

     User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
            System.runAs ( thisUser ) {
            
        UserRole r = new UserRole(DeveloperName = 'MyCustomRole2', Name = 'My Role2');
            insert r;
            
        User u = new User(
             ProfileId = [SELECT Id FROM Profile WHERE Name = 'SFDC Admin'].Id,
             LastName = 'last testingapex',
             Email = 'puser000@amamama.com',
             Username = 'puser000@amamama.com' + System.currentTimeMillis(),
             CompanyName = 'TEST Apex',
             Title = 'title',
             Country = 'United States',
             Phone = '5625551212',
             Alias = 'alias',
             TimeZoneSidKey = 'America/Los_Angeles',
             EmailEncodingKey = 'UTF-8',
             LanguageLocaleKey = 'en_US',
             LocaleSidKey = 'en_US',
             UserRoleId = r.Id
        ); 
        
       insert u;
       
       Account a = [Select Id, Name,Type,billingstate from Account where name ='ZZpbest' limit 1];
       
        Contact con = new Contact(FirstName='Random',LastName='ApexTest', email='apextest@apexmail.com', phone='9995557865',AccountId=a.id,MailingState='ZZ');
        insert con;
       
       Eval_Request__c ev = new Eval_Request__c(
       Expected_Receive_Date__c= date.today(),
       Evaluation_Owner__c = con.id
             
        ); 
        insert ev; 


        Eval_Unit_Details__c eu = new Eval_Unit_Details__c(
			Eval_Request__c = ev.Id,
			SKU__c = [Select Id from Product2 where Name ='Apex Test'].id,
			RMA__c = '12345'
			);

       PageReference myVfPage = Page.EvalRequestsSearch;
       Test.setCurrentPageReference(myVfPage);
       String id = ApexPages.currentPage().getParameters().get('id');
       //ApexPages.StandardController sc = new ApexPages.StandardController(eu);
       //ItemEditController ac = new ItemEditController();
       ItemEditController ac = new ItemEditController(new ApexPages.StandardController(eu));

       ac.search();
       ac.cancel();
       ac.save();



    }      
      

     Test.stopTest();
}
}
}