force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links Viewsonic Users with contacts. Used in automation for the product request roll ups.</description>
    <label>UserID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Quote_Sent_Out__c.field-meta.xml
<CustomField>
    <fullName>Eval_Quote_Sent_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Eval Quote Sent Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Type__c.field-meta.xml
<CustomField>
    <fullName>Eval_Type__c</fullName>
    <label>Evaluation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End-User/Reseller/Disty Eval</fullName>
            </value>
            <value>
                <fullName>ViewSonic Sales Rep Eval</fullName>
            </value>
            <value>
                <fullName>Write Off Request</fullName>
            </value>
            <value>
                <fullName>Reseller Demo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Evaluation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Eval Requests (Evaluation Owner)</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Expected_Receive_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Receive_Date__c</fullName>
    <description>Date when the  customer would like to receive the item(s) by</description>
    <inlineHelpText>Date when the  customer would like to receive the item(s) by</inlineHelpText>
    <label>Expected Receive Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Status__c.field-meta.xml
<CustomField>
    <fullName>Product_Status__c</fullName>
    <description>identifies which email to be sent out</description>
    <label>Product Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Outstanding (Not Past Due)</fullName>
                <default>true</default>
                <label>Outstanding (Not Past Due)</label>
            </value>
            <value>
                <fullName>Past Due</fullName>
            </value>
            <value>
                <fullName>Returned/Purchased</fullName>
            </value>
            <value>
                <fullName>Written Off</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_ID__c</fullName>
    <defaultValue>$User.ContactId</defaultValue>
    <label>Contact ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestEvalRequestTrigger.cls
@isTest
public class TestEvalRequestTrigger
{
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    
    Static testmethod void EvalRequestTriggerTest () {
        User u = [SELECT Id, Manager.Contact_ID__c,Contact_ID__c,managerId FROM User WHERE Id= :UserInfo.getUserId() Limit 1] ;
        contact o = [Select Id, UserId__c from Contact where UserId__c = :UserInfo.getUserId() limit 1];
        Account a = [Select Id, Name,Type,billingstate from Account where name ='ZZpbest' limit 1];
        
        Contact con = new Contact(FirstName='Random',LastName='ApexTest',
                                  email='apextest3@apexmail.com', phone='9995557865',AccountId=a.id,MailingStateCode='CA',
                                 MailingCountryCode='US');
        insert con;
        
        system.debug('user conid '+u.Contact_ID__c);
        
        test.startTest();
        Eval_Request__c e = new Eval_Request__c(
            Expected_Receive_Date__c= date.today(),
            Evaluation_Owner__c = o.Id,
            Eval_Type__c = 'End-User/Reseller/Disty Eval'
            
        ); 
        insert e;
        
        TriggerContextUtility.setFirstRunTrue();
        
        e.Product_Status__c = 'Closed';
        update e;
        
        TriggerContextUtility.setFirstRunTrue();
        
        e.Product_Status__c = 'Outstanding';
        update e;
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');
        
        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId=testcontent.ContentDocumentId;
        contentlink.LinkedEntityId =e.id;
        
        insert contentlink;
        
        
        
        Eval_Unit_Details__c eu1 = new Eval_Unit_Details__c(
            Eval_Request__c= e.Id,
            Name='1521841545'             
        ); 
        insert eu1; 
        
        Eval_Unit_Details__c eu2 = new Eval_Unit_Details__c(
            Eval_Request__c= e.Id,
            Name='18548415487'             
        ); 
        insert eu2; 
        
        TriggerContextUtility.setFirstRunTrue();
        
        Eval_Request__c e1 = [Select Id,Eval_Quote_Sent_Out__c from Eval_Request__c where id =: e.Id limit 1];
        
        e1.Eval_Quote_Sent_Out__c = true;
        update e1;
        
        TriggerContextUtility.setFirstRunTrue();
        
        e1.Eval_Quote_Sent_Out__c = false;
        update e1;
        test.stopTest();
        
    }
    
}