force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Evaluation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Eval Requests (Evaluation Owner)</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Expected_Receive_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Receive_Date__c</fullName>
    <description>Date when the  customer would like to receive the item(s) by</description>
    <inlineHelpText>Date when the  customer would like to receive the item(s) by</inlineHelpText>
    <label>Expected Receive Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Reseller_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Reseller Contact Name</description>
    <label>Reseller Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Eval Requests (Reseller Contact Name)</relationshipLabel>
    <relationshipName>Eval_Requests_Reseller</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Shipping_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/testCountryStatesLWC.cls
@isTest
private class testCountryStatesLWC {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void testgetBillingAddresses()  
    {
        
        test.startTest();
        
        Contact con = [Select id from contact where Account.Name like '%Viewsonic%' limit 1];
        Contact nonVS = [Select id from contact where id != :con.Id limit 1];
        List<Eval_Request__c> records = new List<Eval_Request__c>();
        
        Eval_Request__c eval = new Eval_Request__c(
            Expected_Receive_Date__c= date.today(),
            Evaluation_Owner__c = con.id,
            Reseller_Contact_Name__c = con.id
        ); 
        
        records.add( eval);
        Eval_Request__c eval2 = new Eval_Request__c(
            Expected_Receive_Date__c= date.today(),
            Reseller_Contact_Name__c = nonVS.Id,
            Shipping_Contact_Name__c = nonVS.Id
        ); 
        
        records.add( eval2);
        insert records;
        
        Eval_Unit_Details__c u = new Eval_Unit_Details__c(Eval_Request__c = eval.Id,
                                                          name = 'test');
        insert u;
        
        countryStatesLWC.getCountries();
        countryStatesLWC.getStates();
        
        countryStatesLWC.getAddresses(con.Id);
        countryStatesLWC.getBillingAddresses(eval.Id);
        
        test.stopTest();
    }
    
}