force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Ship_Method__c.field-meta.xml
<CustomField>
    <fullName>Ship_Method__c</fullName>
    <label>Ship Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Type__c.field-meta.xml
<CustomField>
    <fullName>Eval_Type__c</fullName>
    <label>Evaluation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End-User/Reseller/Disty Eval</fullName>
            </value>
            <value>
                <fullName>ViewSonic Sales Rep Eval</fullName>
            </value>
            <value>
                <fullName>Write Off Request</fullName>
            </value>
            <value>
                <fullName>Reseller Demo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Evaluation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Eval Requests (Evaluation Owner)</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Expected_Receive_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Receive_Date__c</fullName>
    <description>Date when the  customer would like to receive the item(s) by</description>
    <inlineHelpText>Date when the  customer would like to receive the item(s) by</inlineHelpText>
    <label>Expected Receive Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2)</booleanFilter>
        <errorMessage>This is a bundle, you must select a non bundle product.

Also Products cannot have -2, -3,-4 in IFP Name. Please use the non dash skus.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/RMA__c.field-meta.xml
<CustomField>
    <fullName>RMA__c</fullName>
    <formula>text(RMA_From_Details__c)</formula>
    <label>RMA #</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <label>Ship Date</label>
    <summarizedField>Eval_Unit_Details__c.Ship_Date__c</summarizedField>
    <summaryForeignKey>Eval_Unit_Details__c.Eval_Request__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Ship_Method__c.field-meta.xml
<CustomField>
    <fullName>Ship_Method__c</fullName>
    <label>Ship Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Delivery</fullName>
            </value>
            <value>
                <fullName>Will Call</fullName>
            </value>
            <value>
                <fullName>Transfer Eval from Previous Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Shipping_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Courier_Info__c.field-meta.xml
<CustomField>
    <fullName>Courier_Info__c</fullName>
    <label>Courier Info</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/RMA__c.field-meta.xml
<CustomField>
    <fullName>RMA__c</fullName>
    <externalId>true</externalId>
    <label>RMA #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Tracking_Number__c.field-meta.xml
<CustomField>
    <fullName>Tracking_Number__c</fullName>
    <label>Tracking Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

force-app/main/default/classes/TestCoverage.cls
@isTest 
public class TestCoverage{
    static testmethod void myCoverageTest() {  
        
        //Create Contact
       
        BuildTestData.AddRecords();
        Account a = [Select Id from Account where name ='ZZpbest' limit 1];

        Contact Con = new Contact(
            lastname = 'test',
            email = 'email@test.com',
            MailingStreet = '123 Main Street',
            MailingCity = 'Test City',
            MailingState = 'CA',
            MailingPostalCode = '12345',
            AccountId =a.id,
            MailingCountry = 'Test Country');
        Insert Con;
        
        //Create Eval_Request
        Eval_Request__c ER = new Eval_Request__c(
            eval_type__c = 'Trade Show Loaner', 
            Evaluation_Owner__c = Con.Id,
            Expected_Receive_Date__c = Date.today(), 
            Billing_Contact_Name__c = Con.id,
            Shipping_contact_Name__c = Con.id,
            Ship_Method__c = 'Delivery',
            Product_Name__c = '01tA0000003J4iH',
            Quantity__c = 1.0);
            
        Insert ER;
        
        // Create Eval_Unit_Dtails       
        Eval_Unit_Details__c EUD1 = new Eval_Unit_Details__c(
        Eval_Request__c = ER.id,
        //Product_SKU__c = SKU,
        Name = '123testnumber',
        RMA__c = '123testnumber',
        Courier_Info__c = 'FedEx-Parcel-Standard Overnight',
        Ship_Date__c = date.today(),
        Tracking_Number__c = '123trackingnumber');
        insert EUD1;
        
        Eval_Unit_Details__c EUD2 = new Eval_Unit_Details__c(
        Eval_Request__c = ER.id,
        //Product_SKU__c = SKU,
        Name = '123testnumber',
        RMA__c = '123testnumber',
        Courier_Info__c = 'FedEx-Parcel-Standard Overnight',
        Ship_Date__c = date.today(),
        Tracking_Number__c = '123trackingnumber');
        insert EUD2;  
        
        Eval_Unit_Details__c EUD3 = new Eval_Unit_Details__c(
        Eval_Request__c = ER.id,
        //Product_SKU__c = SKU,
        Name = '123testnumber',
        RMA__c = '123testnumber',
        Courier_Info__c = 'FedEx-Parcel-Standard Overnight',
        Ship_Date__c = date.today(),
        Tracking_Number__c = '123trackingnumber');
        insert EUD3;
    }
}