force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Expected_Receive_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Receive_Date__c</fullName>
    <description>Date when the  customer would like to receive the item(s) by</description>
    <inlineHelpText>Date when the  customer would like to receive the item(s) by</inlineHelpText>
    <label>Expected Receive Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/testevalBillAcct.cls
@IsTest
public class testevalBillAcct {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
     Static testmethod void TestEvalContact () {
         
         Contact c = [select id from contact where accountid != null limit 1];
         Eval_Request__c e = new Eval_Request__c(Expected_Receive_Date__c=date.today(),
                                                Billing_Contact_Name__c  = c.Id);
         insert e;
         test.startTest();
         Account a = evalBillAcct.getbillAcct(e.Id);
         evalBillAcct.updateAcct(a);
         test.stopTest();
     
     }

}