force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links Viewsonic Users with contacts. Used in automation for the product request roll ups.</description>
    <label>UserID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Process_Stage__c.field-meta.xml
<CustomField>
    <fullName>Eval_Process_Stage__c</fullName>
    <defaultValue>&quot;Awaiting Submission Request&quot;</defaultValue>
    <description>Gives stage to all parties to determine where in the process the request is held  up.</description>
    <label>Eval Process Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Awaiting Submission Request</fullName>
                <default>true</default>
                <label>Awaiting Submission Request</label>
            </value>
            <value>
                <fullName>Awaiting Approval from Director or VP</fullName>
            </value>
            <value>
                <fullName>Awaiting Upload of Agreement</fullName>
            </value>
            <value>
                <fullName>Awaiting Shipping</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Cancellation Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Evaluation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Eval Requests (Evaluation Owner)</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Expected_Receive_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Receive_Date__c</fullName>
    <description>Date when the  customer would like to receive the item(s) by</description>
    <inlineHelpText>Date when the  customer would like to receive the item(s) by</inlineHelpText>
    <label>Expected Receive Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/EvalsUnshippedTest.cls
@isTest
private class EvalsUnshippedTest {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void EvalsUnshipped()
        
    {
        //passed on 10.27.2021
        test.startTest();   
        
            
            
            
            
            
            Account a = [Select Id, Name,Type,billingstate from Account where name ='ZZpbest' limit 1];
            Contact con = new Contact();
            try{
                 con = new Contact(FirstName='Ranfaseasesaddom',LastName='AafdsdfaspexTest', mailingcountrycode='US',
                                      email='apextestasfasdf@apexmail.com', phone='9995557asfd865',AccountId=a.id,MailingStateCode='CA',
                                      UserId__c = UserInfo.getUserId() );
            }catch(Exception e){
                con = [Select id from Contact where accountid =: a.Id limit 1];
			}
            
            
            
            Eval_Request__c ev = new Eval_Request__c(
                Expected_Receive_Date__c= date.today(),
                Evaluation_Owner__c = con.id,
                Eval_Process_Stage__c = 'Awaiting Submission Request'
                
            ); 
            insert ev; 
            //
            Contact c = [Select Id,AccountId from Contact where LastName ='tonythetester' limit 1]; 
            
            //test evals unshipped controller 
               
            List<Eval_Request__c> evals = EvalsUnshipped.getEvals(null); 
            //system.assertEquals(0, evals.size());
            
            List<Eval_Request__c> evalscon = EvalsUnshipped.getEvals(c.Id); 
            //system.assertEquals(1, evalscon.size());
            
            List<Eval_Request__c> evalsacc = EvalsUnshipped.getEvals(c.AccountId); 
            //system.assertEquals(1, evalscon.size());
            test.stopTest();
    }
}