force-app/main/default/objects/Account/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is for the quick action on eval request..it is not to be used for any other purpose. Allows creation of accounts on the VF Eval Pages. HIde from all profiles on layouts but with permissions.</description>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Billing_Account__c.field-meta.xml
<CustomField>
    <fullName>Billing_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Billing_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Billing_Contact_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Billing Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Evaluation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Eval Requests (Evaluation Owner)</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Manager_Contact__c.field-meta.xml
<CustomField>
    <fullName>Manager_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Manager Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Eval Requests (Manager Contact)</relationshipLabel>
    <relationshipName>Eval_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/ManagerID__c.field-meta.xml
<CustomField>
    <fullName>ManagerID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>user id for manager used for manager emails sent weekly</description>
    <label>ManagerID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/OwnerIDUser__c.field-meta.xml
<CustomField>
    <fullName>OwnerIDUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Owner  id based on user object differs from contact object, which is for master detail relationship. Which provides roll up fields for past due and outstanding evaluations.</description>
    <label>OwnerIDUser</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_3__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_4__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_5__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2)</booleanFilter>
        <errorMessage>This is a bundle, you must select a non bundle product.

Also Products cannot have -2, -3,-4 in IFP Name. Please use the non dash skus.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Products_Requested__c.field-meta.xml
<CustomField>
    <fullName>Products_Requested__c</fullName>
    <description>List of Products Requested. Not necessary shipped out as that could change due to inventory and change requests</description>
    <label>Products Requested</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_ID__c</fullName>
    <defaultValue>$User.ContactId</defaultValue>
    <label>Contact ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EvalCreate.cls
public without sharing class EvalCreate {
    
    public static void updateeval(List<Eval_Request__c> evaluations){
        //create sets and add creator of record and
        //evaluation billing contact information to be mapped
        //later to set of records
        
        system.debug('updating eval bililng ');
        Set<Id> creator = new Set<Id>();
        Set<String> evalbill = new Set<String>(); 
        for(Eval_Request__c e : evaluations){
            evalbill.add(e.Billing_Contact_Name__c);
            creator.add(UserInfo.getUserId());
        }
        
        Map<String, Contact> bills = new Map<String, Contact>();
        for (Contact b : [    
            SELECT Name,Id,AccountId,MailingStreet,MailingState,MailingPostalCode,MailingCountry,
            MailingCity,Account.BillingStreet,Account.BillingCity,Account.BillingState,Account.BillingPostalCode,
            Account.BillingCountry FROM Contact
            WHERE Id in: evalbill
        ]) bills.put(b.Id , b);
        
        Map<String, User> managers = new Map<String, User>();
        for (User m : [    
            SELECT Id, Manager.Contact_ID__c,Contact_ID__c,managerId FROM User WHERE Id in: creator
        ]) managers.put(m.Id , m);
        for(Eval_Request__c e : evaluations){
            if(bills.containsKey(e.Billing_Contact_Name__c )== true){                
                Contact bc  = bills.get(e.Billing_Contact_Name__c);
                User u  = managers.get(UserInfo.getUserId());
                
                //e.Manager_Contact__c = u.Manager.Contact_ID__c;
                e.Billing_Account__c = bc.AccountId;
                //e.ManagerID__c = u.ManagerId;
                //e.OwnerIDUser__c = e.CreatedById;            
                //e.Evaluation_Owner__c = u.Contact_ID__c;
                //e.Products_Requested__c = e.Product_Name__r.name+' '+e.Product_Name_2__r.name+' '+
                //e.Product_Name_3__r.name+' '+e.Product_Name_4__r.name+' '+
                //e.Product_Name_5__r.name+' ';
                
            } 
        }
    }
}