force-app/main/default/objects/Account/fields/GetVSContacts__c.field-meta.xml
<CustomField>
    <fullName>GetVSContacts__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GetVSContacts</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links Viewsonic Users with contacts. Used in automation for the product request roll ups.</description>
    <label>UserID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/vsacctcons.cls
public with sharing class vsacctcons{
    
    public static void FindUser(List<Account> records)
{
        
        

        //Set<String> families = new Set<String>();
        for (Account record : records) {
         if(record.GetVSContacts__c == false){
          return;
          }else{
             record.GetVSContacts__c = false;
             List<Contact> constoInsert = new List<Contact>();

       List<User> users = [SELECT Id,FirstName,LastName,Email,Phone,Street,City,State,PostalCode,Country,IsActive FROM User where IsActive = true AND UserType  = 'Standard' AND Country ='United States'] ;
             for (User  u : users){
                Contact con = new Contact(FirstName = u.Firstname,
                    LastName = u.LastName,
                    Email = u.Email,
                    Phone = u.Phone,
                    MailingStreet = u.Street,
                    MailingCity = u.City,
                    MailingState = u.State,
                    MailingPostalCode = u.PostalCode,
                    MailingCountry = u.Country,
                    AccountId = record.Id,
                    UserId__c = u.id
                    );
                constoInsert.add(con);

                }
                insert constoInsert;                
                }
                
                
            
    }
}
}