force-app/main/default/objects/Account/fields/LastSaleWeek__c.field-meta.xml
<CustomField>
    <fullName>LastSaleWeek__c</fullName>
    <description>The last day there was a sale made where we knew the end user via spa id</description>
    <label>SerialLastSaleWeek</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/QtyLastSaleWeek__c.field-meta.xml
<CustomField>
    <fullName>QtyLastSaleWeek__c</fullName>
    <description>This is quantity purchased based on the most recent sale</description>
    <label>SerialQtyLastSaleWeek</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesRevCurrent_Week__c.field-meta.xml
<CustomField>
    <fullName>SalesRevCurrent_Week__c</fullName>
    <description>if sales for current week pos week, which starts on Fridaty, there will be the Reveue amount.</description>
    <label>SerialSalesRevRecentSale</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PosDates__mdt/PosDates__mdt.object-meta.xml
<CustomObject>
    <description>Dates for POS running applications to allow changes to be made from setup instead of changing the code.</description>
    <label>PosDate</label>
    <pluralLabel>PosDates</pluralLabel>
</CustomObject>

force-app/main/default/objects/PosDates__mdt/fields/FromDays__c.field-meta.xml
<CustomField>
    <fullName>FromDays__c</fullName>
    <description>number of days between the 1 weeks of POS and date the application runs. for e.g. if the date range for last week of pos is 6/15 to 6/21 and the app runs on 6/22 the number of days is 8</description>
    <label>FromDays</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AcctAggrPOSSerial.cls
public class AcctAggrPOSSerial {
    public static void getSummary(){
        
        PosDates__mdt pos = [Select FromDays__c  from PosDates__mdt limit 1];
        
        Integer days = pos.FromDays__c.intValue();
        system.debug(pos.FromDays__c);
        Date fromdate = date.today().addDays(days);
        system.debug('days');
        system.debug(fromdate);
        
        AggregateResult[] accsrev = [SELECT AccountId, sum(Price) prc,count(Id) cnt,max(PurchaseDate) pdate 
                                     FROM Asset  where PurchaseDate >= :fromdate GROUP BY AccountId];      
              
        system.debug('ag res');
        system.debug(accsrev);
        List<Account> accts = new List<Account>();
        
        for(AggregateResult ar : accsrev){
             Account a = new Account();
             a.Id = (Id)ar.get('AccountId');
             a.SalesRevCurrent_Week__c = (Decimal)ar.get('prc');
             a.LastSaleWeek__c = (Date)ar.get('pdate');
             a.QtyLastSaleWeek__c  = (Integer)ar.get('cnt');
             accts.add(a);
        }
        system.debug('accts ');
        system.debug(accts);
        system.debug(accts.size());
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.AllowSave = true;
        dml.OptAllOrNone = false;        
        database.update (accts,dml);
    }

}