force-app/main/default/objects/Account/fields/Partner_Incentive_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Incentive_Type__c</fullName>
    <label>Partner Incentive Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Partner_Incentive_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Spiff_Type__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Type__c</fullName>
    <label>Spiff Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Spiff_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/MAP__c.field-meta.xml
<CustomField>
    <fullName>MAP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Partner_Incentive_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Incentive_Type__c</fullName>
    <formula>text( Account.Partner_Incentive_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner Incentive Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Spiff_Type__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Type__c</fullName>
    <formula>text(Account.Spiff_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Portal Spiff Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Pricing__c/Portal_Pricing__c.object-meta.xml
<CustomObject>
    <description>Pricing and Spiff Information</description>
    <label>Partner Portal Price</label>
    <nameField>
        <label>Portal Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portal_Pricing__c/fields/MAP__c.field-meta.xml
<CustomField>
    <fullName>MAP__c</fullName>
    <defaultValue>0</defaultValue>
    <description>For United States Resellers Only</description>
    <label>MAP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Portal_Pricing__c/fields/MSRP__c.field-meta.xml
<CustomField>
    <fullName>MSRP__c</fullName>
    <description>For countries outside of the United States</description>
    <label>MSRP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Portal_Pricing__c/fields/PreviousMonths__c.field-meta.xml
<CustomField>
    <fullName>PreviousMonths__c</fullName>
    <label>PreviousMonths</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Portal_Pricing__c/fields/Spiff_Amount__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Amount__c</fullName>
    <label>Spiff Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Portal_Pricing__c/fields/Spiff_Type__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Type__c</fullName>
    <label>Spiff Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Spiff_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricingEffectiveDate__c/PricingEffectiveDate__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Pricing Effective Date</label>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/fields/Partner_Incentive_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Incentive_Type__c</fullName>
    <formula>if(not(isblank(text(Requester__r.Account.Parent.Partner_Incentive_Type__c ))), text(Requester__r.Account.Parent.Partner_Incentive_Type__c ),
text(Requester__r.Account.Partner_Incentive_Type__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner Incentive Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Spiff RequestsProduct</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requester</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/portalPricingAndSpiffs.cls
public without sharing class portalPricingAndSpiffs {    
 @auraEnabled
    public static List<Portal_Pricing__c> getAdminRecords(Boolean spiffReq,String prod,String recordId){
        
        
        
        List<Portal_Pricing__c> pp= new List<Portal_Pricing__c>();
        Contact con = new Contact();
        try{
            con = [Select id, accountid,account.billingcountry,account.billingcountrycode, Account.partner_incentive_type__c,
                           Account.spiff_type__c from Contact where id in (Select Requester__c from Spiff_Request__c  where id =: recordId) Limit 1];  
        }catch(Exception e){
            
        }
        
        system.debug('prod '+prod);
        system.debug('spiffReq '+spiffReq);
        
        String billCountry = con.Account.BillingCountry;
        String SpiffType = con.Account.spiff_type__c;
        String IncentiveType = con.Account.partner_incentive_type__c;
        
        if(SpiffType == 'Corporate' && IncentiveType == 'Regional NSP'){
            SpiffType = 'Sales Rep';
        }
        
        AggregateResult pdate  = [select count(id), Effective_Date__c from  Portal_Pricing__c  
                                    group by Effective_Date__c order by Effective_Date__c desc  limit 1 offset 1];
        
        Date prevDate = ((Date)pdate.get('Effective_Date__c'));
        system.debug('prev date '+ prevDate);
        
        PricingEffectiveDate__c effDate = [Select Effective_Date__c from PricingEffectiveDate__c where name 
                                           = 'PricingDate' limit 1];
        
        pp = [Select id, Spiff_Amount__c,product__c,PreviousMonths__c,Effective_Date__c from Portal_Pricing__c where Effective_Date__c = : effDate.Effective_Date__c 
                  and Spiff_Amount__c > 0 and Country__c =: billCountry
                  and Partner_Incentive_Type__c =: IncentiveType and  Spiff_Type__c = : SpiffType and product__c like: prod
                 order by product__c];
        
        Map<String,Portal_Pricing__c> dpp = new Map<String,Portal_Pricing__c>();
            for(Portal_Pricing__c p : [Select id, Spiff_Amount__c,product__c,PreviousMonths__c,Effective_Date__c from Portal_Pricing__c where Effective_Date__c = : prevDate
                  and Spiff_Amount__c > 0 and Country__c =: billCountry
                  and Partner_Incentive_Type__c =: IncentiveType and  Spiff_Type__c = : SpiffType and product__c like: prod
                                       order by product__c]){
                                           dpp.put(p.product__c , p);
                                       }
            for(Portal_Pricing__c p : pp){
                if(dpp.containsKey(p.Product__c)){
                    Portal_Pricing__c prevPrice = dpp.get(p.Product__c);
                    p.PreviousMonths__c = prevPrice.Spiff_Amount__c;
                }
            }            
        
        return pp;
	
    }        
        
        
    
    @auraEnabled
    public static List<Portal_Pricing__c> getProductInfo(Boolean spiffReq,String prod){
        List<Portal_Pricing__c> pp= new List<Portal_Pricing__c>();
        Contact con = new Contact();
        try{
            con = [Select id, accountid,account.billingcountry,account.billingcountrycode, Account.partner_incentive_type__c,
                           Account.spiff_type__c from Contact where id in (Select contactid from User where id =: userInfo.getUserId()) Limit 1];  
        }catch(Exception e){
            
        }
        
        system.debug('prod '+prod);
        system.debug('spiffReq '+spiffReq);
        
        String billCountry = con.Account.BillingCountry;
        String SpiffType = con.Account.spiff_type__c;
        String IncentiveType = con.Account.partner_incentive_type__c;
        
        if(SpiffType == 'Corporate' && IncentiveType == 'Regional NSP'){
            SpiffType = 'Sales Rep';
        }
        
        PricingEffectiveDate__c effDate = [Select Effective_Date__c from PricingEffectiveDate__c where name 
                                           = 'PricingDate' limit 1];
        
        
        AggregateResult pdate  = [select count(id), Effective_Date__c from  Portal_Pricing__c  
                                    group by Effective_Date__c order by Effective_Date__c desc  limit 1 offset 1];
        
        Date prevDate = ((Date)pdate.get('Effective_Date__c'));
        system.debug('prev date '+ prevDate);
           
        /*
        for (AggregateResult ar : pdate)  {
            prevDate = ar.get(Effective_Date__c);
        }
        */
        
        
        if(spiffReq){
            pp = [Select id, Spiff_Amount__c,product__c,PreviousMonths__c,Effective_Date__c from Portal_Pricing__c where Effective_Date__c = : effDate.Effective_Date__c 
                  and Spiff_Amount__c > 0 and Country__c =: billCountry
                  and Partner_Incentive_Type__c =: IncentiveType and  Spiff_Type__c = : SpiffType and product__c like: prod
                 order by product__c];
            
            //if something no longer exists, need to create a record
            Map<String,Portal_Pricing__c> dpp = new Map<String,Portal_Pricing__c>();
            for(Portal_Pricing__c p : [Select id, Spiff_Amount__c,product__c,PreviousMonths__c,Effective_Date__c from Portal_Pricing__c where Effective_Date__c = : prevDate
                  and Spiff_Amount__c > 0 and Country__c =: billCountry
                  and Partner_Incentive_Type__c =: IncentiveType and  Spiff_Type__c = : SpiffType and product__c like: prod
                                       order by product__c]){
                                           dpp.put(p.product__c , p);
                                       }
            for(Portal_Pricing__c p : pp){
                if(dpp.containsKey(p.Product__c)){
                    Portal_Pricing__c prevPrice = dpp.get(p.Product__c);
                    p.PreviousMonths__c = prevPrice.Spiff_Amount__c;
                }
            }            
        }else if(billCountry == 'United States'){
            pp = [Select id, MAP__c,product__c from Portal_Pricing__c where Effective_Date__c = : effDate.Effective_Date__c and MAP__c > 0  and product__c like: prod
                 order by product__c];
        }else{
            pp = [Select id, MSRP__c,product__c from Portal_Pricing__c where Effective_Date__c = : effDate.Effective_Date__c and MSRP__c > 0  and product__c like: prod
                 order by product__c];
        }    
        
        return pp;
    }
}