force-app/main/default/objects/Account/fields/POS_Revenue__c.field-meta.xml
<CustomField>
    <fullName>POS_Revenue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>POS Revenue</label>
    <referenceTo>POS_Revenue__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/POS_Revenue__c/POS_Revenue__c.object-meta.xml
<CustomObject>
    <label>POS Revenue</label>
    <nameField>
        <label>POS Revenue  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POS Revenue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POS_Revenue__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>POS Revenue</relationshipLabel>
    <relationshipName>POS_Revenue</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/POS_Revenue__c/fields/CY_Revenue__c.field-meta.xml
<CustomField>
    <fullName>CY_Revenue__c</fullName>
    <label>CY Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/testschBatchPOSRevenueAcctLinks.cls
@isTest
private class testschBatchPOSRevenueAcctLinks{
     public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void TestPosRevenueAcctLink() {
        
        test.startTest();
        
        Account acc = [Select id from account limit 1];
        
        POS_Revenue__c pr = new POS_Revenue__c();
        pr.Account_Name__c = acc.Id;
        pr.Name = 'test name';
        pr.CY_Revenue__c = 900;
        
        insert pr;


        
         // Schedule the test job
        String jobId = System.schedule('ScheduledApexTestposSpaScheudle',
                                       CRON_EXP, 
                                       new schBatchPOSRevenueAccountLink());
        Test.stopTest();
        
        
        
    }
}