force-app/main/default/objects/Account/fields/Reseller_Certificate__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Certificate__c</fullName>
    <label>Reseller Certificate #</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Reseller_Certification_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Certification_Expiration_Date__c</fullName>
    <label>Reseller Certification Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Contact)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/FinchOracleId__c.field-meta.xml
<CustomField>
    <fullName>FinchOracleId__c</fullName>
    <label>FinchOracleId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOA_Request__c/LOA_Request__c.object-meta.xml
<CustomObject>
    <label>LOA Request</label>
    <nameField>
        <displayFormat>LOA-{00000}</displayFormat>
        <label>LOA Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LOA Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LOA_Request__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>LOA Requests</relationshipLabel>
    <relationshipName>LOA_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/LOA_Request__c/fields/Reseller_Certificate__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Certificate__c</fullName>
    <label>Reseller Certificate #</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LOA_Request__c/fields/Reseller_Certification_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Certification_Expiration_Date__c</fullName>
    <label>Reseller Certification Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/LOARequestController.cls
public class LOARequestController {

    @AuraEnabled(cacheable=true)
    public static Contact getUserContactInfo(){
        List<Contact> c = [select id, email, firstname, lastname, Account.Name, Account.Reseller_Certificate__c, FinchOracleId__c, Account.BillingAddress from Contact where email=:UserInfo.getUserEmail() limit 1];
           return c[0];
        

    }
    @AuraEnabled
    public static void insertLOARequest(String resellerNo, Date expDate){
        List<Contact> c = [select id, email, firstname, lastname, Account.Name, Account.Reseller_Certificate__c, FinchOracleId__c, Account.BillingAddress from Contact where email=:UserInfo.getUserEmail() limit 1];
        LOA_Request__c loa = new LOA_Request__c(Contact__c=c[0].id, Reseller_Certificate__c=resellerNo==null ? c[0].Account.Reseller_Certificate__c : resellerNo);
        loa.Reseller_Certification_Expiration_Date__c=expDate;
        insert loa;
        insert new Task(Subject='LOA Requested', Status='Completed', Priority='Normal', WhoId=c[0].id);
    }
   
    
}