force-app/main/default/objects/Account/fields/VIP_in_Approval_Process__c.field-meta.xml
<CustomField>
    <fullName>VIP_in_Approval_Process__c</fullName>
    <defaultValue>false</defaultValue>
    <label>VIP in Approval Process</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/VIP_Service_Reason_for_Request__c.field-meta.xml
<CustomField>
    <fullName>VIP_Service_Reason_for_Request__c</fullName>
    <label>VIP Service Reason for Request</label>
    <length>12000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/TestAccountVIP.cls
@isTest
private class TestAccountVIP {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
     }
  
    static testmethod void accountVIP()
    {		        
        test.startTest();
        Account a = [Select Id,VIP_Service_Reason_for_Request__c,VIP_in_Approval_Process__c  from Account limit 1];
        String recid = a.Id;        
        AccountVIPService.getStatus(recid);
        AccountVIPService.vip(recid);
        test.stopTest();
    }
    
    static testmethod void accountHotline()
    {		        
        test.startTest();
        Account a = [Select Id,VIP_Service_Reason_for_Request__c,VIP_in_Approval_Process__c  from Account limit 1];
        String recid = a.Id;        
        AccountVIPService.getStatus(recid);                     
        AccountVIPService.hotline(recid);
        test.stopTest();
    }
}