force-app/main/default/objects/Account/fields/VIP_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>VIP_Request_Type__c</fullName>
    <inlineHelpText>VIP is express exchange with hotline. Hotline only is a phone number they will get to call for support.</inlineHelpText>
    <label>VIP Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>VIP Gold</fullName>
            </value>
            <value>
                <fullName>Hotline Only</fullName>
            </value>
            <value>
                <fullName>VIP Express Exchange</fullName>
                <isActive>false</isActive>
                <label>VIP Express Exchange</label>
            </value>
            <value>
                <fullName>VIP Platinum</fullName>
                <isActive>false</isActive>
                <label>VIP Platinum</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/VIP_Service_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>VIP_Service_Expiration_Date__c</fullName>
    <label>VIP Service Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AccountVIP.cls
public class AccountVIP {
    @AuraEnabled
    public static Account getRecord(String recid){
        Date d = date.today();
        system.debug('recid');
        
        Account a = [Select id,VIP_Request_Type__c,VIP_Service_Expiration_Date__c, (select Product2.Name from assets where product2Id != null
                                                                                    and TP__c = null and SerialNumber = null)
                     from Account where id in (Select AccountId from Quote where id = : recid)];
        //and VIP_Request_Type__c = 'VIP Express Exchange' and VIP_Service_Expiration_Date__c > :d
        system.debug('account');
        system.debug(a);
        
        return a;
        
        
    }
    
}