force-app/main/default/objects/Account/fields/VSSubRegion__c.field-meta.xml
<CustomField>
    <fullName>VSSubRegion__c</fullName>
    <label>VS SubRegion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_SubRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Status__c.field-meta.xml
<CustomField>
    <fullName>Portal_Status__c</fullName>
    <label>Partner Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disqualified</fullName>
            </value>
            <value>
                <fullName>Verify Account</fullName>
                <default>true</default>
                <label>Verify Account</label>
            </value>
            <value>
                <fullName>Awaiting Info from Customer</fullName>
            </value>
            <value>
                <fullName>Awaiting Review from Channel Admin</fullName>
            </value>
            <value>
                <fullName>Account Verified Need Onboard</fullName>
            </value>
            <value>
                <fullName>Onboarded and Verified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CountriesRegions__c/CountriesRegions__c.object-meta.xml
<CustomObject>
    <label>CountriesRegions</label>
    <nameField>
        <label>CountriesRegions</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CountriesRegions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CountriesRegions__c/fields/VSSubRegion__c.field-meta.xml
<CustomField>
    <fullName>VSSubRegion__c</fullName>
    <label>VS SubRegion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_SubRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Portal_Tasks_State__c/Partner_Portal_Tasks_State__c.object-meta.xml
<CustomObject>
    <description>Junction object for tasks that are state/Province/County/Country Specific and have multiple connections</description>
    <label>Partner Portal Tasks State</label>
    <nameField>
        <label>Partner Portal Tasks State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Tasks States</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_Tasks_State__c/fields/Country_State__c.field-meta.xml
<CustomField>
    <fullName>Country_State__c</fullName>
    <label>Country State</label>
    <referenceTo>CountriesRegions__c</referenceTo>
    <relationshipLabel>Partner Portal Tasks States</relationshipLabel>
    <relationshipName>Partner_Portal_Tasks_States</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Tasks_State__c/fields/Partner_Portal_Task__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Portal Task</label>
    <referenceTo>Portal_Task__c</referenceTo>
    <relationshipLabel>Partner Portal Tasks States</relationshipLabel>
    <relationshipName>Partner_Portal_Tasks_States</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portal_Task__c/Portal_Task__c.object-meta.xml
<CustomObject>
    <label>Partner Portal Task</label>
    <nameField>
        <label>Portal Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portal_Task__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>CountriesRegions__c</referenceTo>
    <relationshipLabel>Partner Portal Tasks</relationshipLabel>
    <relationshipName>Partner_Portal_Tasks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portal_Task__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onboarding</fullName>
            </value>
            <value>
                <fullName>AV Certification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portal_Task__c/fields/VS_Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>VS_Sub_Region__c</fullName>
    <label>VS Sub Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_SubRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PortalOnboardingProgress__c/PortalOnboardingProgress__c.object-meta.xml
<CustomObject>
    <label>Portal Onboarding Progress</label>
    <nameField>
        <label>PortalOnboardingProgress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porta lOnboarding Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PortalOnboardingProgress__c/fields/Partner_Portal_Task__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Portal Task</label>
    <referenceTo>Portal_Task__c</referenceTo>
    <relationshipLabel>Porta lOnboarding Progress</relationshipLabel>
    <relationshipName>Porta_lOnboarding_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PortalOnboardingProgress__c/fields/Portal_Account__c.field-meta.xml
<CustomField>
    <fullName>Portal_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portal Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Porta lOnboarding Progress</relationshipLabel>
    <relationshipName>Porta_lOnboarding_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PortalOnboardingProgress__c/fields/Portal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Portal_Contact__c</fullName>
    <label>Portal Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Porta lOnboarding Progress</relationshipLabel>
    <relationshipName>Porta_lOnboarding_Progress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PortalOnboardingProgress__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/VS_Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>VS_Sub_Region__c</fullName>
    <label>VS Sub Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_SubRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/portalOnboardingAssignTask.cls
global without sharing class portalOnboardingAssignTask {
    @AuraEnabled
    global static void assignTaks(String conId){
        Contact c = [select id , name,Account.name , VSSubRegion__c  ,accountId,mailingcountry,mailingstate
                     from contact where id =: conId];
                CountriesRegions__c cr = new CountriesRegions__c();
        try{
           cr = [SELECT Country__c,VSSubRegion__c FROM CountriesRegions__c
                                 where Country__c = : c.mailingcountry limit 1];  
        }catch(Exception e){
            
        }
        
         //adding field for unverified profile automatic tasks to automate tasks if the account
        //is a net new account based on business rules - user was not mapped to an account
        // state specific field denotes state or province is needed to add to field
        
        List< Portal_Task__c > tskStates =  [Select id, Type__c , Active__c  from Portal_Task__c
                                      where id in (Select Partner_Portal_Task__c
                                                      from Partner_Portal_Tasks_State__c where 
                                                      Country_State__r.State__c  =: c.mailingstate) and active__c = true];        
       
        
        List< Portal_Task__c > tsk = [Select id, Type__c , Active__c  from Portal_Task__c
                                      where required__c = true
                                      and (Country__c  = null or Country__r.Name =: c.mailingcountry )
                                      and (VS_Sub_Region__c   = null or VS_Sub_Region__c  =: cr.VSSubRegion__c  )
                                      and active__c = true];
        //if this is unverified partner account then add the list of 
        List<Contact> parentAccts = [Select id,AccountId,Account.Parent.Id,Account.Parent.Parent.Id from Contact
                                  where id = : conid];
        
        List<String> parentIds = new List<String>();
        for(Contact con : parentAccts){
            parentIds.add(con.AccountId);
            parentIds.add(con.Account.ParentId);
            parentIds.add(con.Account.Parent.ParentId);
        }
        
        /*Account a = [Select id, (Select id from contacts 
                                 where Portal_Status__c = 'Onboarded and Verified' and )
                     from Account where id != '0011H00002BdC3sQAF'
                     and id =: 
                     limit 1];      
          */
        
        List<Contact> portalContacts = [Select id from Contact
                                  where Portal_Status__c = 'Onboarded and Verified' and
                                    accountid in : parentIds and AccountId != '0011H00002BdC3sQAF'];
        
        if(portalContacts.size()>0){
           //if portal users already are onboarded for parent or child accounts and are not unverified
           //then do something here. The else will be portal users that we cannot find a certification
        }else{
             tsk.addAll(tskStates);
        }
        
        List<PortalOnboardingProgress__c > progress = new List<PortalOnboardingProgress__c>();
        
        for(Portal_Task__c p : tsk){
            PortalOnboardingProgress__c  pop = new PortalOnboardingProgress__c();
            pop.Portal_Account__c = c.AccountId;
            pop.Portal_Contact__c = c.Id;
            pop.Partner_Portal_Task__c = p.Id;
            pop.Status__c = 'Not Started';
            pop.Name = 'OnBoard '+c.Name +' '+c.Account.Name;
            //ensuring the string stays under the 80 requirement
            pop.Name = pop.Name.left(79);            
            progress.add(pop);
        }
        
        insert progress;
        
    }
    
}