force-app/main/default/objects/Account/fields/VSSubRegion__c.field-meta.xml
<CustomField>
    <fullName>VSSubRegion__c</fullName>
    <label>VS SubRegion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_SubRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CountriesRegions__c/CountriesRegions__c.object-meta.xml
<CustomObject>
    <label>CountriesRegions</label>
    <nameField>
        <label>CountriesRegions</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CountriesRegions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CountriesRegions__c/fields/Available_StatesProvinces__c.field-meta.xml
<CustomField>
    <fullName>Available_StatesProvinces__c</fullName>
    <label>Available States/Provinces</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CountriesRegions__c/fields/CountryCode__c.field-meta.xml
<CustomField>
    <fullName>CountryCode__c</fullName>
    <label>CountryCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountriesRegions__c/fields/MapOwnerId__c.field-meta.xml
<CustomField>
    <fullName>MapOwnerId__c</fullName>
    <label>MapOwnerId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountriesRegions__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>VSA</fullName>
            </value>
            <value>
                <fullName>VSE</fullName>
            </value>
            <value>
                <fullName>VSI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CountriesRegions__c/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <label>StateCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CountriesRegions__c/fields/VSRegion__c.field-meta.xml
<CustomField>
    <fullName>VSRegion__c</fullName>
    <label>VS Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CountriesRegions__c/fields/VSSubRegion__c.field-meta.xml
<CustomField>
    <fullName>VSSubRegion__c</fullName>
    <label>VS SubRegion</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_SubRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/VSRegion__c.field-meta.xml
<CustomField>
    <fullName>VSRegion__c</fullName>
    <label>VS Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>VS Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_Region</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/VS_Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>VS_Sub_Region__c</fullName>
    <label>VS Sub Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>VS_SubRegion</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/getRegionInfo.cls
public class getRegionInfo {
    public static  Map<String,CountriesRegions__c> getRegion() {
         Map<String,CountriesRegions__c> region = new  Map<String,CountriesRegions__c>();
            List<CountriesRegions__c> cr = [SELECT id,Available_StatesProvinces__c,CountryCode__c,Country__c,
                                            MapOwnerId__c,Name,VSRegion__c,
                                            StateCode__c,State__c,VSSubRegion__c FROM CountriesRegions__c];            
            for(CountriesRegions__c c : cr){
                region.put(c.CountryCode__c, c);
            } 
        return region;
            
        }
    
    public static List<Lead> getRegionLead(List<Lead> records){
        system.debug('Lead Regions running Country '+records.size());
        Map<String,CountriesRegions__c> region = getRegionInfo.getRegion();
        system.debug('map of region');
        system.debug(region);
        for(Lead l : records){
            system.debug(l.CountryCode);
            if(region.containsKey(l.CountryCode)){
                system.debug('Mapped coutnry found '+l.CountryCode);
                CountriesRegions__c c = region.get(l.CountryCode);
                l.VSRegion__c = c.VSRegion__c;
                l.VSSubRegion__c = c.VSSubRegion__c;
            }
        }
        
        return records;
    }
    
    public static List<Account> getRegionAccount(List<Account> records){
         system.debug(records);
        Map<String,CountriesRegions__c> region = getRegionInfo.getRegion();
        system.debug(region);
        for(Account l : records){
            system.debug(l.BillingCountryCode);
            if(region.containsKey(l.BillingCountryCode)){
                CountriesRegions__c c = region.get(l.BillingCountryCode);
                l.VSRegion__c = c.VSRegion__c;
                l.VSSubRegion__c = c.VSSubRegion__c;
            }
        }
        
        return records;
    }
    
    public static List<Contact> getRegionContact(List<Contact> records){
         system.debug(records);
        Map<String,CountriesRegions__c> region = getRegionInfo.getRegion();
        system.debug(region);
        for(Contact l : records){
            system.debug(l.MailingCountryCode);
            if(region.containsKey(l.MailingCountryCode)){
                CountriesRegions__c c = region.get(l.MailingCountryCode);
                l.VSRegion__c = c.VSRegion__c;
                l.VSSubRegion__c = c.VSSubRegion__c;
            }
        }
        
        return records;
    }
    
    public static List<User> getRegionUser(List<User> records){
         system.debug(records);
        Map<String,CountriesRegions__c> region = getRegionInfo.getRegion();
        system.debug(region);
        for(User l : records){
            system.debug(l.CountryCode);
            if(region.containsKey(l.CountryCode)){
                CountriesRegions__c c = region.get(l.CountryCode);
                l.region__c = c.VSRegion__c;
                l.VS_Sub_Region__c = c.VSSubRegion__c;
            }
        }
        
        return records;
    }
}