force-app/main/default/objects/SalesforceProject__c/SalesforceProject__c.object-meta.xml
<CustomObject>
    <description>Deprecation. Need to delete object. There are several dependencies that need updating

For SaleForce Development team to monitor and prioritize SalesForce Projects.</description>
    <label>Salesforce Project</label>
    <nameField>
        <label>Salesforce Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesforceProject__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestSalesForceProjectTrigger.cls
@isTest
private class TestSalesForceProjectTrigger{
    @testSetup
    private static void BuildTestData(){
        //BuildTestData.AddRecords();
    }
    static testmethod void ProjectcsTriggerUpdates() {
        Test.startTest();
        SalesforceProject__c p = new SalesforceProject__c(priority__c = 3,Status__c = 'Planned');
        insert p;

        TriggerContextUtility.setFirstRunTrue();
        SalesforceProject__c p2 = new SalesforceProject__c(priority__c = 4,Status__c = 'Planned');
        insert p2;

        TriggerContextUtility.setFirstRunTrue();        
        p.Priority__c = 4;
        update p;
        
        Test.stopTest();
    }
}