force-app/main/default/objects/SalesforceProject__c/SalesforceProject__c.object-meta.xml
<CustomObject>
    <description>Deprecation. Need to delete object. There are several dependencies that need updating

For SaleForce Development team to monitor and prioritize SalesForce Projects.</description>
    <label>Salesforce Project</label>
    <nameField>
        <label>Salesforce Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salesforce Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesforceProject__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Planned</fullName>
                <default>true</default>
                <label>Planned</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Converted</fullName>
            </value>
            <value>
                <fullName>Merged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MasterSalesforceProject.cls
public class MasterSalesforceProject{
    Map<Id, SalesforceProject__c> oldProj;
    Map<Id, SalesforceProject__c> newProj;
    
    public MasterSalesforceProject(
        Map<Id, SalesforceProject__c> oldTriggerProj, 
        Map<Id, SalesforceProject__c> newTriggerProj) {
            oldProj = oldTriggerProj;
            newProj = newTriggerProj;
        }
    public  void projpriority() {
        
        Decimal newpriorities = 10000;
        Decimal oldpriorities = 10000;
        String projid = '';
        system.debug(newProj);    
        
        if(newProj.size() == 1){ 
            if(Trigger.isUpdate){
                for(SalesforceProject__c p : oldProj.values()){
                    oldpriorities = p.priority__c;
                }
            } 
            for(SalesforceProject__c p : newProj.values()){
                newpriorities = p.priority__c;
                projid = p.Id;
            }
            system.debug('update old then new');    
            system.debug(oldProj);
            system.debug(newProj);
            
            List<SalesforceProject__c> projs = [Select id , priority__c from SalesforceProject__c 
                                                where priority__c >= : newpriorities
                                                and priority__c < : oldpriorities and id != : projid
                                                and (Status__c = 'Planned' or
                                                     Status__c = 'In Progress')];
            system.debug(projs);
            for(SalesforceProject__c p : projs){
                p.Priority__c = p.Priority__c +1;
            }
            update projs;
        }
    }        
}