force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/RMA__c.field-meta.xml
<CustomField>
    <fullName>RMA__c</fullName>
    <externalId>true</externalId>
    <label>RMA #</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of eval unit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product Returned</fullName>
            </value>
            <value>
                <fullName>Purchased/Invoiced</fullName>
            </value>
            <value>
                <fullName>Write-off</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
                <default>true</default>
                <label>Outstanding</label>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Write_off_Reason__c.field-meta.xml
<CustomField>
    <fullName>Write_off_Reason__c</fullName>
    <label>Write-off Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer no longer exist</fullName>
            </value>
            <value>
                <fullName>Ex Employee</fullName>
            </value>
            <value>
                <fullName>Giveaway/Donation</fullName>
            </value>
            <value>
                <fullName>Long term demo - customer site</fullName>
            </value>
            <value>
                <fullName>Lost track at customer end</fullName>
            </value>
            <value>
                <fullName>Lost track at ViewSonic end</fullName>
            </value>
            <value>
                <fullName>Office Use</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Sold</fullName>
            </value>
            <value>
                <fullName>Swap Service/Product</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Damaged</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/recordTypes/Standard.recordType-meta.xml
<RecordType>
    <fullName>Standard</fullName>
    <active>true</active>
    <label>Standard</label>
</RecordType>

force-app/main/default/classes/ItemEditController.cls
public with sharing class ItemEditController {

  private ApexPages.StandardController controller {get; set;}
  public List<Eval_Unit_Details__c> searchResults {get;set;}
  public string searchText {get;set;}

  // standard controller - could also just use custom controller
  public ItemEditController(ApexPages.StandardController controller) { }

  // fired when the search button is clicked
  public PageReference search() {
    String qry = 'select id, RMA__c, Write_off_Reason__c, Status__c, Name from Eval_Unit_Details__c ' +
      'where RMA__c LIKE \'%'+searchText+'%\' order by RMA__c';
    searchResults = Database.query(qry);
    return null;
  }

  // fired when the save records button is clicked
  public PageReference save() {

    try {
      update searchResults;
    } Catch (DMLException e) {
      ApexPages.addMessages(e);
      return null;
    }

    return new PageReference('/apex/EvalRequestsSearch');
  }

  // takes user back to main record
  public PageReference cancel() {
    return new PageReference('/apex/EvalRequestsSearch');
  }

}