force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of eval unit</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Product Returned</fullName>
            </value>
            <value>
                <fullName>Purchased/Invoiced</fullName>
            </value>
            <value>
                <fullName>Write-off</fullName>
            </value>
            <value>
                <fullName>Outstanding</fullName>
                <default>true</default>
                <label>Outstanding</label>
            </value>
            <value>
                <fullName>Purchased</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Status_Date_Change__c.field-meta.xml
<CustomField>
    <fullName>Status_Date_Change__c</fullName>
    <label>Status Date Change</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Write_Off_Date__c.field-meta.xml
<CustomField>
    <fullName>Write_Off_Date__c</fullName>
    <label>Prodcut Write Off Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestMasterEvalUnitsTrigger.cls
@IsTest
public class TestMasterEvalUnitsTrigger  {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    Static testmethod void MasterEvalUnitsTrigger(){
        Test.startTest();
        TriggerContextUtility.setFirstRunTrue();
        
        Eval_Unit_Details__c u = [Select Id,Status__c, Status_Date_Change__c,Write_Off_Date__c
                                 from Eval_Unit_Details__c limit 1];
        u.Status_Date_Change__c = null;
        u.Write_Off_Date__c = null;
        update u;
        TriggerContextUtility.setFirstRunTrue();
        
        u.Status__c = 'Write-off';
        update u;
        
        Test.stopTest();
    } 
}