force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <inlineHelpText>Select the type of Partner</inlineHelpText>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Reseller / VAR</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Likely_Purchase__c.field-meta.xml
<CustomField>
    <fullName>Likely_Purchase__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Likely Purchase</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SPA_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>SPA_Approval_Date__c</fullName>
    <label>SPA Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Bundle__c.field-meta.xml
<CustomField>
    <fullName>Bundle__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bundle</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/quoteResellerGetProducts.cls
public class quoteResellerGetProducts {
 	public Id accId {get;set;}
    public List<Opportunity_Partner__c> parts {get;set;}
    public List<OpportunityLineItem> getCons() {
        List<OpportunityLineItem> cons = [select id, product2.name,quantity,unitprice,Product2.Description,
                                    SPA_Expiration_Date__c,Product2.Bundle__c,SPA_Approval_Date__c,
               Product2.family from OpportunityLineItem where OpportunityId =: accId and Likely_Purchase__c  = true];
        
         parts = [select id, partner_account__r.Name from Opportunity_Partner__c where Opportunity__c =: accId
                                             and Partner_Type__c = 'Distributor'];
        
        //(select id, partner_account__r.Name from Opportunity_Partners__c where Partner_Type__c = 'Distributor' )

         return cons;        
    }
    
}