force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Reseller_Contact__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestOpportunityPartners.cls
@isTest
private class TestOpportunityPartners {
@testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
       
    static testmethod void getOppPartners()
  {		        
      
      List<Opportunity> opp  = [Select Id,(select id from opportunity_partners__r) from Opportunity limit 2];
      List<Opportunity_Partner__c> dpartners = new List<Opportunity_Partner__c>();
      
      //methods getOpp getUser updateopps getSpas
      //setting the variables need to pass to method get spas
      
      String oppid  = opp[0].Id;
      List<Id> oppids = new List<Id>();
      for(Opportunity o : opp){
          for(Opportunity_partner__c op : o.opportunity_partners__r)
              oppids.add(op.id);
      }
      //test method for account, contact or opportunity object as record id
      
      test.startTest();
	  OppResellers.oppResellersget(oppids);      
      dpartners = OpportunityPartners.getOppLInes(oppid);
      OpportunityPartners.updatePartners(dpartners,oppid);
      OpportunityPartners.deleteOppLines(dpartners,oppid);
      
      
      
      test.stopTest();
    }
 }