force-app/main/default/objects/Portal_Pricing__c/Portal_Pricing__c.object-meta.xml
<CustomObject>
    <description>Pricing and Spiff Information</description>
    <label>Partner Portal Price</label>
    <nameField>
        <label>Portal Pricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Pricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Portal_Pricing__c/fields/Spiff_Amount__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Amount__c</fullName>
    <label>Spiff Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricingEffectiveDate__c/PricingEffectiveDate__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Pricing Effective Date</label>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Spiff RequestsProduct</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testPortalPricingAndSpiffs.cls
@isTest
private class testPortalPricingAndSpiffs {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    @isTest
    static void testpricingSearch(){      
        
        test.startTest();
        PricingEffectiveDate__c p = new PricingEffectiveDate__c();
        p.Effective_Date__c = Date.today();
        p.Name = 'PricingDate';
        insert p;
        
        List<Portal_Pricing__c> pric = new List<Portal_Pricing__c>();
        
        Portal_Pricing__c pp1 = new Portal_Pricing__c();
        pp1.Effective_Date__c = Date.today();
        pp1.Spiff_Amount__c = 200;
        pp1.Country__c = 'United States';
        pp1.Product__c = 'CDE2303';
        pric.add(pp1);
        
        Portal_Pricing__c pp2 = new Portal_Pricing__c();
        pp2.Effective_Date__c = Date.today()-1;
        pp2.Country__c = 'United States';
        pp2.Product__c = 'CDE2303';
        pp2.Spiff_Amount__c = 200;
        pric.add(pp2);
        
        insert pric;        
       
        spiff_request__c spiff = [Select id from spiff_request__c limit 1];
        
        Boolean spiffReq = true;
        String prod = 'cde';
        portalPricingAndSpiffs.getProductInfo(spiffReq, prod);
        
        spiffReq = false;
        portalPricingAndSpiffs.getProductInfo(spiffReq, prod);
        spiffReq = true;
        portalPricingAndSpiffs.getAdminRecords(spiffReq, prod, spiff.Id);
        test.stopTest();
        
    }
}