force-app/main/default/objects/User/fields/Dashboard_Group__c.field-meta.xml
<CustomField>
    <fullName>Dashboard_Group__c</fullName>
    <description>Group that user belongs to for dashboards on salesforce</description>
    <label>Dashboard Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dashboard_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Wave_Dashboards__c/Wave_Dashboards__c.object-meta.xml
<CustomObject>
    <label>Configure Einstein Analytics Dashboard</label>
    <nameField>
        <label>Dashboard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Configure Einstein Analytics Dashboard</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Wave_Dashboards__c/fields/Dashboard_Group__c.field-meta.xml
<CustomField>
    <fullName>Dashboard_Group__c</fullName>
    <label>Dashboard Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Dashboard_Group</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Wave_Dashboards__c/fields/Dashboard_Id__c.field-meta.xml
<CustomField>
    <fullName>Dashboard_Id__c</fullName>
    <label>Dashboard Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Wave_Dashboards__c/fields/Group_Order__c.field-meta.xml
<CustomField>
    <fullName>Group_Order__c</fullName>
    <description>Order of the tabs in each group. Allows to set an order</description>
    <inlineHelpText>Order of the tabs in each group. Allows to set an order of how user will see each tab. Can order by type or name or any way that makes sense.</inlineHelpText>
    <label>Group Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Dashboards.cls
public class Dashboards {
    @AuraEnabled
    public static List<Wave_Dashboards__c> getOppLInes(String dgroup){
        User u = getUser.getUser();
        system.debug('user dsah '+u.Dashboard_Group__c);
        List<Wave_Dashboards__c> items = [SELECT Id, Name ,Dashboard_Id__c  FROM Wave_Dashboards__c
                                          where Dashboard_Group__c = : u.Dashboard_Group__c and IsActive__c = true
                                          order by Group_Order__c asc];
        system.debug('list products '+items );
        
        return items;
    }
}