force-app/main/default/objects/User/fields/QuotaFields__c.field-meta.xml
<CustomField>
    <fullName>QuotaFields__c</fullName>
    <label>QuotaFields</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/User/fields/QuotaLabels__c.field-meta.xml
<CustomField>
    <fullName>QuotaLabels__c</fullName>
    <label>QuotaLabels</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/myNewQuota.cls
public class myNewQuota {
    
    @AuraEnabled
     public static List<User> getReps()
    {   
        List<User> myReps = [Select Id,Name,FirstName,LastName,
                             QuotaLabels__c ,QuotaFields__c 
                             from User where ManagerId =:UserInfo.getUserId() and isactive = true];
        
        return myReps;
    }
    @AuraEnabled
     public static User myFields()
    {   
        List<User> myReps = [Select id, QuotaLabels__c ,QuotaFields__c 
                             from User where Id =:UserInfo.getUserId()];
        
        return myReps[0];
    }
    @AuraEnabled
     public static List<SObject> createQuotas(List<SObject> quotas)
    { 
        system.debug(quotas);
        
        for(Sobject s : quotas){
            s.Id = null;
        }
        insert quotas;
        
        system.debug('created quotas');
        system.debug(quotas);
        return quotas;
        
    }

}