force-app/main/default/objects/Accessories__c/Accessories__c.object-meta.xml
<CustomObject>
    <label>Accessory</label>
    <nameField>
        <label>Accessories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessories and Similiar Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accessories__c/fields/Accessory_Product__c.field-meta.xml
<CustomField>
    <fullName>Accessory_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessory Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Accessories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accessories__c/fields/Main_Product__c.field-meta.xml
<CustomField>
    <fullName>Main_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Accessories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestMasterAccessoriesTrigger.cls
@IsTest
public class TestMasterAccessoriesTrigger  {
   @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    
    Static testmethod void insertAcc() {
       List<Product2> prods = [Select id from Product2 where isactive= true limit 3];
        
        List<Accessories__c> newacc = new List<Accessories__c>();
        for(Product2 p : prods){
           Accessories__c acc = new Accessories__c(Main_Product__c = p.id, Accessory_Product__c = p.id);
            newacc.add(acc);
        }
        test.startTest();
        insert newacc;
        
        delete newacc[0];
        test.stopTest();
        
       
        
        
    }

}