force-app/main/default/objects/Accessories__c/Accessories__c.object-meta.xml
<CustomObject>
    <label>Accessory</label>
    <nameField>
        <label>Accessories Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accessories and Similiar Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Accessories__c/fields/Accessory_Product__c.field-meta.xml
<CustomField>
    <fullName>Accessory_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Accessory Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Accessories1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accessories__c/fields/AutoAdd__c.field-meta.xml
<CustomField>
    <fullName>AutoAdd__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Auto Add</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Accessories__c/fields/Main_Product__c.field-meta.xml
<CustomField>
    <fullName>Main_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Accessories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Accessories__c/fields/ProdAccId__c.field-meta.xml
<CustomField>
    <fullName>ProdAccId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ProdAccId</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ProdAccExtension.cls
public with sharing class ProdAccExtension {

    private final Product2 prod;
    private ApexPages.StandardController stdController;
	public List<Accessories__c> accs=new List<Accessories__c>();
    public ProdAccExtension(ApexPages.StandardController stdController) {
        this.prod = (Product2)stdController.getRecord();
        this.stdController = stdController;
    }

    public List<Accessories__c> getaccs()
    {
       
          accs = [SELECT Id, Name, Accessory_Product__c, AutoAdd__c, Main_Product__c, ProdAccId__c from Accessories__c
                  where Main_Product__c=: prod.Id];
        
                    system.debug('accessories '+accs);
        return accs;
    }
   public void updateaccs(){   
   	update accs;
 }

}