force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CalloutKey__mdt/CalloutKey__mdt.object-meta.xml
<CustomObject>
    <label>CalloutKey</label>
    <pluralLabel>CalloutKeys</pluralLabel>
</CustomObject>

force-app/main/default/objects/CalloutKey__mdt/fields/API_Key__c.field-meta.xml
<CustomField>
    <fullName>API_Key__c</fullName>
    <label>API_Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Account_Type__c.field-meta.xml
<CustomField>
    <fullName>Account_Type__c</fullName>
    <formula>TEXT (Account.Type)</formula>
    <label>Account Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/Staging_Govspend_Contact__c.object-meta.xml
<CustomObject>
    <label>Staging Govspend Contact</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Staging Govspend Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Govspend Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Account_Address__c.field-meta.xml
<CustomField>
    <fullName>Account_Address__c</fullName>
    <label>Account Address</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Account_City__c.field-meta.xml
<CustomField>
    <fullName>Account_City__c</fullName>
    <label>Account City</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Account_County__c.field-meta.xml
<CustomField>
    <fullName>Account_County__c</fullName>
    <label>Account County</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Account_Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Account_Fiscal_Year__c</fullName>
    <label>Account Fiscal Year</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Account_State__c.field-meta.xml
<CustomField>
    <fullName>Account_State__c</fullName>
    <label>Account State</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Account_State_Code__c.field-meta.xml
<CustomField>
    <fullName>Account_State_Code__c</fullName>
    <label>Account State Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Account_Website__c.field-meta.xml
<CustomField>
    <fullName>Account_Website__c</fullName>
    <label>Account Website</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_ID__c</fullName>
    <label>Contact ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <label>Plan</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Staging_Govspend_Contact_Header__c.field-meta.xml
<CustomField>
    <fullName>Staging_Govspend_Contact_Header__c</fullName>
    <label>Staging Govspend Contact Header</label>
    <referenceTo>Staging_Govspend_Contact_Header__c</referenceTo>
    <relationshipLabel>Staging Govspend Contacts</relationshipLabel>
    <relationshipName>Staging_Govspend_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/StateCode__c.field-meta.xml
<CustomField>
    <fullName>StateCode__c</fullName>
    <label>StateCode</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact_Header__c/Staging_Govspend_Contact_Header__c.object-meta.xml
<CustomObject>
    <label>Staging Govspend Contact Header</label>
    <nameField>
        <displayFormat>SH-{0}</displayFormat>
        <label>Staging Govspend Contact Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Govspend Contact Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Staging_Govspend_Contact_Header__c/fields/Total_Pages__c.field-meta.xml
<CustomField>
    <fullName>Total_Pages__c</fullName>
    <label>Total Pages</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/GovSpendMappingService.cls
public class GovSpendMappingService {
    
    
    public static void handleSearch(String searchId){
        ExportCreditStats esc = getCreditStats(searchId);
        if(esc.hasSufficientCredits && esc.totalRecords>0){
            Decimal totalRecordsDec = Decimal.valueOf(esc.totalRecords);
            totalRecordsDec = totalRecordsDec/100;
            String jobId = generateGUID();
            Integer totalPages = Integer.valueOf(totalRecordsDec.round(System.RoundingMode.CEILING));
            System.enqueueJob(new GovSpendCalloutQueueable(searchId, 1, totalPages, jobId));
        }
        
    }
        
    public static void doMapping(String searchId, Integer pageNumber, Integer totalPages, String jobId){
        List<Staging_GovSpend_Contact__c> stagingContactsToInsert = new List<Staging_GovSpend_Contact__c>();
        Staging_GovSpend_Contact_Header__c header = new Staging_GovSpend_Contact_Header__c(Page_Number__c=pageNumber, Total_Pages__c=totalPages, Job_Id__c=jobId);
        GovSpendCallout gsc = new GovSpendCallout(getApiKey());
		HttpResponse response = gsc.runSavedSearch(searchId, pageNumber);
        if(response.getStatusCode()!=200&&response.getStatusCode()!=201){
            header.Error_Message__c='Unsuccessful status code: '+response.getStatusCode()+' Response: '+response.getBody();
            insert header;
            return;
        }
        Map<String, Object> responseMap = (Map<String, Object>)JSON.deserializeUntyped(response.getBody());
        insert header;
        List<Object> a = (List<Object>)responseMap.get('result');
        for(integer i=0; i<a.size(); i++){                    
            Map<String, Object> a0 = (Map<String, Object>)a[i];
            Map<String, Object> organization = (Map<String, Object>)a0.get('Organization');
            Map<string, Object> contact = (Map<String, Object>)a0.get('Contact');
            String conString = JSON.serialize(contact);
            GovSpendContact gscon = (GovSpendContact)JSON.deserialize(conString, GovSpendContact.class);
            String accString = JSON.serialize(organization);
            GovSpendAccount gsacc = (GovSpendAccount)JSON.deserialize(accString, GovSpendAccount.class);
            System.debug(gscon);
            Staging_GovSpend_Contact__c stagingCon = govSpendAccountContactMapping(gscon, gsacc);
            stagingCon.Staging_Govspend_Contact_Header__c=header.id;
            stagingContactsToInsert.add(stagingCon);
        }
        insert stagingContactsToInsert;
    }
    
    public static ExportCreditStats getCreditStats(String searchId){
        GovSpendCallout gsc = new GovSpendCallout(getApiKey());
		HttpResponse response = gsc.exportCreditStats(searchId);
        if(response.getStatusCode()!=200&&response.getStatusCode()!=201){
        	throw new CalloutException('Callout to get Credits information failed');
        }
        ExportCreditStats ecs = (ExportCreditStats)JSON.deserialize(response.getBody(), ExportCreditStats.class);
        return ecs;
    }
    
    
    private static String getApiKey(){
        return [select API_Key__c from CalloutKey__mdt where DeveloperName='GovSpend'].API_Key__c;
    }
    
    public static Staging_GovSpend_Contact__c govSpendAccountContactMapping(GovSpendContact con, GovSpendAccount acc){
        
        return new Staging_GovSpend_Contact__c(FirstName__c=con.FirstName,
                                               LastName__c=con.LastName,
                                               Contact_ID__c=con.ID,
                                               Email__c=con.Email,
                                               Address__c=con.Address,
                                               City__c=con.City,
                                               Phone__c=con.Phone,
                                               State__c=con.State,
                                               StateCode__c=con.StateCode,
                                               Title__c=con.Title,
                                               Plan__c=con.Plan,
                                               Account_Name__c=acc.Name,
                                               Account_Address__c=acc.Address1,
                                               Account_City__c=acc.City,
                                               Account_County__c=acc.County,
                                               Account_State__c=acc.State,
                                               Account_State_Code__c=acc.StateCode,
                                               Account_Website__c=acc.WebSite,
                                               Account_Type__c=acc.AccountType,
                                               Account_Fiscal_Year__c=acc.FiscalYear
                                               );                
        
    }
    
    public static String generateGUID(){
		Blob b = Crypto.GenerateAESKey(128);
		String h = EncodingUtil.ConvertTohex(b);
		String hyphen = '-';
		return h.SubString(0,8) + hyphen + h.SubString(8,12) + hyphen + h.SubString(12,16) + hyphen + h.SubString(16,20) + hyphen + h.substring(20);
	}


}