force-app/main/default/objects/PricebookEntry/fields/Disty_Spiff__c.field-meta.xml
<CustomField>
    <fullName>Disty_Spiff__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount of spiff for Distributor on this price</description>
    <label>Disty Spiff</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Reseller_Spiff__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Spiff__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Reseller Spiff</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPIFF__c/SPIFF__c.object-meta.xml
<CustomObject>
    <label>Spiff</label>
    <nameField>
        <label>SPIFF Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SPIFFs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SPIFF__c/fields/AV__c.field-meta.xml
<CustomField>
    <fullName>AV__c</fullName>
    <label>AV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPIFF__c/fields/Distrubution__c.field-meta.xml
<CustomField>
    <fullName>Distrubution__c</fullName>
    <label>Distribution</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPIFF__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>200</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SPIFF__c/fields/Max_Reseller__c.field-meta.xml
<CustomField>
    <fullName>Max_Reseller__c</fullName>
    <formula>MAX(AV__c,CDW__c, NSP__c,SPG__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Max Reseller</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPIFF__c/fields/NSP__c.field-meta.xml
<CustomField>
    <fullName>NSP__c</fullName>
    <label>NSP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SPIFF__c/fields/PriceBook__c.field-meta.xml
<CustomField>
    <fullName>PriceBook__c</fullName>
    <label>PriceBook</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SPIFF__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <label>SKU</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SpiffToPrices.cls
public class SpiffToPrices {
    @AuraEnabled
    public static void updateSpiffs(){
        
        Set<String> pb   = new Set<String>();
        Set<String> prod = new Set<String>();
        
        Map<String, Spiff__c> spiff = New Map<String, Spiff__c>();
        for(Spiff__c s : [Select id, SKU__c ,SPG__c, AV__c , CDW__c ,NSP__c ,Distrubution__c ,Max_Reseller__c, ExternalId__c,PriceBook__c
                          from Spiff__c]){
                              spiff.put(s.SKU__c+s.PriceBook__c,s);
                              pb.add(s.PriceBook__c);
                              prod.add(s.SKU__c);
                          }
        
        List<PricebookEntry> price = [Select id, Reseller_Spiff__c , Disty_Spiff__c, pricebook2.name,product2.name
                                      from PricebookEntry where product2.name in : prod ];
        List<PricebookEntry> pricetoUpdate =  new List<PricebookEntry>();
        
        Integer disti = 0;
        Integer cdw = 0;
        Integer av = 0;
        Integer dmr = 0;
        system.debug(spiff);
        for(PricebookEntry p : price){
            //system.debug(p.product2.name+p.pricebook2.name);
            
            if(spiff.containsKey(p.product2.name+p.pricebook2.name)){
                Spiff__c s = spiff.get(p.product2.name+p.pricebook2.name);
                if(p.pricebook2.name == 'VSA Distributor Price List' || p.pricebook2.name == 'VSA Canadian Price List'){
                    p.Disty_Spiff__c = s.Distrubution__c;
                    p.Reseller_Spiff__c = s.Max_Reseller__c;
                    disti = disti+1;
                }else if(p.pricebook2.name == 'VSA CDW Price List'){
                    p.Reseller_Spiff__c = s.CDW__c;
                    cdw = cdw+1;
                }else if(p.pricebook2.name == 'VSA AV Solution Partner Price List'){
                    p.Reseller_Spiff__c = s.AV__c;
                    av = av+1;
                }else if(p.pricebook2.name == 'VSA DMR Price List'){
                    p.Reseller_Spiff__c = s.NSP__c ;
                    dmr = dmr+1;
                }
                pricetoUpdate.add(p);
                
            }
        }
        
        update pricetoUpdate;
        
        system.debug('updates '+pricetoUpdate.size());
        system.debug('disti '+disti);
        system.debug('cdw '+cdw);
        system.debug('av '+av);
        system.debug('dmr '+dmr);
        
    }
}