force-app/main/default/objects/PricebookEntry/fields/Disty_Spiff__c.field-meta.xml
<CustomField>
    <fullName>Disty_Spiff__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount of spiff for Distributor on this price</description>
    <label>Disty Spiff</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Reseller_Spiff__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Spiff__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Reseller Spiff</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SpiffPricing__c/SpiffPricing__c.object-meta.xml
<CustomObject>
    <description>Object to update the spiff for active products</description>
    <label>Spiffs</label>
    <nameField>
        <label>SpiffPricing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SpiffPricing</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SpiffPricing__c/fields/CDW__c.field-meta.xml
<CustomField>
    <fullName>CDW__c</fullName>
    <label>CDW</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SpiffPricing__c/fields/Distribution__c.field-meta.xml
<CustomField>
    <fullName>Distribution__c</fullName>
    <label>Distribution</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SpiffPricing__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <label>Price Book</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpiffPricing__c/fields/Pricebookentryid__c.field-meta.xml
<CustomField>
    <fullName>Pricebookentryid__c</fullName>
    <label>Pricebookentryid</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SpiffPricing__c/fields/SPG__c.field-meta.xml
<CustomField>
    <fullName>SPG__c</fullName>
    <label>SPG</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/spiffpricing.cls
public class spiffpricing{
    // These variables store Trigger.oldMap and Trigger.newMap
    Map<Id, SpiffPricing__c> oldspiffs;
    Map<Id, SpiffPricing__c> newspiffs; 
    
    // A map of the old and new records is expected as inputs
    public spiffpricing(
        Map<Id, SpiffPricing__c> oldTriggernewspiffs, 
        Map<Id, SpiffPricing__c> newTriggernewspiffs) {
            oldspiffs = oldTriggernewspiffs;
            newspiffs = newTriggernewspiffs;
                    }
    
    public static void updatename(List<SpiffPricing__c> spiffs) {
        Map<String,pricebookentry> pbe = new Map<String,pricebookentry>();
        Set<String> products = new Set<String>();
         for(SpiffPricing__c st : spiffs){
                products.add(st.sku__c);
            }      
        
        
        List<pricebookentry> pbetoUpdate = new List<pricebookentry>();
        if(trigger.isInsert || trigger.isUpdate){
            for(pricebookentry p : [Select id, product2.name,name,pricebook2.name ,Disty_Spiff__c , Reseller_Spiff__c from pricebookentry where product2.name in: products])
            pbe.put(p.product2.name+ p.pricebook2.name, p);
            
            for(SpiffPricing__c s : spiffs){
                s.name = s.SKU__c+s.Price_Book__c;                
                if(s.SPG__c < 0 || s.SPG__c == null){
                    s.SPG__c = 0;
                }
                
                if(s.CDW__c < 0 || s.CDW__c == null){
                    s.CDW__c = 0;
                }
                
                if(s.NSP__c < 0 || s.NSP__c == null){
                    s.NSP__c = 0;
                }
                
                if(s.AV__c < 0 || s.AV__c == null){
                    s.AV__c = 0;
                }
                if(s.Distribution__c < 0 || s.Distribution__c == null){
                    s.Distribution__c = 0;
                }
                
                
                
                Double reseller = null;
                
                reseller = math.max(s.AV__c, s.CDW__c);
                reseller = math.max(reseller, s.NSP__c);
                reseller = math.max(reseller, s.SPG__c);
                system.debug('key: '+s.name);
                if(pbe.containsKey(s.name)){
                    system.debug('key found');
                    PricebookEntry e = pbe.get(s.name);
                    PricebookEntry entry = new PricebookEntry(id = e.Id,
                                                             Disty_Spiff__c = s.Distribution__c,
                                                             Reseller_Spiff__c = reseller);
                    pbetoUpdate.add(entry);
                    s.Pricebookentryid__c = e.Id;
                    
                }
            }
            
        }      
        
        
        
        system.debug('map');
        system.debug(pbe);
        update pbetoUpdate;
        system.debug('pbe to update list ');
        system.debug(pbetoUpdate);
        
    }
    
}