force-app/main/default/objects/PricebookEntry/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Price Book Entries</relationshipLabel>
    <relationshipName>Price_Book_Entries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <formula>PricebookEntry.Product2.ProductCode</formula>
    <label>Product</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Spiff RequestsProduct</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requester</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Sale_Date__c.field-meta.xml
<CustomField>
    <fullName>Sale_Date__c</fullName>
    <label>Sale Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Spa_Number__c.field-meta.xml
<CustomField>
    <fullName>Spa_Number__c</fullName>
    <label>Spa Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Spa_Product__c.field-meta.xml
<CustomField>
    <fullName>Spa_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spa Product</label>
    <referenceTo>QuoteLineItem</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/testSpiffRequestMaster.cls
@IsTest
public class testSpiffRequestMaster  {
   @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    
    Static testmethod void testMasterTrigger() {
        
        test.startTest();
        //build test data will cover the class currently. This is set up for future testing
        //on the master class
        QuoteLineItem qte = [Select id,Quote.Name,product2Id from QuoteLineItem limit 1]; 
        Account acct  = [Select id, name from account where name ='usditi' limit 1];
        Contact var = [Select id, name from contact limit 1];
        /*
        PricebookEntry pb = [Select product2id from PricebookEntry where isactive = true and Pricebook2Id =: qte.pportunity.Pricebook2Id];
        
        Quotelineitem ql = new Quotelineitem();
        ql.UnitPrice */
        
        Spiff_request__c spiffr = new Spiff_request__c();
        spiffr.Product__c= qte.Product2Id;
        spiffr.Sale_Date__c = date.today();
        spiffr.Quantity__c  = 1;
        spiffr.Requester__c = var.Id;
        spiffr.Spa_Number__c = qte.Quote.Name;
        insert spiffr;
        
        
        Spiff_request__c sTest = [Select id, Spa_Product__c from Spiff_request__c where id =:spiffr.Id];
        test.stopTest();
        
        system.assertEquals(qte.Id , sTest.Spa_Product__c);
        
    }
    
}