force-app/main/default/objects/Staging_Govspend_Contact__c/Staging_Govspend_Contact__c.object-meta.xml
<CustomObject>
    <label>Staging Govspend Contact</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Staging Govspend Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Govspend Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Staging_Govspend_Contact_Header__c.field-meta.xml
<CustomField>
    <fullName>Staging_Govspend_Contact_Header__c</fullName>
    <label>Staging Govspend Contact Header</label>
    <referenceTo>Staging_Govspend_Contact_Header__c</referenceTo>
    <relationshipLabel>Staging Govspend Contacts</relationshipLabel>
    <relationshipName>Staging_Govspend_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact_Header__c/Staging_Govspend_Contact_Header__c.object-meta.xml
<CustomObject>
    <label>Staging Govspend Contact Header</label>
    <nameField>
        <displayFormat>SH-{0}</displayFormat>
        <label>Staging Govspend Contact Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Govspend Contact Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GovSpendMappingServiceTest.cls
@isTest
public class GovSpendMappingServiceTest {
	      
    @isTest
    static void test_Success(){
        MultiStaticResourceCalloutMock multimock = new MultiStaticResourceCalloutMock();
        multimock.setStaticResource('https://app.govspend.com/runSavedSearch', 'GovSpend_runSavedSearch_Success');
        multimock.setStaticResource('https://app.govspend.com/exportCreditStats?searchId=ABC123', 'GovSpend_exportCreditStats_Success');
        multimock.setStatusCode(200);
        multimock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.setMock(HttpCalloutMock.class, multimock);
       	Test.startTest();
        GovSpendMappingService.handleSearch('ABC123');
        Test.stopTest();
        System.assertEquals(1, [select id from lead].size());
        System.assertEquals(1, [select id from Staging_GovSpend_Contact_Header__c].size());
        System.assertEquals(1, [select id from Staging_GovSpend_Contact__c].size());
       
    }
    
    
}