force-app/main/default/objects/Staging_Govspend_Contact__c/Staging_Govspend_Contact__c.object-meta.xml
<CustomObject>
    <label>Staging Govspend Contact</label>
    <nameField>
        <displayFormat>S-{0}</displayFormat>
        <label>Staging Govspend Contact Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Govspend Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_ID__c</fullName>
    <label>Contact ID</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>LastName</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact__c/fields/Staging_Govspend_Contact_Header__c.field-meta.xml
<CustomField>
    <fullName>Staging_Govspend_Contact_Header__c</fullName>
    <label>Staging Govspend Contact Header</label>
    <referenceTo>Staging_Govspend_Contact_Header__c</referenceTo>
    <relationshipLabel>Staging Govspend Contacts</relationshipLabel>
    <relationshipName>Staging_Govspend_Contacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Staging_Govspend_Contact_Header__c/Staging_Govspend_Contact_Header__c.object-meta.xml
<CustomObject>
    <label>Staging Govspend Contact Header</label>
    <nameField>
        <displayFormat>SH-{0}</displayFormat>
        <label>Staging Govspend Contact Header Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Staging Govspend Contact Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GovSpendContactTriggerTest.cls
@isTest
public class GovSpendContactTriggerTest {

    @isTest
    static void test_Success(){
        Campaign cam = new Campaign(name=System.Label.GovSpend_Campaign_Name);
        insert cam;
    	Staging_GovSpend_Contact_Header__c sgch = new Staging_GovSpend_Contact_Header__c();
        insert sgch;
        Staging_GovSpend_Contact__c sgc = new Staging_GovSpend_Contact__c(Staging_GovSpend_Contact_Header__c=sgch.id, FirstName__c='John', LastName__c='Doe', Contact_ID__c='abc123', Email__c='johndoe@yahoo.com', Account_Name__c='Walmart');
        insert sgc;
        System.assertEquals(1, [select id from Lead where Email='johndoe@yahoo.com'].size());
     //   Contact c = new Contact(FirstName='Jane', LastName='Doe', Email='jdoe@gmail.com', AccountId=[select id from account limit 1].id);
   //     insert c;
     //   Staging_GovSpend_Contact__c sgc2 = new Staging_GovSpend_Contact__c(Staging_GovSpend_Contact_Header__c=sgch.id, FirstName__c='Jane', LastName__c='Doe', Contact_ID__c='abc124', Email__c='jdoe@gmail.com', Account_Name__c='Walmart');
     //   insert sgc2;
        Staging_GovSpend_Contact__c sgc3 = new Staging_GovSpend_Contact__c(Staging_GovSpend_Contact_Header__c=sgch.id, FirstName__c='John', LastName__c='Doe', Contact_ID__c='abc123', Email__c='johndoe@yahoo.com', Account_Name__c='Walmart');
        insert sgc3;
        System.assertEquals(1, [select id from Lead where Email='johndoe@yahoo.com'].size()); //we know a contact was updated and a Lead was updated. No lead creation.
    }
    
}