force-app/main/default/objects/Opportunity/fields/ApexTest__c.field-meta.xml
<CustomField>
    <fullName>ApexTest__c</fullName>
    <defaultValue>false</defaultValue>
    <description>used for test to run without hitting query limits on all the updates. This will be less needed as classes and triggers are updated with better efficiency</description>
    <label>Apex Test</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Cloning__c.field-meta.xml
<CustomField>
    <fullName>Cloning__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to suppress unbulkified flows when cloning. Cloning buttons must be url hacked for this to work</description>
    <label>Cloning</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Count_of_Quotes__c.field-meta.xml
<CustomField>
    <fullName>Count_of_Quotes__c</fullName>
    <label>Count of Quotes</label>
    <summaryFilterItems>
        <field>Quote.Status</field>
        <operation>equals</operation>
        <value>Needs Review, Approved, Delayed Info Missing, Inactive</value>
    </summaryFilterItems>
    <summaryForeignKey>Quote.OpportunityId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Lookup_Account__c.field-meta.xml
<CustomField>
    <fullName>End_User_Lookup_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Use this to lookup existing end user accounts. If it does not exist, then you can just enter as text in the section below. &quot;End User Company, City, and state&quot; You only need to fill one section.</inlineHelpText>
    <label>End User</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <errorMessage>Must Select End User Account. If you do not see an existing account, please make sure the Account &apos;Type&apos; is set as &apos;End User&apos;</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>End User</value>
        </filterItems>
        <filterItems>
            <field>$User.UserType</field>
            <operation>equals</operation>
            <value>Standard</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (End User Lookup Account)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Quote/fields/EDI_Approval_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>EDI_Approval_Date_Time__c</fullName>
    <label>EDI Approval Date Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/First_Time_Buyer__c.field-meta.xml
<CustomField>
    <fullName>First_Time_Buyer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Time Buyer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Resubmission_Date__c.field-meta.xml
<CustomField>
    <fullName>Resubmission_Date__c</fullName>
    <label>Resubmission Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Resubmission_Notes__c.field-meta.xml
<CustomField>
    <fullName>Resubmission_Notes__c</fullName>
    <label>Resubmission Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Resubmitter__c.field-meta.xml
<CustomField>
    <fullName>Resubmitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resubmitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Resubmitter_Email__c.field-meta.xml
<CustomField>
    <fullName>Resubmitter_Email__c</fullName>
    <label>Resubmitter Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Spa_Stage__c.field-meta.xml
<CustomField>
    <fullName>Spa_Stage__c</fullName>
    <formula>&quot;&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spa Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Distributor_Rep__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Rep__c</fullName>
    <label>Distributor Sales Rep</label>
    <relationshipName>DistributorSalesRep</relationshipName>
    <restrictedAdminField>false</restrictedAdminField>
    <type>Hierarchy</type>
</CustomField>

force-app/main/default/objects/User/fields/PartnerDistiEmail__c.field-meta.xml
<CustomField>
    <fullName>PartnerDistiEmail__c</fullName>
    <formula>Distributor_Rep__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner Disti Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PartnerDistiName__c.field-meta.xml
<CustomField>
    <fullName>PartnerDistiName__c</fullName>
    <formula>Distributor_Rep__r.FirstName &amp;&apos; &apos;&amp;  Distributor_Rep__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner Disti Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/PartnerDistiPhone__c.field-meta.xml
<CustomField>
    <fullName>PartnerDistiPhone__c</fullName>
    <formula>Distributor_Rep__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Partner Disti Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Category__c.field-meta.xml
<CustomField>
    <fullName>Sales_Category__c</fullName>
    <label>Sales Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>RBM</fullName>
            </value>
            <value>
                <fullName>TM</fullName>
            </value>
            <value>
                <fullName>Managment</fullName>
            </value>
            <value>
                <fullName>Distributor Partner</fullName>
            </value>
            <value>
                <fullName>Manager/Director</fullName>
            </value>
            <value>
                <fullName>AV Solutions</fullName>
            </value>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>Disti</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppsSpaUpdates.cls
public class OppsSpaUpdates{
    // These variables store Trigger.oldMap and Trigger.newMap
    Map<Id, Opportunity> oldOpps;
    Map<Id, Opportunity> newOpps;
    
    
    public OppsSpaUpdates(
        Map<Id, Opportunity> oldTriggerOpps, 
        Map<Id, Opportunity> newTriggerOpps) {
            
            oldOpps = oldTriggerOpps;
            newOpps = newTriggerOpps;
        }
    
    // The one method your master trigger will call
    public void SpaSubmission() {
        
        List<Quote> quotesToInsert = new List<Quote>();
       
        system.debug('check the size of the new map ' +newOpps.size());
        if(newOpps.size() >0){
            
            User u = [Select FirstName,LastName,Name,Id,Email, Phone,Sales_Category__c from user where id = : UserInfo.getUserId() ];
            
            for (Opportunity opp : newOpps.values()) {
                Opportunity oldOpp  = oldOpps.get(opp.Id);
                 if((opp.StageName == 'Distributor SPA Request'   && opp.HasOpportunityLineItem == true && opp.Count_of_Quotes__c < 1) ||
                    (opp.ApexTest__c == true && opp.Cloning__c == false)){
                     Quote q = new Quote(OpportunityId = opp.Id,
                                    Name= opp.SPA_ID__c,
                                   Status= 'Needs Review');
                quotesToInsert.add(q);
                system.debug('spaid '+opp.SPA_ID__c+ ' oppid '+opp.Id);                 
                     
                 }
                
                //check if the accountid field is blank but the end user account lookup is filled and update accountid
                if(opp.AccountId == null && opp.End_User_Lookup_Account__c != null){
                    opp.AccountId = opp.End_User_Lookup_Account__c;                    
                }
            }
           
        }
        /* -- jason orbison 10.30.19 -- no longer adding quote using a trigger. instead using the flow on the opporutnity page to control submissions 
         * and resubmissions for Partners */
        
         //insert quotesToInsert;
    }  
    /*
    public void SpaStageApproval() {
        
        User u = [SELECT Id,Name,Email,Distributor_Rep__c, PartnerDistiName__c,PartnerDistiEmail__c,
                  PartnerDistiPhone__c,AccountId,Sales_Category__c
                  FROM User WHERE Id= :UserInfo.getUserId()] ;
        
        List<Quote> quotesToUpdate = new List<Quote>();
        
        Map<Id, Quote> mquotes = new Map<Id, Quote>();
        for(Quote q : [Select Id,Resubmitter__c,Resubmitter_Email__c,Resubmission_Date__c,Resubmission_Notes__c,
                       Status,OpportunityId from Quote  where  First_Time_Buyer__c = false and Opportunityid in: newOpps.values() order by CreatedDate desc ])
            mquotes.put(q.OpportunityId , q);
        
        for (Opportunity o : newOpps.values()) {
            Opportunity old  = oldOpps.get(o.Id);
            
            if (o.Spa_Recent_Approval_Date__c != old.Spa_Recent_Approval_Date__c) {       
                o.EDI_Approval_Date_Time__c = DateTime.Now();
            } 
            
            if ((o.Spa_Resubmission_Note__c != null && old.Spa_Resubmission_Note__c == null) || o.Spa_Resubmission_Note__c != old.Spa_Resubmission_Note__c){
                if(o.Spa_Resubmission_Note__c != null && old.Spa_Resubmission_Note__c == null)
                o.Spa_Stage__c = 'Resubmitted';
                o.Spa_Resubmitter__c = u.Id;
                o.Spa_Resubmitter_Email__c = u.Email;
                o.Spa_Resubmitted_Date__c = DateTime.Now();
                
                OpportunityTeamMember team = new OpportunityTeamMember(
                    OpportunityId = o.Id,
                    TeamMemberRole = u.Sales_Category__c,
                    UserId = u.Id,
                    OpportunityAccessLevel = 'Edit'    
                );
                insert team;
                
                if(mquotes.containsKey(o.Id) && o.Spa_Resubmission_Note__c != null && old.Spa_Resubmission_Note__c == null){
                    Quote q = mquotes.get(o.Id);
                    
                    q.Resubmitter__c = u.Id;
                    q.Resubmitter_Email__c = u.Email;
                    q.Resubmission_Date__c = DateTime.Now();
                    q.Resubmission_Notes__c = o.Spa_Resubmission_Note__c;
                    q.Status = 'Needs Review';
                    
                    quotesToUpdate.add(q);
                    
                }else if(mquotes.containsKey(o.Id) && o.Spa_Resubmission_Note__c != old.Spa_Resubmission_Note__c ){
                    Quote q = mquotes.get(o.Id);    
                    q.Resubmission_Notes__c = q.Resubmission_Notes__c +' '+o.Spa_Resubmission_Note__c;
                    quotesToUpdate.add(q);
                }
            } 
            
            
            if(o.Spa_Stage__c == 'Rejected' && old.Spa_Stage__c != 'Rejected'){
                o.Spa_Reject_Date__c = Date.Today();
                
            }
        }
        update quotesToUpdate;

		
    }
    */
    /*
    public static  void AddTeam(List<Opportunity> opps,Map<Id, Opportunity> oldOpps,Map<Id, Opportunity> newOpps) { 
        
        List<Opportunity> oppsTeam = new List<Opportunity>();
        
        for(Opportunity o : opps){
            Opportunity oldOppo  = oldOpps.get(o.Id);
            if(oldOppo.SPA_Request__c == null &&  o.SPA_Request__c != null && o.StageName !='Distributor SPA Request'){
                //comment - adding opps to list that have a change in spa request
                //and sending to opp team update helper class
                oppsTeam.add(o) ;
            }
            
            OpportunityTeamAdd.teams(oppsTeam);
            
        }
    }
	*/
    
}