force-app/main/default/objects/Opportunity/fields/Auto_Update_Opp_Name__c.field-meta.xml
<CustomField>
    <fullName>Auto_Update_Opp_Name__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>If checked, automatically updates the opportunity name to match external or internal naming conventions. Mobile Users are recommended to check this field.</inlineHelpText>
    <label>Auto Create Opp Name</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Distributor_Account__c.field-meta.xml
<CustomField>
    <fullName>Distributor_Account__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>This ensures that competing distributors are not added to the opportunity partners.</inlineHelpText>
    <label>Partner Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Spa_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Spa_Approval_Date__c</fullName>
    <label>Spa Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/CDW.recordType-meta.xml
<RecordType>
    <fullName>CDW</fullName>
    <active>true</active>
    <businessProcess>VSA Sales Stages</businessProcess>
    <label>CDW</label>
</RecordType>

force-app/main/default/classes/TestSpaStage.cls
@IsTest
public class TestSpaStage {
    Static testmethod void TestSpaStage() {
    
        PriceBook2 pb = new Pricebook2(Name='VSA Distributor Price List',IsActive=true);
        insert pb;

        PriceBook2 pb2 = new Pricebook2(Name='VSA Canadian Price List',IsActive=true);
        insert pb2;

        PriceBook2 pb3 = new Pricebook2(Name='VSA CDW Price List',IsActive=true);
        insert pb3;

            Opportunity o = new Opportunity();
            o.Name = 'Apex Test';
            o.Type = 'Project' ;
            o.CloseDate = Date.Today() ;
            o.StageName = 'Contract';
            o.Spa_Approval_Date__c = Date.Today() ;
            o.Distributor_Account__c = True;
            o.Auto_Update_Opp_Name__c = false;
             insert o;
             
            
             }
       
 }