force-app/main/default/objects/Opportunity/fields/Bid_Registered__c.field-meta.xml
<CustomField>
    <fullName>Bid_Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Automatically updated when Spa Request field has bid registered selected.</inlineHelpText>
    <label>Bid Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Bid_Registered__c.field-meta.xml
<CustomField>
    <fullName>Bid_Registered__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Bid Registered</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Recent_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Recent_Approval_Date__c</fullName>
    <formula>if(isblank( Resubmission_Approval_Date__c ),  Approval_Date__c , Resubmission_Approval_Date__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Recent Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Specialty_Spa__c.field-meta.xml
<CustomField>
    <fullName>Specialty_Spa__c</fullName>
    <description>Special type of spas that run concurrently with a normal spa. This is used so that a 2nd opportunity does not have to be created.</description>
    <label>Specialty Spa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FTB</fullName>
            </value>
            <value>
                <fullName>Demo</fullName>
            </value>
            <value>
                <fullName>ACC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/getSpas.cls
public class getSpas {
    @AuraEnabled
    public static List<Quote> getspas(String quoteid){
        system.debug('quoteid '+ quoteid);
        //get a list of sibling spas that are related to the opportunity
        List<Opportunity> opps = [select id, 
                                  (Select id , name, status, expirationdate,Bid_Registered__c,Specialty_Spa__c,Recent_Approval_Date__c from quotes where id != : quoteid) 
                               from opportunity where Id in (Select OpportunityId from Quote where id =: quoteid) limit 1];
        
        List<Quote> records = opps[0].Quotes;
        
        
        System.debug( records );
        
        return records;
    }
}