force-app/main/default/objects/Opportunity/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Region of the deal.</description>
    <inlineHelpText>Region of deal. The distributors added depend on this field. US, Canada, or no distributors will be added based on this field.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>United States</fullName>
                <default>true</default>
                <label>United States</label>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Latin America</fullName>
            </value>
            <value>
                <fullName>VSI</fullName>
            </value>
            <value>
                <fullName>VSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Spa_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Spa_Approval_Date__c</fullName>
    <label>Spa Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Spa_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Spa_Expiration_Date__c</fullName>
    <label>Spa Expiration Date</label>
    <summarizedField>Quote.ExpirationDate</summarizedField>
    <summaryForeignKey>Quote.OpportunityId</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Max_Qty__c.field-meta.xml
<CustomField>
    <fullName>Max_Qty__c</fullName>
    <label>Max Qty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/SPA_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>SPA_Expiration_Date__c</fullName>
    <label>SPA Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/productAlphaSortComponentController.cls
public class productAlphaSortComponentController {
    
  public String controllerValue;
  public List<QuoteLineItem> lineItems {get;set;}
    
  public void setControllerValue (String s) {
      controllerValue = s;
      lineItems = [select Product2.Name, Quote.Opportunity.Country__c, Max_Qty__c, ListPrice, Quantity, Approved_Price__c, SPA_Approval_Date__c, SPA_Expiration_Date__c, Product2.Description from QuoteLineItem where QuoteId=:s order by Product2.Name asc];
  }
    
  public String getControllerValue() {
      return controllerValue;
  } 

}