force-app/main/default/objects/Opportunity/fields/Distributor__c.field-meta.xml
<CustomField>
    <fullName>Distributor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Type 2 or more characters and Press Enter to Search for a Distributor</inlineHelpText>
    <label>Distributor</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <errorMessage>Please Use an Account that is the Type Distributor</errorMessage>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Auto_Create_Disti__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Account.Name</field>
            <operation>equals</operation>
            <value>Data Visual Marketing</value>
        </filterItems>
        <infoMessage>Press Enter to Search for Distributor Account</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Distributor)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/PosSerialNumber__c/PosSerialNumber__c.object-meta.xml
<CustomObject>
    <description>Reviewed 7.19.2021 this object is needed as it is a temporary memory for pos spa information that is used it the serial number update process.</description>
    <label>PosSerialNumber</label>
    <nameField>
        <label>PosSerialNumber Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PosSerialNumbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PosSerialNumber__c/fields/Reseller__c.field-meta.xml
<CustomField>
    <fullName>Reseller__c</fullName>
    <label>Reseller</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PosSerialNumber__c/fields/SaleDate__c.field-meta.xml
<CustomField>
    <fullName>SaleDate__c</fullName>
    <label>SaleDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TestposSerialBatch.cls
@isTest
private class TestposSerialBatch{
     public static String CRON_EXP = '0 0 0 15 3 ? 2022';
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void TestposSerial() {
        
        test.startTest();
        Opportunity o = [Select id, SPA_ID__c from Opportunity limit 1];
        
        List<PosSerialNumber__c> psn = new List<PosSerialNumber__c>();
            PosSerialNumber__c posser = new PosSerialNumber__c();
            	posser.Distributor__c = 'test ';
                posser.Product__c = 'test';
                posser.Reseller__c = 'test';
                posser.Revenue__c = 300;
                posser.SaleDate__c = date.today();
                posser.Serial_Number__c = '33832-092387test';
                posser.SpaId__c = o.SPA_ID__c;
            
            psn.add(posser);
            
            insert psn;
        
         // Schedule the test job
        String jobId = System.schedule('ScheduledApexTestposSpaScheudle',
                                       CRON_EXP, 
                                       new posSpaSchedule());
        Test.stopTest();
        
        
        
    }
}