force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>End_User_Company__c</formula>
    <inlineHelpText>For Reporting. Clean Column and dashboard look</inlineHelpText>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Quote__c.field-meta.xml
<CustomField>
    <fullName>Primary_Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary quote that opp is using. this allows user to see the quote stages</description>
    <label>Primary Quote</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Spa_Request_Submitter__c.field-meta.xml
<CustomField>
    <fullName>Spa_Request_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spa Request Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipLabel>Opportunities (Spa Request Submitter)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Inactive.recordType-meta.xml
<RecordType>
    <fullName>Inactive</fullName>
    <active>true</active>
    <businessProcess>VSA Sales Stages</businessProcess>
    <label>Inactive</label>
</RecordType>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>Opportunity__r.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Quote.Specialty_Spa__c</field>
            <operation>notEqual</operation>
            <value>FTB, Demo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Competitor_Name_del__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Name_del__c</fullName>
    <label>Competitor Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acer</fullName>
            </value>
            <value>
                <fullName>Asus</fullName>
            </value>
            <value>
                <fullName>BenQ</fullName>
            </value>
            <value>
                <fullName>Boxlight</fullName>
            </value>
            <value>
                <fullName>ClearTouch</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>Epson</fullName>
            </value>
            <value>
                <fullName>Hitachi</fullName>
            </value>
            <value>
                <fullName>HP</fullName>
            </value>
            <value>
                <fullName>InFocus</fullName>
            </value>
            <value>
                <fullName>LG</fullName>
            </value>
            <value>
                <fullName>NEC</fullName>
            </value>
            <value>
                <fullName>Optoma</fullName>
            </value>
            <value>
                <fullName>Panasonic</fullName>
            </value>
            <value>
                <fullName>Planar</fullName>
            </value>
            <value>
                <fullName>Recordex</fullName>
            </value>
            <value>
                <fullName>Samsung</fullName>
            </value>
            <value>
                <fullName>Sharp</fullName>
            </value>
            <value>
                <fullName>Smart</fullName>
            </value>
            <value>
                <fullName>Vivitek</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Competitor_Price_del__c.field-meta.xml
<CustomField>
    <fullName>Competitor_Price_del__c</fullName>
    <label>Competitor Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Competitor_SKU__c.field-meta.xml
<CustomField>
    <fullName>Competitor_SKU__c</fullName>
    <label>Competitor SKU</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>if(Approved_Price__c = 0,
((UnitPrice  -  Landed_Cost__c )/UnitPrice),
((Approved_Price__c -  PricebookEntry.Total_Cost__c   )/Approved_Price__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <label>Requestor Email</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityTeamMember/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Custom</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Team</relationshipLabel>
    <relationshipName>Opportunity_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityTeamMember/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Quote.Specialty_Spa__c</field>
            <operation>notEqual</operation>
            <value>FTB, Demo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunity Team</relationshipLabel>
    <relationshipName>Opportunity_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Business_Reason_for_Bid_Registration__c.field-meta.xml
<CustomField>
    <fullName>Business_Reason_for_Bid_Registration__c</fullName>
    <label>BR Business Reason</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Bypass_Trigger__c.field-meta.xml
<CustomField>
    <fullName>Bypass_Trigger__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Demo - Bypass Trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>Opportunity.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/End_User_Account__c.field-meta.xml
<CustomField>
    <fullName>End_User_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Field used with a trigger to give a related list of spas (quotes) on the account page</description>
    <label>End User</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/End_User_Text__c.field-meta.xml
<CustomField>
    <fullName>End_User_Text__c</fullName>
    <label>End User Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Hot_Swap_Requested__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check Box to Know if this SPA has Hot Swap Requested or Not</description>
    <label>Hot Swap Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/In_Approval_Review__c.field-meta.xml
<CustomField>
    <fullName>In_Approval_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In Approval Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/List_of_Work_Activity_c__c.field-meta.xml
<CustomField>
    <fullName>List_of_Work_Activity_c__c</fullName>
    <label>BR List of Work</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Partner</label>
    <referenceTo>Opportunity_Partner__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Requestor_Email__c.field-meta.xml
<CustomField>
    <fullName>Requestor_Email__c</fullName>
    <label>Requestor Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Scope_of_Bid_Registration__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Bid_Registration__c</fullName>
    <label>BR Scope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Spa_Name__c.field-meta.xml
<CustomField>
    <fullName>Spa_Name__c</fullName>
    <formula>HYPERLINK(Id, Opportunity.Name,&quot;_self&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spa Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Spa_Request_Submitter__c.field-meta.xml
<CustomField>
    <fullName>Spa_Request_Submitter__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spa Request Submitter</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Spa_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Spa_Request_Type__c</fullName>
    <defaultValue>&quot;Spa Request&quot;</defaultValue>
    <label>Spa Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spa Request</fullName>
            </value>
            <value>
                <fullName>Bid Register Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/SpaId__c.field-meta.xml
<CustomField>
    <fullName>SpaId__c</fullName>
    <formula>Opportunity.SPA_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SpaId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Inactive.recordType-meta.xml
<RecordType>
    <fullName>Inactive</fullName>
    <active>true</active>
    <label>Inactive</label>
</RecordType>

force-app/main/default/objects/QuoteLineItem/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>Quote.Opportunity.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Hot_Swap_Flag__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to determine if the SKU is chosen/requested for Hot Swap</description>
    <label>Hot Swap Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Hotswap_Identification__c.field-meta.xml
<CustomField>
    <fullName>Hotswap_Identification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to Identify to update the HotSwap Flag after approving or rejecting the HotSwap</description>
    <label>Hotswap_Identification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <formula>if(Landed_Cost__c=0,0,
if(Approved_Price__c = 0,
((UnitPrice  -  Landed_Cost__c)/UnitPrice),
((Approved_Price__c - Landed_Cost__c)/Approved_Price__c )))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/QuoteUpdates.cls
public class QuoteUpdates {
    Map<Id, Quote> oldQuotes;
    Map<Id, Quote> newQuotes;
    
    
    public QuoteUpdates(
        Map<Id, Quote> oldTriggerQuotes,
        Map<Id, Quote> newTriggerQuotes) {
            oldQuotes = oldTriggerQuotes;
            newQuotes = newTriggerQuotes;
        }
    public  void inactivated()
    {
        system.debug('inacivated ');
        //if this is not an inactive sku, then do not run query and stop class
        
        Set<Id> oppids = new Set<Id>();
        
        for(Quote newq : newQuotes.values()){
            Quote oldq = oldquotes.get(newq.Id);
            system.debug('old '+oldq.Active__c );
            system.debug('new '+newq.Active__c );
            
            if(oldq.Active__c == true && newq.Active__c == false){
                oppids.add(newq.OpportunityId);
                
            }else{
                return;
            }
        }
        
        
        QuoteUpdates.oppActiveQuote(oppids);
        
        
        
        
    }
    
    //changes for hotswap process 07192019 by Prasad
    
    public static void updateHotSwapFlag(map<id,Quote> newmap,map<id,Quote> oldmap){
        set<id> quoteids = new set<id>();
        for(Quote qo:newmap.values()){
            if(qo.In_Approval_Review__c != oldmap.get(qo.id).In_Approval_Review__c && qo.In_Approval_Review__c != true){
                quoteids.add(qo.id);
            }
        }
       list<QuoteLineItem> lineItems = [select id,QuoteId,Hotswap_Identification__c,Hot_Swap_Flag__c from QuoteLineItem where QuoteId IN:quoteids and Hotswap_Identification__c = true ];
        system.debug('testt------------------>'+lineItems);
        for(QuoteLineItem qli:lineItems){
            if(newmap.containsKey(qli.QuoteId)){
                if(newmap.get(qli.QuoteId).Hot_Swap_Requested__c == true){
                    qli.Hotswap_Identification__c = false;
                    qli.Hot_Swap_Flag__c = true;
                }else{
                     qli.Hotswap_Identification__c = false;
                     qli.Hot_Swap_Flag__c = false;
                }
                
            }
            
        }
             system.debug('testt------------------>'+lineItems);
        update lineItems;
    }
    
    public static void updatequote(List<Quote> records)
    {
        //udpate pricebook if not done already
        system.debug('quotest to update '+records);
        User u = [Select id, firstname,email,lastname,managerid,manager.firstname from user where id =: UserInfo.getUserId()];
        Set<String> opps = new Set<String>();
        for(Quote q : records){
            //q.End_User_Account__c  = q.AccountId;
            opps.add(q.opportunityid);
        }
        
        List<Opportunity> oppsToUpdate = new List<Opportunity>();
        Map<String, Opportunity> ops = new Map<String,Opportunity>();
        for(Opportunity o : [Select ID,PriceBook2Id,Opportunity.End_User__c
                             from opportunity where id in: opps]){
                                 ops.put(o.Id, o);
                             }
        
        for(Quote q : records){
            if(ops.containsKey(q.OpportunityId)){
                Opportunity o = ops.get(q.OpportunityId);
                q.PriceBook2Id = o.PriceBook2Id;
                q.Status = 'Needs Review';
                q.Spa_Request_Submitter__c = UserInfo.getUserId();
                q.Requestor_Email__c = UserInfo.getUserEmail();
                q.End_User_Text__c = o.End_User__c;
                String subject = '';
                subject = 'Submission Request Received SPA : '+q.Spa_Name__c;
                String body = '';
                body += u.FirstName+ ',<br/><br/>' ;
                body += 'Your Submission has been sent to the bid desk and is set for review.<br/>thank you <br/><br/>';
                body += 'Notes: '+q.Notes__c +'<br/>';
                body += 'spa id: '+q.SpaId__c +'<br/><br/>';
                
                
                Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
                String[] to = new String[] {u.Email};            
                    //String[] cc = new String[] {Label.AdminEmail};
                    system.debug('subject');
                system.debug(subject);
                mail.setToAddresses(to);
                mail.setSubject(subject);
                mail.setHtmlBody(body);
                mail.setHtmlBody(body);
                //mail.setCcAddresses(cc);
                mail.setTargetObjectId(q.id);   
                mail.setSaveAsActivity(true);
                
                Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                //
                EmailMessage em = new EmailMessage ();
                em.Subject = 'Submission Request Received SPA : '+q.Spa_Name__c;
                em.ToAddress = u.email;
                em.TextBody = 'test ';
                
                //insert em;
                
                
                
                if(q.Spa_Request_Type__c == 'Bid Register Request'){
                    if( q.Business_Reason_for_Bid_Registration__c == null || q.Scope_of_Bid_Registration__c == null || q.List_of_Work_Activity_c__c == null){
                        q.addError('The fields Business Reason for Bid Registration, Scope of Bid Registration, and List of Work must have valid reasons and be filled out');
                    }else if( q.Business_Reason_for_Bid_Registration__c.length() < 6 || q.Scope_of_Bid_Registration__c.length() < 6 || q.List_of_Work_Activity_c__c.length() < 6){
                        q.addError('The fields Business Reason for Bid Registration, Scope of Bid Registration, and List of Work must have at least 6 Characters and must have valid reasons.');
                    }
                }
            }            
        }
        update oppsToUpdate;
    }
    
    public static void updatequotelines(List<Quote> records)
    {
        Set<String> opps = new Set<String>();
        for(Quote q : records){
            opps.add(q.opportunityid);
        }
        
        Map<String, Opportunity> oproducts = new Map<String,Opportunity>();        
        for(Opportunity ops : [Select ID,primary_quote__c ,(Select PricebookEntryId,Quantity,UnitPrice,PriceBookEntry.IsActive, Competitor_Name_del__c ,
                                                            Competitor_Price_del__c , Competitor_SKU__c , Notes__c, Margin__c   from OpportunityLineItems)
                               from opportunity where id in: opps]){
                                   oproducts.put(ops.Id, ops);
                               }
        Set<Id> quotes = new Set<Id>();
        
        
        List<Opportunity_Partner__c> parts = [Select Id,Quote__c from Opportunity_Partner__c where Opportunity__c in: opps];
        List<OpportunityTeamMember> team = [Select Id,Quote__c from OpportunityTeamMember where OpportunityId in: opps];
        
        List<QuoteLineItem> linesToAdd = new List<QuoteLineItem>();
        
        for(Quote q : records){
            if(oproducts.containsKey(q.OpportunityId) ){
                Opportunity o = oproducts.get(q.opportunityId);
                for(OpportunityLineItem p : o.OpportunityLineItems){
                    if(p.PriceBookEntry.Isactive == True && q.Bypass_Trigger__c != true){
                        QuoteLineItem ql = new QuoteLineItem(QuoteId = q.Id,
                                                             PricebookEntryId = p.PricebookEntryId,
                                                             Quantity = p.Quantity,
                                                             UnitPrice = p.UnitPrice,
                                                             Competitor_Name_del__c =  p.Competitor_Name_del__c,
                                                             Competitor_Price_del__c = p.Competitor_Price_del__c ,
                                                             Competitor_SKU__c = p.Competitor_SKU__c ,
                                                             Notes__c = p.Competitor_SKU__c,
                                                             MarginMultiEdit__c   = p.Margin__c,
                                                             Demo_System_Debug__c  ='From QuoteUpdates');
                        linesToAdd.add(ql);
                        quotes.add(q.Id);                        
                        
                    }
                }
                for(Opportunity_Partner__c p : parts){
                    p.Quote__c = q.Id;                    
                }
                for(OpportunityTeamMember t : team){
                    t.Quote__c = q.Id;                    
                }
            }   
        }
        if(linesToAdd.size()>0){
        try{
             insert linesToAdd;
        }catch(Exception e){
            String msg = e.getMessage();
            String zeromsg = '';
            if(msg.contains('zero')){
                zeromsg = 'Product(s) have a 0 Quantity or 0 Price. Please ensure all products have a non zero in quantity and price and then you can create the SPA ';
            }
            trigger.New[0].addError('Error! '+zeromsg+' Server Message is:  '+msg);
        }
        }
        update parts;
        update team;
        QuoteUpdates.oppQuoteInfo(quotes,trigger.isInsert);
        
        
    }
    public static void spateam(List<Quote> records){
        //not running acctTeam rules on quote creation because it locks records and we will monitor if the acctTeams 
        //should be reset more often. Current set up has bid desk clicking a button that updates the account team when it is not corrected. 
        //
        //note to self, there is a scheduled batch that updates account teams when there are new owners, this may need to be tweaked if account
        //teams are found to be incorrect more often than not
        //
        Boolean runrules = false;
        Set<Opportunity> oppset = new Set<Opportunity>();
        
        for(Quote q : records){
            Opportunity o = new Opportunity(Id = q.OpportunityId);
            oppset.add(o);
        }
        
        
        List<Opportunity> oppteams = new List<Opportunity>(oppset);
        OpportunityTeamAdd.teams(oppteams,runrules);
        system.debug(oppset);
        system.debug('op ids');
        system.debug(oppset.size());
        system.debug('Spa Team Class runing and runnig class opp team add');
        
    }
    public  void upquote()
    {
        //stop update triggers from running
        TriggerContextUtility.setFirstRunFalse();
        User u = [Select id, firstname,email,lastname,managerid,manager.firstname from user where id =: UserInfo.getUserId()];
        Set<String> opps = new Set<String>();
        Set<String> lines = new Set<String>();
        Set<Opportunity> oppset = new Set<Opportunity>();
        
        for(Quote q : newQuotes.values()){
            opps.add(q.OpportunityId);
            lines.add(q.Id);
        }
        
        
        
        
        //List<QuoteLineItem> ql = [Select Id,SPA_Expiration_Date__c ,Quote.ExpirationDate from QuoteLineItem where QuoteId in : lines];
        
        List<Opportunity> oppsToUpdate = new List<Opportunity>();
        
        //creating a list of opportunities to cross reference for open tasks
        Set<Id> oppsToTasks = new Set<Id>();
        
        
        Map<String, Opportunity> oppsUpdate = new Map<String, Opportunity>();
        for(Opportunity op : [Select Id,AccountId,OwnerId
                              from Opportunity where Id in : opps]){
                                  oppsUpdate.put(op.Id , op);
                              } 
        
        
        for(Quote q : newQuotes.values()){
            Quote old = oldQuotes.get(q.Id);
            Opportunity o = oppsUpdate.get(q.OpportunityId);
            
            if(q.status == 'Approved'){
                oppsToTasks.add(q.Opportunityid); 
                
            }
            
            if(q.Resubmission_Notes__c != old.Resubmission_Notes__c 
               && q.Resubmission_Notes__c != null && q.Resubmission_Notes__c != ''){
                   q.Status = 'Needs Review';
                   q.Resubmitter__c = UserInfo.getUserId();
                   q.Resubmitter_Email__c = UserInfo.getUserEmail();
                   String body = '';
                   body += u.FirstName+ ',<br/><br/>' ;
                   body += 'Your resubmission has been sent to the bid desk and is set for review.<br/>thank you <br/><br/>';
                   body += 'Resubmission Notes: '+q.Resubmission_Notes__c +'<br/>';
                   body += 'spa id: '+q.SpaId__c +'<br/><br/>';
                   
                   
                   Messaging.SingleEmailMessage mail=new Messaging.SingleEmailMessage();
                   String[] to = new String[] {u.Email};            
                       //String[] cc = new String[] {Label.AdminEmail};
                       mail.setToAddresses(to);
                   mail.setSubject('Resubmission Request Received SPA : '+q.Spa_Name__c);
                   mail.setHtmlBody(body);
                   //mail.setCcAddresses(cc);   
                   mail.setSaveAsActivity(true);           
                   Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
               }
            if(q.Resubmission_Notes__c != old.Resubmission_Notes__c 
               && q.Resubmission_Notes__c != null && q.Resubmission_Notes__c != '' & old.Status == 'Approved'){
                   q.Resubmission_Date__c = datetime.now(); 
               }
        }
       
       /*   
       for(QuoteLineItem q : ql){
            Quote newq =  newQuotes.get(q.QuoteId);
        }
        
        update ql;
       */
        
        List<Task> delayed = [Select id, whatid, status from task where whatid in : oppsToTasks and status != 'Completed'
                              and subject like '%SPA Delayed! Missing Data%'];
        
        for(Task t : delayed){ 
            t.status = 'Completed';           
        }
        update delayed;
    }
    @future
    public static void oppActiveQuote(Set<Id> oppids) {
        
        String oppid = '';
        for(Id o : oppids){
            oppid = o;
        }
        
        
        String quoteid = '';
        
        Opportunity opps = [Select id, primary_quote__c ,(Select id from quotes where active__c = true and First_Time_Buyer__c = false order by CreatedDate desc limit 1)
                            ,(Select id, Quote__c from Opportunity_Partners__r),(Select Id, Quote__c from OpportunityTeamMembers) from opportunity where id =: oppid limit 1];
        
        
        system.debug('opp querey results');
        system.debug(opps);
        List<Opportunity_Partner__c> partToUpdate = new List<Opportunity_Partner__c>();
        List<OpportunityTeamMember> TeamToUpdate = new List<OpportunityTeamMember>();
        
        if(opps.quotes.size() > 0){
            
            quoteid = opps.quotes[0].Id;
            opps.Primary_Quote__c = quoteid;
            for(OpportunityTeamMember t : opps.OpportunityTeamMembers){
                t.Quote__c = quoteid;
                TeamToUpdate.add(t);
            }
            for(Opportunity_Partner__c p : opps.Opportunity_Partners__r){
                p.Quote__c = quoteid; 
                partToUpdate.add(p); 
            }
        }
        system.debug('ran the lists to update');
        system.debug(opps);
        system.debug(partToUpdate);
        update opps;
        update partToUpdate;
        update TeamToUpdate;
        
    }
    @future
    public static void oppQuoteInfo(Set<Id> records,Boolean trg) {
        
        List<Quote> quotes = [Select Id, OpportunityId, Spa_Request_Type__c,Specialty_Spa__c  from quote where id in: records];
        
        //need the primary quote so Community members can request a resubmission. This is how they get the quote id
        //on the flow. Eventually, we need to put on lightning and give them access to resubmit the spa
        //directly outside of the opportunity
        
        
        //check if speciality spa before updating primary quote
        Set<Opportunity> opdedup = new Set<Opportunity>();
        for(Quote q : quotes){
            if(q.Specialty_Spa__c == null){
                Opportunity opp = New Opportunity(Id = q.OpportunityId, Primary_Quote__c = q.id );
                opdedup.add(opp);
            }else{
                Opportunity opp = New Opportunity(Id = q.OpportunityId );
                opdedup.add(opp);
            }
            
        }
        
        List<Opportunity> oppsToUpdate = new List<Opportunity>(opdedup);
        
        List<QuoteLineItem> qlines = [Select Id,Product2Id, Competitor_SKU__c,Notes__c,Competitor_Price_del__c,Competitor_Name_del__c,Quote.OpportunityId  from Quotelineitem where quote.opportunityid in : oppsToUpdate];
        
        
        
        //the following code add custom fields from opportunity line items to quote line items..this only needs to be done on creation, not on edit
        //passing the trigger context to avoid running on edit
        if(trg == true){
            Map<String, OpportunityLineItem> olines = new Map<String, OpportunityLineItem>();
            for(OpportunityLineItem o : [Select Id, Product2Id, OpportunityId,Competitor_Name_del__c ,Competitor_Price_del__c ,Competitor_SKU__c ,Notes__c from OpportunityLineItem where
                                         OpportunityId in: oppsToUpdate])
                olines.put(String.valueOf(o.product2Id)+String.valueOf(o.OpportunityId),o);
            for(QuoteLineItem q : qlines){
                if(olines.containsKey(String.valueOf(q.Product2Id)+String.valueOf(q.Quote.OpportunityId))){
                    OpportunityLineItem o = olines.get(String.valueOf(q.Product2Id)+String.valueOf(q.Quote.OpportunityId));
                    q.Competitor_Name_del__c = o.Competitor_Name_del__c;
                    q.Competitor_Price_del__c = o.Competitor_Price_del__c;
                    q.Competitor_SKU__c = o.Competitor_SKU__c;
                    q.Notes__c = o.Notes__c; 
                }            
            }
        }
        
        
        update qlines;
        update oppsToUpdate;
        
    }
}