force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>End_User_Company__c</formula>
    <inlineHelpText>For Reporting. Clean Column and dashboard look</inlineHelpText>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Spa_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Spa_Approval_Date__c</fullName>
    <label>Spa Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Approved_Price__c.field-meta.xml
<CustomField>
    <fullName>Approved_Price__c</fullName>
    <label>Approved Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SPA_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>SPA_Approval_Date__c</fullName>
    <label>SPA Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>Opportunity.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/StateSpaSync__c.field-meta.xml
<CustomField>
    <fullName>StateSpaSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>StateSpaSync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <formula>Quote.Opportunity.Account.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/IsStateSpa__c.field-meta.xml
<CustomField>
    <fullName>IsStateSpa__c</fullName>
    <defaultValue>false</defaultValue>
    <description>is used in State Spa Syncs. after insert, the spa will look at the opportunity product approval dates. If there is a date, the system will use that date, otherwise the date will be the day of insert</description>
    <label>IsStateSpa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>Disti List Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestSpaStateSyncwithOpps.cls
@isTest
private class TestSpaStateSyncwithOpps {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }

    public static String CRON_EXP = '0 0 0 15 3 ? 2022';

    static testmethod void testScheduledJob() {

        // Create some out of date Opportunity records
        // 
        Test.startTest();
        Product2 prodstate = new Product2(Name = 'statesyncApex Test', family = 'test family',List_Price__c=5.00, IsActive= true);
           insert prodstate;
        
        PriceBookEntry pbEntrys = new PriceBookEntry(
                UnitPrice = 300,
                PriceBook2Id = Test.getStandardPricebookId() ,
                Product2Id = prodstate.Id,
                IsActive = true);
        
        insert pbEntrys;
        
        Opportunity opp = [Select Id, Pricebook2Id,End_User__c,
                           (Select PricebookEntryId from OpportunityLineItems where pricebookentry.isactive = true) from opportunity
                            where Id in (Select Opportunityid from OpportunityLineItem where pricebookentry.isactive = true) limit 1];
        
        String pbe = '';
           
        for(OpportunityLineItem oline : opp.OpportunityLineItems){
                
                pbe = oline.PricebookentryId;
            }
        
         PriceBookEntry pbEntry = new PriceBookEntry(
                UnitPrice = 300,
                PriceBook2Id = opp.Pricebook2Id ,
                Product2Id = prodstate.Id,
                IsActive = true);
        
        insert pbEntry;
        
        Quote q = new Quote(OpportunityId = opp.Id,
                           name = 'Apex Test',
                           Pricebook2Id = opp.PriceBook2Id,
                           StateSpaSync__c  = true,
                           Status = 'Needs Review');
        insert q;
        
        List<QuoteLineItem> lines = new List<QuoteLineItem>();
        
        QuoteLineItem qstatesync = new QuoteLineItem(QuoteId = q.Id,
                                            Quantity = 3, 
                                            unitPrice = 300,
                                            pricebookentryId = pbe,
                                            IsStateSpa__c  = true,
                                            SPA_Approval_Date__c = date.today());
        lines.add(qstatesync);
        
        QuoteLineItem qstatesyncopp = new QuoteLineItem(QuoteId = q.Id,
                                            Quantity = 3, 
                                            unitPrice = 300,
                                            pricebookentryId = pbEntry.Id,
                                            IsStateSpa__c  = true,
                                            SPA_Approval_Date__c = date.today());
        
        lines.add(qstatesyncopp);
        
        insert lines;
        
        TriggerContextUtility.setFirstRunTrue();
        
        for(QuoteLineItem l : lines){
            l.SPA_Approval_Date__c = date.today() -22;
            l.Approved_Price__c = 100;
        }       
        
        
        update lines;
        
        
        // Schedule the test job
        String jobId = System.schedule('ScheduledApexTest',
            CRON_EXP, 
            new SpaStateSyncwithOpps());
        Test.stopTest();

    }
}