force-app/main/default/objects/Opportunity/fields/Manager_Note__c.field-meta.xml
<CustomField>
    <fullName>Manager_Note__c</fullName>
    <label>Manager Note</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Notes__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Notes__c</fullName>
    <description>Sales Rep can enter notes to set up reminders and situation on the the opportunity</description>
    <inlineHelpText>Sales Rep can enter notes to set up reminders and situation on the the opportunity</inlineHelpText>
    <label>Opportunity Notes</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_or_Site_Information__c.field-meta.xml
<CustomField>
    <fullName>Project_or_Site_Information__c</fullName>
    <inlineHelpText>Adds Project Name or Site information to Opportunity Name</inlineHelpText>
    <label>Project or Site Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resellers_and_Type__c.field-meta.xml
<CustomField>
    <fullName>Resellers_and_Type__c</fullName>
    <description>Updated by flow</description>
    <label>Resellers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Ship_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Out_Date__c</fullName>
    <label>Ship Out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Spa_ID__c.field-meta.xml
<CustomField>
    <fullName>Spa_ID__c</fullName>
    <description>Used for informatica task that matches spa price with spa  claim</description>
    <formula>Opportunity.SPA_ID__c</formula>
    <label>Spa ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Interest&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Quote Request</fullName>
            </value>
            <value>
                <fullName>Agreed to Purchase</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Decided not to buy</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product Manager object. easily update any changes to product line</description>
    <label>Product Pillar</label>
    <referenceTo>Product_Manager__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Product_Manager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Manager__c.field-meta.xml
<CustomField>
    <fullName>Product_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Manager__c/Product_Manager__c.object-meta.xml
<CustomObject>
    <description>Delete this object but need to update classes that reference it</description>
    <label>Product Pillar</label>
    <nameField>
        <label>Product Pillar</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Pillars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Manager__c/fields/Product_Manager__c.field-meta.xml
<CustomField>
    <fullName>Product_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Product_Manager</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SpaSearch.cls
public class SpaSearch {
    @AuraEnabled
     public static User getUser()
    {     
         Id userId = UserInfo.getUserId();
        
         return [SELECT Name,Country FROM User WHERE Id = :userId];
    }    
    @AuraEnabled
    public static List<Opportunity> getSpas(String product,String reseller,String enduser,
                                            String industry,String ofields,String pfields,
                                           String family, String spaid)
    {     
     
        String prodsearch = '%'+product+'%';
        if(reseller == null || reseller == ''){
            reseller='%%';
        }else{
            reseller =  '%'+reseller+'%';
        }
         if(product == null || product == ''){
            product='%%';
        }else{
            product =  '%'+product+'%';
        }
        
        if(enduser == null || enduser == ''){
            enduser='%%';
        }else{
            enduser =  '%'+enduser+'%';
        }
        if(industry  == null || industry == '' || industry =='--None--'){
            industry='%%';
        }else{
            industry =  '%'+industry+'%';
        }
        if(family  == null || family == '' || family =='--None--'){
            family='%%';
        }else{
            family =  '%'+family+'%';
        }
        if(spaid  == null || spaid == '' || spaid =='--None--'){
            spaid='%%';
        }else{
            spaid =  '%'+spaid+'%';
        }

        
       List<OpportunityLineItem> opps = [Select ProductCode,OpportunityId,Opportunity.Account.Name,Opportunity.StageName,name
             ,quantity,ServiceDate,unitprice,product2id,product2.name,opportunity.name,opportunity.Opportunity_Notes__c,
             opportunity.Project_or_Site_Information__c,opportunity.Manager_Note__c,opportunity.Resellers_and_Type__c,Ship_Out_Date__c,status__c 
             from OpportunityLineItem
             where
             Opportunity.OwnerId = : UserInfo.getUserId() AND
             Product2.Name Like :product AND
             Opportunity.SPA_ID__c Like :spaid AND                            
             Opportunity.Account.Industry Like :industry AND                           
             Opportunity.Name Like :enduser AND
             Product2.Product_Line__r.Name Like :family AND                            
             (Opportunity.Resellers_and_Type__c Like  : reseller OR Opportunity.Resellers_and_Type__c = null)
             Order By  OpportunityId desc  NULLS last limit 150];
        
        Set<String> oppids = new Set<String>();
            for (OpportunityLineItem oline : opps) oppids.add(oline.opportunityId);
        
        
         List<Opportunity> spasToReturn = Database.query('Select '+ofields+',(Select '+pfields+                                             
                      ' from OpportunityLineItems) from opportunity where ID in: oppids '+
                       'and Spa_Stage__c != null limit 25');
        
        
         return spasToReturn;
    }
    @AuraEnabled
   public static List<Opportunity> updateopps(List<Opportunity> opps,String product){  
    
        //save the opportuntiy and line items in collections after clicking on save
     
       String  errormessages = '';
       Integer numerrors = 0;
       Integer numsuccess = 0;
       Integer numopps = 1;
        
        List<Database.SaveResult> updateResults = Database.update(opps, false);
                for(Integer i=0;i<updateResults.size();i++){
                    if (updateResults.get(i).isSuccess()){
                        updateResults.get(i).getId();
                        //system.debug('success id '+ opps.get(i).Name);
                        numsuccess += 1;
                
                    }else if (!updateResults.get(i).isSuccess()){
                        // DML operation failed
                        Database.Error error = updateResults.get(i).getErrors().get(0);
                        String failedDML = error.getMessage();
                        opps.get(i);//failed record from the list
                        //system.debug('Failed ID '+opps.get(i).Name);
                        system.debug('Message '+ failedDML);
                        numerrors += 1;
                     }
                }
        
       system.debug('number of errors '+numerrors+ ' successes '+numsuccess);
       
       return opps;
 } 
    @AuraEnabled
    public static List<String> getStatus()  
  {
        List<String> options = new List<String>();
        options.add('--None--');
        Schema.DescribeFieldResult fieldResult = OpportunityLineItem.Status__c.getDescribe();
    
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getValue());
        } 
        system.debug('options');      
       
      return options;
    }
     @AuraEnabled
    public static List<String> getProdTypes()  
  {
        List<String> options = new List<String>();
        options.add('--None--');
        
        List<Product_Manager__c> pillars = [Select Id, Name from Product_Manager__c];
    
        for (Product_Manager__c p: pillars) {
            options.add(p.name);
        } 
        system.debug('options');      
       
      return options;
    }
     @AuraEnabled
    public static List<String> getIndustries()  
  {
        List<String> options = new List<String>();
        options.add('--None--');
        Schema.DescribeFieldResult fieldResult = Account.Industry.getDescribe();
    
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
        for (Schema.PicklistEntry f: ple) {
            options.add(f.getValue());
        } 
        system.debug('options');      
       
      return options;
    }

}