force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_Resellers__c.field-meta.xml
<CustomField>
    <fullName>SPA_Resellers__c</fullName>
    <label>SPA Resellers</label>
    <summaryFilterItems>
        <field>Opportunity_Partner__c.Partner_Type__c</field>
        <operation>equals</operation>
        <value>Reseller / VAR</value>
    </summaryFilterItems>
    <summaryForeignKey>Opportunity_Partner__c.Opportunity__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <inlineHelpText>Select the type of Partner</inlineHelpText>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Reseller / VAR</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Business_Reason_for_Bid_Registration__c.field-meta.xml
<CustomField>
    <fullName>Business_Reason_for_Bid_Registration__c</fullName>
    <label>BR Business Reason</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/List_of_Work_Activity_c__c.field-meta.xml
<CustomField>
    <fullName>List_of_Work_Activity_c__c</fullName>
    <label>BR List of Work</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Partner</label>
    <referenceTo>Opportunity_Partner__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Scope_of_Bid_Registration__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Bid_Registration__c</fullName>
    <label>BR Scope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Spa_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Spa_Request_Type__c</fullName>
    <defaultValue>&quot;Spa Request&quot;</defaultValue>
    <label>Spa Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spa Request</fullName>
            </value>
            <value>
                <fullName>Bid Register Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestMasterOppPartner.cls
@IsTest
public class TestMasterOppPartner  {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    Static testmethod void MasterOppInsert() {
        TriggerContextUtility.setFirstRunFalse();    
        
        
        Test.startTest();
        Opportunity opp = [Select id, AccountId, name,(Select id, name , Spa_Request_Type__c  from quotes)
         from Opportunity where SPA_Resellers__c = 1 and
        id in (select OpportunityId from Quote) limit 1];
        
       
        
        Opportunity_Partner__c op = new Opportunity_Partner__c();
        op.Partner_Account__c = opp.AccountId;
        op.Partner_Type__c = 'Reseller / VAR';
        op.Opportunity__c = opp.Id;
        
        Boolean validationError1 = false;
        Boolean validationError2 = false;
        
        try{
            insert op;
        }catch(Exception e){
			system.debug('there was an error '+e);
            validationError1 = true;
            
        }
         delete op;
         Quote q = new Quote (id = opp.Quotes[0].Id,
                            Spa_Request_Type__c = 'Bid Register Request',
                             Business_Reason_for_Bid_Registration__c = 'blah blah blah test'  ,
                            Scope_of_Bid_Registration__c = 'blah blah blah test', 
                            List_of_Work_Activity_c__c = 'blah blah blah test');
        update q;
        
        try{
            insert op;
        }catch(Exception e){
			system.debug('there was an error '+e);
            validationError2 = true;
            
        } 
        
        Test.stoptest();
        
        system.assertEquals(validationError1, false);
        system.assertEquals(validationError2, true);
    }
    Static testmethod void partnerupdate() {
        test.startTest();
        Opportunity_Partner__c part = [Select Id,Partner_Account__c from 
                                      Opportunity_Partner__c limit 1];
        Account a = [Select id from account limit 1];
        TriggerContextUtility.setFirstRunTrue();
        part.Partner_Account__c = a.Id;
        update part;
        
        
        test.stopTest();
        
    }
    
    Static testmethod void partnerdelete() {
        test.startTest();
        Opportunity_Partner__c part = [Select Id,Partner_Account__c from 
                                      Opportunity_Partner__c where Partner_Type__c = 'Reseller / VAR'  limit 1 ];
        //TriggerContextUtility.setFirstRunTrue();
        delete part;
        
        
        test.stopTest();
        
    }
    

}