force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reseller_Names__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Names__c</fullName>
    <label>Partner Names</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resellers__c.field-meta.xml
<CustomField>
    <fullName>Resellers__c</fullName>
    <description>Field is used for Wave Pipeline to search for Resellers.</description>
    <label>Resellers</label>
    <length>8000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resellers_and_Type__c.field-meta.xml
<CustomField>
    <fullName>Resellers_and_Type__c</fullName>
    <description>Updated by flow</description>
    <label>Resellers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <inlineHelpText>Select the type of Partner</inlineHelpText>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Reseller / VAR</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Quote.Specialty_Spa__c</field>
            <operation>notEqual</operation>
            <value>FTB, Demo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/BR_Resellers_OverRide__c.field-meta.xml
<CustomField>
    <fullName>BR_Resellers_OverRide__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Allows multiple resellers to be on BR</description>
    <inlineHelpText>Allows multiple resellers to be on BR</inlineHelpText>
    <label>BR Resellers OverRide</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Partner</label>
    <referenceTo>Opportunity_Partner__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Resellers__c.field-meta.xml
<CustomField>
    <fullName>Resellers__c</fullName>
    <formula>Opportunity.Resellers_and_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Resellers</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Spa_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Spa_Request_Type__c</fullName>
    <defaultValue>&quot;Spa Request&quot;</defaultValue>
    <label>Spa Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spa Request</fullName>
            </value>
            <value>
                <fullName>Bid Register Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppPartnersMasterClass.cls
public class OppPartnersMasterClass{
    Map<Id, Opportunity_Partner__c> oldOpps;
    Map<Id, Opportunity_Partner__c> newOpps;
    public OppPartnersMasterClass(
        Map<Id, Opportunity_Partner__c> oldTriggerOpps, 
        Map<Id, Opportunity_Partner__c> newTriggerOpps) {
            oldOpps = oldTriggerOpps;
            newOpps = newTriggerOpps;
        }
    
    public static void partnerCreatedBRCheck(List<Opportunity_Partner__c> records) {
        List<String> oppIds = new List<String>();
        for(Opportunity_Partner__c p : records){
        oppIds.add(p.Opportunity__c);
            
        }
        Map<String, Opportunity> oppsBRd = new Map<String,Opportunity>();
        for(Opportunity o : [Select id from opportunity where id in : oppIds and 
                            id in (Select opportunityId from Quote 
                                   where Spa_Request_Type__c = 'Bid Register Request'
                                   and BR_Resellers_OverRide__c  = false)]){
                                       oppsBRd.put(o.Id,o);
                                   }
        
        for(Opportunity_Partner__c p : records){
        //check if partner related to spa that is br'd
            if(oppsBrd.containsKey(p.opportunity__c)&& p.Partner_Type__c == 'Reseller / VAR'){
                //show error
                p.addError('There is a Bid Registered Spa. Only bid desk can add Resellers and must explicitly override this validation rule. '+
                                'This Message is from OppPartnersMasterClass and MasterOppPartnerTrigger.',false);
            }
            
        }
        
        
    }
    
    public void partnerChange() {
        
        //making sure the future class is only run on insert or delete of opportunity records
        //and only for resellers, not distributors. This will prevent the future to run when it is not needed.
        Set<Id> oppids = new Set<Id>();
        
        if(trigger.isInsert){
            for(Opportunity_Partner__c p : newOpps.values()){
                if(p.Partner_Type__c == 'Reseller / VAR'){
                    oppids.add(p.opportunity__c);                    
                }
                system.debug('size new opps '+newOpps.size());
            }
        }else if(trigger.isDelete){
            for(Opportunity_Partner__c p : oldOpps.values()){
                if(p.Partner_Type__c == 'Reseller / VAR'){
                    oppids.add(p.opportunity__c);                    
                }
                system.debug('size old opps '+oldOpps.size());
            }
        }
        
        if(oppids.size()>0){
            OppPartnersMasterClass.oppResellers(oppids);
        }
    }
    
    
    @future
    public static void oppResellers(Set<Id>oppids) { 
        //need to update the list of opportunity resellers on the field of opportunity
        //this is to have one long text field that can be filtered in Einstein analytics
        //by reseller.
        
        List<Opportunity> parts = [Select id,Resellers__c,Resellers_and_Type__c,Reseller_Names__c,( select id,opportunity__c,Partner_Type__c,partner_account__r.name
                                                                                                   from Opportunity_Partners__r where opportunity__c in: oppids and Partner_Type__c  = 'Reseller / VAR')
                                   from opportunity where id in : oppids for update];
        
        for(Opportunity o : parts){
            String partnames = '';
            String names = '';
            String res = '';
            
            for(Opportunity_Partner__c p : o.Opportunity_Partners__r){
                if(partnames == ''){
                    if(p.Partner_Type__c  == 'Reseller / VAR'){
                        res = p.partner_account__r.name;
                    }
                    
                    partnames = p.partner_account__c;
                    names =    p.partner_account__r.name;
                }else{
                    if(p.Partner_Type__c  == 'Reseller / VAR'){
                        res = res+'/'+p.partner_account__r.name;
                    }
                    partnames = partnames+'/'+p.partner_account__c;
                    names = names+'/'+p.partner_account__r.name;
                }
                
            }
            o.Resellers__c = partnames;
            o.Reseller_Names__c = names;
            o.Resellers_and_Type__c =  res.left(250);
        }
        try{update parts;}catch(Exception e){String t = 'Opportunity Reseller Names Update Error for id '+ parts[0].Id;AdminErrorMessage.SendError(e, t);}
    }
    
}