force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/resellerSpaEmailAlertTest.cls
@isTest(SeeAllData=true)
public class resellerSpaEmailAlertTest {
	
    @isTest
    public static void testEmail(){
      //  Account a = new Account(name='Neils fun acc', Industry='NeilsIndo', BillingCity='TestCityIndo', BillingCountry='United States', BillingState='California', Website='www.neilstesting.com');
     //   BuildTestData.addRecords();
     //   insert a;
  //      Opportunity o = new Opportunity(name='Test opp', StageName='Open', AccountId=a.id, CloseDate=Date.today());
   //    insert o;
      Opportunity_Partner__c op = new Opportunity_Partner__c(Partner_Account__c=[select id from Account LIMIT 1].id, Opportunity__c=[select id from Opportunity LIMIT 1].id);
       insert op;
        resellerSpaEmailAlert.sendNotification(new List<String>{op.id});
    }
 
}