force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <description>Name of contact at the Reseller, End User, or Distributor</description>
    <inlineHelpText>Name of contact at the Reseller, End User, or Distributor</inlineHelpText>
    <label>Contact Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <inlineHelpText>Select the type of Partner</inlineHelpText>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Reseller / VAR</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Quote.Specialty_Spa__c</field>
            <operation>notEqual</operation>
            <value>FTB, Demo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Reseller_Contact__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/ResellerSpaEmail__c.field-meta.xml
<CustomField>
    <fullName>ResellerSpaEmail__c</fullName>
    <description>This field is filled out during the Spa Approval Email process and will put email address of the current requestor of the email</description>
    <label>ResellerSpa Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/OpportunityTeamMember/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Custom</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Team</relationshipLabel>
    <relationshipName>Opportunity_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityTeamMember/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Quote.Specialty_Spa__c</field>
            <operation>notEqual</operation>
            <value>FTB, Demo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunity Team</relationshipLabel>
    <relationshipName>Opportunity_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Partner</label>
    <referenceTo>Opportunity_Partner__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityPartners.cls
public class OpportunityPartners {
    @AuraEnabled
    public static List<Opportunity_Partner__c> getOppLInes(String oppid){
        system.debug('partners op id '+ oppid);
        // without an ID, simply specify the object to then derive the sobject type		
        
        DescribeSObjectResult describeResult = Opportunity_Partner__c.getSObjectType().getDescribe();
        
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
        
        String query =		  ' SELECT ' +		      String.join( fieldNames, ',' ) +		  ', Partner_Account__r.Name,Reseller_Contact__r.Name  FROM '
            +		      describeResult.getName()	+
            ' WHERE Opportunity__c = : oppid or quote__c =: oppid  or partner_account__c = : oppid order by Partner_Type__c desc'	;		
        // return generic list of sobjects or typecast to expected type
        List<SObject> records = Database.query( query );
        Id opportunityId = [select OpportunityId from Quote where id=:oppid].OpportunityId;
       
      //  List<OpportunityContactRole> ocrs = [select Role, ContactId, OpportunityId, Contact.Name, Contact.Email, Contact.AccountId from OpportunityContactRole where OpportunityId=:opportunityId and role='End User Contact'];
    //    List<OpportunityTeamMember> otms = [select name, User.Email from OpportunityTeamMember where OpportunityId=:opportunityId];
        Set<String> emails = new Set<String>();
        for(SObject record: records){
            emails.add((String)record.get('ResellerSpaEmail__c'));
        }
      /*  for(OpportunityTeamMember otm: otms){
            Opportunity_Partner__c op = new Opportunity_Partner__c(Partner_Type__c='Opportunity Team Member');
            op.Contact_Name__c = otm.Name;
            op.Partner_Account__c = [select id from Account where name='ViewSonic Corporation' limit 1].id;
            op.ResellerSpaEmail__c = otm.User.Email;
            op.Quote__c=oppid;
            op.Opportunity__c=opportunityId;
            if(!emails.contains(op.ResellerSpaEmail__c)){
                insert op;
                records.add(op);
            } 

        }*/
  /*      for(OpportunityContactRole oc: ocrs){
            Opportunity_Partner__c op = new Opportunity_Partner__c(Partner_Type__c='End User Contact'); 
            System.debug(oc);
            op.Reseller_Contact__c=oc.ContactId;
            op.Partner_Account__c=oc.Contact.AccountId;
            op.ResellerSpaEmail__c=oc.Contact.Email;
            op.Quote__c=oppid;
            op.Opportunity__c=opportunityId;
            if(!emails.contains(op.ResellerSpaEmail__c)){
                insert op;
                records.add(op);
            } 
        }*/
        System.debug( records );
        //[SELECT Id,Opportunity__c,Partner_Account__r.Name,Partner_Type__c,Reseller_Contact__c
               // FROM Opportunity_Partner__c
                //WHERE Opportunity__c = :oppid order by Partner_Type__c desc]; 
        
        return records;
    }
    @AuraEnabled
    public static List<Opportunity_Partner__c> deleteOppLines(List<Opportunity_Partner__c> dpartners, String oppid){
        system.debug('prods ' +dpartners);
        
        
        system.debug(dpartners);
        delete  dpartners;
        return [SELECT Id,Opportunity__c,Partner_Account__r.Name,Partner_Type__c,Reseller_Contact__c
                FROM Opportunity_Partner__c
                WHERE Opportunity__c = :oppid order by Partner_Type__c desc];        
        
    }
    @AuraEnabled
    public static List<Opportunity_Partner__c> updatePartners(List<Opportunity_Partner__c> uppartners, String oppid){
        
        update uppartners;
        system.debug(uppartners);
        return [SELECT Id,Opportunity__c,Partner_Account__r.Name,Partner_Type__c,Reseller_Contact__c
                FROM Opportunity_Partner__c
                WHERE Opportunity__c = :oppid order by Partner_Type__c desc];
        
        
    }
}