force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Order/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Named_Location_of_Training__c.field-meta.xml
<CustomField>
    <fullName>Named_Location_of_Training__c</fullName>
    <label>Training Location (School or Company)</label>
    <length>200</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Objective_1__c.field-meta.xml
<CustomField>
    <fullName>Objective_1__c</fullName>
    <label>Objective 1</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/SpaNumber__c.field-meta.xml
<CustomField>
    <fullName>SpaNumber__c</fullName>
    <label>SpaNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/testOrderMasterTrigger.cls
@isTest
private class testOrderMasterTrigger{
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void orderTrigger() {        
        test.startTest();
        Opportunity opp = [Select id , spa_Id__c from opportunity limit 1];
        
        Quote q1 = new Quote();
        q1.OpportunityId = opp.Id;
        q1.Name = opp.spa_Id__c;
        insert q1;
        
        Quote q = [Select id,OpportunityId,AccountId,Name from Quote where id =: q1.Id limit 1];   
        
        Account a = [Select id from account where id = : q.AccountId limit 1];
        system.debug('Quote info '+q.Name +' '+q.OpportunityId+' '+q.AccountId);
        Order o = new Order();
        o.Status = 'Draft';
        o.Contact_Name__c = 'john';
        o.Named_Location_of_Training__c  = 'testing';
        o.AccountId = a.Id;
        o.EffectiveDate = date.today();
        o.SpaNumber__c = q.Name;
        insert o;
        
        
        
        Order ordTest = [Select id, opportunity__c,AccountId,SpaNumber__c,quoteid, Objective_1__c   from Order where id = : o.Id limit 1];
        Id qt = ordTest.quoteid;
        
        ordTest.quoteid = null;
        update ordTest;
        TriggerContextUtility.setFirstRunTrue(); 
        ordTest.quoteid = qt;
        update ordTest;
        
        
        test.stopTest();
       
        system.debug('test acct id, opp id , spa name '+ordTest.SpaNumber__c+' '+ordTest.Opportunity__c+ ' '+ordTest.AccountId);
        system.assertEquals(q.AccountId, ordTest.AccountId);
        system.assertEquals(q.OpportunityId, ordTest.opportunity__c );
        
    }
}