force-app/main/default/objects/Opportunity/fields/Record_is_Locked__c.field-meta.xml
<CustomField>
    <fullName>Record_is_Locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Record is Locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Quote/fields/record_is_locked__c.field-meta.xml
<CustomField>
    <fullName>record_is_locked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>record is locked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Spa_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Spa_Request_Type__c</fullName>
    <defaultValue>&quot;Spa Request&quot;</defaultValue>
    <label>Spa Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spa Request</fullName>
            </value>
            <value>
                <fullName>Bid Register Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AnyRecordUnlockCMPControllerTest.cls
@isTest 
public class AnyRecordUnlockCMPControllerTest {
    @testSetup
    public static void createdata ()
    {
        BuildTestData.AddRecords();
        
    }
    
    static testMethod void getUpdatedRecordTest() { 
        test.startTest();
        opportunity opp=[select id,spa_id__c from opportunity limit 1];
        quote q=new quote(opportunityId=opp.id,
                          spa_Request_type__c='Spa Request',
                          name='apex test');
        
        insert q;
        AnyRecordUnlockCMPController.getUnclockRecord(q.id);
        
        Quote q1 = [select id,record_is_locked__c from Quote where id =:q.id];
        test.stopTest();
        system.assertEquals(false, q.record_is_locked__c);
        
        
    }
    
    
    
}