force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Spa_ID__c.field-meta.xml
<CustomField>
    <fullName>Spa_ID__c</fullName>
    <description>Used for informatica task that matches spa price with spa  claim</description>
    <formula>Opportunity.SPA_ID__c</formula>
    <label>Spa ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Spa_Stage__c.field-meta.xml
<CustomField>
    <fullName>Spa_Stage__c</fullName>
    <formula>&quot;&quot;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Spa Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestMasterOppProduct.cls
@IsTest
public class TestMasterOppProduct  {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    
    Static testmethod void MasterOppProductInsert() {
        
        //Opportunity o = [Select Id,Pricebook2Id,SPA_ID__c from Opportunity where Spa_Stage__c != null limit 1];
        
        //Quote q = new Quote(OpportunityId = o.id,Pricebook2Id=o.pricebook2id,name = o.SPA_ID__c);
        //insert q;
        
        //OpportunityLineItem op = new OpportunityLineItem(OpportunityId = o.id,
                                                         //Quantity = 5,
                                                        //UnitPrice =30,
                                                        //Pricebookentryid = [Select Id from Pricebookentry where
                                                                           //isactive = true and Pricebook2id =: o.Pricebook2id limit 1].id);
        test.startTest();
        //insert op;
        test.stopTest();
        
        
    }
}