force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Business_Reason_for_Bid_Registration__c.field-meta.xml
<CustomField>
    <fullName>Business_Reason_for_Bid_Registration__c</fullName>
    <label>BR Business Reason</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/List_of_Work_Activity_c__c.field-meta.xml
<CustomField>
    <fullName>List_of_Work_Activity_c__c</fullName>
    <label>BR List of Work</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>CASESAFEID(OpportunityId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Scope_of_Bid_Registration__c.field-meta.xml
<CustomField>
    <fullName>Scope_of_Bid_Registration__c</fullName>
    <label>BR Scope</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Spa_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Spa_Request_Type__c</fullName>
    <defaultValue>&quot;Spa Request&quot;</defaultValue>
    <label>Spa Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spa Request</fullName>
            </value>
            <value>
                <fullName>Bid Register Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateSpaControllerTest.cls
@isTest 
public class UpdateSpaControllerTest {
     @testSetup
    public static void createdata ()
    {
        BuildTestData.AddRecords();
        
    }
    static testMethod void getUpdatedRecordTest() { 
        test.startTest();
        //Quote q=[select id from Quote where spa_Request_type__c ='Spa Request' limit 1];
     opportunity opp=[select id,spa_id__c from opportunity limit 1];
        quote q=new quote(opportunityId=opp.id,
                         spa_Request_type__c='Spa Request',
                         name='apex test');
        
        insert q;
        
        
        String currentRecord=q.id;
        String WorkActivity='testworkactivittyjlkfj';
        String ScopeOfBidRegistration='test workactiv itt yjlkfj';
        String BusinessReasonforBidRegistration='test workactiv itt yjlkfj';
        
        UpdateSpaController.getQuoteDetails(currentRecord);
        UpdateSpaController.getUpdatedRecord(currentRecord, WorkActivity, ScopeOfBidRegistration, BusinessReasonforBidRegistration);  
        
        //WorkActivity='';
        
        //UpdateSpaController.getUpdatedRecord(currentRecord, WorkActivity, ScopeOfBidRegistration, BusinessReasonforBidRegistration);
        //
       // Quote q1=[select id, Locked from Quote where id=:q.id limit 1];
        test.stopTest();
        
        /*   createdata ();
Quote testingquote = [select id,Spa_Request_Type__c,Business_Reason_for_Bid_Registration__c,OpportunityId__c,Scope_of_Bid_Registration__c, List_of_Work_Activity_c__c  from Quote where name='apext test'];
UpdateSpaController.getUpdatedRecord(testingquote.id,'WorkActivity', 'ScopeOfBidRegistrationtest', 'BusinessReasonforBidRegistrationtesssss');*/
    }   
    
}