force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Quote/fields/SpaId__c.field-meta.xml
<CustomField>
    <fullName>SpaId__c</fullName>
    <formula>Opportunity.SPA_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SpaId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/VSA_Open_Order__c.object-meta.xml
<CustomObject>
    <label>VSA_Open_Orders</label>
    <nameField>
        <label>VSA_Open_Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>VSA_Open_Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VSA_Open_Order__c/fields/Packing_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Packing_Instructions__c</fullName>
    <label>Packing Instructions</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/PO_Number__c.field-meta.xml
<CustomField>
    <fullName>PO_Number__c</fullName>
    <label>PO Number</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Ship_State__c.field-meta.xml
<CustomField>
    <fullName>Ship_State__c</fullName>
    <label>Ship State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Ship_to_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Address_2__c</fullName>
    <label>Ship to Address 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Ship_to_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Instructions__c</fullName>
    <label>Ship to Instructions</label>
    <length>13000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Ship_to_Name__c.field-meta.xml
<CustomField>
    <fullName>Ship_to_Name__c</fullName>
    <label>Ship to Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Ship_Zip__c.field-meta.xml
<CustomField>
    <fullName>Ship_Zip__c</fullName>
    <label>Ship Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/Spa_Number__c.field-meta.xml
<CustomField>
    <fullName>Spa_Number__c</fullName>
    <label>Spa Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VSA_Open_Order__c/fields/SpaId__c.field-meta.xml
<CustomField>
    <fullName>SpaId__c</fullName>
    <formula>substitute(
substitute(
 substitute( 
substitute( 
substitute(Spa_Number__c,&quot; &quot;,&quot;&quot;)
,&quot;BR&quot;,&quot;&quot;)
,&quot;ACC&quot;,&quot;&quot;)
,&quot;/&quot;,&quot;&quot;)
,&quot;FTZ&quot;,&quot;&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SpaId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/getAccountsConsSpa.cls
public without sharing class getAccountsConsSpa {
    //12.9.19 notes added 2 methods. Intead of returning string, returning entire
    //object of vsaopen orders so we can get the entire object in case we need to get more 
    //data. 
    //
    //added opportunityid as a method so we can use opportunity related components on different pages
    //
    //
    @AuraEnabled
    public static Account getAccount(String spaid){
        Account a = [Select id, name, industry, Type, owner.name, billingstate
                    from account where id in (Select AccountId from Quote where 
                                             Name = : spaid or Opportunity.Spa_Id__c = : spaid)];
        return a;        
    }
    @AuraEnabled
    public static List<Sobject> getAccountPO(String ponumber){
        List<sObject> retObjects = new List<sObject>();
        
        DescribeSObjectResult describeResult = VSA_Open_Order__c.getSObjectType().getDescribe();
        
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
        
        String query =		  ' SELECT ' +		      String.join( fieldNames, ',' ) +	  ' FROM '
            +		      describeResult.getName()	+' WHERE PO_Number__c  = : ponumber ';		
        // return generic list of sobjects or typecast to expected type
        
        List<VSA_Open_Order__c> records = Database.query( query );	
        
        VSA_Open_Order__c oo = records[0];
        
        /*
        VSA_Open_Order__c oo = [Select Ship_to_Instructions__c ,Packing_Instructions__c , Spa_Number__c ,status__c, Product__c,
                                 Ship_to_Address_2__c ,Ship_to_Name__c ,Ship_Zip__c ,SpaId__c, Ship_State__c 
                                from VSA_Open_Order__c  where 
                                             PO_Number__c  = : ponumber limit 1];
      */
        
        retObjects.add(oo);
        
        Account a = new Account();
        Opportunity opp = new Opportunity();
        
        try{
            a = [Select id, name, industry, Type, owner.name, billingstate,
                     (select id, firstname,lastname, phone,email, Title,Marketing_Post_Sales__c,
                              Account.Name,MailingState,Account.Parent.Name from contacts) 
                    from account where id in (Select AccountId  from Quote where name = : oo.Spa_Number__c)];
            
        }catch(exception e){
            a = null;
        }
        
         
        
        retObjects.add(a);
        
        
        try{
            opp = [Select Id,name,createddate,closedate,account.name,opportunity.owner.name
                         from opportunity where id in (Select opportunityId from Quote where name = : oo.Spa_Number__c) limit 1 ];
        
            
        }catch(exception e){
            opp = null;
        }
        
        
        retObjects.add(opp);
        
        return retObjects;
        
    }
     @AuraEnabled
    public static VSA_Open_Order__c getShippingInstPackingInst(String ponumber){
        VSA_Open_Order__c a = [Select Ship_to_Instructions__c ,Packing_Instructions__c , Spa_Number__c ,status__c, Product__c 
                               from VSA_Open_Order__c  where 
                                             PO_Number__c  = : ponumber limit 1];
        
        return a;
    }
        

         @AuraEnabled
    public static Opportunity getOpportunity(String ponumber){
        
        VSA_Open_Order__c oo = [Select Spa_Number__c   from VSA_Open_Order__c  where 
                                             PO_Number__c  = : ponumber limit 1];
        
        Opportunity a = [Select Id,name,createddate,closedate,account.name,opportunity.owner.name
                         from opportunity where id in (Select opportunityId from Quote where name = : oo.Spa_Number__c) limit 1 ];
        
        return a;
    }
    
    @AuraEnabled
    public static String getShippingInst(String ponumber){
        String ship = '';
        VSA_Open_Order__c a = [Select Ship_to_Instructions__c , Spa_Number__c ,status__c  from VSA_Open_Order__c  where 
                                             PO_Number__c  = : ponumber limit 1];
        ship = a.Ship_to_Instructions__c;
        return ship;
        
    }
}