force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Spa_Request_Type__c.field-meta.xml
<CustomField>
    <fullName>Spa_Request_Type__c</fullName>
    <defaultValue>&quot;Spa Request&quot;</defaultValue>
    <label>Spa Request Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Spa Request</fullName>
            </value>
            <value>
                <fullName>Bid Register Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SpaAutoRenewalControllerTest.cls
@isTest
public class SpaAutoRenewalControllerTest {
    @testSetup
    public static void createdata ()
    {
        BuildTestData.AddRecords();
        
    }
    //comment nothing
    static testMethod void getUpdatedQuoteTest() { 
        test.startTest();
        //Quote q=[select id from Quote where spa_Request_type__c ='Spa Request' limit 1];
        opportunity opp=[select id,spa_id__c from opportunity limit 1];
        quote q=new quote(opportunityId=opp.id,
                          spa_Request_type__c='Spa Request',
                          name='apex test');
        
        insert q;
        SpaAutoRenewalController.getUpdatedQuote('test',q.id);
    }
    
}