force-app/main/default/objects/Opportunity/fields/Spa_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>Spa_Approval_Date__c</fullName>
    <label>Spa Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Approved_Price__c.field-meta.xml
<CustomField>
    <fullName>Approved_Price__c</fullName>
    <label>Approved Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/SPA_Approval_Date__c.field-meta.xml
<CustomField>
    <fullName>SPA_Approval_Date__c</fullName>
    <label>SPA Approval Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SpaStateSync__c/SpaStateSync__c.object-meta.xml
<CustomObject>
    <description>Deprecation. Need to delete object. There are several dependencies that need updating

when a new sku is approved in a spa, this object is used to store values for bulk scheduled apex to update the opportunity products</description>
    <label>SpaStateSync</label>
    <nameField>
        <label>SpaStateSync Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SpaStateSync</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SpaStateSync__c/fields/ApprovalDate__c.field-meta.xml
<CustomField>
    <fullName>ApprovalDate__c</fullName>
    <label>ApprovalDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SpaStateSync__c/fields/Approved_Price__c.field-meta.xml
<CustomField>
    <fullName>Approved_Price__c</fullName>
    <label>Approved Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SpaStateSync__c/fields/PricbookEntryID__c.field-meta.xml
<CustomField>
    <fullName>PricbookEntryID__c</fullName>
    <label>PricbookEntryID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SpaStateSyncwithOpps.cls
global class SpaStateSyncwithOpps implements Schedulable {
    global void execute(SchedulableContext ctx) {
        
         List<SpaStateSync__c> products = [Select PricbookEntryID__c ,OpportunityId__c ,Quantity__c ,Approved_Price__c, ApprovalDate__c  from SpaStateSync__c];
        
        Set<Id> opps = new Set<Id>();
        
        //neeed to de-duplicate any state spas that have multiple values
        
        Map<String, SpaStateSync__c> updatedprods = new Map<String, SpaStateSync__c>();
        for(SpaStateSync__c s : [Select PricbookEntryID__c ,OpportunityId__c ,Quantity__c ,Approved_Price__c, ApprovalDate__c  from SpaStateSync__c order by LastModifiedDate desc]){
            updatedprods.put(s.OpportunityId__c + s.PricbookEntryID__c, s);
           
        }
        //now that the map has deduped the list, put back in list to loop through and create the opportunity line items
        //
        List<SpaStateSync__c> prodsToAdd = new List<SpaStateSync__c>();
            for(SpaStateSync__c ds : updatedprods.values()){
                prodsToAdd.add(ds); 
            }
        
		system.debug('list of prods cleand');
		system.debug(prodsToAdd);
        
        Double price = 100;
        List<OpportunityLineItem> linesToInsert = new  List<OpportunityLineItem>();
        for(SpaStateSync__c s : prodsToAdd ){
             system.debug('approved price '+price+' quantity '+s.Quantity__c);
                OpportunityLineItem line = new OpportunityLineItem(Pricebookentryid = s.PricbookEntryID__c    , 
                                                                   opportunityId  =  s.OpportunityID__c,
                                                                   Quantity = s.Quantity__c,
                                                                   UnitPrice =  price,
                                                                   Approved_Price__c = s.Approved_Price__c,
                                                                   SPA_Approval_Date__c = s.ApprovalDate__c);
            linesToInsert.add(line);
            
        }     
        
        insert linesToInsert;
        system.debug('map dupe potential ');
        system.debug(updatedprods);
        system.debug('list');
        system.debug(linesToInsert);
        delete products;
    }
}