force-app/main/default/objects/Opportunity/fields/Test_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Test_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>For flows to not run when running Test Coverage on Apex Classes</description>
    <label>Test Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/CDW.recordType-meta.xml
<RecordType>
    <fullName>CDW</fullName>
    <active>true</active>
    <businessProcess>VSA Sales Stages</businessProcess>
    <label>CDW</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Approved_Price__c.field-meta.xml
<CustomField>
    <fullName>Approved_Price__c</fullName>
    <label>Approved Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestApprovedSpaPrice.cls
@IsTest
public class TestApprovedSpaPrice  {
    Static testmethod void TestApprovedSpaPrice() {


PriceBook2 pb = new Pricebook2(Name='VSA Distributor Price List',IsActive=true);
		insert pb;

		PriceBook2 pb2 = new Pricebook2(Name='VSA Canadian Price List',IsActive=true);
		insert pb2;

		PriceBook2 pb3 = new Pricebook2(Name='VSA CDW Price List',IsActive=true);
		insert pb3;
		
Account acc = new Account(Name = 'Test',billingstate= 'ZZ',BillingCity='City',Type='End User');
insert acc;

Opportunity oppObj = new Opportunity(Name = 'TestOpp',AccountID = acc.Id,Amount = 2000,CloseDate=Date.today(),StageName='Close Won',Type='New Customer',Test_Opportunity__c=True);
//insert oppObj;

Product2 newProd = new Product2(Name = 'test product', family = 'test family');
insert newProd;

PriceBookEntry pbEntry = new PriceBookEntry(
    UnitPrice = 300,
    PriceBook2Id = Test.getStandardPricebookId(),
    Product2Id = newProd.Id,
    IsActive = true);

insert pbEntry ;

OpportunityLineItem oppLine = new OpportunityLineItem(pricebookentryid=pbEntry.Id,Approved_Price__c=2.00,TotalPrice=2000,Quantity = 2,OpportunityID = oppObj.Id);
//insert oppLine;
}
}