force-app/main/default/objects/POSAccountAliases__c/POSAccountAliases__c.object-meta.xml
<CustomObject>
    <description>Aliases for Accounts and how they show on POS</description>
    <label>POSAccountAlias</label>
    <nameField>
        <label>Name to Display</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>POSAccountAliases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/POSAccountAliases__c/fields/SFDC_Account__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFDC Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>POSAccountAliases</relationshipLabel>
    <relationshipName>POSAccountAliases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestPosAcctAliasMaster.cls
@IsTest
public class TestPosAcctAliasMaster  {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    
    Static testmethod void MasterAcctAliasInsert() {
        test.startTest();
        List<Account> accts = [Select id,name from account limit 2];
        
        POSAccountAliases__c p = new POSAccountAliases__c();
        p.name = 'Test Name';
        p.SFDC_Account__c = null;
        
        insert p;
        
        POSAccountAliases__c p2 = new POSAccountAliases__c();
        p2.name = 'Test Name';
        p2.SFDC_Account__c = accts[0].Id;
        
        insert p2;
        
        p.SFDC_Account__c = accts[1].Id;
        update p;
        
    }

}