force-app/main/default/objects/Apex_Error_Message__c/Apex_Error_Message__c.object-meta.xml
<CustomObject>
    <label>Apex Error Message</label>
    <nameField>
        <label>Apex Error Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Error Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Error_Message__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Apex Error Messages</relationshipLabel>
    <relationshipName>Apex_Error_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Message__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <label>Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Message__c/fields/Callout_Body__c.field-meta.xml
<CustomField>
    <fullName>Callout_Body__c</fullName>
    <label>Callout Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Message__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>6000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Message__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <label>ObjectType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Message__c/fields/RecordName__c.field-meta.xml
<CustomField>
    <fullName>RecordName__c</fullName>
    <label>RecordName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/createComponentErrorLog.cls
public without sharing class createComponentErrorLog {
    @future
    public static void createComponentErrorLog(String name, String cmp,String userid,String errmssg,
    String recordId,String calloutBody,String objType,String acctId,String recordname) {
        
        Apex_Error_Message__c am = new Apex_Error_Message__c();
            am.Name = name; 
            am.recordId__c = recordId;
            am.Callout_Body__c = calloutBody;
            am.RecordName__c = recordname;
            am.Account__c = acctId;
            am.Error_Message__c = errmssg;
            am.Apex_Class__c = cmp;
            am.UserId__c =userid;
            am.ObjectType__c  = objType;

            insert am;
    }
}