force-app/main/default/objects/Apex_Error_Message__c/Apex_Error_Message__c.object-meta.xml
<CustomObject>
    <label>Apex Error Message</label>
    <nameField>
        <label>Apex Error Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Error Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Apex_Error_Message__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <label>Component</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Message__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>6000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Apex_Error_Message__c/fields/ObjectType__c.field-meta.xml
<CustomField>
    <fullName>ObjectType__c</fullName>
    <label>ObjectType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Reseller_Names__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Names__c</fullName>
    <label>Partner Names</label>
    <length>20000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resellers__c.field-meta.xml
<CustomField>
    <fullName>Resellers__c</fullName>
    <description>Field is used for Wave Pipeline to search for Resellers.</description>
    <label>Resellers</label>
    <length>8000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resellers_and_Type__c.field-meta.xml
<CustomField>
    <fullName>Resellers_and_Type__c</fullName>
    <description>Updated by flow</description>
    <label>Resellers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <inlineHelpText>Select the type of Partner</inlineHelpText>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Reseller / VAR</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OppResellers.cls
public class OppResellers {    
    @InvocableMethod(label='Get Reseller Names')
    public static void oppResellersget(List<Id>oppids) { 
        //need to update the list of opportunity resellers on the field of opportunity
        //this is to have one long text field that can be filtered in Einstein analytics
        //by reseller.
        
        Set<Id> opps = new Set<Id>();
        
        List <Opportunity_Partner__c> parts = [Select id,opportunity__c from Opportunity_Partner__c where
                                              id in : oppids];
        
        for(Opportunity_Partner__c p : parts){
            opps.add(p.opportunity__c);
        }
        
        OppResellers.oppaddResellers(opps);
        system.debug('invocable oppresellers ran');        
    }
    
    @future
    public static void oppaddResellers(Set<Id>oppsids) { 
        //need to update the list of opportunity resellers on the field of opportunity
        //this is to have one long text field that can be filtered in Einstein analytics
        //by reseller.
        
        List<Opportunity> parts = [Select id,Resellers__c,Resellers_and_Type__c,Reseller_Names__c,( select id,opportunity__c,Partner_Type__c,partner_account__r.name
                                                                                                   from Opportunity_Partners__r where opportunity__c in: oppsids and Partner_Type__c  = 'Reseller / VAR')
                                   from opportunity where id in : oppsids for update];
        
        for(Opportunity o : parts){
            String partnames = '';
            String names = '';
            String res = '';
            
            for(Opportunity_Partner__c p : o.Opportunity_Partners__r){
                if(partnames == ''){
                    if(p.Partner_Type__c  == 'Reseller / VAR'){
                        res = p.partner_account__r.name;
                    }
                    
                    partnames = p.partner_account__c;
                    names =    p.partner_account__r.name;
                }else{
                    if(p.Partner_Type__c  == 'Reseller / VAR'){
                        res = res+'/'+p.partner_account__r.name;
                    }
                    partnames = partnames+'/'+p.partner_account__c;
                    names = names+'/'+p.partner_account__r.name;
                }
                
            }
            o.Resellers__c = partnames;
            o.Reseller_Names__c = names;
            o.Resellers_and_Type__c =  res.left(250);
            system.debug('future reseller names '+parts);
        }
        try{update parts;}catch(Exception e){String t = 'Opportunity Reseller Names Update Error for id '+ parts[0].Id;AdminErrorMessage.SendError(e, t);Apex_Error_Message__c msg = new Apex_Error_Message__c ();msg.recordId__c = parts[0].Id;msg.ObjectType__c  = 'Opportunity Resellers Field';msg.Apex_Class__c = 'OppResellers';msg.UserId__c = UserInfo.getUserId(); msg.Error_Message__c = e.getmessage();database.insert(msg, false);}
    }

}