force-app/main/default/objects/Contact/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <description>Account.Id for funded heads criteria</description>
    <label>AccountId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links Viewsonic Users with contacts. Used in automation for the product request roll ups.</description>
    <label>UserID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <label>AccountId</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_ID__c</fullName>
    <defaultValue>$User.ContactId</defaultValue>
    <label>Contact ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ContactUser.cls
public with sharing class ContactUser{
    
    public static void FindUser(List<Contact> records)
{
        
        

        Set<String> families = new Set<String>();
        for (Contact record : records) families.add(record.UserID__c);


       Map<String, Contact> managers = new Map<String, Contact>();
        for (Contact manager : [
            SELECT Name,Id,UserID__c,AccountId FROM Contact
            WHERE UserID__c IN :families AND UserID__c != Null
        ]) managers.put(manager.UserID__c , manager);



       List<User> users = [Select Id,Contact_ID__c from User where Id IN :families AND Country != null];

        if(users.size() >0){
       for (User  user : users){
                user.Contact_ID__c = managers.get(user.Id).Id;
                user.AccountId__c = managers.get(user.Id).AccountId;

                 update user;

            }




            
    }
}
}