force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Contact)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Legal_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_First_Name__c</fullName>
    <description>Legal name for payouts to customer or partner</description>
    <inlineHelpText>Legal name for payouts to customer or partner</inlineHelpText>
    <label>Legal First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Legal_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Last_Name__c</fullName>
    <description>Legal name for payouts to customer or partner</description>
    <inlineHelpText>Legal name for payouts to customer or partner</inlineHelpText>
    <label>Legal Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/spiffPmtAmt__c.field-meta.xml
<CustomField>
    <fullName>spiffPmtAmt__c</fullName>
    <label>spiffPmtAmt</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/spiffPmtAmtCD__c.field-meta.xml
<CustomField>
    <fullName>spiffPmtAmtCD__c</fullName>
    <label>spiffPmtAmtCD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/spiffPmtAmtIFP__c.field-meta.xml
<CustomField>
    <fullName>spiffPmtAmtIFP__c</fullName>
    <label>spiffPmtAmtIFP</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/spiffPmtAmtLCD__c.field-meta.xml
<CustomField>
    <fullName>spiffPmtAmtLCD__c</fullName>
    <label>spiffPmtAmtLCD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/spiffPmtAmtPJ__c.field-meta.xml
<CustomField>
    <fullName>spiffPmtAmtPJ__c</fullName>
    <label>spiffPmtAmtPJ</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/spiffPmtQty__c.field-meta.xml
<CustomField>
    <fullName>spiffPmtQty__c</fullName>
    <label>spiffPmtQty</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/spiffPmtQtyCD__c.field-meta.xml
<CustomField>
    <fullName>spiffPmtQtyCD__c</fullName>
    <label>spiffPmtQtyCD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/spiffPmtQtyIFP__c.field-meta.xml
<CustomField>
    <fullName>spiffPmtQtyIFP__c</fullName>
    <label>spiffPmtQtyIFP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/spiffPmtQtyLCD__c.field-meta.xml
<CustomField>
    <fullName>spiffPmtQtyLCD__c</fullName>
    <label>spiffPmtQtyLCD</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/spiffPmtQtyPJ__c.field-meta.xml
<CustomField>
    <fullName>spiffPmtQtyPJ__c</fullName>
    <label>spiffPmtQtyPJ</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Spiff_Claim_Payment__c/Spiff_Claim_Payment__c.object-meta.xml
<CustomObject>
    <label>Spiff Claim Payment</label>
    <nameField>
        <label>Spiff Claim Payment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Spiff Claim Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Claim_Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Spiff Claim Payments</relationshipLabel>
    <relationshipName>Spiff_Claim_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Claim_Payment__c/fields/finclaimerFname__c.field-meta.xml
<CustomField>
    <fullName>finclaimerFname__c</fullName>
    <label>claimerFname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Claim_Payment__c/fields/finclaimerLname__c.field-meta.xml
<CustomField>
    <fullName>finclaimerLname__c</fullName>
    <label>claimerLname</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Claim_Payment__c/fields/fincontactEmail__c.field-meta.xml
<CustomField>
    <fullName>fincontactEmail__c</fullName>
    <externalId>true</externalId>
    <label>contactEmail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Claim_Payment__c/fields/finofferAmount__c.field-meta.xml
<CustomField>
    <fullName>finofferAmount__c</fullName>
    <label>offerAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Spiff_Claim_Payment__c/fields/finofferNumber__c.field-meta.xml
<CustomField>
    <fullName>finofferNumber__c</fullName>
    <label>offerNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Spiff_Claim_Payment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&apos;Submitted to Finance&apos;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted to Finance</fullName>
                <default>true</default>
                <label>Submitted to Finance</label>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/fields/productLine__c.field-meta.xml
<CustomField>
    <fullName>productLine__c</fullName>
    <formula>text(Product__r.Family )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>productLine</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requester</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Requester_Company__c.field-meta.xml
<CustomField>
    <fullName>Requester_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requester Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Spiff_Claim_Payment__c.field-meta.xml
<CustomField>
    <fullName>Spiff_Claim_Payment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Spiff Claim Payment</label>
    <referenceTo>Spiff_Claim_Payment__c</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Submitted&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Requesting more info</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Submitted to Accounting</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Total_Spiff_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Spiff_Amount__c</fullName>
    <formula>Quantity__c *  Total_SPIF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>For All Units Total Spiff Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/spiffPaymentToFinance.cls
public without sharing class spiffPaymentToFinance {
    @AuraEnabled
    public static List<Spiff_Claim_Payment__c> updateFinance(){    
        
        String status = 'Approved';
        
        DescribeSObjectResult describeResult = Contact.getSObjectType().getDescribe();
        List< Spiff_Claim_Payment__c > paid = [Select id ,status__c from Spiff_Claim_Payment__c where status__c != 'Paid' ];
        for(Spiff_Claim_Payment__c s : paid){
            s.Status__c = 'Paid';
        }
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
        
        
        DescribeSObjectResult describeSpiff = Spiff_Request__c.getSObjectType().getDescribe();
        
        List<String> SpifffieldNames = new List<String>( describeSpiff.fields.getMap().keySet() );
        List< Spiff_Claim_Payment__c > scp = new List< Spiff_Claim_Payment__c >();
        List< Spiff_Request__c > spiffs = new List< Spiff_Request__c >();
        //Map<Id, Spiff_Request__c >child = new Map< Id,Spiff_Request__c >();
        
        String query =		  ' SELECT ' +		      String.join( fieldNames, ',' ) +',Account.BillingCountry,(Select '+ String.join( SpifffieldNames, ',' )+  
            ' FROM spiff_requests__r where Status__c = :status ) '
            +	' FROM '+	      describeResult.getName()	+' WHERE id in (select Requester__c  from spiff_request__c where Status__c = :status) ';
        
      
        system.debug(query);
        List<Contact> records = Database.query( query ); 
        system.debug(records[0].Account.BillingCountry+' bil country');
        system.debug(records);
        
        for(Contact c: records){
            if(c.Legal_Last_Name__c != Null){
                c.LastName = c.Legal_Last_Name__c;
            }
            if(c.Legal_First_Name__c != Null){
                c.FirstName = c.Legal_First_Name__c;
            }
            Double qty =0;
            Double rev =0;
            Double qtyIFp =0;
            Double revIFP =0;
            Double qtyPJ =0;
            Double revPJ =0;
            Double qtyLCD =0;
            Double revLCD =0;
            Double qtyCd =0;
            Double revCD =0;
            for(Spiff_Request__c s : c.Spiff_requests__r){
                s.status__c = 'Submitted to Accounting';
                spiffs.add(s);
                
                qty = qty+s.Quantity__c;
                rev = rev+s.Total_Spiff_Amount__c;
                if(s.productLine__c == 'IFP'){
                    qtyIFp = qtyIFp+s.Quantity__c;
                    revIFP = revIFP+s.Total_Spiff_Amount__c;
                }else if(s.productLine__c == 'CD'){
                    qtyCd = qtyCd+s.Quantity__c;
                    revCD = revCD+s.Total_Spiff_Amount__c;
                }else if(s.productLine__c == 'LCD'){
                    qtyLCD = qtyLCD+s.Quantity__c;
                    revLCD = revLCD+s.Total_Spiff_Amount__c;
                }else if(s.productLine__c == 'PJ'){
                    qtyPJ = qtyPJ+s.Quantity__c;
                    revPJ = revPJ+s.Total_Spiff_Amount__c;
                }
            }
            
            if(c.Account.BillingCountry != 'Canada'){
                Spiff_Claim_Payment__c  sp = new Spiff_Claim_Payment__c ();
                //sp.finofferNumber__c = qty;
                sp.Product_Line__c = 'All';
                sp.finofferAmount__c = rev;
                sp.fincontactEmail__c  = c.Email;
                sp.finclaimerFname__c = c.FirstName;
                sp.finclaimerLname__c = c.LastName;
                sp.Contact__c = c.Id;
                scp.add(sp);
                
            }else if(c.Account.BillingCountry == 'Canada') {
                if(qtyIFp > 0){
                    Spiff_Claim_Payment__c  sp1 = new Spiff_Claim_Payment__c ();
                    sp1.Product_Line__c = 'IFP';
                    //sp1.finofferNumber__c = qtyIFp;
                    sp1.finofferAmount__c = revIFP;
                    sp1.finclaimerFname__c = c.FirstName;
                    sp1.finclaimerLname__c = c.LastName;
                    sp1.fincontactEmail__c  = c.Email;
                    sp1.Contact__c = c.Id;
                    scp.add(sp1);
                }
                if(qtyPJ > 0){
                    Spiff_Claim_Payment__c  sp2 = new Spiff_Claim_Payment__c ();
                    sp2.Product_Line__c = 'PJ';
                    //sp2.finofferNumber__c = qtyPJ;
                    sp2.finofferAmount__c = revPJ;
                    sp2.finclaimerFname__c = c.FirstName;
                    sp2.finclaimerLname__c = c.LastName;
                    sp2.fincontactEmail__c  = c.Email;
                    sp2.Contact__c = c.Id;
                    scp.add(sp2);
                }
                if(qtyLCD > 0){
                    Spiff_Claim_Payment__c  sp3 = new Spiff_Claim_Payment__c ();
                    sp3.Product_Line__c = 'LCD';
                    //sp3.finofferNumber__c = qtyLCD;
                    sp3.finofferAmount__c = revLCD;
                    sp3.finclaimerFname__c = c.FirstName;
                    sp3.finclaimerLname__c = c.LastName;
                    sp3.fincontactEmail__c  = c.Email;
                    sp3.Contact__c = c.Id;
                    scp.add(sp3);
                }
                if(qtyCd > 0){
                    Spiff_Claim_Payment__c  sp4 = new Spiff_Claim_Payment__c ();
                    sp4.Product_Line__c = 'CD';
                    //sp4.finofferNumber__c = qtyCd;
                    sp4.finofferAmount__c = revCD;
                    sp4.finclaimerFname__c = c.FirstName;
                    sp4.finclaimerLname__c = c.LastName;
                    sp4.fincontactEmail__c  = c.Email;
                    sp4.Contact__c = c.Id;
                    scp.add(sp4);
                }
            }
        }
        insert scp;
        update paid;
        
        Map<String,Spiff_Claim_Payment__c> pmts = new Map<String,Spiff_Claim_Payment__c>();
        for(Spiff_Claim_Payment__c s : [Select id, Product_Line__c, contact__c from Spiff_Claim_Payment__c where id in: scp]){
            pmts.put(s.contact__c+s.Product_Line__c, s);
            
        }
        
        for(Spiff_Request__c s : spiffs){
            if(pmts.containsKey(s.requester__c+s.productLineKey__c)){
                Spiff_Claim_Payment__c pm = pmts.get(s.requester__c+s.productLineKey__c);
                s.Spiff_Claim_Payment__c = pm.Id;                
            }
        }
        system.debug(spiffs);
        
        update spiffs;
        
        return scp;
                              
        
        
                        //update records;
                        /*    
                        c.spiffPmtQty__c = qty;
                        c.spiffPmtAmt__c = rev;           
                        c.spiffPmtQtyIFP__c  = qtyIFp;
                        c.spiffPmtAmtIFP__c = revIFP;
                        c.spiffPmtQtyPJ__c  = qtyPJ;
                        c.spiffPmtAmtPJ__c = revPJ;
                        c.spiffPmtQtyLCD__c  = qtyLCD;
                        c.spiffPmtAmtLCD__c = revLCD;
                        c.spiffPmtQtyCD__c  = qtyCd;
                        c.spiffPmtAmtCD__c = revCD;
                        */
    }
    
    
}