force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Contact)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Role__c/Contact_Role__c.object-meta.xml
<CustomObject>
    <description>This is a better version of the OpportunityContactRole because reps can send follow up emails using this object&apos;s list view button</description>
    <label>Opp Follow Up Contacts</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Follow Up Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opp Follow Up Contacts</relationshipLabel>
    <relationshipName>Contact_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User_Contact__c.field-meta.xml
<CustomField>
    <fullName>End_User_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>The email Address will be attached to the opportunity once an email is attached to the contact</inlineHelpText>
    <label>End User Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (End User Contact)</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Notes__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Notes__c</fullName>
    <description>Sales Rep can enter notes to set up reminders and situation on the the opportunity</description>
    <inlineHelpText>Sales Rep can enter notes to set up reminders and situation on the the opportunity</inlineHelpText>
    <label>Opportunity Notes</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Partner_Account_Search__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account_Search__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Re-Seller VAR will be added to opportunity partners. If you need to add additional Resellers, Please Use Opportunity Partners.</inlineHelpText>
    <label>Reseller Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ResellerContact__c.field-meta.xml
<CustomField>
    <fullName>ResellerContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Reseller Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SPA_ID__c.field-meta.xml
<CustomField>
    <fullName>SPA_ID__c</fullName>
    <displayFormat>{0000000}</displayFormat>
    <externalId>true</externalId>
    <inlineHelpText>Spa ID from the new spa portal. autmatically generated based on the year, month, and sequence of opportunity created.</inlineHelpText>
    <label>SPA ID</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Trade_Show_or_Marketing_Campaign__c.field-meta.xml
<CustomField>
    <fullName>Trade_Show_or_Marketing_Campaign__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Campaign or Trade Show</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <formula>Partner_Account__r.Id</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Account Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Quote.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Quote.Specialty_Spa__c</field>
            <operation>notEqual</operation>
            <value>FTB, Demo</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Partner</label>
    <referenceTo>Opportunity_Partner__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OppPipelineSpas.cls
public with sharing class OppPipelineSpas {    
    @AuraEnabled
    public static List<Quote> getSpas(String recid,String ofields,String pfields)
    {     
        //create set of accounts to query the correct spas
        //account id can come from opportunity, contact, or account
        system.debug(' get spas method record id is '+recid);
        system.debug(' ofields '+ofields);
        system.debug(' pfields  '+pfields);
        
        Set<Id> recids = new Set<Id>();
        
        recids.add(recid);
        //Set<Id> oppids = new Set<Id>();        
        //Set<Id> consInOpp = new Set<ID>(); 
        
        String oppfields = String.escapeSingleQuotes(ofields);
        String prodfields = String.escapeSingleQuotes(pfields);
        
        system.debug(recid.substring(0,3)+' recid prefix');
        //get the acccount and parent account info from the opportunity
        //to search for similiar spas when getting from opportunity page
        
        //comment out. going to put the recid for any type of record in the set and then 
        //do a couple subqueries and merge the quieried records
        
        /*
        
        if(recid.substring(0,3) == '006'){
            Opportunity opp = [Select Id, AccountID,Account.ParentId from Opportunity where Id =:recid];
      
        //Limit the amount of Ids from the query before querying based account and parent accounts
            accounts.add(opp.AccountId);
            if(opp.Account.ParentId != null){
                accounts.add(opp.Account.ParentId); 
            }
            
           
        
        //go through the accounts and see if there any childern that should be added to results
        //since this may affect school districts and give too much data, we will exclude eduction
            List<Account> childAccs = [Select Id from account where ParentId in: accounts and Industry != 'Education'];
            for(Account a : childAccs){
                accounts.add(a.Id);
            }
            
        }else if(recid.substring(0,3) == '001'){
            Account acc = [Select Id, ParentId from Account where Id =:recid];
      
        //Limit the amount of Ids from the query before querying based account and parent accounts
            accounts.add(acc.Id);
            system.debug('parent id '+acc.ParentId);
            if(acc.ParentId != null){
                accounts.add(acc.ParentId);
            }
            
        
        //go through the accounts and see if there any childern that should be added to results
        //since this may affect school districts and give too much data, we will exclude eduction
        //
        //comment out since no longer looking at child accounts
            List<Account> childAccs = [Select Id from account where ParentId in: accounts and Industry != 'Education'];
            for(Account a : childAccs){
                accounts.add(a.Id);
            }
        }else if(recid.substring(0,3) == '003'){
            Contact con = [Select Id,AccountId,Account.ParentId from Contact where Id =:recid];
            //get the opportunities related to this contact
                       
            List<OpportunityContactRole> conopp = [Select OpportunityId from OpportunityContactRole where ContactId = : recid];
            
            List<Contact_Role__c> conopps = [Select Opportunity__c from Contact_Role__c where Contact__c = : recid];
            
            for(OpportunityContactRole op : conopp){
                 consInOpp.add(op.OpportunityId);
            } 
            
            for(Contact_Role__c opp : conopps){
                consInOpp.add(opp.Opportunity__c);
            } 
            
      
        //Limit the amount of Ids from the query before querying based account and parent accounts
            accounts.add(con.AccountId);
            if(con.Account.ParentId != null){
                accounts.add(con.Account.ParentId);
            }
           
        
        //go through the contacts and see if there any childern that should be added to results
        //since this may affect school districts and give too much data, we will exclude eduction
            List<Account> childAccs = [Select Id from account where ParentId in: accounts and Industry != 'Education'];
            for(Account a : childAccs){
                accounts.add(a.Id);
            }
        }
        //also need to query based on any link that was created with  the 
        //spa opp junction object
        
        //go through lists and get the parent account ids from all accounts so that we can
    	//go through query opp partners getting resellers and end users in results
    	List<Opportunity_Partner__c> partners = [Select  Opportunity__c from Opportunity_Partner__c where Account_Id__c in: accounts];
        for(Opportunity_Partner__c op : partners){
            oppids.add(op.opportunity__c);
        }
        */
        List<Quote> spasToReturn = Database.query('Select '+oppfields+',(Select '+prodfields+                                             
                      ' from QuoteLineItems) from Quote where Active__c = true and (AccountId in: recids or OpportunityId in: recids '+
                       ' )'+
                       ' order by ExpirationDate desc limit 25');
        
        List<Quote> spasPartners = Database.query('Select '+oppfields+',(Select '+prodfields+                                             
                      ' from QuoteLineItems) from Quote where Active__c = true and id in (select quote__c from opportunity_partner__c where partner_account__c in : recids) '+
                       ' order by ExpirationDate desc limit 25');
        
        List<Quote> spasOppAccounts = Database.query('Select '+oppfields+',(Select '+prodfields+                                             
                      ' from QuoteLineItems) from Quote where Active__c = true and AccountId in (select AccountId from Opportunity where Id in : recids) '+
                       ' order by ExpirationDate desc limit 25');
        
        List<Quote> spasOppContacts = Database.query('Select '+oppfields+',(Select '+prodfields+                                             
                      ' from QuoteLineItems) from Quote where Active__c = true and AccountId in (select AccountId from Contact where Id in : recids) '+
                       ' order by ExpirationDate desc limit 25');
        
        spasToReturn.addall(spasPartners);
        spasToReturn.addall(spasOppAccounts);
        spasToReturn.addall(spasOppContacts);
        
         List<Quote> spas = Database.query('Select '+oppfields+',(Select '+prodfields+                                             
                      ' from QuoteLineItems) from Quote where Active__c = true and Id in: spasToReturn '+
                       ' order by ExpirationDate desc limit 25');
        
        
        //add list to set and remove duplicates and then ret back to list to controller
        
        
        /*Set<Quote> spas = new Set<Quote>();
        spas.addAll(spasToReturn);

        system.debug(spas.size()+ ' set size');
        Integer indx = 0;
        List<Quote> retSpas = new List<Quote>();
        for(Quote s : spas){
            indx = indx+1;
            retSpas.add(s);
            system.debug(indx);
        }
        system.debug('get opps, the accounts found');
        system.debug(retSpas.size()+ ' list size');
		*/
        
        system.debug(spas.size()+' spa list size');
        return  spas;

    }

     @AuraEnabled
    public static Opportunity getOpp(String oppid)
    {    
        system.debug('the opp id is '+oppid);
        return [Select Id,Name,AccountId,Partner_Account_Search__c,Account.Name,
                ResellerContact__c,End_User_Contact__c,Trade_Show_or_Marketing_Campaign__c,
                CloseDate,Opportunity_Notes__c,Spa_ID__c, Pricebook2Id
                from Opportunity where id =:oppid limit 1];
    }
    @AuraEnabled
     public static User getUser()
    {     
         Id userId = UserInfo.getUserId();
        
         return [SELECT Name,Country FROM User WHERE Id = :userId];
    }
    

}