force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Contact)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map Leads to Accounts for apex conversion when lead is really part of an existing account. 
This ensures that the contact is set up for proper marketing and sales activities</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Map to contact. We have a lot of duplicates, and this allows us to map leads that are duplicated as contacts and convert them and merge them.</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AutoConvertLeads.cls
Public class AutoConvertLeads 
{     @InvocableMethod   
    public static void LeadAssign(List<Id> LeadIds)  
    {         
        Set<String> emails = new Set<String>();
        List<Lead> sers = [Select id, account__c,contact__c,email from lead 
                           where id in : leadIds];
        for(Lead l : sers){
            emails.add(l.email);
        }
        system.debug(emails);
        system.debug('emails');
        LeadStatus CLeadStatus= [SELECT Id, MasterLabel FROM LeadStatus WHERE IsConverted=true Limit 1];
        
        Map<String,Contact> cons = new Map<String,Contact>();
        for(Contact c : [Select id, accountId, email from contact where email in : emails ]){
            cons.put(c.email,c);
        }
        system.debug(cons);
        system.debug('check map');
        
        List<Database.LeadConvert> MassLeadconvert = new List<Database.LeadConvert>();
        for(Lead l : sers){
            if(cons.containsKey(l.email)){
                Contact c = cons.get(l.email);               
                
                Database.LeadConvert lc = new Database.LeadConvert();
                lc.setLeadId(l.Id); 
                lc.setAccountId(c.AccountId);
                lc.setContactId(c.Id);
                lc.setConvertedStatus(CLeadStatus.MasterLabel);
                lc.setDoNotCreateOpportunity(TRUE); //Remove this line if you want to create an opportunity from Lead Conversion 
                MassLeadconvert.add(lc);
            }
            
        }
        
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.DuplicateRuleHeader.allowSave = true;
        dml.DuplicateRuleHeader.runAsCurrentUser = true;
        dml.optAllOrNone = false;
        
        if (!MassLeadconvert.isEmpty()) {
            List<Database.LeadConvertResult> lcr = Database.convertLead(MassLeadconvert,false);
        }
        
        
        
        //knfoaisnfei
    } 
}