force-app/main/default/objects/Contact/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Contacts (Contact)</relationshipLabel>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact_Role__c/Contact_Role__c.object-meta.xml
<CustomObject>
    <description>This is a better version of the OpportunityContactRole because reps can send follow up emails using this object&apos;s list view button</description>
    <label>Opp Follow Up Contacts</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opp Follow Up Contacts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Role__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opp Follow Up Contacts</relationshipLabel>
    <relationshipName>Contact_Roles</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <formula>Contact__r.FirstName&amp;&apos; &apos;&amp;Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Contact Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/End_User_Account__c.field-meta.xml
<CustomField>
    <fullName>End_User_Account__c</fullName>
    <formula>Opportunity__r.End_User_Lookup_Account__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End User Account</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Contact_Roles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>End User Contact</fullName>
            </value>
            <value>
                <fullName>Reseller Contact</fullName>
            </value>
            <value>
                <fullName>Distributor Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact_Role__c/fields/Send_Follow_Up_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Follow_Up_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>field to trigger email alert workflow</description>
    <label>Send Follow Up Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Send_Follow_Up_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Follow_Up_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Send Follow Up Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Contact_Name__c</fullName>
    <label>Contact Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OppPipelineFollowUp.cls
public class OppPipelineFollowUp {
     @AuraEnabled
    public static List<Contact_Role__c> getOppContacts(List<Opportunity> opps)
    {     
        system.debug(opps);
        
        return [Select Id,Opportunity__r.Name,Contact__r.Name,Opportunity__r.Account.Name,Contact__r.Email,Send_Follow_Up_Email__c,
                Role__c,Contact_Name__c,Email__c,End_User_Account__c,Contact__r.Account.Name from Contact_Role__c where Opportunity__c in: opps order by Opportunity__r.Name];
    }
    @AuraEnabled
    public static List<Contact_Role__c> emailCons(List<Contact_Role__c> oppcons)
    {     
        List<Contact_Role__c> selectedCons =  [Select Id,Send_Follow_Up_Email__c from Contact_Role__c 
                                             where id in: oppcons];        
        
        List<Contact_Role__c> consToUpdate =  new List<Contact_Role__c>();
            
        system.debug('cons to email'+oppcons);
        
        for(Contact_Role__c c: selectedCons){
            c.Send_Follow_Up_Email__c = true;
                consToUpdate.add(c);
        }
        update consToUpdate;
        system.debug(consToUpdate);
        return oppcons;
    }
    

}