force-app/main/default/objects/Contact/fields/GetUserId__c.field-meta.xml
<CustomField>
    <fullName>GetUserId__c</fullName>
    <defaultValue>false</defaultValue>
    <label>GetUserId</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links Viewsonic Users with contacts. Used in automation for the product request roll ups.</description>
    <label>UserID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SandboxConUserLink.cls
public with sharing class SandboxConUserLink{
    public static void updatecons(List<Contact> records){
    	


    	 Set<String> emails = new Set<String>();
         for (Contact record : records) emails.add(record.Email);

         Map<String, User> managers = new Map<String, User>();

         for (User manager : [
         	SELECT Id,Name,Email FROM User
            WHERE Email IN :emails
       		])managers.put(manager.Email , manager);

          

          List<Contact> consToUpdate = new List<Contact>();
           for (Contact  con : records){
           	 	if (managers.containsKey(con.Email)){
           	 		if(con.GetUserId__c == true){
                //con.UserID__c = managers.get(con.Email).Id;
           		con.GetUserId__c	= false;
           		con.UserID__c = managers.get(con.Email).Id;
           		//ContactUser.FindUser(trigger.new);
            }else{
            	con.GetUserId__c	= false;
            }
            con.GetUserId__c	= false;
           	 	}
             
           		con.GetUserId__c	= false;	
           			
           		
           }

          
  	}
  }