force-app/main/default/objects/Contact/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <label>PR Opportunity Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Type__c.field-meta.xml
<CustomField>
    <fullName>Eval_Type__c</fullName>
    <label>Evaluation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End-User/Reseller/Disty Eval</fullName>
            </value>
            <value>
                <fullName>ViewSonic Sales Rep Eval</fullName>
            </value>
            <value>
                <fullName>Write Off Request</fullName>
            </value>
            <value>
                <fullName>Reseller Demo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Evals_Outstanding_Contact__c.field-meta.xml
<CustomField>
    <fullName>Evals_Outstanding_Contact__c</fullName>
    <label>Evals Outstanding Contact</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Evals_Past_Due_Contact__c.field-meta.xml
<CustomField>
    <fullName>Evals_Past_Due_Contact__c</fullName>
    <label>Evals Past Due Contact</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Evaluation_Owner__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation Owner</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Eval Requests (Evaluation Owner)</relationshipLabel>
    <relationshipName>Product_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity Name</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_3__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_4__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_5__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2)</booleanFilter>
        <errorMessage>This is a bundle, you must select a non bundle product.

Also Products cannot have -2, -3,-4 in IFP Name. Please use the non dash skus.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_2__c.field-meta.xml
<CustomField>
    <fullName>Quantity_2__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_3__c.field-meta.xml
<CustomField>
    <fullName>Quantity_3__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_4__c.field-meta.xml
<CustomField>
    <fullName>Quantity_4__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_5__c.field-meta.xml
<CustomField>
    <fullName>Quantity_5__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Total_Past_Due_Evals__c.field-meta.xml
<CustomField>
    <fullName>Total_Past_Due_Evals__c</fullName>
    <label>Total Past Due Evals</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Trade_Show__c.field-meta.xml
<CustomField>
    <fullName>Trade_Show__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trade Show</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Name__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Name__c</fullName>
    <formula>left(
if(not(isblank(Account.Name)),
SUBSTITUTE(Account.Name, &quot;&apos;&quot;, &quot;&quot;),
if(not(isblank( Partner_Account_Search__r.Name )),Partner_Account_Search__r.Name,&apos;Need End User or Reseller&apos;)),120)

&amp; &quot; &quot;&amp; if(not(isblank( School__c)) ,School__r.Name,  Project_or_Site_Information__c )    &amp;
 if(Count_of_Quotes__c=0,&quot; &quot;, &quot; Spa ID# &quot;&amp;SPA_ID__c&amp;&apos; &apos;)
&amp;
if(not(isblank(Product_Name__c)),Product_Name__c&amp; &quot; Qty &quot;&amp;text(Product_Quantity__c),&apos;&apos;)&amp;&apos; &apos;&amp;BR_Conga__c</formula>
    <label>Opportunity Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <inlineHelpText>Workaround for Product Name appearing in Opportunity Name. This is not visible in any sales layouts.</inlineHelpText>
    <label>Product Name</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Evaluation_Product__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Product if checked will be added to the eval when created</description>
    <label>Evaluation Product</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Contact_ID__c</fullName>
    <defaultValue>$User.ContactId</defaultValue>
    <label>Contact ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EvalContact.cls
public class EvalContact {
    Eval_Request__c eval {get;set;}
    Opportunity opp{get;set;}

    //constructor for extension
    public EvalContact(ApexPages.StandardController stdController){
        eval = (Eval_Request__c)stdController.getRecord();
        List<Opportunity> opps = [SELECT ID,Name FROM Opportunity WHERE Name = 'Viewsonic Sales Rep Evaluations' LIMIT 1];
        List<Opportunity> opps1 = [SELECT ID,Name FROM Opportunity WHERE Name = 'Viewsonic Trade Show Loaner Eval Requests' LIMIT 1];
    
        User current_user=[SELECT Contact_ID__c,Id,Name FROM User WHERE Id= :UserInfo.getUserId()] ;
        
        if(eval.Eval_Type__c == 'ViewSonic Sales Rep Eval' && eval.Opportunity_Name__c == null && eval.Trade_Show__c == false && opps.size() >0){
        eval.Opportunity_Name__c = opps[0].Id;
        }
        if(eval.Trade_Show__c == True && eval.Opportunity_Name__c == null && opps1.size() >0){
        eval.Opportunity_Name__c = opps1[0].Id;
        }
        // set up the owner of the record to be the Contact that is linked to the user. 
       
       eval.Evaluation_Owner__c = current_user.Contact_ID__c;
       //get contact id and all related past due and outstanding roll up summaries to determine if okay to proceed or to lock out of eval creation
       //Contact cont = [Select PR_Outstanding_Evals_EU_Disty__c,PR_Past_Due_Evals__c,PR_Write_offs_Last_12_Months__c FROM Contact Where Id= :current_user.Contact_ID__c LIMIT 1];
       //eval.Total_Past_Due_Evals__c = cont.Past_Due__c;
       //eval.Evals_Outstanding_Contact__c = cont.PR_Outstanding_Evals_EU_Disty__c; 
       //eval.Evals_Past_Due_Contact__c = cont.PR_Past_Due_Evals__c;
       //pull the opportunity line items that were created and linked to this eval. Must use button on opportunity page to pull the data from opportunity
       List<OpportunityLineItem> prod = [SELECT ID,ProductCode,Quantity,Product2Id,Evaluation_Product__c FROM OpportunityLineItem WHERE Evaluation_Product__c = True AND OpportunityId = :ApexPages.currentPage().getParameters().get('CF00NA000000AJjZv_lkid')];
         // If opportunity products exists, then pull the id otherwise do not depending on the size of the list, different skus will be pulled
     if(prod.size() > 4) {
        eval.Product_Name__c = prod[0].Product2Id;
        eval.Quantity__c = 1;
        
        eval.Product_Name_2__c = prod[1].Product2Id;
        eval.Quantity_2__c = 1;
        
        eval.Product_Name_3__c = prod[2].Product2Id;
        eval.Quantity_3__c = 1;
        
        eval.Product_Name_4__c = prod[3].Product2Id;
        eval.Quantity_4__c = 1;
        
        eval.Product_Name_5__c = prod[4].Product2Id;
        eval.Quantity_5__c = 1;
        
}  

else if(prod.size() == 4) {
    
    eval.Evaluation_Owner__c = current_user.Contact_ID__c;
        eval.Product_Name__c = prod[0].Product2Id;
        eval.Quantity__c = 1;
        
        eval.Product_Name_2__c = prod[1].Product2Id;
        eval.Quantity_2__c = 1;
        
        eval.Product_Name_3__c = prod[2].Product2Id;
        eval.Quantity_3__c = 1;
        
        eval.Product_Name_4__c = prod[3].Product2Id;
        eval.Quantity_4__c = 1;
}  
else if(prod.size() == 3) {
    
    eval.Evaluation_Owner__c = current_user.Contact_ID__c;
        eval.Product_Name__c = prod[0].Product2Id;
        eval.Quantity__c = 1;
        
        eval.Product_Name_2__c = prod[1].Product2Id;
        eval.Quantity_2__c = 1;
        
        eval.Product_Name_3__c = prod[2].Product2Id;
        eval.Quantity_3__c = 1;
        
        
}   
else if(prod.size() == 2) {
    
    eval.Evaluation_Owner__c = current_user.Contact_ID__c;
        eval.Product_Name__c = prod[0].Product2Id;
        eval.Quantity__c = 1;
        
        eval.Product_Name_2__c = prod[1].Product2Id;
        eval.Quantity_2__c = 1;
       
        
        
} 
else if(prod.size() == 1) {
    
    eval.Evaluation_Owner__c = current_user.Contact_ID__c;
        eval.Product_Name__c = prod[0].Product2Id;
        eval.Quantity__c = 1;
        
} 



eval.Evaluation_Owner__c = current_user.Contact_ID__c;

    }
}