force-app/main/default/objects/Contact/fields/Portal_Corporate_Spiff_Admin__c.field-meta.xml
<CustomField>
    <fullName>Portal_Corporate_Spiff_Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If Checked, user has access to all spas and all company spiffs within their company. If other users cannot enter spiffs, then the company must have Spiff Type Corporate, otherwise all individuals in company will be able to access spiffs.</inlineHelpText>
    <label>Portal Corporate Spiff Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Reseller_Contact__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reseller Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Partner</label>
    <referenceTo>Opportunity_Partner__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/portalSpaSpiffSearch.cls
public  without sharing class portalSpaSpiffSearch {
    @AuraEnabled
    public static List<Quote> getSpas(String spaName){
        String spa = spaName;
        spaName = '%'+spaName+'%';
       List<Contact> cons = new List<Contact>();
       List<String> accts = new List<String>();        
      
        if(!test.isRunningTest()){
            cons = [Select Id,AccountId,Account.ParentId, Portal_Corporate_Spiff_Admin__c  from Contact where id in (Select ContactId  from user where id =:  userinfo.getuserId() )];
            if(cons.size() > 0 && cons[0].Portal_Corporate_Spiff_Admin__c){
                accts.add(cons[0].AccountId);accts.add(cons[0].Account.ParentId);
            }
        }       
         /*
        
        List<Account> partnerAcct = new List<Account>();
        if(test.isRunningTest()){
            Opportunity_partner__c part = [Select partner_account__c from Opportunity_partner__c where opportunity__c in 
                                           (select opportunityid from quote where name =: spa)];
            
            Account a = [Select id from account where id =: part.partner_account__c];           
            partnerAcct.add(a);
        }
        
        try{
            partnerAcct =  [Select id, parentid from account where id = : con.AccountId
                            or id =: con.Account.ParentId];
        }catch(Exception e){
            if(!test.isRunningTest()){
                throw new AuraHandledException('Darn it! Something went wrong: '+ e.getMessage()+ ' account id = '+con.AccountId);
            }
        }
        */
        List<Quote> record = new List <Quote>();
        List<Quote> recordConRole = new List <Quote>();
        
        recordConRole = [select id, name , AccountId,Account.Name from Quote where
                  Opportunityid in (Select OpportunityId from OpportunityContactRole
                                    where ContactId  in : cons) and Status in ('Approved','Needs Review')
                  and Name like : spaName order by expirationdate desc limit 75];
        
        
        record = [select id, name , AccountId,Account.Name from Quote where
                  Opportunityid in (Select Opportunity__c from Opportunity_partner__c
                                    where Reseller_Contact__c  in : cons or partner_account__c in : accts) and Status in ('Approved','Needs Review')
                  and Name like : spaName order by expirationdate desc limit 75];
        
        record.addAll(recordConRole);
        
        return record;
    }
    
}