force-app/main/default/objects/Contact/fields/pp_SendOnboardingAlert__c.field-meta.xml
<CustomField>
    <fullName>pp_SendOnboardingAlert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>pp_SendOnboardingAlert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/pp_SendOnboardingCnt__c.field-meta.xml
<CustomField>
    <fullName>pp_SendOnboardingCnt__c</fullName>
    <description>The number of onboarding tasks for Partner Program that were assigned.</description>
    <label>pp_SendOnboardingCnt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portal_Task__c/Portal_Task__c.object-meta.xml
<CustomObject>
    <label>Partner Portal Task</label>
    <nameField>
        <label>Portal Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PortalOnboardingProgress__c/PortalOnboardingProgress__c.object-meta.xml
<CustomObject>
    <label>Portal Onboarding Progress</label>
    <nameField>
        <label>PortalOnboardingProgress Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Porta lOnboarding Progress</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PortalOnboardingProgress__c/fields/Partner_Portal_Task__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Task__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Portal Task</label>
    <referenceTo>Portal_Task__c</referenceTo>
    <relationshipLabel>Porta lOnboarding Progress</relationshipLabel>
    <relationshipName>Porta_lOnboarding_Progress</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PortalOnboardingProgress__c/fields/Portal_Contact__c.field-meta.xml
<CustomField>
    <fullName>Portal_Contact__c</fullName>
    <label>Portal Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Porta lOnboarding Progress</relationshipLabel>
    <relationshipName>Porta_lOnboarding_Progress</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/PortalOnboardingProgress__c/fields/sendAlert__c.field-meta.xml
<CustomField>
    <fullName>sendAlert__c</fullName>
    <defaultValue>true</defaultValue>
    <label>sendAlert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PortalOnboardingProgress__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Started</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Under Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/pp_schOnboardingTaks.cls
global class pp_schOnboardingTaks implements Schedulable {
    global void execute(SchedulableContext ctx) {
        
        List<Contact> cons = [Select id,pp_SendOnboardingAlert__c, (select id, sendAlert__c from Porta_lOnboarding_Progress__r
                                                                   where sendAlert__c = true
                              and Partner_Portal_Task__r.Required__c = false and Status__c  = 'Not Started' ) from Contact where id in 
                              (Select Portal_Contact__c  from PortalOnboardingProgress__c where sendAlert__c = true
                              and Partner_Portal_Task__r.Required__c = false and Status__c  = 'Not Started')];
        
        List<PortalOnboardingProgress__c> pptoUpdate = new List<PortalOnboardingProgress__c>();
        
        for(Contact c : cons){
            c.pp_SendOnboardingAlert__c = true;
            c.pp_SendOnboardingCnt__c = c.Porta_lOnboarding_Progress__r.size();
            for(PortalOnboardingProgress__c p : c.Porta_lOnboarding_Progress__r){
                p.sendAlert__c = false;
                pptoUpdate.add(p);                
            }
        }
        
        update cons;
        update pptoUpdate;
    }
    
}