force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Ship_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Out_Date__c</fullName>
    <label>Ship Out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Interest&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Quote Request</fullName>
            </value>
            <value>
                <fullName>Agreed to Purchase</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Decided not to buy</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/List_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Price__c</fullName>
    <label>List Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/TestOppProducts.cls
@isTest
private class TestOppProducts {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void getStatus()  
    {
        test.startTest();
        OppProducts.getStatus();
        test.stopTest();
    }
    
    static testmethod void getOppLInes()
    {		        
        
        test.startTest();
        Product2 prodstate = new Product2(Name = 'statesyncApex Test', family = 'test family',List_Price__c=5.00, IsActive= true);
        insert prodstate;
        
        PriceBookEntry pbEntrys = new PriceBookEntry(
            UnitPrice = 300,
            PriceBook2Id = Test.getStandardPricebookId() ,
            Product2Id = prodstate.Id,
            IsActive = true);
        
        insert pbEntrys;
        
        TriggerContextUtility.setFirstRunTrue();
        
        prodstate.CanUseQuantitySchedule = true;
        update prodstate;
        
        List<Opportunity> opp  = [Select Id,Opportunity.Pricebook2Id,(Select Id,product2.name,Quantity,Ship_Out_Date__c,Product2Id,
                                                                      OpportunityId,unitprice,Status__c,TotalPrice from OpportunityLineItems) from Opportunity where HasOpportunityLineItem = true limit 2];
        
        PriceBookEntry pbEntry = new PriceBookEntry(
            UnitPrice = 300,
            PriceBook2Id = opp[0].Pricebook2Id ,
            Product2Id = prodstate.Id,
            IsActive = true);
        
        insert pbEntry;
        
        OpportunityLineItem oline = new OpportunityLineItem(OpportunityId = opp[0].Id,
                                                            PricebookEntryId = pbEntry.Id,
                                                            Quantity = 10,
                                                            UnitPrice = 100);
        insert oline;
        
        
        
        
        List<OpportunityLineItem> lineitems = new List<OpportunityLineItem>();
        lineitems.add(oline);
        Set<String> lineproducts = new Set<String>();
        
        if(opp[0].opportunitylineitems.size() > 0 ){
            
            lineitems.add(opp[0].OpportunityLineItems[0]);
            
            for(OpportunityLineItem l : lineitems){
                lineproducts.add(l.Product2Id);
            }
            
            List<Product2> prods = [Select id ,CanUseQuantitySchedule from Product2 where Id in :lineproducts];
            
            TriggerContextUtility.setFirstRunTrue();
            for(Product2 p : prods){
                p.CanUseQuantitySchedule = true;
                update p; 
            }
            
            
            lineitems[0].Ship_Out_Date__c = null;
            update lineitems[0];
            
            OpportunityLineItemSchedule sch = new OpportunityLineItemSchedule(OpportunityLineItemId = lineitems[0].Id,
                                                                              Quantity = 30,
                                                                              ScheduleDate = date.today(),
                                                                              Type = 'Quantity');
            insert sch;
            
            
        }
        if(opp[0].opportunitylineitems.size() > 1 ){
            lineitems.add(opp[0].OpportunityLineItems[1]);
        }
        
        
        
        //methods getOpp getUser updateopps getSpas
        //setting the variables need to pass to method get spas
        
        String oppid  = opp[0].Id;
        
        //test method for account, contact or opportunity object as record id
        
        lineitems = OppProducts.getOppLInes(oppid);
        OppProducts.updateOppLines(lineitems,oppid);
        
        lineitems[0].Ship_Out_Date__c = date.today();
        update lineitems[0];
        
        OpportunityLineItemSchedule sch = new OpportunityLineItemSchedule(OpportunityLineItemId = lineitems[0].Id,
                                                                              Quantity = 30,
                                                                              ScheduleDate = date.today(),
                                                                              Type = 'Quantity');
        insert sch;
        
        OppProducts.updateOppLines(lineitems,oppid);
        OppProducts.deleteOppLines(lineitems,oppid);
        
        test.stopTest();
    }
}