force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/Spiff_Request__c.object-meta.xml
<CustomObject>
    <description>Requests are tied to a Contact and Account where there is a request for spiff to be paid out</description>
    <label>Spiff Request</label>
    <nameField>
        <displayFormat>S-{MM}{YYYY}-{000000}</displayFormat>
        <label>Spiff Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Spiff Requests</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Spiff_Request__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Spiff RequestsProduct</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Requester</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Spiff Requests</relationshipLabel>
    <relationshipName>Spiff_Requests</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Spiff_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Submitted&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Requesting more info</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Submitted to Accounting</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/testSpiffPaymentFinanceUpdate.cls
@isTest
private class testSpiffPaymentFinanceUpdate {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    
    static testmethod void getLines()
    {		        
        
        
        test.startTest();        
        Spiff_request__c sp = [Select id, status__c,product__c,Requester__c ,Requester__r.AccountId from Spiff_request__c limit 1];
        Account acc = [Select billingCountry, billingstate,id from account where id = : sp.Requester__r.AccountId limit 1];
        
        Product2 p = [Select id, family from product2 limit 1];
        p.family = 'IFP';
        update p;
        sp.Status__c = 'Approved';
        sp.product__c = p.Id;
        update sp;
        
        spiffPaymentToFinance.updateFinance();
        
        acc.BillingCountry = 'Canada';
        acc.BillingState = 'Alberta';
        update acc;
        
        sp.Status__c = 'Approved';
        update sp;
        p.family = 'CD';
        update p;
        spiffPaymentToFinance.updateFinance();
        sp.Status__c = 'Approved';
        update sp;
        p.family = 'LCD';
        update p;
        spiffPaymentToFinance.updateFinance();
        sp.Status__c = 'Approved';
        update sp;
        p.family = 'PJ';
        update p;
        spiffPaymentToFinance.updateFinance();
        sp.Status__c = 'Approved';
        update sp;
        p.family = 'IFP';
        update p;
        spiffPaymentToFinance.updateFinance();
        
        test.stopTest();
    }
}