force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Name_Main__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Main__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is for mobile users to quickly add a product to an opportunity so that it has the most important Product Listed. This Could be used to update the Opportunity Name.</inlineHelpText>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>This product must be active and must be part of the default price book.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_or_Site_Information__c.field-meta.xml
<CustomField>
    <fullName>Project_or_Site_Information__c</fullName>
    <inlineHelpText>Adds Project Name or Site information to Opportunity Name</inlineHelpText>
    <label>Project or Site Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resellers_and_Type__c.field-meta.xml
<CustomField>
    <fullName>Resellers_and_Type__c</fullName>
    <description>Updated by flow</description>
    <label>Resellers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Ship_Out_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Out_Date__c</fullName>
    <label>Ship Out Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Interest&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Interest</fullName>
            </value>
            <value>
                <fullName>Quote Request</fullName>
            </value>
            <value>
                <fullName>Agreed to Purchase</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Decided not to buy</fullName>
            </value>
            <value>
                <fullName>--None--</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestOppPipelineRecPage.cls
@isTest
private class TestOppPipelineRecPage {
@testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
    static testmethod void getPicklists()  
      {         
           test.startTest();
           OppPipelineRecPage.getStatus();
           OppPipelineRecPage.getUser();
           test.stopTest();
      }
    static testmethod void getPipe()  
  {
      List<Opportunity> oppid = [Select Id,Name,StageName from Opportunity limit 5];
      List<Opportunity> opps = new List<Opportunity>();
      List<Account> acc = [Select Id from Account limit 5];
      List<Contact> con = [Select Id from Contact limit 5];
      
      String ofields = 'Id,AccountId, Account.Name,Product_Name_Main__c,'+
                       'CloseDate,Project_or_Site_Information__c,name,Resellers_and_Type__c,'+
                       'Pricebook2Id';
      String pfields = 'Name,Quantity,Product2Id,Product2.Name,ServiceDate'+
                       ',Ship_Out_Date__c,status__c';
      
      String clause = '';
      
      String recid = oppid[0].Id;
      
      system.debug(recid+' opp id');
      List<OpportunityLineItem> lines = [Select Id,Quantity,Name,Status__c from OpportunityLineItem limit 5];
      
      test.startTest();    
      opps = OppPipelineRecPage.getPipe(recid,ofields,pfields,clause);
      
      recid = acc[0].Id;
      OppPipelineRecPage.getPipe(recid,ofields,pfields,clause);
      
      recid = con[0].Id;
      OppPipelineRecPage.getPipe(recid,ofields,pfields,clause);
      
      //this will cause database update success
      OppPipelineRecPage.updateopps(opps,lines);
      
      //this will cause database update failure by putting bad value in picklist
      //also use other oppid list to ensure records are being saves
       
      for(OpportunityLineItem l : lines){
          
          l.Status__c = 'failure';
      }
      opps = oppid;
      OppPipelineRecPage.updateopps(opps,lines);
      test.stopTest();
  }
    static testmethod void delProd()  
      {         
           List<Opportunity> opps = [Select Id from Opportunity limit 5]; 
           List<OpportunityLineItem> lines = [Select Id,Quantity,Name from OpportunityLineItem limit 5];
           String prodid = lines[0].Id;
           String product = '';
          
           test.startTest();
           OppPipelineRecPage.delProd(prodid,opps,lines,product);
           test.stopTest();
      }
	
}