force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
            </value>
            <value>
                <fullName>Secondary</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Name_Main__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_Main__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This is for mobile users to quickly add a product to an opportunity so that it has the most important Product Listed. This Could be used to update the Opportunity Name.</inlineHelpText>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>This product must be active and must be part of the default price book.</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_or_Site_Information__c.field-meta.xml
<CustomField>
    <fullName>Project_or_Site_Information__c</fullName>
    <inlineHelpText>Adds Project Name or Site information to Opportunity Name</inlineHelpText>
    <label>Project or Site Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Resellers_and_Type__c.field-meta.xml
<CustomField>
    <fullName>Resellers_and_Type__c</fullName>
    <description>Updated by flow</description>
    <label>Resellers</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestSpaSearch.cls
@isTest
private class TestSpaSearch {
@testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    }
static testmethod void getUser()  
  {
       //  Methods industries and status  is metadata, don't need records,
       //   just need to run the method
       //   product types is querying the product pillar object
       //   which a record is created in build test data testsetup
       test.startTest();
       SpaSearch.getUser();
       SpaSearch.getStatus();
       SpaSearch.getProdTypes();
       SpaSearch.getIndustries();
       test.stopTest();
  }
        
    static testmethod void getSpas()
  {		        
           
      List<Opportunity> opps = new List<Opportunity> ();
      
      String product  = '';
      String reseller = '';
      String enduser  = '';
      String industry = '';
      String spaid = '';
      String family = '';
      //methods getOpp getUser updateopps getSpas
      //setting the variables need to pass to method get spas
      String ofields = 'Id,AccountId, Account.Name,Product_Name_Main__c,'+
                       'CloseDate,Project_or_Site_Information__c,name,Resellers_and_Type__c,'+
                       'Pricebook2Id';
      String pfields = 'Name,Quantity,Product2Id,Product2.Name,ServiceDate'+
                       ',Ship_Out_Date__c,status__c';
     
      //test method for account, contact or opportunity object as record id
      
      test.startTest();
      
      opps = SpaSearch.getSpas(product,reseller,enduser,industry,ofields,pfields,family,spaid);
      
      product  = 'va';
      reseller = 'edu';
      enduser  = 'edu';
      industry = 'edu';
      spaid = '';
      family = 'monitor';
      
      SpaSearch.getSpas(product,reseller,enduser,industry,ofields,pfields,family,spaid);
      
      SpaSearch.updateopps(opps,product);
      
      test.stopTest();
    }
 }