force-app/main/default/objects/Contact/fields/UserID__c.field-meta.xml
<CustomField>
    <fullName>UserID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Links Viewsonic Users with contacts. Used in automation for the product request roll ups.</description>
    <label>UserID</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/Eval_Request__c.object-meta.xml
<CustomObject>
    <description>Product Request Information</description>
    <label>Eval Request</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>Eval Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eval Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Request__c/fields/Eval_Type__c.field-meta.xml
<CustomField>
    <fullName>Eval_Type__c</fullName>
    <label>Evaluation Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>End-User/Reseller/Disty Eval</fullName>
            </value>
            <value>
                <fullName>ViewSonic Sales Rep Eval</fullName>
            </value>
            <value>
                <fullName>Write Off Request</fullName>
            </value>
            <value>
                <fullName>Reseller Demo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_2__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_3__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_4__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name_5__c.field-meta.xml
<CustomField>
    <fullName>Product_Name_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>This is a bundle, you must select a non bundle product.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2)</booleanFilter>
        <errorMessage>This is a bundle, you must select a non bundle product.

Also Products cannot have -2, -3,-4 in IFP Name. Please use the non dash skus.</errorMessage>
        <filterItems>
            <field>Product2.Bundle__c</field>
            <operation>equals</operation>
            <value>False</value>
        </filterItems>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Eval Requests (Product Name)</relationshipLabel>
    <relationshipName>Eval_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_2__c.field-meta.xml
<CustomField>
    <fullName>Quantity_2__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_3__c.field-meta.xml
<CustomField>
    <fullName>Quantity_3__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_4__c.field-meta.xml
<CustomField>
    <fullName>Quantity_4__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Request__c/fields/Quantity_5__c.field-meta.xml
<CustomField>
    <fullName>Quantity_5__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/Eval_Unit_Details__c.object-meta.xml
<CustomObject>
    <label>Eval Unit Details</label>
    <nameField>
        <label>Serial Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Eval Unit Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Eval_Request__c.field-meta.xml
<CustomField>
    <fullName>Eval_Request__c</fullName>
    <label>Eval Request</label>
    <referenceTo>Eval_Request__c</referenceTo>
    <relationshipName>Eval_Unit_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/SKU__c.field-meta.xml
<CustomField>
    <fullName>SKU__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Testing Field. Will pull from product</inlineHelpText>
    <label>SKU</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Product_Unit_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Eval_Unit_Details__c/fields/Transfer_Requested__c.field-meta.xml
<CustomField>
    <fullName>Transfer_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Transfer Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NewEval.cls
public class NewEval {
    @AuraEnabled
     public static Eval_Request__c getEval(String recid){
        system.debug('get the eval '+recid);
        Schema.SObjectType convertType = Schema.getGlobalDescribe().get('Eval_Request__c');

        Sobject genericObject = convertType.newSObject();
        
        DescribeSObjectResult describeResult = genericObject.getSObjectType().getDescribe();
        
        List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
        
        
        String query =		  ' SELECT ' +		      String.join( fieldNames, ',' ) + 
        ' , (Select id, sku__c,sku__r.name from eval_unit_details__r where Transfer_Requested__c = true '+
        ' and sku__c != null) FROM '
            +		      describeResult.getName()	+' where id =: recid limit 1' 	;		
        // return generic list of sobjects or typecast to expected type
       
        Eval_Request__c record = Database.query( query );
        system.debug('get the eval '+record);
        ///clear out all the product fiels and reiterate with the
        //products that were selected to transfer
        //limitation being spl and sample and b stock skus that could not be mapped
        //to a parent sku in Salesforce. Those skus will not be added
        //
        system.debug(record.eval_unit_details__r);
        system.debug(record.eval_unit_details__r.size());
        system.debug('above is details and then size');
        record.Product_Name_2__c = null;
        record.Product_Name_3__c = null;
        record.Product_Name_4__c = null;
        record.Product_Name_5__c = null;

        record.Quantity__c = null;
        record.Quantity_2__c = null;
        record.Quantity_3__c = null;
        record.Quantity_4__c = null;
        record.Quantity_5__c = null;
        for (Integer i = 0; i < record.eval_unit_details__r.size(); i++) {
            if(i==0){
                system.debug('first sku '+record.eval_unit_details__r[i].Sku__r.Name);
                record.product_name__c = record.eval_unit_details__r[i].Sku__c;
                record.Quantity__c = 1;
            }
            if(i==1){
                system.debug('2nd sku '+record.eval_unit_details__r[i].Sku__r.name);
                record.Product_Name_2__c = record.eval_unit_details__r[i].Sku__c;
                record.Quantity_2__c = 1;
            }
            if(i==2){
                system.debug('3rd sku '+record.eval_unit_details__r[i].Sku__r.name);
                record.Product_Name_3__c = record.eval_unit_details__r[i].Sku__c;
                record.Quantity_3__c = 1;
            }
            if(i==3){
                record.Product_Name_4__c = record.eval_unit_details__r[i].Sku__c;
                record.Quantity_4__c = 1;
            }
            if(i==4){
                record.Product_Name_5__c = record.eval_unit_details__r[i].Sku__c;
                record.Quantity_5__c = 1;
            }
        }
        
        system.debug(record.Quantity__c);
        system.debug(record.product_name__c);
        return record;
         
    }
    
    @AuraEnabled
     public static String getUser()
    {     
         Id userId = UserInfo.getUserId();
         
         Contact con = [SELECT ID, Name FROM Contact WHERE UserID__c = :userId limit 1];
         
         return con.Id;
         
    }
    @AuraEnabled
    public static List<String> getTypes(Boolean trade)  
  {
        List<String> options = new List<String>();
      
		options.add('--None--');
        Schema.DescribeFieldResult fieldResult = Eval_Request__c.Eval_Type__c.getDescribe();
    
       List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    
       if(trade != true || trade == null){  
           for (Schema.PicklistEntry f: ple){
                options.add(f.getValue());
           }
       }else{
            for (Schema.PicklistEntry f: ple) {
                if(f.getValue() !='Reseller Demo' && f.getValue() != 'Write Off Request' ){
                     options.add(f.getValue());
                }               
       		}
       }
	  system.debug('options');
      system.debug(options);         
       
      return options;
    }

}