force-app/main/default/objects/Hot_Swap__c/Hot_Swap__c.object-meta.xml
<CustomObject>
    <label>Hot Swap</label>
    <nameField>
        <label>Hot Swap  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hot Swaps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hot_Swap__c/fields/Customer_Service_Action__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Action__c</fullName>
    <label>Customer Service Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Hot_Swap_Products_Tracking_Id__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Products_Tracking_Id__c</fullName>
    <label>Hot Swap Products Tracking Id &amp; Case Id</label>
    <length>38768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Hot_Swap_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Request_Status__c</fullName>
    <formula>IF (HotSwap_Final_Status__c==FALSE, TEXT(SPA__r.Hot_Swap_Approved_Or_Rejected__c),&apos;Request Closed&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Hot Swap Approval Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Hot_Swap_Request_Summary__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Request_Summary__c</fullName>
    <label>Hot Swap Request Summary</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/HotSwap_Final_Status__c.field-meta.xml
<CustomField>
    <fullName>HotSwap_Final_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HotSwap Final Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/HotSwap_Product_Quantity__c.field-meta.xml
<CustomField>
    <fullName>HotSwap_Product_Quantity__c</fullName>
    <label>Requested Qty/Sold Qty-Product Requested</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>PostalCode</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Reason_For_Hot_Swap__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Hot_Swap__c</fullName>
    <label>Reason For Hot Swap</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Recipient_Email__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Email__c</fullName>
    <label>Recipient Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Recipient_Name__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Name__c</fullName>
    <label>Recipient Name</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/Recipient_Phone__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Phone__c</fullName>
    <label>Recipient Phone</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/SPA__c.field-meta.xml
<CustomField>
    <fullName>SPA__c</fullName>
    <label>SPA</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Hot Swaps</relationshipLabel>
    <relationshipName>Hot_Swaps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hot_Swap__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Hot_Swap_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Quantity__c</fullName>
    <label>Hot Swap Quantity</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_ID__c.field-meta.xml
<CustomField>
    <fullName>Product_ID__c</fullName>
    <formula>CASESAFEID(Id)</formula>
    <label>Product ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Quantity_Sold__c.field-meta.xml
<CustomField>
    <fullName>Product_Quantity_Sold__c</fullName>
    <description>Created Field for hotswap project which shows how many products are sold</description>
    <label>Product Quantity Sold</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/BR_ManagerId__c.field-meta.xml
<CustomField>
    <fullName>BR_ManagerId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Manager for the rep that submitted a BR request. This is used in the approval process for BR to route to manager</description>
    <label>BR ManagerId</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Hot_Swap_Approved_Or_Rejected__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Approved_Or_Rejected__c</fullName>
    <description>Field to determine if the HotSwap is Approved or Rejected.</description>
    <label>Hot Swap Approved Or Rejected</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending For Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Hot_Swap_Requested__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Requested__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check Box to Know if this SPA has Hot Swap Requested or Not</description>
    <label>Hot Swap Requested</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Hotswap_Items__c.field-meta.xml
<CustomField>
    <fullName>Hotswap_Items__c</fullName>
    <label>Hotswap_Items</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Quote/fields/In_Hot_Swap_Review__c.field-meta.xml
<CustomField>
    <fullName>In_Hot_Swap_Review__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to Identify if the SPA is in Hot Swap Request Approval Review</description>
    <label>In Hot Swap Review</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Quote/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>CASESAFEID(OpportunityId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Reason_For_Hotswap__c.field-meta.xml
<CustomField>
    <fullName>Reason_For_Hotswap__c</fullName>
    <description>Reason to be entered for Hotswap Request</description>
    <label>Reason For Hotswap</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Hot_Swap_Flag__c.field-meta.xml
<CustomField>
    <fullName>Hot_Swap_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Flag to determine if the SKU is chosen/requested for Hot Swap</description>
    <label>Hot Swap Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/Hotswap_Identification__c.field-meta.xml
<CustomField>
    <fullName>Hotswap_Identification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Field to Identify to update the HotSwap Flag after approving or rejecting the HotSwap</description>
    <label>Hotswap_Identification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLineItem/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <formula>Casesafeid(Quote.OpportunityId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>OpportunityId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HotSwapCmpController.cls
public class HotSwapCmpController {
        @AuraEnabled
        public static List<QuoteLineItem> getSpaProducts(String recordId){
            list<QuoteLineItem> QuoteLineItemList = [select id,Quantity,Product2.Name,UnitPrice,Approved_Price__c,Hot_Swap_Flag__c,Hotswap_Identification__c from QuoteLineItem where QuoteId =:recordId];
            return QuoteLineItemList; 
        }
        
        
        @AuraEnabled
          public static String getUpdateSpaProducts(String recordId,Hot_Swap__c htswap,list<QuoteLineItem> spaProducts){ // Added "Hot_Swap__c htswap" by Shweta for creating HotSwap Records for  Hotswap project on 27-10-2022
              string status='';
              string skunames = '';
            string prodHotSwap='';
              
            List<String> prodList=new List<String>();
             List<ProcessInstance> swaplist=new List<ProcessInstance>();
              swaplist=[select id,Status,TargetObjectId from ProcessInstance where TargetObjectId =:recordId and Status Not In('Rejected','Approved') ];
                if(swaplist==null || swaplist.isEmpty()){                  
            for(QuoteLineItem e : spaProducts){
                //e.Hot_Swap_Flag__c = true;
                System.debug('e.Product2.Name'+e);
                 e.Hotswap_Identification__c = true;
                skunames = skunames+';'+e.Product2.Name;
                System.debug('Hot Swap'+e.pricebookentryId);
                System.debug('Hot Swap'+e.Product2id);
                if(Test.isRunningTest())
                e.product2 = [select Name,Hot_Swap_Quantity__c,Product_Quantity_Sold__c from product2 where id = :e.Product2id];
                if(e.Product2.Hot_Swap_Quantity__c==null )
                {
                    e.Product2.Hot_Swap_Quantity__c='1';
                    
                }
                
                prodHotSwap=prodHotSwap+''+e.Product2.Hot_Swap_Quantity__c+'/'+e.Product2.Product_Quantity_Sold__c+' - '+e.Product2.Name+'\n'; // Added "Hot_Swap__c htswap" by Shweta for creating HotSwap Records for  Hotswap project on 28-10-2022               
                System.debug('prodHotSwap'+prodHotSwap);
                String prodName=e.Product2.Name;
                prodList.add(prodName );
                System.debug('Prod list'+prodList);
            }
           List<Hot_Swap__c> preHotswapRecordFinal=new List<Hot_Swap__c>();
            List<Hot_Swap__c> preHotswapRecords=new List<Hot_Swap__c>();
                  preHotswapRecords=[select ID ,SPA__c,HotSwap_Final_Status__c,Hot_Swap_Request_Status__c,Hot_Swap_Request_Summary__c from Hot_Swap__c where SPA__c=:recordId];  
                    System.debug('preHotswapRecords'+preHotswapRecords);
                    if(preHotswapRecords!=null || !preHotswapRecords.isEmpty() || preHotswapRecords.size()!=0){
                    for(Hot_Swap__c h:preHotswapRecords){
                        if(h.HotSwap_Final_Status__c!=true){
                            
                            h.HotSwap_Final_Status__c=true;
                        }
                        if(h.Hot_Swap_Request_Status__c=='Approved'){
                            h.Hot_Swap_Request_Summary__c='Approved';
                        }
                        else if(h.Hot_Swap_Request_Status__c=='Rejected'){
                            h.Hot_Swap_Request_Summary__c='Rejected';
                        }
                        preHotswapRecordFinal.add(h);
                        System.debug('preHotswapRecordFinal'+preHotswapRecordFinal);
                    }
                    Database.update(preHotswapRecordFinal);
                    }
            User u = [select id, managerid from user where id =: UserInfo.getUserId()];
            Quote newQuote = new Quote();
            newQuote.ID = recordId;
            newQuote.BR_ManagerId__c = u.ManagerId;
            newQuote.Reason_For_Hotswap__c = htswap.Reason_For_Hot_Swap__c;
            //newQuote.Hot_Swap_Requested__c = true; --- commented on 0729
            newQuote.In_Hot_Swap_Review__c=  true;
            //newQuote.hot_swap_approved_or_rejected__C='Approved'; --- commented on 0729
           //newQuote.Hotswap_Items__c = skunames.substring(1, skunames.length());
           newQuote.Hotswap_Items__c = prodHotSwap;
            newQuote.Hot_Swap_Approved_Or_Rejected__c='Pending For Approval';
                    
            //try{
            system.debug('---spa products identification'+spaProducts);
           
            
            update spaProducts;
            update newQuote;
            //Start: Added by Shweta for creating HotSwap Records for  Hotswap project//
            
                    
            Hot_Swap__c newHotSwap= new Hot_Swap__c();
            newHotSwap.SPA__c=recordId;
            newHotSwap.Recipient_Name__c=htswap.Recipient_Name__c;
            newHotSwap.Recipient_Phone__c=htswap.Recipient_Phone__c;
            newHotSwap.Recipient_Email__c=htswap.Recipient_Email__c;
            newHotSwap.Reason_For_Hot_Swap__c=htswap.Reason_For_Hot_Swap__c;
            newHotSwap.Street__c=htswap.Street__c;
            newHotSwap.State__c=htswap.State__c;
            newHotSwap.PostalCode__c=htswap.PostalCode__c;
            newHotSwap.City__c=htswap.City__c;
            newHotSwap.Country__c=htswap.Country__c;
            newHotSwap.HotSwap_Product_Quantity__c= prodHotSwap;
 			newHotSwap.Hot_Swap_Products_Tracking_Id__c=prodHotSwap;
            newHotSwap.Customer_Service_Action__c='Pending';
            insert newHotSwap;
          /*  List<Product2> prodUpdateList =new List<Product2>();
            List<Product2> getProdList=[Select Hot_Swap_ID__c,Hot_Swap_Quantity__c,Product_ID__c FROM Product2 where Name in : prodList];
            System.debug('Prod List '+getProdList);
            if(getProdList!=null){ 
               for(Product2 p:getProdList){
                   p.Hot_Swap_ID__c=newHotSwap.Id;

                     prodUpdateList.add(p); 
                
            }
               update prodUpdateList;
                 System.debug('prodUpdateList'+prodUpdateList);
                
            }*/
               // }
            
             //End: Added by Shweta for creating HotSwap Records for  Hotswap project//
                //start approval process   
                       Approval.ProcessSubmitRequest req1 = new Approval.ProcessSubmitRequest();
                        req1.setComments('Submitted for Hot Swap Request Approval');
                        req1.setObjectId(newQuote.id);   // req1.setObjectId(q.OpportunityId__c);
                        
                        // Submit on behalf of a specific submitter
                        //req1.setSubmitterId(unsub.Id); 
                
                        // Submit the record to specific process and skip the criteria evaluation
                        req1.setProcessDefinitionNameOrId('SPA_Hot_Swap_Request');
                        //req1.setSkipEntryCriteria(true);
                        SYSTEM.debug('@@@@@Approval'+req1); 
                
                       Approval.ProcessResult result = Approval.process(req1);
          
            status='Hotswap Record Created';
                }
                else{                    
                     status='No Hotswap Record Created';            
                }

              return status;
        }

    }