force-app/main/default/objects/Contact/recordTypes/Distributor.recordType-meta.xml
<RecordType>
    <fullName>Distributor</fullName>
    <active>true</active>
    <label>Distributor</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <formula>HYPERLINK(&apos;/&apos;&amp; Id , Name)</formula>
    <label>Opportunity</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/Opportunity_Partner__c.object-meta.xml
<CustomObject>
    <description>Junction object to tie Accounts to an Opportunity</description>
    <label>Opportunity Partner</label>
    <nameField>
        <displayFormat>OP - {0000000}</displayFormat>
        <label>Record #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Partners</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_Partner__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Partners</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Account__c.field-meta.xml
<CustomField>
    <fullName>Partner_Account__c</fullName>
    <inlineHelpText>Lookup and select the Account that is a partner on this Opportunity</inlineHelpText>
    <label>Partner Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Partner Opportunites</relationshipLabel>
    <relationshipName>Opportunity_Partners</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity_Partner__c/fields/Partner_Type__c.field-meta.xml
<CustomField>
    <fullName>Partner_Type__c</fullName>
    <inlineHelpText>Select the type of Partner</inlineHelpText>
    <label>Partner Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Reseller / VAR</fullName>
            </value>
            <value>
                <fullName>Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote/fields/Opportunity_Partner__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Partner</label>
    <referenceTo>Opportunity_Partner__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestUserOppTeam.cls
@IsTest
public class TestUserOppTeam  {
    @testSetup
    private static void BuildTestData(){
        BuildTestData.AddRecords();
    } 
    
    Static testmethod void communityuser() {
        test.startTest();
        
        list<account> acc = [select name from account where billingcountry = 'United States'];
        
        system.debug(acc.size()+' acct size test');
        
        Contact con = new Contact(LastName = 'Trout',
                                  FirstName='Mike the MVP',
                                  email='troutmvp@testapex.com',
                                  accountid = acc[0].Id,
                                  phone='5625551212',
                                  mailingCountry='United States');
        insert con;
        system.debug(con);
        
        //Set<String> customerUserTypes = new Set<String> {'CSPLiteUser', 'PowerPartner', 'PowerCustomerSuccess',   'CustomerSuccess'};
            User thisUser = [ select Id from User where Id = :UserInfo.getUserId() ];
        System.runAs ( thisUser ) {
            UserRole ur = [Select PortalType, PortalAccountId From UserRole where PortalType like '%Partner%' limit 1];
            Profile p = [select Id,name from Profile where UserType like '%Partner%' limit 1];           
            
            User newUser = new User(
                //UserRoleId = ur.Id, 
                profileId = p.id,
                username = 'miketroutmvpusertest@mvptesting.com',
                email = con.email,
                emailencodingkey = 'UTF-8',
                localesidkey = 'en_US',
                languagelocalekey = 'en_US',
                timezonesidkey = 'America/Los_Angeles',
                alias='nuser',
                lastname='lastname',
                contactId = con.id,
                phone=con.phone,
                Country=con.mailingcountry
            );
            insert newUser;  
        }
        
        User u = [Select id,email from user where username = 'miketroutmvpusertest@mvptesting.com' limit 1];
        
        List<Opportunity> opp = [Select id,(select id, status from quotes) from opportunity where id in (select opportunityid from quote) limit 10];
        List<Quote> quoteup = new List<Quote>();
        
        List<Opportunity_Partner__c> parts = new List<Opportunity_Partner__c>();
        for(Opportunity o : opp){
            Opportunity_Partner__c p = new Opportunity_Partner__c(Opportunity__c = o.Id,
                                                                  Partner_Account__c = con.AccountId,
                                                                  Partner_Type__c = 'Distributor'
                                                                 );
            parts.add(p);
            for(Quote q :o.quotes){
                q.status = 'approved';
                quoteup.add(q);
            }
        }
        
        update quoteup;
        
        insert parts;        
        system.debug(u);
        UserOppTeam.communityuser(u.email);
        UserOppTeam.accTrans(u.email);
        UserOppTeam.oppTeam(u.email);
        UserOppTeam.oppTrans(u.email, u.email);
        
        test.stopTest();
        
    }
    Static testmethod void acctrans() {
        test.startTest();
    }
}